### ISSUE TITLE
[BUG] SegmentReplicationUsingRemoteStoreIT.testMultipleShards flaky test failure 

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#10027]
Coming from https://github.com/opensearch-project/OpenSearch/issues/8279#issuecomment-1718117854, SegmentReplicationUsingRemoteStoreIT.testMultipleShards is flaky.

Build with test failures: (24057,24205,24358,25310,25397)

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testMultipleShards" -Dtests.seed=C3ABB282A1C73F4C -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-SG -Dtests.timezone=Asia/Kabul -Druntime.java=20
```

Assertion trip
```
java.lang.AssertionError: Expected search hits on node: node_t2 to be at least 56 but was: 37
	at __randomizedtesting.SeedInfo.seed([C3ABB282A1C73F4C:38ECCF766FD92160]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.lambda$waitForSearchableDocs$0(SegmentReplicationBaseIT.java:124)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1086)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:119)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:114)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:131)
	at org.opensearch.indices.replication.SegmentReplicationIT.testMultipleShards(SegmentReplicationIT.java:382)
```

**Comment by dreamer-89** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/9712
