### ISSUE TITLE
[BUG]org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimarySingleReplica 

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#10193]
**Describe the bug**
org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimarySingleReplica failure seen on autocut gradle check failure to main. (https://github.com/opensearch-project/OpenSearch/issues/10149). 

**Expected behavior**
Test should pass always.

**Stacktrace:**
```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([5784F3A051D8B7A3:61806557B4685E4E]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1086)
	at org.opensearch.remotestore.RemoteStoreStatsIT.testDownloadStatsCorrectnessSinglePrimarySingleReplica(RemoteStoreStatsIT.java:294)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1623)
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:87)
		at org.junit.Assert.assertTrue(Assert.java:42)
		at org.junit.Assert.assertTrue(Assert.java:53)
		at org.opensearch.remotestore.RemoteStoreStatsIT.lambda$testDownloadStatsCorrectnessSinglePrimarySingleReplica$6(RemoteStoreStatsIT.java:310)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1074)
		... 39 more
		```

**Comment by ashking94** [comment]
https://github.com/opensearch-project/OpenSearch/pull/11021#issuecomment-1789441294

**Comment by Poojita-Raj** [comment]
<img width="1027" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/20815824/0fce0787-eb4d-4357-8830-60427bad09dc">

Ran it successfully 1000 times - twice on local. 
Tested the test suite 200 times, tried running the module. 
Wasn't able to reproduce the failure even with any of the seeds on previously seen failures.

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14310
