### ISSUE TITLE
[BUG] opensearch process exits during addition of documents with knn_vector field

### ISSUE THREAD

**Issue by billschell** [opensearch-project/OpenSearch#1030]
**Describe the bug**
While adding ~1.3M documents with a knn_vector type field, the opensearch process exited with KNN related errors.  This happened after adding approximately 800K documents.  The document mapping and index info are below.   I was using the latest docker image (version data below), with a single mode.

**Errors in log**
(there were tens of these error pairs before the process exited)
```
[2021-07-30T18:36:47,770][WARN ][o.o.t.ThreadPool         ] [opensearch-node1] failed to run scheduled task [org.opensearch.indices.IndexingMemoryController$ShardsIndicesStatusChecker@4027ffab] on thread pool [same]
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:877) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:891) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter.getFlushingBytes(IndexWriter.java:781) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.opensearch.index.engine.InternalEngine.getWritingBytes(InternalEngine.java:635) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.index.shard.IndexShard.getWritingBytes(IndexShard.java:991) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.indices.IndexingMemoryController.getShardWritingBytes(IndexingMemoryController.java:195) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.indices.IndexingMemoryController$ShardsIndicesStatusChecker.runUnlocked(IndexingMemoryController.java:323) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.indices.IndexingMemoryController$ShardsIndicesStatusChecker.run(IndexingMemoryController.java:303) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:226) [opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:756) [opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.0.0.jar:1.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.RuntimeException: java.lang.Exception: Check failed: it's either a bug or inconsistent data!
	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.merge(KNN80DocValuesConsumer.java:165) ~[?:?]
	at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.merge(PerFieldDocValuesFormat.java:155) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.SegmentMerger.mergeDocValues(SegmentMerger.java:195) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:150) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4760) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4364) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:5923) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:624) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:113) ~[opensearch-1.0.0.jar:1.0.0]
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:682) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
Caused by: java.lang.Exception: Check failed: it's either a bug or inconsistent data!
	at org.opensearch.knn.index.v2011.KNNIndex.saveIndex(Native Method) ~[?:?]
	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer$1.run(KNN80DocValuesConsumer.java:117) ~[?:?]
	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer$1.run(KNN80DocValuesConsumer.java:115) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.addKNNBinaryField(KNN80DocValuesConsumer.java:114) ~[?:?]
	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.merge(KNN80DocValuesConsumer.java:161) ~[?:?]
	at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.merge(PerFieldDocValuesFormat.java:155) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.SegmentMerger.mergeDocValues(SegmentMerger.java:195) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:150) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4760) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4364) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:5923) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:624) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:113) ~[opensearch-1.0.0.jar:1.0.0]
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:682) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
Killing performance analyzer process 11
OpenSearch exited with code 137
Performance analyzer exited with code 143
./opensearch-docker-entrypoint.sh: line 109:    10 Killed                  $OPENSEARCH_HOME/bin/opensearch "${opensearch_opts[@]}
```

**Mapping info**
```
{
  "test_knn" : {
    "aliases" : { },
    "mappings" : {
      "dynamic" : "true",
      "properties" : {
        "end" : {
          "type" : "integer"
        },
        "id" : {
          "type" : "keyword"
        },
        "index" : {
          "type" : "keyword"
        },
        "start" : {
          "type" : "integer"
        },
        "text" : {
          "type" : "keyword"
        },
        "type" : {
          "type" : "keyword"
        },
        "vector" : {
          "type" : "knn_vector",
          "dimension" : 768,
          "method" : {
            "engine" : "nmslib",
            "space_type" : "innerproduct",
            "name" : "hnsw",
            "parameters" : {
              "ef_construction" : 512,
              "m" : 24
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "number_of_shards" : "1",
        "knn.algo_param" : {
          "ef_search" : "100"
        },
        "provided_name" : "test_knn",
        "knn" : "true",
        "creation_date" : "1627660076506",
        "number_of_replicas" : "0",
        "uuid" : "FZj47j44TUyarSBU3ZjMaw",
        "version" : {
          "created" : "135217827"
        }
      }
    }
  }
}

```
**Version info**
```
{
  "name" : "opensearch-node1",
  "cluster_name" : "opensearch-cluster",
  "cluster_uuid" : "IeOOVXJoRACXnucMfKNzqQ",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.0.0",
    "build_type" : "tar",
    "build_hash" : "34550c5b17124ddc59458ef774f6b43a086522e3",
    "build_date" : "2021-07-02T23:22:21.383695Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**To Reproduce**
Unclear.  This happens sporadically during loading large number of documents. Documents are being added  via the Python bulk update API  (which appears to hit the server with 500 documents at a time).

**Expected behavior**
Opensearch process doesn't exit

**Plugins**
opensearch-node1 opensearch-alerting             1.0.0.0
opensearch-node1 opensearch-anomaly-detection    1.0.0.0
opensearch-node1 opensearch-asynchronous-search  1.0.0.0
opensearch-node1 opensearch-index-management     1.0.0.0
opensearch-node1 opensearch-job-scheduler        1.0.0.0
opensearch-node1 opensearch-knn                  1.0.0.0
opensearch-node1 opensearch-notebooks            1.0.0.0
opensearch-node1 opensearch-performance-analyzer 1.0.0.0
opensearch-node1 opensearch-reports-scheduler    1.0.0.0
opensearch-node1 opensearch-security             1.0.0.0
opensearch-node1 opensearch-sql                  1.0.0.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: latest docker image from here https://www.opensearch.org/downloads.htm
 - Host is Centos 7.9
 - Version 1.0.0
 - Docker-compose file edited for only one node 
 - OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g"
 - those were the only changes 'before docker-compose up'

**Additional context**
AWS m5.xlarge host machine

**Comment by billschell** [comment]
OK, I was doing the exact same thing again.  About thirty 500 document bulk updates had completed when opensearch aborted.   This time there was nothing in the log but this:
```
double free or corruption (out)
Killing performance analyzer process 11
OpenSearch exited with code 134
Performance analyzer exited with code 143
./opensearch-docker-entrypoint.sh: line 109:    10 Aborted                 (core dumped) $OPENSEARCH_HOME/bin/opensearch "${opensearch_opts[@]}"
```
It did leave a 23GB core file. If anyone is interested, I can upload it to somewhere.

**Comment by dblock** [comment]
While this may not be actually related to k-nn, I'll move it into that repo. If we can build a repro that doesn't use k-nn feel free to move it back.
