### ISSUE TITLE
Lenient FsHealth checks 

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#1040]
**Is your feature request related to a problem? Please describe.**
FS health checks fail commonly if segment merges fail to free up space instantly, causing node drops. The health checks run at 2 mins default interval, we can make it run frequently which making it check multiple data points within the same 2 min frequency.
```
[2021-07-25T09:22:03,754][WARN ][o.e.c.r.a.AllocationService] [71c0fc82d21543cfa8976609efc33534] failing shard [failed shard, shard [prod-9ai1zb5rixgf2xk1wresmj-log-ccgf-audit][0], node[GKwqdV1HQvS4yVafMvUSyw], [P], s[STARTED], a[id=a8HRp0CSQvu-CrQkiprCZA], message [shard failure, reason [merge failed]], failure [NotSerializableExceptionWrapper[merge_exception: org.apache.lucene.store.AlreadyClosedException: refusing to delete any files: this IndexWriter hit an unrecoverable exception]; nested: AlreadyClosedException[refusing to delete any files: this IndexWriter hit an unrecoverable exception]; nested: IOException[No space left on device]; ], markAsStale [true]]
org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: merge_exception: org.apache.lucene.store.AlreadyClosedException: refusing to delete any files: this IndexWriter hit an unrecoverable exception
        at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler$2.doRun(InternalEngine.java:2389) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:782) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36) ~[elasticsearch-7.4.2.jar:7.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.apache.lucene.store.AlreadyClosedException: refusing to delete any files: this IndexWriter hit an unrecoverable exception
        at org.apache.lucene.index.IndexFileDeleter.ensureOpen(IndexFileDeleter.java:349) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
        at org.apache.lucene.index.IndexFileDeleter.deleteFiles(IndexFileDeleter.java:669) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
        at org.apache.lucene.index.IndexFileDeleter.deleteNewFiles(IndexFileDeleter.java:664) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
        at org.apache.lucene.index.IndexWriter.deleteNewFiles(IndexWriter.java:5033) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4548) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4056) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:625) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
        at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:101) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:662) ~[lucene-core-8.2.0.jar:8.2.0-SNAPSHOT 0f22e910cb5c8ec4900a92b58e74439a30831213 - malpani - 2020-02-28 14:00:43]
Caused by: java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[?:?]
```

```
[2021-07-25T11:00:45,446][ERROR][o.e.m.f.FsHealthService  ] [7339268867fb20d4ce8e79e114ad61ce] health check of [/apollo/env/swift-us-west-2-prod-ES_7_4AMI-ES2-p001/var/es/data/nodes/0] failed
java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[?:?]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280) ~[?:?]
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
        at java.nio.channels.Channels.writeFully(Channels.java:97) ~[?:?]
        at java.nio.channels.Channels$1.write(Channels.java:172) ~[?:?]
        at java.io.OutputStream.write(OutputStream.java:122) ~[?:?]
        at org.elasticsearch.monitor.fs.FsHealthService$FsHealthMonitor.monitorFSHealth(FsHealthService.java:172) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.monitor.fs.FsHealthService$FsHealthMonitor.run(FsHealthService.java:146) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:225) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:782) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36) [elasticsearch-7.4.2.jar:7.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```

```
[2021-07-25T09:24:45,435][DEBUG][o.e.c.c.FollowersChecker ] [71c0fc82d21543cfa8976609efc33534] FollowerChecker{discoveryNode={7339268867fb20d4ce8e79e114ad61ce}{c1SWB3QGTh25YTZGtwUvmw}{arGWoss9Qk6S8yaMAC9ahg}{172.16.19.16}{172.16.19.16:9300}{di}{dp_version=20210401, distributed_snapshot_deletion_enabled=true, di_number=4, zone=us-west-2a, cross_cluster_transport_address=2600:1f13:ae6:d800:d5ab:8a52:17e7:9d0f}, failureCountSinceLastSuccess=1, [cluster.fault_detection.follower_check.retry_count]=3} health check failed
org.elasticsearch.transport.RemoteTransportException: [7339268867fb20d4ce8e79e114ad61ce][172.16.19.16:9300][internal:coordination/fault_detection/follower_check]
Caused by: org.elasticsearch.cluster.coordination.NodeHealthCheckFailureException: handleFollowerCheck: node is unhealthy [health check failed on [/apollo/env/swift-us-west-2-prod-ES_7_4AMI-ES2-p001/var/es/data/nodes/0]], rejecting health check failed on [/apollo/env/swift-us-west-2-prod-ES_7_4AMI-ES2-p001/var/es/data/nodes/0]
        at org.elasticsearch.cluster.coordination.FollowersChecker.handleFollowerCheck(FollowersChecker.java:183) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.cluster.coordination.FollowersChecker.lambda$new$0(FollowersChecker.java:123) ~[elasticsearch-7.4.2.jar:7.4.2]
        at com.amazonaws.elasticsearch.iam.IamTransportRequestHandler.messageReceived(IamTransportRequestHandler.java:55) ~[?:?]
        at com.amazonaws.elasticsearch.ccs.CrossClusterRequestInterceptor$CrossClusterRequestHandler.messageReceived(CrossClusterRequestInterceptor.java:133) ~[?:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:51) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:264) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:249) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:185) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:118) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:663) [elasticsearch-7.4.2.jar:7.4.2]

```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anasalkouz** [comment]
Hi @Bukhtawar, Could you clarify if this is still needed? specially after #1041. Are you looking to run the check more frequently?  Could you elaborate more?

**Comment by anasalkouz** [comment]
Closing it. @Bukhtawar feel free to reopen if there is anything still pending.

**Comment by Bukhtawar** [comment]
@anasalkouz Please re-open this issue, the problem is not fixed and would appreciate any community help on this
