### ISSUE TITLE
[BUG] org.opensearch.search.aggregations.bucket.DateRangeIT.testSingleValueFieldWithStringDates {p0={"search.concurrent_segment_search.enabled":"false"}}

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#10475]
**Describe the bug**
Test is flaky: org.opensearch.search.aggregations.bucket.DateRangeIT.testSingleValueFieldWithStringDates {p0={"search.concurrent_segment_search.enabled":"false"}}

https://build.ci.opensearch.org/job/gradle-check/27311/testReport/junit/org.opensearch.search.aggregations.bucket/DateRangeIT/testSingleValueFieldWithStringDates__p0___search_concurrent_segment_search_enabled___false___/

```
java.lang.AssertionError: Unexpected ShardFailures: [shard [[oFevbBxtQsy8MR4fkfKdlw][idx][2]], reason [RemoteTransportException[[node_s1][127.0.0.1:45191][indices:data/read/search[phase/dfs]]]; nested: OpenSearchParseException[failed to parse date field [2012-02-15] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]: [failed to parse date field [2012-02-15] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]]]; nested: IllegalArgumentException[failed to parse date field [2012-02-15] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]]; nested: DateTimeParseException[Failed to parse with all enclosed parsers]; ], cause [OpenSearchParseException[failed to parse date field [2012-02-15] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]: [failed to parse date field [2012-02-15] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]]]; nested: IllegalArgumentException[failed to parse date field [2012-02-15] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]]; nested: DateTimeParseException[Failed to parse with all enclosed parsers];
	at org.opensearch.common.time.JavaDateMathParser.parseDateTime(JavaDateMathParser.java:247)
	at org.opensearch.common.time.JavaDateMathParser.parse(JavaDateMathParser.java:89)
	at org.opensearch.search.DocValueFormat$DateTime.parseLong(DocValueFormat.java:299)
	at org.opensearch.search.DocValueFormat$DateTime.parseDouble(DocValueFormat.java:304)
	at org.opensearch.search.aggregations.bucket.range.DateRangeAggregationBuilder.lambda$innerBuild$2(DateRangeAggregationBuilder.java:349)
	at org.opensearch.search.aggregations.bucket.range.AbstractRangeBuilder.processRanges(AbstractRangeBuilder.java:104)
	at org.opensearch.search.aggregations.bucket.range.DateRangeAggregationBuilder.innerBuild(DateRangeAggregationBuilder.java:334)
	at org.opensearch.search.aggregations.bucket.range.DateRangeAggregationBuilder.innerBuild(DateRangeAggregationBuilder.java:57)
	at org.opensearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:411)
	at org.opensearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:60)
	at org.opensearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:155)
	at org.opensearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:459)
	at org.opensearch.search.SearchService.parseSource(SearchService.java:1294)
	at org.opensearch.search.SearchService.createContext(SearchService.java:998)
	at org.opensearch.search.SearchService.executeDfsPhase(SearchService.java:526)
	at org.opensearch.search.SearchService$1.lambda$onResponse$0(SearchService.java:511)
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74)
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalArgumentException: failed to parse date field [2012-02-15] with format [strict_date_time_no_millis||strict_date_optional_time||epoch_millis]
	at org.opensearch.common.time.JavaDateFormatter.parse(JavaDateFormatter.java:268)
	at org.opensearch.common.time.JavaDateMathParser.parseDateTime(JavaDateMathParser.java:238)
	... 26 more
Caused by: java.time.format.DateTimeParseException: Failed to parse with all enclosed parsers
	at org.opensearch.common.time.JavaDateFormatter.doParse(JavaDateFormatter.java:307)
	at org.opensearch.common.time.JavaDateFormatter.parse(JavaDateFormatter.java:266)
	... 27 more
]]
Expected: <0>
     but: was <1>
```

**To Reproduce**
CI Link is shared above

**Expected behavior**
Test should always pass

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by reta** [comment]
CC @CaptainDredge

**Comment by CaptainDredge** [comment]
@reta can you close this? Not able to repro it
