### ISSUE TITLE
[BUG] org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#10749]
**Describe the bug**
The test case org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata is flaky:

```
java.lang.AssertionError: timed out waiting for green state

java.lang.AssertionError: timed out waiting for green state
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1012)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:943)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:932)
	at org.opensearch.remotestore.BaseRemoteStoreRestoreIT.verifyRestoredData(BaseRemoteStoreRestoreIT.java:63)
	at org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata(RemoteStoreClusterStateRestoreIT.java:249)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**To Reproduce**
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata" -Dtests.seed=4FA936F087F8BF6B 
```

**Expected behavior**
The test must always pass

**Plugins**
Standard

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/28446/testReport/junit/org.opensearch.remotestore/RemoteStoreClusterStateRestoreIT/testFullClusterRestoreGlobalMetadata/

**Comment by linuxpi** [comment]
We have fixed all flaky tests in org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT. Closing, please reopen if you see any failures

**Comment by ketanv3** [comment]
@linuxpi Slightly different occurrence: https://build.ci.opensearch.org/job/gradle-check/29421/testReport/junit/org.opensearch.remotestore/RemoteStoreClusterStateRestoreIT/testFullClusterRestoreGlobalMetadata/

**Comment by reta** [comment]
And again here https://build.ci.opensearch.org/job/gradle-check/29586/testReport/junit/org.opensearch.remotestore/RemoteStoreClusterStateRestoreIT/testFullClusterRestoreGlobalMetadata/
 
```
java.lang.IllegalStateException: Error while downloading cluster metadata - manifest__9223372036854775806__9223372036854775776__P__9223370337568370205__1
```

**Comment by mch2** [comment]
Got a failure in this test class on `[testFullClusterRestoreMultipleIndices](https://build.ci.opensearch.org/job/gradle-check/29562/testReport/junit/org.opensearch.remotestore/RemoteStoreClusterStateRestoreIT/testFullClusterRestoreMultipleIndices/)` - https://build.ci.opensearch.org/job/gradle-check/29562/

**Comment by peternied** [comment]
Another failure, impacted  #11102, [logs](https://build.ci.opensearch.org/job/gradle-check/29576/).

**Comment by bowenlan-amzn** [comment]
saw this test failed again https://build.ci.opensearch.org/job/gradle-check/33624/testReport/
@linuxpi could you maybe take a look

**Comment by peternied** [comment]
@msfroh could you close when this has been backported to 2.12/2.x?

**Comment by bowenlan-amzn** [comment]
Close as the backport 2.12 PR has been merged
