### ISSUE TITLE
[BUG] MockLogAppender appended to after stopping

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#10799]
See test failure here: https://build.ci.opensearch.org/job/gradle-check/28539/consoleText

```
org.opensearch.transport.netty4.SimpleNetty4TransportTests > testTracerLog FAILED
    java.lang.AssertionError: 
    Expected: an empty collection
         but: <[Attempted to append to non-started appender mock]>
        at __randomizedtesting.SeedInfo.seed([C98A4BF58C821570:CA09B64B8D8ABBA5]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.test.OpenSearchTestCase.checkStaticState(OpenSearchTestCase.java:638)
        at org.opensearch.test.OpenSearchTestCase.after(OpenSearchTestCase.java:428)
        at java.****/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.****/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.****/java.lang.Thread.run(Thread.java:1623)

```

I thought I fixed this problem in #1595. After glancing at the code I don't see where the problem is so this remains a mystery.

**Comment by reta** [comment]
Sadly came back here: https://github.com/opensearch-project/OpenSearch/pull/12000

**Comment by andrross** [comment]
From [this failure](https://build.ci.opensearch.org/job/gradle-check/32770/consoleText):

```
REPRODUCE WITH: ./gradlew ':plugins:transport-nio:test' --tests "org.opensearch.transport.nio.SimpleNioTransportTests.testTracerLog" -Dtests.seed=25BED9B96E9788F7 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nl-BE -Dtests.timezone=US/Mountain -Druntime.java=21

org.opensearch.transport.nio.SimpleNioTransportTests > testTracerLog FAILED
    java.lang.AssertionError: 
    Expected: an empty collection
         but: <[Attempted to append to non-started appender org.opensearch.transport.AbstractSimpleTransportTestCase-mock-log-appender]>
```

The new logging suggests `AbstractSimpleTransportTestCase` is the culprit...

**Comment by andrross** [comment]
With the added logging, I believe the code is correct and not a simple start/add/remove/stop ordering issue of the logging appender. I think this could be a concurrency issue in `org.apache.logging.log4j.core.config.LoggerConfig` in that we remove the appender and then stop it, but an on-going logging event still has an older reference of `AppenderControlArraySet` (which has similar semantics to CopyOnWriteArraySet according to the documentation) that holds a reference to the now-stopped appender.
