### ISSUE TITLE
[BUG] org.opensearch.search.profile.query.QueryProfilerTests.testBasic {p0=5} is flaky

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#10941]
**Describe the bug**
`org.opensearch.search.profile.query.QueryProfilerTests.testBasic {p0=5}` test is flaky.

Below assertion failure can be seen -
```
java.lang.AssertionError: 
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>
```

**To Reproduce**
https://build.ci.opensearch.org/job/gradle-check/29044/testReport/junit/org.opensearch.search.profile.query/QueryProfilerTests/testBasic__p0_5_/

**Expected behavior**
Test must always pass.

**Comment by nknize** [comment]
Similar reproducible error:

```
./gradlew ':server:test' --tests "org.opensearch.search.profile.query.QueryProfilerTests.testApproximations {p0=5}" -Dtests.seed=D11999824BA0CE71 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-CN -Dtests.timezone=Africa/Bamako
```

```
  2> java.lang.AssertionError: 
    Expected: a value greater than <0L>
         but: <0L> was equal to <0L>
        at __randomizedtesting.SeedInfo.seed([D11999824BA0CE71:14FADAE707F9B355]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.search.profile.query.QueryProfilerTests.testApproximations(QueryProfilerTests.java:349)
```

**Comment by nknize** [comment]
I removed the flaky test label and added a severity. If I have some cycles I'll look at this.

**Comment by dblock** [comment]
Happened again in https://github.com/opensearch-project/OpenSearch/pull/13358, reopening.
