### ISSUE TITLE
[BUG] RemoteStoreRestoreIT.testRTSRestoreWithNoDataPostCommitPrimaryReplicaDown test is flaky

### ISSUE THREAD

**Issue by bharath-techie** [opensearch-project/OpenSearch#10972]
**Describe the bug**
Flaky test - https://build.ci.opensearch.org/job/gradle-check/29123/

```
java.lang.AssertionError:  inconsistent generation 
	at __randomizedtesting.SeedInfo.seed([515498453653F8C9]:0)
	at org.opensearch.index.translog.transfer.TranslogCheckpointTransferSnapshot$Builder.build(TranslogCheckpointTransferSnapshot.java:180)
	at org.opensearch.index.translog.RemoteFsTranslog.upload(RemoteFsTranslog.java:333)
	at org.opensearch.index.translog.RemoteFsTranslog.prepareAndUpload(RemoteFsTranslog.java:305)
	at org.opensearch.index.translog.RemoteFsTranslog.sync(RemoteFsTranslog.java:360)
	at org.opensearch.index.translog.InternalTranslogManager.syncTranslog(InternalTranslogManager.java:197)
	at org.opensearch.index.shard.IndexShard.postActivatePrimaryMode(IndexShard.java:3404)
	at org.opensearch.index.shard.IndexShard.lambda$updateShardState$4(IndexShard.java:714)
	at org.opensearch.index.shard.IndexShard$5.onResponse(IndexShard.java:4007)
	at org.opensearch.index.shard.IndexShard$5.onResponse(IndexShard.java:3977)
	at org.opensearch.index.shard.IndexShard.lambda$asyncBlockOperations$36(IndexShard.java:3928)
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82)
	at org.opensearch.index.shard.IndexShardOperationPermits$1.doRun(IndexShardOperationPermits.java:157)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

Also saw `org.opensearch.remotestore.RemoteStoreRestoreIT.classMethod` in the same gradle check

```
FileChannel(/var/jenkins/workspace/gradle-check/search/server/build/testrun/internalClusterTest/temp/org.opensearch.remotestore.RemoteStoreRestoreIT_515498453653F8C9-001/tempDir-002/node_s1/nodes/0/indices/wz5JYfV6S3CXHQ_2RsfXhQ/1/translog/translog-10.tlog), FileChannel(/var/jenkins/workspace/gradle-check/search/server/build/testrun/internalClusterTest/temp/org.opensearch.remotestore.RemoteStoreRestoreIT_515498453653F8C9-001/tempDir-002/node_s1/nodes/0/indices/wz5JYfV6S3CXHQ_2RsfXhQ/1/translog/translog-13.tlog)]
```

**To Reproduce**
Intermittent failure , only can catch with higher iterations

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by ashking94** [comment]
The root cause for this same as #10902. We will track #10902 for the same.
