### ISSUE TITLE
[BUG] Reproducible failure in SearchCancellationIT.testMSearchChildReqCancellationWithHybridTimeout 

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1099]
#986 introduced test failures; indicating the feature was likely merged prematurely. 

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchCancellationIT.testMSearchChildReqCancellationWithHybridTimeout" -Dtests.seed=596A2CDAD4EE2410 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=he -Dtests.timezone=America/Halifax -Druntime.java=15
```

First and third queries are expected to be cancelled. But only the first query is cancelled. Expanding the `clusterCancellationTimeout` has no effect (possibly ruling out a race condition) so there is a separate issue going on here.

```
org.opensearch.search.SearchCancellationIT > testMSearchChildReqCancellationWithHybridTimeout FAILED
    java.lang.AssertionError: Actual child request with cancellation failure is different that expected expected:<[0, 2]> but was:<[0]>
        at __randomizedtesting.SeedInfo.seed([596A2CDAD4EE2410:A60B6D246603635E]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.opensearch.search.SearchCancellationIT.ensureMSearchWasCancelled(SearchCancellationIT.java:195)
        at org.opensearch.search.SearchCancellationIT.testMSearchChildReqCancellationWithHybridTimeout(SearchCancellationIT.java:566)
```

**Comment by sohami** [comment]
Thanks for sharing this, will open a PR with the fix

**Comment by minalsha** [comment]
The fix has been backported.
