### ISSUE TITLE
[BUG] ScriptQuerySearchIT.testCustomScriptBoost, testDisallowExpensiveQueries, and testCustomScriptBinaryField for concurrent search are flaky

### ISSUE THREAD

**Issue by ticheng-aws** [opensearch-project/OpenSearch#11070]
**Describe the bug**
Following tests are always failing:
1. testCustomScriptBoost [p0={"search.concurrent_segment_search.enabled":"true"}]
2. testDisallowExpensiveQueries [p0={"search.concurrent_segment_search.enabled":"true"}]
3. testCustomScriptBinaryField [p0={"search.concurrent_segment_search.enabled":"true"}]

**To Reproduce**
```
PRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.scriptfilter.ScriptQuerySearchIT" -Dtests.method="testCustomScriptBoost [p0={"search.concurrent_segment_search.enabled":"true"}]" -Dtests.seed=36249842BAD3ED51 -Dtests.locale=sr-Latn -Dtests.timezone=Etc/GMT-9 -Druntime.java=17

Failed to execute phase [query], all shards failed
; shardFailures {[3V1xKIykSuShvY5EpgKx6w][test][4]: RemoteTransportException[[node_s3][127.0.0.1:61959][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[0YcOxtQARACG81LyJFjx7g][test][3]: RemoteTransportException[[node_s4][127.0.0.1:61961][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[0rq-q0KhTBa8QVwzE7lPog][test][0]: RemoteTransportException[[node_s5][127.0.0.1:61965][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[3V1xKIykSuShvY5EpgKx6w][test][1]: RemoteTransportException[[node_s3][127.0.0.1:61959][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[0YcOxtQARACG81LyJFjx7g][test][2]: RemoteTransportException[[node_s4][127.0.0.1:61961][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }
	at __randomizedtesting.SeedInfo.seed([36249842BAD3ED51:64FE74617DA87DCF]:0)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:708)
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:380)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:747)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:504)
	at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:302)
	at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
	at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
	at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:749)
	at org.opensearch.telemetry.tracing.handler.TraceableTransportResponseHandler.handleException(TraceableTransportResponseHandler.java:81)
	at org.opensearch.transport.TransportService$6.handleException(TransportService.java:892)
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1503)
	at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438)
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
	at org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:436)
	at org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:428)
	at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:166)
	at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:123)
	at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770)
	at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
	at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
	at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
	at org.opensearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:343)
	at org.opensearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:246)
	at org.opensearch.nio.BytesChannelContext.read(BytesChannelContext.java:59)
	at org.opensearch.nio.EventHandler.handleRead(EventHandler.java:152)
	at org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167)
	at org.opensearch.nio.NioSelector.handleRead(NioSelector.java:438)
	at org.opensearch.nio.NioSelector.processKey(NioSelector.java:264)
	at org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:191)
	at org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: OpenSearchException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!];
	at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:708)
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:378)
	... 29 more
Caused by: java.lang.IllegalStateException: A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!
	at org.opensearch.index.fielddata.ScriptDocValues$Doubles.get(ScriptDocValues.java:285)
	at org.opensearch.index.fielddata.ScriptDocValues$Doubles.getValue(ScriptDocValues.java:279)
	at org.opensearch.search.scriptfilter.ScriptQuerySearchIT$CustomScriptPlugin.lambda$pluginScripts$1(ScriptQuerySearchIT.java:111)
	at org.opensearch.script.MockDeterministicScript$1.apply(MockDeterministicScript.java:55)
	at org.opensearch.script.MockDeterministicScript$1.apply(MockDeterministicScript.java:47)
	at org.opensearch.script.MockScriptEngine$MockFilterScript$1.execute(MockScriptEngine.java:387)
	at org.opensearch.index.query.ScriptQueryBuilder$ScriptQuery$1$1.matches(ScriptQueryBuilder.java:226)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:329)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:233)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
	at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:324)
	at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:280)
	at org.apache.lucene.search.IndexSearcher.lambda$search$1(IndexSearcher.java:715)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```
```
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.scriptfilter.ScriptQuerySearchIT" -Dtests.method="testDisallowExpensiveQueries [p0={"search.concurrent_segment_search.enabled":"true"}]" -Dtests.seed=36249842BAD3ED51 -Dtests.locale=sr-Latn -Dtests.timezone=Etc/GMT-9 -Druntime.java=17

Failed to execute phase [query], all shards failed
; shardFailures {[0YcOxtQARACG81LyJFjx7g][test-index][0]: RemoteTransportException[[node_s4][127.0.0.1:61961][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[3V1xKIykSuShvY5EpgKx6w][test-index][1]: RemoteTransportException[[node_s3][127.0.0.1:61959][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[0rq-q0KhTBa8QVwzE7lPog][test-index][2]: RemoteTransportException[[node_s5][127.0.0.1:61965][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }
	at __randomizedtesting.SeedInfo.seed([36249842BAD3ED51:1133E0C7AE37CA81]:0)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:708)
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:380)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:747)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:504)
	at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:302)
	at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
	at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
	at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:749)
	at org.opensearch.telemetry.tracing.handler.TraceableTransportResponseHandler.handleException(TraceableTransportResponseHandler.java:81)
	at org.opensearch.transport.TransportService$6.handleException(TransportService.java:892)
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1503)
	at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438)
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
	at org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:436)
	at org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:428)
	at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:166)
	at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:123)
	at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770)
	at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
	at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
	at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
	at org.opensearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:343)
	at org.opensearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:246)
	at org.opensearch.nio.BytesChannelContext.read(BytesChannelContext.java:59)
	at org.opensearch.nio.EventHandler.handleRead(EventHandler.java:152)
	at org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167)
	at org.opensearch.nio.NioSelector.handleRead(NioSelector.java:438)
	at org.opensearch.nio.NioSelector.processKey(NioSelector.java:264)
	at org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:191)
	at org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: OpenSearchException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!];
	at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:708)
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:378)
	... 29 more
Caused by: java.lang.IllegalStateException: A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!
	at org.opensearch.index.fielddata.ScriptDocValues$Doubles.get(ScriptDocValues.java:285)
	at org.opensearch.index.fielddata.ScriptDocValues$Doubles.getValue(ScriptDocValues.java:279)
	at org.opensearch.search.scriptfilter.ScriptQuerySearchIT$CustomScriptPlugin.lambda$pluginScripts$1(ScriptQuerySearchIT.java:111)
	at org.opensearch.script.MockDeterministicScript$1.apply(MockDeterministicScript.java:55)
	at org.opensearch.script.MockDeterministicScript$1.apply(MockDeterministicScript.java:47)
	at org.opensearch.script.MockScriptEngine$MockFilterScript$1.execute(MockScriptEngine.java:387)
	at org.opensearch.index.query.ScriptQueryBuilder$ScriptQuery$1$1.matches(ScriptQueryBuilder.java:226)
	at org.apache.lucene.search.ConstantScoreScorer$1.matches(ConstantScoreScorer.java:107)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:295)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:236)
	at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
	at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:324)
	at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:280)
	at org.apache.lucene.search.IndexSearcher.lambda$search$1(IndexSearcher.java:715)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```
```
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.scriptfilter.ScriptQuerySearchIT" -Dtests.method="testCustomScriptBinaryField [p0={"search.concurrent_segment_search.enabled":"true"}]" -Dtests.seed=DBDAB76A2CC388C5 -Dtests.locale=es-CO -Dtests.timezone=Asia/Aden -Druntime.java=17

Failed to execute phase [query], all shards failed
; shardFailures {[4qMdPtYNTj6mryA_y_0pGA][my-index][0]: RemoteTransportException[[node_s5][127.0.0.1:62713][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[eqxECnhOTCWOvJzWoFF96A][my-index][1]: RemoteTransportException[[node_s3][127.0.0.1:62712][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[MPeQZtupSPOvk7xLOCtDGg][my-index][2]: RemoteTransportException[[node_s4][127.0.0.1:62708][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[4qMdPtYNTj6mryA_y_0pGA][my-index][3]: RemoteTransportException[[node_s5][127.0.0.1:62713][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[eqxECnhOTCWOvJzWoFF96A][my-index][4]: RemoteTransportException[[node_s3][127.0.0.1:62712][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }{[MPeQZtupSPOvk7xLOCtDGg][my-index][5]: RemoteTransportException[[node_s4][127.0.0.1:62708][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; }
	at __randomizedtesting.SeedInfo.seed([DBDAB76A2CC388C5:342A8BE8644F0778]:0)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:708)
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:380)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:747)
	at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:504)
	at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:302)
	at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
	at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
	at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:749)
	at org.opensearch.telemetry.tracing.handler.TraceableTransportResponseHandler.handleException(TraceableTransportResponseHandler.java:81)
	at org.opensearch.transport.TransportService$6.handleException(TransportService.java:892)
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1503)
	at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438)
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
	at org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:436)
	at org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:428)
	at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:166)
	at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:123)
	at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770)
	at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
	at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
	at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
	at org.opensearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:343)
	at org.opensearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:246)
	at org.opensearch.nio.BytesChannelContext.read(BytesChannelContext.java:59)
	at org.opensearch.nio.EventHandler.handleRead(EventHandler.java:152)
	at org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167)
	at org.opensearch.nio.NioSelector.handleRead(NioSelector.java:438)
	at org.opensearch.nio.NioSelector.processKey(NioSelector.java:264)
	at org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:191)
	at org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: OpenSearchException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!]; nested: IllegalStateException[A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!];
	at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:708)
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:378)
	... 29 more
Caused by: java.lang.IllegalStateException: A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!
	at org.opensearch.index.fielddata.ScriptDocValues$BytesRefs.get(ScriptDocValues.java:587)
	at org.opensearch.search.scriptfilter.ScriptQuerySearchIT$CustomScriptPlugin.lambda$pluginScripts$4(ScriptQuerySearchIT.java:129)
	at org.opensearch.script.MockDeterministicScript$1.apply(MockDeterministicScript.java:55)
	at org.opensearch.script.MockDeterministicScript$1.apply(MockDeterministicScript.java:47)
	at org.opensearch.script.MockScriptEngine$MockFilterScript$1.execute(MockScriptEngine.java:387)
	at org.opensearch.index.query.ScriptQueryBuilder$ScriptQuery$1$1.matches(ScriptQueryBuilder.java:226)
	at org.apache.lucene.search.ConstantScoreScorer$1.matches(ConstantScoreScorer.java:107)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:295)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:236)
	at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
	at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:324)
	at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:280)
	at org.apache.lucene.search.IndexSearcher.lambda$search$1(IndexSearcher.java:715)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
The test should always pass

**Comment by ticheng-aws** [comment]
These tests are not working with https://github.com/opensearch-project/OpenSearch/pull/10247 solution. We need to handle separately.
