### ISSUE TITLE
[BUG] org.opensearch.recovery.RelocationIT.testRelocateWhileWaitingForRefresh is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#11113]
**Describe the bug**
The test case org.opensearch.recovery.RelocationIT.testRelocateWhileWaitingForRefresh is flaky:

```
org.opensearch.recovery.RelocationIT.testRelocateWhileWaitingForRefresh

java.lang.AssertionError: Unexpected ShardFailures: [shard [[-RiKDuSXScO6_bS1kOrA9w][test][0]], reason [NodeDisconnectedException[[node_t1][127.0.0.1:44623][indices:data/read/search[phase/fetch/id]] disconnected]], cause [NodeDisconnectedException[[node_t1][127.0.0.1:44623][indices:data/read/search[phase/fetch/id]] disconnected]
]]
Expected: <0>
     but: was <1>
	at __randomizedtesting.SeedInfo.seed([6D8F777A72F32A76]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertNoFailures(OpenSearchAssertions.java:339)
	at org.opensearch.recovery.RelocationIT.lambda$testIndexSearchAndRelocateConcurrently$8(RelocationIT.java:550)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.recovery.RelocationIT.testIndexSearchAndRelocateConcurrently" -Dtests.seed=6D8F777A72F32A76
```

**Expected behavior**

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI
 - 
**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/29612/testReport/junit/org.opensearch.recovery/RelocationIT/testRelocateWhileWaitingForRefresh/

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14309
