### ISSUE TITLE
[BUG] org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testDataStreamPostRemoteStateRestore is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#11483]
**Describe the bug**
The test case org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testDataStreamPostRemoteStateRestore is flaky:

```
org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testDataStreamPostRemoteStateRestore

com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=2588, name=opensearch[node_t2][remote_refresh_retry][T#1], state=RUNNABLE, group=TGRP-RemoteStoreClusterStateRestoreIT]
	at __randomizedtesting.SeedInfo.seed([6F53DEF57F1BE2B6:704F47A55513DDB]:0)
Caused by: org.opensearch.core.concurrency.OpenSearchRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@ea40f13[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7665f2c5[Wrapped task = [threaded] org.opensearch.index.shard.ReleasableRetryableRefreshListener$$Lambda/0x00007ff53ca2e3a8@509663e1]] on org.opensearch.threadpool.Scheduler$SafeScheduledThreadPoolExecutor@421eefc[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34]
	at __randomizedtesting.SeedInfo.seed([6F53DEF57F1BE2B6]:0)
	at app//org.opensearch.common.util.concurrent.OpenSearchAbortPolicy.rejectedExecution(OpenSearchAbortPolicy.java:67)
	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
	at java.base@21.0.1/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base@21.0.1/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at app//org.opensearch.threadpool.ThreadPool.schedule(ThreadPool.java:487)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.scheduleRetry(ReleasableRetryableRefreshListener.java:125)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.scheduleRetry(ReleasableRetryableRefreshListener.java:178)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.runAfterRefreshWithPermit(ReleasableRetryableRefreshListener.java:167)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.lambda$scheduleRetry$2(ReleasableRetryableRefreshListener.java:126)
	at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:852)
	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)

```

**To Reproduce**
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testDataStreamPostRemoteStateRestore" -Dtests.seed=6F53DEF57F1BE2B6
```

**Expected behavior**
The test should always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/30847/testReport/junit/org.opensearch.remotestore/RemoteStoreClusterStateRestoreIT/testDataStreamPostRemoteStateRestore/

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14326
