### ISSUE TITLE
Opensearch crashes after upgrading to 2.11.0 or 2.11.1 from 2.10.0

### ISSUE THREAD

**Issue by zirus001** [opensearch-project/OpenSearch#11482]
**Describe the bug**
We are deploying a new Graylog cluster which utilizes Opensearch. Just recently we updating everything to get on the latest of Graylog, mongod, and Opensearch. Opensearch was on 2.9.0. After the initial jump to 2.11.1 the service breaks and will not start. We stepped up to 2.10.0 and was able to keep Opensearch running stable.

**To Reproduce**
Update Opensearch from anything < 2.11.0 to 2.11.0

**Expected behavior**
The service to continue running.

**Plugins**
This is a basic install with just the default plugins.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: RHEL
 - Version 8.9

**Additional context**

Output of the Opensearch log:
# cat /var/log/opensearch/graylog.log
[2023-12-05T21:09:35,113][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [systemname] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
        at org.opensearch.bootstrap.JNANatives.definitelyRunningAsRoot(JNANatives.java:192) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.Natives.definitelyRunningAsRoot(Natives.java:83) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:123) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:191) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.11.1.jar:2.11.1]
        at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.11.1.jar:2.11.1]
Caused by: java.lang.UnsupportedOperationException: Failed to allocate closure
        at com.sun.jna.Native.registerMethod(Native Method) ~[jna-5.13.0.jar:5.13.0 (b0)]
        at com.sun.jna.Native.register(Native.java:1906) ~[jna-5.13.0.jar:5.13.0 (b0)]
        at com.sun.jna.Native.register(Native.java:1775) ~[jna-5.13.0.jar:5.13.0 (b0)]
        at com.sun.jna.Native.register(Native.java:1493) ~[jna-5.13.0.jar:5.13.0 (b0)]
        at org.opensearch.bootstrap.JNACLibrary.<clinit>(JNACLibrary.java:64) ~[opensearch-2.11.1.jar:2.11.1]
        ... 12 more

Service output:
        
# systemctl status opensearch.service       
opensearch.service - OpenSearch
   Loaded: loaded (/usr/lib/systemd/system/opensearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2023-12-04 18:12:57 UTC; 1 day 2h ago
     Docs: https://opensearch.org/
  Process: 72357 ExecStart=/usr/share/opensearch/bin/systemd-entrypoint -p ${PID_DIR}/opensearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 72357 (code=exited, status=1/FAILURE)

Dec 04 18:12:54 systemname systemd-entrypoint[72357]: Caused by: java.lang.UnsupportedOperationException: Failed to allocate closure
Dec 04 18:12:54 systemname systemd-entrypoint[72357]:         at com.sun.jna.Native.registerMethod(Native Method)
Dec 04 18:12:54 systemname systemd-entrypoint[72357]:         at com.sun.jna.Native.register(Native.java:1906)
Dec 04 18:12:54 systemname systemd-entrypoint[72357]:         at com.sun.jna.Native.register(Native.java:1775)
Dec 04 18:12:54 systemname systemd-entrypoint[72357]:         at com.sun.jna.Native.register(Native.java:1493)
Dec 04 18:12:54 systemname systemd-entrypoint[72357]:         at org.opensearch.bootstrap.JNACLibrary.<clinit>(JNACLibrary.java:64)
Dec 04 18:12:54 systemname systemd-entrypoint[72357]:         ... 12 more
Dec 04 18:12:57 systemname systemd[1]: opensearch.service: Main process exited, code=exited, status=1/FAILURE
Dec 04 18:12:57 systemname systemd[1]: opensearch.service: Failed with result 'exit-code'.
Dec 04 18:12:57 systemname systemd[1]: Failed to start OpenSearch.

**Comment by reta** [comment]
@zirus001 could you please confirm that you have been using the JDK version, bundled with `2.11.x`? If not, could you please share the JDK you have been using? Thank you.

**Comment by zirus001** [comment]
So with two of them there was JavaJDK installed. Here are the steps I did to fix the issue:
Step 1. Remove all Java, JavaJDK packages.
Step 2. backup Opensearch configuration
Step 3. remove Opensearch.
Step 4. Reboot.
Step 5. Remove NOEXEC from /tmp mount in /etc/fstab (Only applies to hardened systems ie. STIG'd)
Step 6. Install Opensearch (copying over the configuration).

There was an additional problem after Step 4. That most people wont have. But being a DoD entity we have these systems nearly 100% STIG'd. Therefore the NOEXEC was set on the /tmp mount. Causing the following error:

Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/opensearch-3208800188162299925/jna4038580472759412228.tmp: /tmp/opensearch-3208800188162299925/jna4038580472759412228.tmp: failed to map segment from shared object [in thread "main"]

I wanted to share that in case anyone else runs across this thread.  We are now back up and running.

That was what I found. If anyone at Opensearch has any suggestions on being able to configure Opensearch to not use the /tmp directory for execution that would be extremely helpful..lol

**Comment by reta** [comment]
@zirus001 found this interesting article from Elasticsearch here [1] but I think it may well apply to OpenSearch (specifically with more native libs like ZSTD integrated recently).

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/executable-jna-tmpdir.html

**Comment by zirus001** [comment]
Yes. We were actually one step ahead but basically the same concept..lol I ended up changing the temp directory in /etc/opensearch/jvm.options to the following:

-Djava.io.tmpdir=/opt/OpensearchTmp

This lets me configure the backup option of our configs a bit easier since they are in the same location.

**Comment by reta** [comment]
@zirus001 I think we could close this issue, right?

**Comment by zirus001** [comment]
100% Thank you for the assist!
