### ISSUE TITLE
[BUG] GeoPointShapeQueryTests.testQueryLinearRing fails with UnsupportedOperationException

### ISSUE THREAD

**Issue by rishabhmaurya** [opensearch-project/OpenSearch#11688]
### Describe the bug

GeoPointShapeQueryTests.testQueryLinearRing fails with UnsupportedOperationException - 

Here is the failed test - https://build.ci.opensearch.org/job/gradle-check/31539/testReport/junit/org.opensearch.search.geo/GeoPointShapeQueryTests/testQueryLinearRing/

The failure is not reproducible on mac, amazonlinux and ubuntu when I tried to reproduce them locally with the same seed. 

Relates to PR - https://github.com/opensearch-project/OpenSearch/pull/11039

```
java.lang.UnsupportedOperationException: line ring cannot be serialized using GeoJson
	at __randomizedtesting.SeedInfo.seed([D24747E5E9B452AE:CFF1D9D2D64D1980]:0)
	at org.opensearch.common.geo.GeoJson$3.visit(GeoJson.java:561)
	at org.opensearch.common.geo.GeoJson$3.visit(GeoJson.java:543)
	at org.opensearch.geometry.LinearRing.visit(LinearRing.java:84)
	at org.opensearch.common.geo.GeoJson.getGeoJsonName(GeoJson.java:543)
	at org.opensearch.common.geo.GeoJson.toXContent(GeoJson.java:103)
	at org.opensearch.index.query.AbstractGeometryQueryBuilder.doXContent(AbstractGeometryQueryBuilder.java:452)
	at org.opensearch.index.query.AbstractQueryBuilder.toXContent(AbstractQueryBuilder.java:101)
	at org.opensearch.core.xcontent.XContentBuilder.value(XContentBuilder.java:887)
	at org.opensearch.core.xcontent.XContentBuilder.value(XContentBuilder.java:880)
	at org.opensearch.core.xcontent.XContentBuilder.field(XContentBuilder.java:872)
	at org.opensearch.search.builder.SearchSourceBuilder.innerToXContent(SearchSourceBuilder.java:1350)
	at org.opensearch.search.builder.SearchSourceBuilder.toXContent(SearchSourceBuilder.java:1490)
	at org.opensearch.core.xcontent.XContentHelper.toXContent(XContentHelper.java:46)
	at org.opensearch.search.builder.SearchSourceBuilder.toString(SearchSourceBuilder.java:1810)
	at org.opensearch.action.search.SearchRequest.buildDescription(SearchRequest.java:715)
	at org.opensearch.action.search.SearchTask.getDescription(SearchTask.java:83)
	at org.opensearch.tasks.TaskManager.register(TaskManager.java:210)
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:99)
	at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110)
	at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97)
	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:476)
	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:463)
	at org.opensearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:66)
	at org.opensearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:73)
	at org.opensearch.search.geo.GeoPointShapeQueryTests.testQueryLinearRing(GeoPointShapeQueryTests.java:140)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
		at org.opensearch.core.xcontent.XContentBuilder.close(XContentBuilder.java:1044)
		at org.opensearch.core.xcontent.XContentHelper.toXContent(XContentHelper.java:41)
		... 50 more
	Caused by: java.io.IOException: Unclosed object or array found
		at org.opensearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:494)
		at org.opensearch.core.xcontent.XContentBuilder.close(XContentBuilder.java:1042)
		... 51 more
```

### Related component

Build

### To Reproduce

Here are the steps to reproduce it, although its not reproducible - 

https://build.ci.opensearch.org/job/gradle-check/31539/testReport/junit/org.opensearch.search.geo/GeoPointShapeQueryTests/testQueryLinearRing/

```
./gradlew ':server:test' --tests "org.opensearch.search.geo.GeoPointShapeQueryTests.testQueryLinearRing" -Dtests.seed=E6A53B1422E4284A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=hu-HU -Dtests.timezone=Pacific/Funafuti -Druntime.java=21
```

### Expected behavior

Ideally such serialization/deserialization failures should be deterministic not be environment dependent.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by rishabhmaurya** [comment]
Found that it fails here - 
https://github.com/opensearch-project/OpenSearch/blob/e8df9dbf5d890014f8e25f7134ea423acfdd5637/server/src/main/java/org/opensearch/tasks/TaskManager.java#L210
So when trace logs are enabled and it goes to line 210 and calls `task.getDescription()` - it results in following exception. When trace logs are not enabled, this line never gets called and tests executes normally. 


```
java.lang.UnsupportedOperationException: line ring cannot be serialized using GeoJson
	at __randomizedtesting.SeedInfo.seed([D24747E5E9B452AE:CFF1D9D2D64D1980]:0)
	at org.opensearch.common.geo.GeoJson$3.visit(GeoJson.java:561)
	at org.opensearch.common.geo.GeoJson$3.visit(GeoJson.java:543)
	at org.opensearch.geometry.LinearRing.visit(LinearRing.java:84)
	at org.opensearch.common.geo.GeoJson.getGeoJsonName(GeoJson.java:543)
	at org.opensearch.common.geo.GeoJson.toXContent(GeoJson.java:103)
	at org.opensearch.index.query.AbstractGeometryQueryBuilder.doXContent(AbstractGeometryQueryBuilder.java:452)
	at org.opensearch.index.query.AbstractQueryBuilder.toXContent(AbstractQueryBuilder.java:101)
	at org.opensearch.core.xcontent.XContentBuilder.value(XContentBuilder.java:887)
	at org.opensearch.core.xcontent.XContentBuilder.value(XContentBuilder.java:880)
	at org.opensearch.core.xcontent.XContentBuilder.field(XContentBuilder.java:872)
	at org.opensearch.search.builder.SearchSourceBuilder.innerToXContent(SearchSourceBuilder.java:1350)
	at org.opensearch.search.builder.SearchSourceBuilder.toXContent(SearchSourceBuilder.java:1490)
	at org.opensearch.core.xcontent.XContentHelper.toXContent(XContentHelper.java:46)
	at org.opensearch.search.builder.SearchSourceBuilder.toString(SearchSourceBuilder.java:1810)
	at org.opensearch.action.search.SearchRequest.buildDescription(SearchRequest.java:715)
	at org.opensearch.action.search.SearchTask.getDescription(SearchTask.java:83)
	at org.opensearch.tasks.TaskManager.register(TaskManager.java:210)
```

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/andrross) [4](https://github.com/CEHENKLE) [5](https://github.com/dbwiddis) [6](https://github.com/reta/) [7](https://github.com/anasalkouz) [8](https://github.com/aggarwalShivani)]
@rishabhmaurya Thanks for filing.

@andrross It sounds like there are more details to this issue, could you update the description to better fit what should be addressed.

**Comment by ajaymovva** [comment]
Facing the same issue: https://build.ci.opensearch.org/job/gradle-check/33006/testReport/junit/org.opensearch.search.geo/GeoPointShapeQueryTests/testQueryLinearRing/

PR: https://github.com/opensearch-project/OpenSearch/pull/12111

**Comment by shwetathareja** [comment]
PR - https://github.com/opensearch-project/OpenSearch/pull/8992 observed same failure here - https://build.ci.opensearch.org/job/gradle-check/35326/

**Comment by shwetathareja** [comment]
This test seems like a serial offender, causing gradle check across multiple PRs to fail. can this be muted @andrross ?

**Comment by rishabhmaurya** [comment]
Or we can remove - 
`task.getDescription()` from ` logger.trace("register {} [{}] [{}] [{}]", task.getId(), type, action, task.getDescription()); ` to fix it. Not sure how viable this option is.

**Comment by shwetathareja** [comment]
> Or we can remove -
task.getDescription() from logger.trace("register {} [{}] [{}] [{}]", task.getId(), type, action, task.getDescription()); to fix it. Not sure how viable this option is.

@rishabhmaurya : It wouldn't be preferred as it is a trace log and may be useful in the context of debugging for other type of tasks. We should fix the test.

**Comment by shwetathareja** [comment]
As @rishabhmaurya pointed out, right now it is failing when trace logging is enabled.
This would be consistent failure when trace is enabled, so we need to check during gradle-check why some runs are with trace enabled and while others are not.

I looked into the test, it is a negative and it expects this same exception, just that from a different flow, but when trace logging is enabled, that exception is pre-empted via task.getDescription() call

```
    public void testQueryLinearRing() throws Exception {
        XContentBuilder xcb = createDefaultMapping();
        client().admin().indices().prepareCreate("test").setMapping(xcb).get();
        ensureGreen();

        LinearRing linearRing = new LinearRing(new double[] { -25, -35, -25 }, new double[] { -25, -35, -25 });

        try {
            // LinearRing extends Line implements Geometry: expose the build process
            GeoShapeQueryBuilder queryBuilder = new GeoShapeQueryBuilder(defaultGeoFieldName, linearRing);
            SearchRequestBuilder searchRequestBuilder = new SearchRequestBuilder(client(), SearchAction.INSTANCE);
            searchRequestBuilder.setQuery(queryBuilder);
            searchRequestBuilder.setIndices("test");
            searchRequestBuilder.get();       --------->  // here it fails during search task register before it could start the execution, which would have thrown the same exception 
        } catch (SearchPhaseExecutionException e) {
            assertThat(
                e.getCause().getMessage(),
                containsString("Field [" + defaultGeoFieldName + "] does not support LINEARRING queries")
            );
        }
    }

```

I don't think we can control the logging behavior in SearchTask as it is generic across all tasks. 
Our options to fix the test
1. Expect ```UnsupportedOperationException``` in the test and assert on it as well
2. Change log level for this test? What if somebody introduces another log at debug, this would start to fail again

I would prefer Option 1. 
@peternied / Others : Please feel free to share your thoughts if you think there is a better way to handle it.

**Comment by shwetathareja** [comment]
Raised the PR to fix it - https://github.com/opensearch-project/OpenSearch/pull/12783

**Comment by dblock** [comment]
The fix in https://github.com/opensearch-project/OpenSearch/pull/12783 doesn't look right, reopening so we don't lose it, cc: @Bukhtawar @shwetathareja (https://github.com/opensearch-project/OpenSearch/pull/12783#issuecomment-2010561836)

**Comment by peternied** [comment]
Does anyone know why is a LinearRing should **not** be representable in OpenSearch?  From the GeoJSON RFC [1] its a polygon... seems easier for our users (and test cases) by representing it as a polygon when outputted.

- [1] https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6

**Comment by rishabhmaurya** [comment]
@andrross @shwetathareja  how about this fix - https://github.com/opensearch-project/OpenSearch/pull/12844 ?
