### ISSUE TITLE
[BUG] 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip.asc

### ISSUE THREAD

**Issue by joshuacox** [opensearch-project/OpenSearch#1169]
**Describe the bug**

403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip.asc

**To Reproduce**
1.  /usr/share/opensearch/bin/opensearch-plugin install --batch repository-s3
2. view error

**Expected behavior**
plugin to install

**Plugins**
That's the point the plugin did not install.

Here's the full output from an example dockerfile:

```
docker build . -t test:opensearch
Sending build context to Docker daemon  5.632kB
Step 1/3 : FROM opensearchproject/opensearch:1.0.0
 ---> 88b67cc9e81f
Step 2/3 : RUN /usr/share/opensearch/bin/opensearch-plugin install --batch repository-s3
 ---> Running in b2785c4c2ef8
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip.asc
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1167)
	at org.opensearch.plugins.InstallPluginCommand.urlOpenStream(InstallPluginCommand.java:482)
	at org.opensearch.plugins.InstallPluginCommand.verifySignature(InstallPluginCommand.java:622)
	at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:600)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:306)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
The command '/bin/sh -c /usr/share/opensearch/bin/opensearch-plugin install --batch repository-s3' returned a non-zero code: 1
```

**Host/Environment (please complete the following information):**
 - OS: bionic beaver

**Additional context**

Example Dockerfile to reproduce error:

```
FROM opensearchproject/opensearch:1.0.0
RUN /usr/share/opensearch/bin/opensearch-plugin install --batch repository-s3
```

Following these pages:
https://opensearch.org/docs/opensearch/install/docker#customize-the-docker-image
https://opensearch.org/docs/opensearch/snapshot-restore/#amazon-s3

**Comment by abbashus** [comment]
No sure where the `.asc` is coming in the URL. But I am able to download with this URL 
```
wget https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip
```

**Comment by abbashus** [comment]
I realized `repository-s3-1.0.0.zip.asc` is actually the PGP signature file to verify integrity of download plugin artifact. Need to check with infra team that maintains artifact distribution.
@peterzhuamazon @bbarani

**Comment by AmiStrn** [comment]
perhaps relates to:
https://github.com/opensearch-project/opensearch-build/issues/86

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/OpenSearch/issues/996
We are still in discussion here will close this issue as it is duplicated.
Thanks.
