### ISSUE TITLE
[BUG] NoClassDefFoundError: com.sun.management.ThreadMXBean

### ISSUE THREAD

**Issue by lytvynenko-dmitriy** [opensearch-project/OpenSearch#11893]
### Describe the bug

OpenSearch fails to start on AIX platform with IBM Semeru Runtime Certified Edition 17.0.6.0 (build 17.0.6+10)

### Related component

Build

### To Reproduce

Start OS on IBM Semeru Runtime Certified Edition 17.0.6.0 (build 17.0.6+10)

Observed:
java.lang.NoClassDefFoundError: com.sun.management.ThreadMXBean
	at org.opensearch.tasks.TaskResourceTrackingService.<clinit>(TaskResourceTrackingService.java:51) ~[?:?]
	at org.opensearch.common.settings.ClusterSettings.<clinit>(ClusterSettings.java:233) ~[?:?]
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:84) ~[?:?]
	at org.opensearch.node.Node.<init>(Node.java:556) ~[?:?]

### Expected behavior

There is com.sun.management.ThreadMXBean class is used in OpenSearch implementation (https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java) which is platform dependent. The java.lang.management.ThreadMXBean must be used instead which is platform independednt.

**Comment by reta** [comment]
@lytvynenko-dmitriy thank you for filing the issue, I think we've never tested / run OpenSearch on OpenJ9 JVM (since there wasn't too much interest). It is good to know there is an interest though

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/macohen) [4](https://github.com/jainankitk)]
Thanks for filing, we don't specifically support this JRE but we could consider adding it.  We'd welcome a pull request to add this platform to the matrix and then determine next steps.

**Comment by msfroh** [comment]
The underlying issue is that `TaskResourceTrackingService` uses the `getThreadAllocatedBytes()` method, which is only available in `com.sun.management.ThreadMXBean`, not in `java.lang.management.ThreadMXBean`.

One option could be to split `TaskResourceTrackingService` into a more platform-independent version (that doesn't track allocated bytes per thread), and then a platform-specific version (only if the runtime type of the `ThreadMXBean` implements `com.sun.management.ThreadMXBean`, as determined via reflection).

**Comment by reta** [comment]
> The underlying issue is that `TaskResourceTrackingService` uses the `getThreadAllocatedBytes()` method, which is only available in `com.sun.management.ThreadMXBean`, not in `java.lang.management.ThreadMXBean`.
> 
> One option could be to split `TaskResourceTrackingService` into a more platform-independent version (that doesn't track allocated bytes per thread), and then a platform-specific version (only if the runtime type of the `ThreadMXBean` implements `com.sun.management.ThreadMXBean`, as determined via reflection).

Thanks @msfroh , it should be fined I think, we used to check  `isXxxEnabled` / `isXxxSupported` to figure out which features are support / enabled by JVM (would need a bit of wrapping but not a big deal).
