### ISSUE TITLE
[BUG] :plugins:transport-reactor-netty4:test flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#11935]
### Describe the bug

```
> Task :plugins:transport-reactor-netty4:test
WARNING: Using incubator modules: jdk.incubator.vector

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/home/ubuntu/.gradle/wrapper/dists/gradle-8.5-all/3zlzzgtsutfj0pbojr50n2l7z/gradle-8.5/lib/plugins/gradle-testing-****-8.5.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release
Jan 18, 2024 8:27:54 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release

> Task :client:rest-high-level:asyncIntegTest
WARNING: Using incubator modules: jdk.incubator.vector

org.gradle.internal.remote.internal.ConnectException: Could not connect to server [ab4b7ead-95e2-434b-9d3f-1593704e0499 port:39181, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:103)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.net.ConnectException: Connection refused
	at java.****/sun.nio.ch.Net.pollConnect(Native Method)
	at java.****/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.****/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1191)
	at java.****/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1233)
	at java.****/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:102)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)
	... 5 more
```

### Related component

Libraries

### To Reproduce

Not sure, see https://build.ci.opensearch.org/job/gradle-check/32314

### Expected behavior

Tests to pass.

### Additional Details

https://build.ci.opensearch.org/job/gradle-check/32314/consoleText

**Comment by reta** [comment]
@dblock I am closing this one since this is not the test but Gradle daemon failure:

```
org.gradle.internal.remote.internal.ConnectException: Could not connect to server [ab4b7ead-95e2-434b-9d3f-1593704e0499 port:39181, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
```
