### ISSUE TITLE
[BUG] Flaky test org.opensearch.discovery.ClusterManagerDisruptionIT.testIsolateClusterManagerAndVerifyClusterStateConsensus

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#12095]
### Describe the bug

Found this flaky test on gradle check: 
[org.opensearch.discovery.ClusterManagerDisruptionIT.testIsolateClusterManagerAndVerifyClusterStateConsensus](https://build.ci.opensearch.org/job/gradle-check/32905/testReport/junit/org.opensearch.discovery/ClusterManagerDisruptionIT/testIsolateClusterManagerAndVerifyClusterStateConsensus/) 

https://build.ci.opensearch.org/job/gradle-check/32905/ 

### Related component

Cluster Manager

### To Reproduce

Might show up on running gradle check 

### Expected behavior

Expect test to pass

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.discovery.ClusterManagerDisruptionIT.testIsolateClusterManagerAndVerifyClusterStateConsensus" -Dtests.seed=CA2671C1619AE45E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=da-DK -Dtests.timezone=America/Lima -Druntime.java=21

org.opensearch.discovery.ClusterManagerDisruptionIT > testIsolateClusterManagerAndVerifyClusterStateConsensus FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([CA2671C1619AE45E:7556C7CBC3B6BC4F]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.discovery.ClusterManagerDisruptionIT.lambda$testIsolateClusterManagerAndVerifyClusterStateConsensus$0(ClusterManagerDisruptionIT.java:204)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1089)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1062)
        at org.opensearch.discovery.ClusterManagerDisruptionIT.testIsolateClusterManagerAndVerifyClusterStateConsensus(ClusterManagerDisruptionIT.java:167)
```

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/andrross) [4](https://github.com/CEHENKLE) [5](https://github.com/dbwiddis) [6](https://github.com/reta/) [7](https://github.com/anasalkouz) [8](https://github.com/aggarwalShivani)]
@Poojita-Raj thanks for filing, we'd gladly review a pull request

**Comment by shwetathareja** [comment]
Able to consistent repro the test failure with
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.discovery.ClusterManagerDisruptionIT.testIsolateClusterManagerAndVerifyClusterStateConsensus" -Dtests.seed=CA2671C1619AE45E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=da-DK -Dtests.timezone=America/Lima
```

Issue is that in test 
https://github.com/opensearch-project/OpenSearch/blob/5db84d16a96932e4530ff1303bdd6edde52f4caf/server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java#L203-L204

It is picking a random node as specific node is not provided in ```internalCluster().clusterService()``` which results in the random behavior.

```isolatedNode``` should be passed here as internalCluster().clusterService(isolatedNode) so that it deterministically checks this node for clusterState update failed count. The test is passing locally consistently. will raise the PR.

**Comment by jaideep-m** [comment]
Q: Verify if the cluster state is guaranteed to be updated after the isolation
> Yes its guaranteed that the cluster state will be updated after the isolation

Tried reproducing the issue by running the test 1000 times. Its not reproducing now

**Comment by rajiv-kv** [comment]
Thanks @jaideep-m - this looks fixed with adding `isolatedNode` being passed as parameter
