### ISSUE TITLE
Failing tests on x86 for task test:fixtures:krb5kdc-fixture:postProcessFixture

### ISSUE THREAD

**Issue by Sunidhi-Gaonkar1** [opensearch-project/OpenSearch#12274]
### Describe the bug

Hi Team, I am working on validating OpenSearch v2.11.1 , I have followed the build steps mentioned in https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md and am observing failures for test `test:fixtures:krb5kdc-fixture:postProcessFixture` on x86 with following error:

```
./gradlew test:fixtures:krb5kdc-fixture:postProcessFixture --stacktrace
> Task :buildSrc:reaper:compileJava UP-TO-DATE
> Task :buildSrc:reaper:processResources NO-SOURCE
> Task :buildSrc:reaper:classes UP-TO-DATE
> Task :buildSrc:reaper:jar UP-TO-DATE
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:generateVersionProperties UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.6
  OS Info               : Linux 5.4.0-169-generic (ppc64le)
  JDK Version           : 20 (Eclipse Temurin JDK)
  JAVA_HOME             : /usr/local/jdk-20+36
  Random Testing Seed   : 5F594D4BA762E903
  In FIPS 140 mode      : false
=======================================
> Task :libs:opensearch-cli:processResources NO-SOURCE
> Task :libs:opensearch-common:processResources UP-TO-DATE
> Task :libs:opensearch-compress:processResources UP-TO-DATE
> Task :libs:opensearch-core:processResources UP-TO-DATE
> Task :libs:opensearch-geo:processResources NO-SOURCE
> Task :libs:opensearch-plugin-classloader:processResources NO-SOURCE
> Task :libs:opensearch-secure-sm:processResources NO-SOURCE
> Task :libs:opensearch-x-content:processResources UP-TO-DATE
> Task :libs:opensearch-telemetry:processResources NO-SOURCE
> Task :server:extractProto UP-TO-DATE
> Task :libs:opensearch-common:compileJava UP-TO-DATE
> Task :libs:opensearch-cli:compileJava UP-TO-DATE
> Task :libs:opensearch-common:classes UP-TO-DATE
> Task :server:extractIncludeProto UP-TO-DATE
> Task :libs:opensearch-common:compileJava20Java UP-TO-DATE
> Task :libs:opensearch-common:processJava20Resources NO-SOURCE
> Task :libs:opensearch-common:java20Classes UP-TO-DATE
> Task :server:generateProto UP-TO-DATE
> Task :libs:opensearch-common:jar UP-TO-DATE
> Task :libs:opensearch-core:compileJava UP-TO-DATE
> Task :libs:opensearch-geo:compileJava UP-TO-DATE
> Task :libs:opensearch-compress:compileJava UP-TO-DATE
> Task :libs:opensearch-plugin-classloader:compileJava UP-TO-DATE
> Task :libs:opensearch-secure-sm:compileJava UP-TO-DATE
> Task :libs:opensearch-telemetry:compileJava UP-TO-DATE
> Task :libs:opensearch-x-content:compileJava UP-TO-DATE
> Task :plugins:repository-hdfs:processResources NO-SOURCE
> Task :client:rest:compileJava UP-TO-DATE
> Task :client:sniffer:compileJava UP-TO-DATE
> Task :libs:opensearch-nio:compileJava UP-TO-DATE
> Task :test:telemetry:compileJava UP-TO-DATE
> Task :plugins:repository-hdfs:copyPluginPropertiesTemplate UP-TO-DATE
> Task :plugins:repository-hdfs:pluginProperties UP-TO-DATE
> Task :plugins:repository-hdfs:copyYamlTestsTask NO-SOURCE
> Task :server:compileJava UP-TO-DATE
> Task :plugins:repository-hdfs:copyRestApiSpecsTask UP-TO-DATE
> Task :plugins:repository-hdfs:compileJava UP-TO-DATE
> Task :plugins:repository-hdfs:classes UP-TO-DATE
> Task :plugins:repository-hdfs:processTestResources UP-TO-DATE
> Task :server:generateModulesList UP-TO-DATE
> Task :server:generatePluginsList UP-TO-DATE
> Task :server:processResources UP-TO-DATE
> Task :test:framework:compileJava UP-TO-DATE
> Task :server:classes UP-TO-DATE
> Task :server:jar UP-TO-DATE
> Task :plugins:repository-hdfs:compileTestJava UP-TO-DATE
> Task :plugins:repository-hdfs:testClasses UP-TO-DATE
> Task :client:sniffer:processResources NO-SOURCE
> Task :client:sniffer:classes UP-TO-DATE
> Task :client:rest:processResources NO-SOURCE
> Task :client:rest:classes UP-TO-DATE
> Task :client:rest:jar UP-TO-DATE
> Task :libs:opensearch-cli:classes UP-TO-DATE
> Task :client:sniffer:jar UP-TO-DATE
> Task :libs:opensearch-compress:classes UP-TO-DATE
> Task :libs:opensearch-compress:jar UP-TO-DATE
> Task :libs:opensearch-core:classes UP-TO-DATE
> Task :libs:opensearch-cli:jar UP-TO-DATE
> Task :libs:opensearch-geo:classes UP-TO-DATE
> Task :libs:opensearch-geo:jar UP-TO-DATE
> Task :libs:opensearch-core:jar UP-TO-DATE
> Task :libs:opensearch-secure-sm:classes UP-TO-DATE
> Task :libs:opensearch-nio:processResources NO-SOURCE
> Task :libs:opensearch-nio:classes UP-TO-DATE
> Task :libs:opensearch-nio:jar UP-TO-DATE
> Task :libs:opensearch-telemetry:classes UP-TO-DATE
> Task :libs:opensearch-secure-sm:jar UP-TO-DATE
> Task :libs:opensearch-x-content:classes UP-TO-DATE
> Task :libs:opensearch-x-content:jar UP-TO-DATE
> Task :libs:opensearch-telemetry:jar UP-TO-DATE
> Task :test:framework:processResources UP-TO-DATE
> Task :test:framework:classes UP-TO-DATE
> Task :test:telemetry:processResources NO-SOURCE
> Task :test:telemetry:classes UP-TO-DATE
> Task :test:telemetry:jar UP-TO-DATE
> Task :test:framework:jar UP-TO-DATE
> Task :plugins:repository-hdfs:jarHell UP-TO-DATE
> Task :plugins:repository-hdfs:testingConventions UP-TO-DATE

> Task :test:fixtures:krb5kdc-fixture:composeBuild
Building peppa
Building hdfs

> Task :test:fixtures:krb5kdc-fixture:preProcessFixture UP-TO-DATE

> Task :test:fixtures:krb5kdc-fixture:composeUp
Starting 08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__peppa_1 ...
Starting 08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__hdfs_1  ...
Starting 08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__peppa_1 ... done
Starting 08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__hdfs_1  ... done
Gateway cannot be read from container inspection - trying to read from network inspection (network '08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__default')
Will use 172.18.0.1 (network 08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__default) as host of peppa
Gateway cannot be read from container inspection - trying to read from network inspection (network '08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__default')
Will use 172.18.0.1 (network 08b394ca661d8f827aefdafee1213473_krb5kdc-fixture__default) as host of hdfs

> Task :test:fixtures:krb5kdc-fixture:composeDownForcedOnFailure SKIPPED
> Task :test:fixtures:krb5kdc-fixture:buildFixture
> Task :test:fixtures:krb5kdc-fixture:postProcessFixture FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/user4/sunidhi/opensearch/test/fixtures/krb5kdc-fixture/build.gradle' line: 51

* What went wrong:
Execution failed for task ':test:fixtures:krb5kdc-fixture:postProcessFixture'.
> assert confTemplate.exists()
         |            |
         |            false
         /home/user4/sunidhi/opensearch/test/fixtures/krb5kdc-fixture/testfixtures_shared/shared/peppa/krb5.conf.template

* Try:
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test:fixtures:krb5kdc-fixture:postProcessFixture'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: Assertion failed:

assert confTemplate.exists()
       |            |
       |            false
       /home/user4/sunidhi/opensearch/test/fixtures/krb5kdc-fixture/testfixtures_shared/shared/peppa/krb5.conf.template

        at build_8rss8yrmdslmkbnxcsdiy2k84$_run_closure2$_closure7$_closure8.doCall$original(/home/user4/sunidhi/opensearch/test/fixtures/krb5kdc-fixture/build.gradle:51)
        at build_8rss8yrmdslmkbnxcsdiy2k84$_run_closure2$_closure7$_closure8.doCall(/home/user4/sunidhi/opensearch/test/fixtures/krb5kdc-fixture/build.gradle)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.doExecute(AbstractTask.java:784)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.lambda$execute$0(AbstractTask.java:771)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:97)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:771)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:746)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:247)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:232)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:215)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:198)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:165)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:64)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:42)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
        at org.gradle.internal.Either$Right.fold(Either.java:175)
        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:76)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:76)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:37)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:106)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:55)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:292)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:66)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:66)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:38)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:36)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:26)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:47)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)


BUILD FAILED in 10s
61 actionable tasks: 3 executed, 58 up-to-date

```

### Related component

Other

### To Reproduce

1 Install JDK 11,Docker & Docker Compose
2 Clone the repository
3 ./gradlew
4 ./gradlew check

### Expected behavior

Tests should pass.

### Additional Details

Host/Environment (please complete the following information):
 - OS: Ubuntu
 - Version 20.04.6

Not sure if I am missing something, any pointers regarding this will be helpful, Thank you.

**Comment by Sunidhi-Gaonkar1** [comment]
Hi @peternied , Sorry my bad, I was cross-checking the logs and accidentally attached the ppc64le logs. I have pasted the x86 logs below for v2.12.0. Thank you.

```
$ ./gradlew plugins:repository-hdfs:secureHdfsFixture
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.6
  OS Info               : Linux 4.18.0-372.32.1.el8_6.x86_64 (amd64)
  JDK Version           : 11 (Ubuntu JDK)
  JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
  Random Testing Seed   : 176B159EA19A04CC
  In FIPS 140 mode      : false
=======================================

> Task :libs:opensearch-common:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test:fixtures:krb5kdc-fixture:composeBuild
Building peppa
Building hdfs

> Task :libs:opensearch-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :libs:opensearch-x-content:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :server:compileJava
Note: Processing Log4j annotations
Note: Annotations processed
Note: Processing OpenSearch Api annotations
Note: The element org.opensearch.common.inject.Module is part of the public APIs but is not marked as @PublicApi, @ExperimentalApi or @DeprecatedApi (referenced by org.opensearch.plugins.Plugin)
Note: Processing Log4j annotations
Note: No elements to process
Note: Processing OpenSearch Api annotations
/opensearch/server/src/main/java/org/opensearch/common/network/NetworkModule.java:312: warning: no description for @param
         * @param <T>
           ^
/opensearch/server/src/main/java/org/opensearch/index/codec/fuzzy/LongArrayBackedBitSet.java:42: warning: no description for @throws
     * @throws IOException
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 warnings

> Task :test:framework:compileJava
Note: Processing Log4j annotations
Note: Annotations processed
Note: Processing Log4j annotations
Note: No elements to process
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :plugins:repository-hdfs:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :test:fixtures:krb5kdc-fixture:composeUp
Creating bf00347bdf8445cfac5662a914e39336_krb5kdc-fixture__hdfs_1 ...
Creating bf00347bdf8445cfac5662a914e39336_krb5kdc-fixture__peppa_1 ...
Creating bf00347bdf8445cfac5662a914e39336_krb5kdc-fixture__peppa_1 ... done
Creating bf00347bdf8445cfac5662a914e39336_krb5kdc-fixture__hdfs_1  ... done
Will use 172.18.0.1 (network bf00347bdf8445cfac5662a914e39336_krb5kdc-fixture__default) as host of peppa
More forwarded TCP ports for service 'peppa:4444 [[HostIp:0.0.0.0, HostPort:32783], [HostIp:::, HostPort:32783]]'. Will use the first one.
More forwarded UDP ports for service 'peppa:88 [[HostIp:0.0.0.0, HostPort:32775], [HostIp:::, HostPort:32775]]'. Will use the first one.
Will use 172.18.0.1 (network bf00347bdf8445cfac5662a914e39336_krb5kdc-fixture__default) as host of hdfs
More forwarded TCP ports for service 'hdfs:4444 [[HostIp:0.0.0.0, HostPort:32784], [HostIp:::, HostPort:32784]]'. Will use the first one.
More forwarded UDP ports for service 'hdfs:88 [[HostIp:0.0.0.0, HostPort:32776], [HostIp:::, HostPort:32776]]'. Will use the first one.
Probing TCP socket on 172.18.0.1:32783 of 'peppa_1'
TCP socket on 172.18.0.1:32783 of 'peppa_1' is ready
Probing TCP socket on 172.18.0.1:32784 of 'hdfs_1'
TCP socket on 172.18.0.1:32784 of 'hdfs_1' is ready
+---------+----------------+------------------+
| Name    | Container Port | Mapping          |
+---------+----------------+------------------+
| peppa_1 | 4444           | 172.18.0.1:32783 |
+---------+----------------+------------------+
| hdfs_1  | 4444           | 172.18.0.1:32784 |
+---------+----------------+------------------+

> Task :test:fixtures:krb5kdc-fixture:postProcessFixture FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/opensearch/test/fixtures/krb5kdc-fixture/build.gradle' line: 51

* What went wrong:
Execution failed for task ':test:fixtures:krb5kdc-fixture:postProcessFixture'.
> assert confTemplate.exists()
         |            |
         |            false
         /opensearch/test/fixtures/krb5kdc-fixture/testfixtures_shared/shared/peppa/krb5.conf.template

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BUILD FAILED in 35m 37s
63 actionable tasks: 57 executed, 6 up-to-date
```
