### ISSUE TITLE
[BUG] Container does not start on Apple M1

### ISSUE THREAD

**Issue by hsimpson** [opensearch-project/OpenSearch#1253]
**Describe the bug**
Trying to use the latest Docker image "opensearchproject/opensearch:latest" which looks like it is (1.0.1) within my "docker-compose.yml":
```yaml
opensearch:
  image: opensearchproject/opensearch:latest
  restart: always
  environment:
    - discovery.type=single-node
    - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
    - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
      hard: 65536
  volumes:
    - opensearch-data:/usr/share/opensearch/data
  ports:
    - '9200:9200'
    - '9600:9600' # required for Performance Analyzer
  networks:
    - opensearch
```
When it try to starup this error occurs:
```shell
Exception in thread "main" java.io.IOException: Cannot run program "/usr/share/opensearch/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 327, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.opensearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:127)
	at org.opensearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:101)
	at org.opensearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:72)
	at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:152)
	at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:110)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 327, exit value: 1
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 6 more
Killing performance analyzer process 21
OpenSearch exited with code 1
Performance analyzer exited with code 143
```

**To Reproduce**
1. Create a "docker-compose.yml" with above settings
2. `docker-compose up'
3. See error

**Expected behavior**
Container should run

**Host/Environment (please complete the following information):**
 - OS: macOS Big Sur 11.5.2 (20G95)
 - Chip Apple M1
 - Docker info:
 ```shell
Server Version: 20.10.8
Kernel Version: 5.10.47-linuxkit
Operating System: Docker Desktop
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 3.841GiB
```

**Comment by tamanugi** [comment]
I'm facing same issue 😇 

I used `opensearch staging / opensearch: 1.0.0-multi-test` instead and it worked fine 👍

**Comment by saratvemulapalli** [comment]
Thanks for reaching out. Will transfer this to opensearch-build who builds our docker images.
