### ISSUE TITLE
[BUG] [Remote Store] ClassCastException during translog upload - NullPointerException cannot be cast to FileTransferException

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#12544]
### Describe the bug

During translog uploads, any failures in onResponse callback will lead to onFailure callback being executed with specific exception which occurred in onResponse. 

But in our case the onFailure callback fails with ClassCastException if the exception type is not FileTransferException. So when onResponse callback fails with a NullPointerException, we try to cast it to FileTransferException, which leads to ClassCastException and swallow the actual NullPointerException.

https://github.com/opensearch-project/OpenSearch/blob/cf1a0a29d6e5d59adef4a49b9c8eb00e9fea57da/server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java#L125-L141

To root cause the actual NullPointerException we need to know what caused it, so we onFailure callback to log the exception before trying to cast to FileTransferException

### Related component

Storage:Remote

### To Reproduce

<No definitive steps yet to reproduce this.>

### Expected behavior

Ideally even the NullPointerException should not come, but to solve that we first need to add some logging to understand the cause of NullPointerException next time we encounter this.

### Additional Details

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux 2
 - Version 2.11

**Additional context**
ClassCastException trace

```
[2024-03-04T08:00:22,318][ERROR][o.o.i.t.t.BlobStoreTransferService] [ed772283e38d0efe747a289e3369f8c1] Failed to upload blob translog-685.tlog
java.lang.ClassCastException: class java.lang.NullPointerException cannot be cast to class org.opensearch.index.translog.transfer.FileTransferException (java.lang.NullPointerException is in module java.base of loader 'bootstrap'; org.opensearch.index.translog.transfer.FileTransferException is in unnamed module of loader 'app')
        at org.opensearch.index.translog.transfer.TranslogTransferManager.lambda$transferSnapshot$0(TranslogTransferManager.java:129)
        at org.apache.logging.log4j.util.LambdaUtil.get(LambdaUtil.java:77)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1962)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1807)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:768)
        at org.opensearch.index.translog.transfer.TranslogTransferManager.lambda$transferSnapshot$1(TranslogTransferManager.java:128)
        at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90)
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:84)
        at org.opensearch.action.LatchedActionListener.onResponse(LatchedActionListener.java:58)
        at org.opensearch.index.translog.transfer.BlobStoreTransferService.lambda$uploadBlob$4(BlobStoreTransferService.java:133)
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82)
        at org.opensearch.core.action.ActionListener$6.onResponse(ActionListener.java:301)
        at org.opensearch.repositories.s3.S3BlobContainer.lambda$asyncBlobUpload$5(S3BlobContainer.java:238)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.opensearch.repositories.s3.async.AsyncTransferManager.lambda$handleExceptionOrResponse$14(AsyncTransferManager.java:241)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:69)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:177)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:238)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)




  at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:69)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:177)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:238)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:858)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassCastException: class java.lang.NullPointerException cannot be cast to class org.opensearch.index.translog.transfer.FileTransferException (java.lang.NullPointerException is in module java.base of loader 'bootstrap'; org.opensearch.index.translog.transfer.FileTransferException is in unnamed module of loader 'app')
        at org.opensearch.index.translog.transfer.TranslogTransferManager.lambda$transferSnapshot$0(TranslogTransferManager.java:129)
        at org.apache.logging.log4j.util.LambdaUtil.get(LambdaUtil.java:77)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1962)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1807)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:768)
        at org.opensearch.index.translog.transfer.TranslogTransferManager.lambda$transferSnapshot$1(TranslogTransferManager.java:128)
        at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90)
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:84)
        at org.opensearch.action.LatchedActionListener.onResponse(LatchedActionListener.java:58)
        at org.opensearch.index.translog.transfer.BlobStoreTransferService.lambda$uploadBlob$4(BlobStoreTransferService.java:133)
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82)
```

**Comment by linuxpi** [comment]
Will raise a PR to add sufficient logging to get to the root cause of NullPointerException
