### ISSUE TITLE
[BUG] org.opensearch.indices.stats.IndexStatsIT.testFilterCacheStats is flaky

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#12610]
### Describe the bug

Gradle check failure: https://build.ci.opensearch.org/job/gradle-check/34668/consoleFull

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.stats.IndexStatsIT" -Dtests.method="testFilterCacheStats {p0={"cluster.indices.replication.strategy":"SEGMENT"}}" -Dtests.seed=DD7603082E5D7F87 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-SA -Dtests.timezone=Pacific/Guam -Druntime.java=21
  2> java.lang.AssertionError: 
    Expected: <5L>
         but: was <-1L>
        at __randomizedtesting.SeedInfo.seed([DD7603082E5D7F87:B849FE4D9E5578FE]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.indices.stats.IndexStatsIT.persistGlobalCheckpoint(IndexStatsIT.java:1508)
        at org.opensearch.indices.stats.IndexStatsIT.testFilterCacheStats(IndexStatsIT.java:1254)
```
### Related component

Indexing:Replication

### To Reproduce

Not able to reproduce.

### Expected behavior

Test should always succeed

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/andrross) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek)]
@ankitkala Thanks for filing this issue.
