### ISSUE TITLE
[BUG] org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.* are flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#12664]
### Describe the bug

A number of `org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.*` are flaky:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
	at __randomizedtesting.SeedInfo.seed([65E3DFFD00C5A81B:1710CEB101EDB3A6]:0)
	at org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.testAdmissionControlRejectionEnforcedMode(AdmissionControlSingleNodeTests.java:102)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Other

### To Reproduce

```
./gradlew ':server:test' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.testAdmissionControlRejectionEnforcedMode" -Dtests.seed=65E3DFFD00C5A81B
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI
 
**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/34896/

**Comment by ajaymovva** [comment]
Not able to reproduce in 300 iterations debugging further
```
➜  OpenSearch git:(main) ./gradlew ':server:test' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.testAdmissionControlRejectionMonitorOnlyMode" -Dtests.seed=14E018DE8C6ECC4B -Dtests.iters=300

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.6
  OS Info               : Mac OS X 14.3.1 (aarch64)
  JDK Version           : 21 (Amazon Corretto JDK)
  JAVA_HOME             : /Users/movvaam/.sdkman/candidates/java/21.0.2-amzn
  Random Testing Seed   : 14E018DE8C6ECC4B
  In FIPS 140 mode      : false
=======================================

> Task :server:test
WARNING: Using incubator modules: jdk.incubator.vector
Mar 14, 2024 7:21:10 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/Users/movvaam/AWS/OpenSource/core/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/Users/movvaam/.gradle/wrapper/dists/gradle-8.6-all/3mbtmo166bl6vumsh5k2lkq5h/gradle-8.6/lib/plugins/gradle-testing-base-8.6.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 8m 35s

```

**Comment by reta** [comment]
> Not able to reproduce in 300 iterations debugging further

Please try to reproduce without `-Dtests.seed=14E018DE8C6ECC4B` , the issue is there

**Comment by ajaymovva** [comment]
On Mac: 

```
➜  OpenSearch git:(main) ./gradlew ':server:test' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.testAdmissionControlRejectionEnforcedMode" -Dtests.iters=100                              

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.6
  OS Info               : Mac OS X 14.3.1 (aarch64)
  JDK Version           : 21 (Amazon Corretto JDK)
  JAVA_HOME             : /Users/movvaam/.sdkman/candidates/java/21.0.2-amzn
  Random Testing Seed   : 732CED713A830FB3
  In FIPS 140 mode      : false
=======================================

> Task :server:test
WARNING: Using incubator modules: jdk.incubator.vector
Mar 14, 2024 7:44:48 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>

BUILD SUCCESSFUL in 2m 37s
54 actionable tasks: 1 executed, 53 up-to-date

➜  OpenSearch git:(main) ./gradlew ':server:test' --tests "org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.testAdmissionControlRejectionMonitorOnlyMode" -Dtests.iters=100

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.6
  OS Info               : Mac OS X 14.3.1 (aarch64)
  JDK Version           : 21 (Amazon Corretto JDK)
  JAVA_HOME             : /Users/movvaam/.sdkman/candidates/java/21.0.2-amzn
  Random Testing Seed   : B23CAC66FF9FC526
  In FIPS 140 mode      : false
=======================================

> Task :server:test
WARNING: Using incubator modules: jdk.incubator.vector
Mar 14, 2024 7:48:36 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>

BUILD SUCCESSFUL in 2m 37s
54 actionable tasks: 1 executed, 53 up-to-date

```

**Comment by reta** [comment]
@ajaymovva this is a problem with a flaky tests - it is difficult to reproduce, another occurrence: 
 - https://build.ci.opensearch.org/job/gradle-check/34905/testReport/junit/org.opensearch.ratelimitting.admissioncontrol/AdmissionControlSingleNodeTests/testAdmissionControlRejectionEnforcedMode/

**Comment by andrross** [comment]
I created a revert PR #12670 to unblock things while we figure out the test failures

**Comment by reta** [comment]
Closing, the change has been reverted https://github.com/opensearch-project/OpenSearch/commit/f37b6ac69fd4e778d6e193e7d19ad4b827e80eb0

**Comment by harishbhakuni** [comment]
test org.opensearch.ratelimitting.admissioncontrol.AdmissionControlSingleNodeTests.testAdmissionControlRejectionMonitorOnlyMode is still flaky and failing here: https://build.ci.opensearch.org/job/gradle-check/34952/

**Comment by reta** [comment]
@harishbhakuni please rebase against the target branch, the commits which introduced the issue where reverted
