### ISSUE TITLE
[BUG] org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}

### ISSUE THREAD

**Issue by shwetathareja** [opensearch-project/OpenSearch#12799]
### Describe the bug

Flaky test

java.lang.AssertionError: expected:<0> but was:<1>
	at __randomizedtesting.SeedInfo.seed([C947BA1B67BC1110:8A1D534D51CC4613]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.opensearch.search.SearchTimeoutIT.testSimpleTimeout(SearchTimeoutIT.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)

https://build.ci.opensearch.org/job/gradle-check/35486/testReport/junit/org.opensearch.search/SearchTimeoutIT/testSimpleTimeout__p0___search_concurrent_segment_search_enabled___true___/

### Related component

Search

### To Reproduce

./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchTimeoutIT" -Dtests.method="testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}" -Dtests.seed=C947BA1B67BC1110 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pl-PL -Dtests.timezone=Antarctica/McMurdo -Druntime.java=21

### Expected behavior

.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by jed326** [comment]
Think this may be a duplicate:
- https://github.com/opensearch-project/OpenSearch/issues/9401

**Comment by peternied** [comment]
Closing in favor of https://github.com/opensearch-project/OpenSearch/issues/9401
