### ISSUE TITLE
[BUG] org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithMultipleIndices if flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#12802]
### Describe the bug

The test case `org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithMultipleIndices` if flaky:

```
java.lang.AssertionError: 
Expected: an empty iterable
     but: [<UnavailableShardsException[[test-3][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-3][7]] containing [index {[test-3][4], source[{"candidate":true}]}]]]>,<UnavailableShardsException[[test-4][5] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-4][5]] containing [index {[test-4][0], source[{"candidate":true}]}]]]>,<UnavailableShardsException[[test-4][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-4][7]] containing [index {[test-4][12], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-3][6] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-3][6]] containing [index {[test-3][14], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-3][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-3][7]] containing [index {[test-3][12], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-3][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-3][4]] containing [index {[test-3][8], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-4][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-4][4]] containing [index {[test-4][15], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-4][6] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-4][6]] containing [index {[test-4][14], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-3][5] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-3][5]] containing [index {[test-3][0], source[{"candidate":true}]}]]]>,<UnavailableShardsException[[test-3][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-3][4]] containing [index {[test-3][15], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-4][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-4][7]] containing [index {[test-4][13], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-3][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-3][7]] containing [index {[test-3][13], source[{"candidate":false}]}]]]>,<UnavailableShardsException[[test-4][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test-4][4]] containing [index {[test-4][8], source[{"candidate":false}]}]]]>]
	at __randomizedtesting.SeedInfo.seed([9466FD311F6CC6D4:AC56840045FA8252]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.test.OpenSearchIntegTestCase.indexRandom(OpenSearchIntegTestCase.java:1590)
	at org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithMultipleIndices(DeleteByQueryBasicTests.java:140)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Search

### To Reproduce

```
 ./gradlew ':modules:reindex:test' --tests "org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithMultipleIndices" -Dtests.seed=9466FD311F6CC6D4
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI
 - 
**Additional context**
 - https://build.ci.opensearch.org/job/gradle-check/35503/testReport/junit/org.opensearch.index.reindex/DeleteByQueryBasicTests/testDeleteByQueryWithMultipleIndices/

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/) [6](https://github.com/srikanthpadakanti) [7](https://github.com/Mahima081)]
@reta Thanks for filing

**Comment by sandeshkr419** [comment]
Closing this issue since we haven't been seeing this test as flaky for a while and if it happens again then `opensearch-ci-bot` will open up the issue back automatically.
