### ISSUE TITLE
[BUG] [] Cluster state reponse handling thread blocked

### ISSUE THREAD

**Issue by shwetathareja** [opensearch-project/OpenSearch#12820]
### Describe the bug

Observed this during gradle-check run for https://github.com/opensearch-project/OpenSearch/pull/12813#issuecomment-2011604246

https://build.ci.opensearch.org/job/gradle-check/35542/console

3 generic threads were blocked for processing publication response (it was 3 node cluster in test)

```
Thread[id=5851, name=opensearch[node_t0][generic][T#2], state=BLOCKED, group=TGRP-SearchWeightedRoutingIT]
  2>         at org.opensearch.cluster.coordination.Coordinator$5.onResponse(Coordinator.java:1381)
  2>         at org.opensearch.cluster.coordination.PublicationTransportHandler$PublicationContext$3.handleResponse(PublicationTransportHandler.java:442)
  2>         at org.opensearch.cluster.coordination.PublicationTransportHandler$PublicationContext$3.handleResponse(PublicationTransportHandler.java:433)
  2>         at org.opensearch.telemetry.tracing.handler.TraceableTransportResponseHandler.handleResponse(TraceableTransportResponseHandler.java:72)
  2>         at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1501)
  2>         at org.opensearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:420)
  2>         at org.opensearch.transport.InboundHandler.lambda$handleResponse$3(InboundHandler.java:414)
  2>         at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854)
  2>         at java.****/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  2>         at java.****/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
```
All the threads were probably waiting on below mutex :

https://github.com/opensearch-project/OpenSearch/blob/f3d2beee637f63e38c8f26dbcee9f2a82f9c87b6/server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java#L1376-L1392

### Related component

Cluster Manager

### Expected behavior

Investigate which code path was holding mutex and it can be optimized. Right now, it is not clear for how long the threads were blocked.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/) [6](https://github.com/srikanthpadakanti) [7](https://github.com/Mahima081)]
@shwetathareja Thanks for creating this issue

**Comment by rajiv-kv** [comment]
[Attendees - [1](https://github.com/sumitasr), [2](https://github.com/Pranshu-S), [3](https://github.com/rajiv-kv)] 
Next Steps
- Verify if the test is flaky 
- Understand as to why the state publication is performed from generic threadpool
