### ISSUE TITLE
[BUG] org.opensearch.indices.store.IndicesStoreIntegrationIT.testShardActiveElsewhereDoesNotDeleteAnother with remote store enabled is flaky

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#12835]
### Describe the bug

org.opensearch.indices.store.IndicesStoreIntegrationIT.testShardActiveElsewhereDoesNotDeleteAnother

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=2648, name=opensearch[node_t1][remote_refresh_retry][T#1], state=RUNNABLE, group=TGRP-IndicesStoreIntegrationIT]
	at __randomizedtesting.SeedInfo.seed([D0CBB573CE1C86B1:636A211921CEDAC3]:0)
Caused by: org.opensearch.core.concurrency.OpenSearchRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@299ba45c[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@11232e88[Wrapped task = [threaded] org.opensearch.index.shard.ReleasableRetryableRefreshListener$$Lambda/0x00007f39bcba8f88@53ce2a03]] on org.opensearch.threadpool.Scheduler$SafeScheduledThreadPoolExecutor@641c0c3b[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 15]
	at __randomizedtesting.SeedInfo.seed([D0CBB573CE1C86B1]:0)
	at app//org.opensearch.common.util.concurrent.OpenSearchAbortPolicy.rejectedExecution(OpenSearchAbortPolicy.java:67)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
	at java.base@21.0.2/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base@21.0.2/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at app//org.opensearch.threadpool.ThreadPool.schedule(ThreadPool.java:469)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.scheduleRetry(ReleasableRetryableRefreshListener.java:125)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.scheduleRetry(ReleasableRetryableRefreshListener.java:178)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.runAfterRefreshWithPermit(ReleasableRetryableRefreshListener.java:167)
	at app//org.opensearch.index.shard.ReleasableRetryableRefreshListener.lambda$scheduleRetry$2(ReleasableRetryableRefreshListener.java:126)
	at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Storage:Durability

### To Reproduce

See https://github.com/opensearch-project/OpenSearch/pull/12817

### Expected behavior

Test always passes.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied/) [2](https://github.com/lukas-vlcek/) [3](https://github.com/cwperks) [4](https://github.com/scrawfor99) [5](https://github.com/reta/) [6](https://github.com/srikanthpadakanti) [7](https://github.com/Mahima081)]
@dblock Thanks for creating this issue.

**Comment by skumawat2025** [comment]
This got fixed with https://github.com/opensearch-project/OpenSearch/pull/13301.
tests were run 9000+ times, and the issue did not reproduce.
