### ISSUE TITLE
Exception while creating a PIT with high level client

### ISSUE THREAD

**Issue by aravind-musigumpula** [opensearch-project/OpenSearch#13144]
### Describe the bug

I am using opensearch rest high level client 2.12.0 and java version 21.
While trying to create a PIT in opensearch, getting the below exception:
```
java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class org.opensearch.common.unit.TimeValue
	at org.opensearch.core.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:863)
	at org.opensearch.core.xcontent.XContentBuilder.value(XContentBuilder.java:834)
	at org.opensearch.core.xcontent.XContentBuilder.field(XContentBuilder.java:819)
	at org.opensearch.action.search.CreatePitRequest.toXContent(CreatePitRequest.java:185)
	at org.opensearch.core.xcontent.XContentHelper.toXContent(XContentHelper.java:46)
	at org.opensearch.client.RequestConverters.createEntity(RequestConverters.java:829)
	at org.opensearch.client.RequestConverters.createEntity(RequestConverters.java:825)
	at org.opensearch.client.RequestConverters.createPit(RequestConverters.java:498)
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1914)
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1884)
	at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1852)
	at org.opensearch.client.RestHighLevelClient.createPit(RestHighLevelClient.java:1273)
	at io.trino.plugin.opensearch.client.BackpressureRestHighLevelClient.lambda$createPointInTime$3(BackpressureRestHighLevelClient.java:150)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
	at io.trino.plugin.opensearch.client.BackpressureRestHighLevelClient.executeWithRetries(BackpressureRestHighLevelClient.java:129)
	at io.trino.plugin.opensearch.client.BackpressureRestHighLevelClient.createPointInTime(BackpressureRestHighLevelClient.java:150)
	at io.trino.plugin.opensearch.client.OpenSearchClient.createPITRequest(OpenSearchClient.java:601)
	at io.trino.plugin.opensearch.OpenSearchSplitManager.getSplits(OpenSearchSplitManager.java:70)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:89)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.createSplitSource(SplitSourceFactory.java:183)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitFilter(SplitSourceFactory.java:254)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitFilter(SplitSourceFactory.java:130)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:74)
	at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:110)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1051)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:927)
```

Any idea how to solve this?

### Related component

Clients

### Expected behavior

When creating PIT using high level client, PIT should be created and PITResponse should be returned.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by Hailong-am** [comment]
@aravind-musigumpula can you share your createPitRequest?

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/vikasvb90
) [4](https://github.com/andrross
) [5](https://github.com/lukas-vlcek/
) [6](https://github.com/srikanthpadakanti)]
@aravind-musigumpula thanks for creating this issue - it would be helpful if you could update the descriptions repro steps as @Hailong-am requested.

**Comment by aravind-musigumpula** [comment]
This is how I am creating PIT request

`
CreatePitRequest pitRequest = new CreatePitRequest(new TimeValue(60000), true, index);
restHighLevelClient.createPit(pitRequest, RequestOptions.DEFAULT));
`

**Comment by peternied** [comment]
@aravind-musigumpula Could you writing out the step by step instructions including create the index, populating it and then the request to create the PIT?  For example see this bug that has specific reproduction steps and expectations for them [1]

Alternatively, if you update one of the test cases to reproduce the failure that would be good too, then you can publish a draft PR so it can be shared and investigated by members of the community, what do you think?


- [1] https://github.com/opensearch-project/OpenSearch/issues/13079

**Comment by aravind-musigumpula** [comment]
Hi @peternied 
If you see the stack trace provided, Request haven't reached opensource yet. It failed when building request for opensource.
So irrespective of how the index is created, we get this error.(Added the steps)

**Comment by Hailong-am** [comment]
thanks @aravind-musigumpula, i am trying to setup same in my local to see whether i can reproduce this error

**Comment by aravind-musigumpula** [comment]
Some similar issues I have found :
https://github.com/elastic/elasticsearch/issues/31853
https://github.com/elastic/elasticsearch/issues/68617

**Comment by Hailong-am** [comment]
> elastic/elasticsearch#68617

By looking into this, it should be same cause as explained https://github.com/elastic/elasticsearch/issues/68617#issuecomment-904361805
