### ISSUE TITLE
[BUG] org.opensearch.common.util.concurrent.AbstractAsyncTaskTests.testAutoRepeat is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#13169]
### Describe the bug

The test case org.opensearch.common.util.concurrent.AbstractAsyncTaskTests.testAutoRepeat is flaky:

```
java.lang.AssertionError: interrupted
	at __randomizedtesting.SeedInfo.seed([DD4EBA07C4C6FEE9]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.common.util.concurrent.AbstractAsyncTaskTests$1.runInternal(AbstractAsyncTaskTests.java:85)
	at org.opensearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:159)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Other

### To Reproduce

```
./gradlew ':server:test' --tests "org.opensearch.common.util.concurrent.AbstractAsyncTaskTests.testAutoRepeat" -Dtests.seed=DD4EBA07C4C6FEE9
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
 - https://build.ci.opensearch.org/job/gradle-check/36856/testReport/junit/org.opensearch.common.util.concurrent/AbstractAsyncTaskTests/testAutoRepeat/

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@reta Thanks for creating this issue.

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14316
