### ISSUE TITLE
[BUG] org.opensearch.search.CrossClusterSearchUnavailableClusterIT.testSearchSkipUnavailable

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#13278]
### Describe the bug

```


org.opensearch.search.CrossClusterSearchUnavailableClusterIT > testSearchSkipUnavailable FAILED
    [remote1:index] OpenSearchStatusException[OpenSearch exception [type=index_not_found_exception, reason=no such index [remote1:index]]]
        at __randomizedtesting.SeedInfo.seed([6F72FDAAD0C11A3D:B56172678EB6A1D4]:0)
        at app//org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:210)
        at app//org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2235)
        at app//org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2212)
        at app//org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1931)
        at app//org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1884)
        at app//org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1852)
        at app//org.opensearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1095)
        at app//org.opensearch.search.CrossClusterSearchUnavailableClusterIT.testSearchSkipUnavailable(CrossClusterSearchUnavailableClusterIT.java:177)

```

### Related component

Search

### To Reproduce

```
REPRODUCE WITH: ./gradlew ':qa:ccs-unavailable-clusters:integTest' --tests "org.opensearch.search.CrossClusterSearchUnavailableClusterIT.testSearchSkipUnavailable" -Dtests.seed=6F72FDAAD0C11A3D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-NI -Dtests.timezone=Europe/Brussels -Druntime.java=21
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
CI

**Additional context**

**Comment by owaiskazi19** [comment]
not a flaky test but related
