### ISSUE TITLE
[BUG] org.opensearch.indices.IndicesRequestCacheIT.testStaleKeysCleanupWithLowThreshold {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}} is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#13540]
### Describe the bug

The test case `org.opensearch.indices.IndicesRequestCacheIT.testStaleKeysCleanupWithLowThreshold {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}` is flaky:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([F5E7FF9737DAEC01:67C83A7F84D4002A]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.opensearch.indices.IndicesRequestCacheIT.testStaleKeysCleanupWithLowThreshold(IndicesRequestCacheIT.java:782)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Storage:Remote

### To Reproduce

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.IndicesRequestCacheIT" -Dtests.method="testStaleKeysCleanupWithLowThreshold {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}" -Dtests.seed=F5E7FF9737DAEC01 -Dtests.security.manager=true
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**

**Comment by reta** [comment]
@sohami @sgup432  @kiranprakash154 it might be caused by https://github.com/opensearch-project/OpenSearch/pull/12941

**Comment by kiranprakash154** [comment]
Thanks @reta, I will take a look.

**Comment by kiranprakash154** [comment]
This suite seems to be timing out as observed in this PR - https://github.com/opensearch-project/OpenSearch/pull/13553
build - https://build.ci.opensearch.org/job/gradle-check/38388/
```
Test abandoned because suite timeout was reached.
```

**Comment by reta** [comment]
It might but not in this case (see please description)

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/dbwiddis) [3](https://github.com/reta/) [4](https://github.com/vikasvb90/)]
@reta Thanks for filing

**Comment by kiranprakash154** [comment]
I agree this is a 2 fold problem, my comment was intended for that, but i'll make it more obvious by adding "also". Thanks for pointing out.

**Comment by kiranprakash154** [comment]
I created a seperate issue to solve the problem of the test suite timing out - https://github.com/opensearch-project/OpenSearch/issues/13734

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14288
