### ISSUE TITLE
[Feature Request] Log the actual exception for InternalTestCluster shardLock failure

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch#13628]
### Is your feature request related to a problem? Please describe

When i troubleshoot a flaky test of https://github.com/opensearch-project/ml-commons/issues/2436 

the error message report the the test is below, it tells that shard [.plugins-ml-config][0] is still locked for somehow, there is no reason/details logged. It's inconvenient to know why the shard is still locked.

```
java.lang.AssertionError: Shard [.plugins-ml-config][0] is still locked after 5 sec waiting
        at __randomizedtesting.SeedInfo.seed([CC4F8C51F54E62C2:CF7AF5C5193A2F89]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2773)
```

https://github.com/opensearch-project/OpenSearch/blob/cd55bca3ee32d5754018e994b1b87799c1bffc32/test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java#L2769-L2774

### Describe the solution you'd like

As shared lock will have a detail/reason of why shard been locked, it would be better we log the exception which contains the detail of existing lock and then fail the test case.

https://github.com/opensearch-project/OpenSearch/blob/cd55bca3ee32d5754018e994b1b87799c1bffc32/server/src/main/java/org/opensearch/env/NodeEnvironment.java#L728-L742

```java
try {
    env.shardLock(id, "InternalTestCluster assert after test", TimeUnit.SECONDS.toMillis(5)).close();
} catch (ShardLockObtainFailedException ex) {
    // would like to log out the ex that will helps to troubleshoot
    // logger.error(ex);
    fail("Shard " + id + " is still locked after 5 sec waiting");
}
```

the log should be similar like below, `lock already held for [starting shard]` this is the reason why it still been locked.
```
org.opensearch.env.ShardLockObtainFailedException: [.plugins-ml-config][0]: obtaining shard lock for [InternalTestCluster assert after test] timed out after [5000ms], lock already held for [starting shard] with age [20365ms]
	at org.opensearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:877) ~[opensearch-2.15.0-SNAPSHOT.jar:2.15.0-SNAPSHOT]
```

### Related component

Other

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@Hailong-am Thanks for creating this issue, could you create a pull request for this issue?
