### ISSUE TITLE
[Snapshot Interop] Shallow copy snapshots failing for closed indices

### ISSUE THREAD

**Issue by harishbhakuni** [opensearch-project/OpenSearch#13805]
### Describe the bug

We recently found out a issue where shallow copy snapshots are failing for closed indices. However full copy succeeds for those indices.

```
Snapshot shard failed
java.nio.file.NoSuchFileException: Metadata file is not present for given primary term 2 and generation 6
    at org.opensearch.index.store.RemoteSegmentStoreDirectory.getMetadataFileForCommit(RemoteSegmentStoreDirectory.java:527)
    at org.opensearch.index.store.RemoteSegmentStoreDirectory.acquireLock(RemoteSegmentStoreDirectory.java:480)
    at org.opensearch.index.shard.IndexShard.acquireLockOnCommitData(IndexShard.java:1655)
    at org.opensearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:631)
    at org.opensearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:393)
    at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractPrioritizedRunnable.doRun(ThreadContext.java:979)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
```

For shallow copy snapshots, we refer latest remote store data and acquire a lock on that data. since the indices are closed no new data is being written to remote store which should get triggered as part of snapshot flush. this is causing snapshots to fail.

### Related component

Storage:Snapshots

### To Reproduce

1. Create a remote store enabled cluster.
2. Create indices and close them.
3. Register a snapshot repository and enable shallow copy snapshots or use system repository created during cluster creation.
4. Trigger snapshot, it will fail.

### Expected behavior

Snapshots should pass.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/lukas-vlcek/) [5](https://github.com/dbwiddis) [6](https://github.com/srikanthpadakanti/)
@harishbhakuni Thanks for creating this issue, we would welcome a pull request to address this bug

**Comment by sachinpkale** [comment]
[Storage Triage - attendees [1](https://github.com/reta) [2](https://github.com/lukas-vlcek) [3](https://github.com/hasnain2808) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi) [6](https://github.com/TODO) [7](https://github.com/sachinpkale) [8](https://github.com/astute-decipher) [9](https://github.com/BhumikaSaini-Amazon) [10](https://github.com/ltaragi) ]

Added release target `2.16`

**Comment by moritzzimmer** [comment]
We face the same issue on AWS OpenSearch service. Unfortunately this also seems to prevent domain upgrades, since the service tries to make a shallow snapshot first.

As a workaround, we needed to (re-) open and/or delete closed indices to be able to upgrade our domain.
