### ISSUE TITLE
[BUG] org.opensearch.search.sort.FieldSortIT.testCastDate {p0={"search.concurrent_segment_search.enabled":"false"}} if flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#13849]
### Describe the bug

The test case `org.opensearch.search.sort.FieldSortIT.testCastDate {p0={"search.concurrent_segment_search.enabled":"false"}}` if flaky:

```
Failed to execute phase [fetch], ; shardFailures {[0G8Ni_89RCuL-CE9rFyUow][index_date][0]: RemoteTransportException[[node_s2][127.0.0.1:44133][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalArgumentException[milliSeconds [-2042496763000] are before the epoch in 1970 and cannot be converted to nanoseconds]; }
	at __randomizedtesting.SeedInfo.seed([7A144EB79AD6ACE9:9D8F93B8B2B9858C]:0)
	at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:757)
	at app//org.opensearch.action.search.FetchSearchPhase$2.innerOnResponse(FetchSearchPhase.java:245)
	at app//org.opensearch.action.search.FetchSearchPhase$2.innerOnResponse(FetchSearchPhase.java:238)
	at app//org.opensearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:59)
	at app//org.opensearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:44)
	at app//org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:70)
	at app//org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleResponse(SearchTransportService.java:757)
	at app//org.opensearch.telemetry.tracing.handler.TraceableTransportResponseHandler.handleResponse(TraceableTransportResponseHandler.java:72)
	at app//org.opensearch.transport.TransportService$9.handleResponse(TransportService.java:1723)
	at app//org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1505)
	at app//org.opensearch.transport.NativeMessageHandler.doHandleResponse(NativeMessageHandler.java:427)
	at app//org.opensearch.transport.NativeMessageHandler.handleResponse(NativeMessageHandler.java:419)
	at app//org.opensearch.transport.NativeMessageHandler.handleMessage(NativeMessageHandler.java:174)
	at app//org.opensearch.transport.NativeMessageHandler.messageReceived(NativeMessageHandler.java:126)
	at app//org.opensearch.transport.InboundHandler.messageReceivedFromPipeline(InboundHandler.java:121)
	at app//org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:113)
	at app//org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:800)
	at app//org.opensearch.transport.nativeprotocol.NativeInboundBytesHandler.forwardFragments(NativeInboundBytesHandler.java:157)
	at app//org.opensearch.transport.nativeprotocol.NativeInboundBytesHandler.doHandleBytes(NativeInboundBytesHandler.java:94)
	at app//org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:143)
	at app//org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:119)
	at app//org.opensearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:343)
	at app//org.opensearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:246)
	at app//org.opensearch.nio.BytesChannelContext.read(BytesChannelContext.java:59)
	at app//org.opensearch.nio.EventHandler.handleRead(EventHandler.java:152)
	at app//org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167)
	at app//org.opensearch.nio.NioSelector.handleRead(NioSelector.java:438)
	at app//org.opensearch.nio.NioSelector.processKey(NioSelector.java:264)
	at app//org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:191)
	at app//org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148)
	at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at org.opensearch.search.SearchSortValues.<init>(SearchSortValues.java:72)
	at org.opensearch.search.SearchHit.sortValues(SearchHit.java:531)
	at org.opensearch.action.search.SearchPhaseController.getHits(SearchPhaseController.java:384)
	at org.opensearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:301)
	at org.opensearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:292)
	at org.opensearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:138)
	at org.opensearch.action.search.CountedCollector.countDown(CountedCollector.java:66)
	at org.opensearch.action.search.ArraySearchPhaseResults.consumeResult(ArraySearchPhaseResults.java:61)
	at org.opensearch.action.search.CountedCollector.onResult(CountedCollector.java:74)
	at org.opensearch.action.search.FetchSearchPhase$2.innerOnResponse(FetchSearchPhase.java:243)
	... 29 more
```

### Related component

Search

### To Reproduce

```
 ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.sort.FieldSortIT" -Dtests.method="testCastDate {p0={"search.concurrent_segment_search.enabled":"false"}}" -Dtests.seed=7A144EB79AD6ACE9
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/39307/testReport/junit/org.opensearch.search.sort/FieldSortIT/testCastDate__p0___search_concurrent_segment_search_enabled___false___/

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/lukas-vlcek/) [5](https://github.com/dbwiddis) [6](https://github.com/srikanthpadakanti/)
@reta Thanks for creating this issue.

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14287
