### ISSUE TITLE
[BUG] NestedQueryBuilderTests.testParentFilterFromInlineLeafInnerHitsNestedQuery is flaky

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/OpenSearch#13890]
### Describe the bug

See e.g. https://build.ci.opensearch.org/job/gradle-check/39435/testReport/junit/org.opensearch.index.query/NestedQueryBuilderTests/testParentFilterFromInlineLeafInnerHitsNestedQuery/

```
[xZY] QueryShardException[No mapping found for [bbSiO] in order to sort on]
	at __randomizedtesting.SeedInfo.seed([82773C9793E6B096:83316B8C6652D666]:0)
	at app//org.opensearch.search.sort.FieldSortBuilder.resolveUnmappedType(FieldSortBuilder.java:564)
	at app//org.opensearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:411)
	at app//org.opensearch.search.sort.SortBuilder.buildSort(SortBuilder.java:168)
	at app//org.opensearch.index.query.InnerHitContextBuilder.setupInnerHitsContext(InnerHitContextBuilder.java:143)
	at app//org.opensearch.index.query.NestedQueryBuilder$NestedInnerHitContextBuilder.doBuild(NestedQueryBuilder.java:422)
	at app//org.opensearch.index.query.InnerHitContextBuilder.build(InnerHitContextBuilder.java:86)
	at app//org.opensearch.index.query.NestedQueryBuilderTests.testParentFilterFromInlineLeafInnerHitsNestedQuery(NestedQueryBuilderTests.java:344)
```

### Related component

Search:Query Capabilities

### To Reproduce

Reproduces reliably with:

```
./gradlew ':server:test' --tests "org.opensearch.index.query.NestedQueryBuilderTests.testParentFilterFromInlineLeafInnerHitsNestedQuery" -Dtests.seed=82773C9793E6B096 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-GT -Dtests.timezone=Europe/Astrakhan -Druntime.java=21
```

### Expected behavior

The test should pass all the time 😁 

### Additional Details

This failure was probably triggered by the merge of https://github.com/opensearch-project/OpenSearch/pull/13770

**Comment by msfroh** [comment]
We may want to revert https://github.com/opensearch-project/OpenSearch/pull/13770 as a quick fix, then reapply it once we have a reliable fix.

**Comment by heemin32** [comment]
There was a bug in the test case. Raised a new PR after the fix. https://github.com/opensearch-project/OpenSearch/pull/13903

**Comment by msfroh** [comment]
Fixed by https://github.com/opensearch-project/OpenSearch/pull/13896 and https://github.com/opensearch-project/OpenSearch/pull/13903
