### ISSUE TITLE
[BUG] UpdateByQueryBasicTests.testMultipleSources is flaky

### ISSUE THREAD

**Issue by shiv0408** [opensearch-project/OpenSearch#13912]
### Describe the bug

`org.opensearch.index.reindex.UpdateByQueryBasicTests.testMultipleSources` is flaky

Stacktrace:
```
java.lang.AssertionError: 
Expected: an empty iterable
     but: [<UnavailableShardsException[[test1][5] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][5]] containing [index {[test1][bogus_doc_a6], source[{}]}]]]>,<UnavailableShardsException[[test1][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][0]] containing [index {[test1][bogus_doc_a1], source[{}]}]]]>,<UnavailableShardsException[[test1][5] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][5]] containing [index {[test1][2], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][4]] containing [index {[test1][10], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][4]] containing [index {[test1][7], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][7]] containing [index {[test1][0], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test3][8] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][8]] containing [index {[test3][1], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][2] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][2]] containing [index {[test1][5], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][5] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][5]] containing [index {[test1][9], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][5] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][5]] containing [index {[test1][13], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test3][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][7]] containing [index {[test3][3], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test3][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][7]] containing [index {[test3][0], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][8] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][8]] containing [index {[test1][8], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][2] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][2]] containing [index {[test1][11], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][3] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][3]] containing [index {[test1][6], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][7] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][7]] containing [index {[test1][3], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][4]] containing [index {[test1][12], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][4]] containing [index {[test1][4], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test2][8] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test2][8]] containing [index {[test2][1], source[{"foo":"a"}]}]]]>]
	at __randomizedtesting.SeedInfo.seed([312DCBFC1E640870:B684E7E8F42EA624]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.test.OpenSearchIntegTestCase.indexRandom(OpenSearchIntegTestCase.java:1566)
	at org.opensearch.test.OpenSearchIntegTestCase.indexRandom(OpenSearchIntegTestCase.java:1479)
	at org.opensearch.test.OpenSearchIntegTestCase.indexRandom(OpenSearchIntegTestCase.java:1463)
	at org.opensearch.index.reindex.UpdateByQueryBasicTests.testMultipleSources(UpdateByQueryBasicTests.java:146)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

CI: https://build.ci.opensearch.org/job/gradle-check/38717/testReport/org.opensearch.index.reindex/UpdateByQueryBasicTests/testMultipleSources/

### Related component

Indexing

### To Reproduce

REPRODUCE WITH: ./gradlew ':modules:reindex:test' --tests "org.opensearch.index.reindex.UpdateByQueryBasicTests.testMultipleSources" -Dtests.seed=312DCBFC1E640870 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-PY -Dtests.timezone=Poland -Druntime.java=21

### Expected behavior

Test should always pass

**Comment by prachi-gaonkar** [comment]
Hi Team, 
we are also getting the same error on ppc64le

REPRODUCE WITH: ./gradlew ':modules:reindex:test' --tests "org.opensearch.index.reindex.UpdateByQueryBasicTests.testMultipleSources" -Dtests.seed=8E7EA906723D86BB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=Antarctica/Rothera -Druntime.java=21

UpdateByQueryBasicTests > testMultipleSources FAILED
    java.lang.AssertionError:
    Expected: an empty iterable
         but: [<UnavailableShardsException[[test3][4] primary shard is not active Timeout: [1m],
		 request: [BulkShardRequest [[test3][4]] containing [index {[test3][bogus_doc_aa14], source[{}]}]]]>,
		 <UnavailableShardsException[[test1][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][4]]
		 containing [index {[test1][4], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test3][4] primary shard is not active Timeout:
		 [1m], request: [BulkShardRequest [[test3][4]] containing [index {[test3][4], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][3]
		 primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][3]] containing [index {[test1][8], source[{"foo":"a"}]}]]]>,
		 <UnavailableShardsException[[test3][6] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][6]] 
		 containing [index {[test3][bogus_doc_aa19], source[{}]}]]]>,<UnavailableShardsException[[test3][4] primary shard is not active
		 Timeout: [1m], request: [BulkShardRequest [[test3][4]] containing [index {[test3][12], source[{"foo":"a"}]}]]]>,
		 <UnavailableShardsException[[test3][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest 
		 [[test3][4]] containing [index {[test3][bogus_doc_aa13], source[{}]}]]]>,<UnavailableShardsException[[test3][4] 
		 primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][4]] containing [index {[test3][9], 
		 source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test1][4] primary shard is not active Timeout:
		 [1m], request: [BulkShardRequest [[test1][4]] containing [index {[test1][9], source[{"foo":"a"}]}]]]>,
		 <UnavailableShardsException[[test1][5] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][5]] containing [index {[test1][bogus_doc_aa17], source[{}]}]]]>,<UnavailableShardsException[[test1][3] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test1][3]] containing [index {[test1][2], source[{"foo":"a"}]}]]]>,<UnavailableShardsException[[test3][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][4]] containing [index {[test3][bogus_doc_㇍a23], source[{}]}]]]>,<UnavailableShardsException[[test3][6] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][6]] containing [index {[test3][bogus_doc_ⷡa9], source[{}]}]]]>,<UnavailableShardsException[[test3][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[test3][4]] containing [index {[test3][10],

**Comment by prachi-gaonkar** [comment]
Hi Team
is there any updated on this issue?
