### ISSUE TITLE
same  visualization works in opensearch 2.13, but fails in 2.14

### ISSUE THREAD

**Issue by franfreire** [opensearch-project/OpenSearch#13967]
Visualization type:  **Controls**

I had this visualization working in opensearch until I updated to 2.14. I tested it back in opensearch 2.13 and in this version it works properly

![Selección_999(471)](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/68546347/a3b75f37-d221-4977-a4f9-01dcb65d658b)

When I check opensearch logs I see the following error:

```
org.opensearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:757) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:394) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:796) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:542) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:315) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:766) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.transport.TransportService$9.handleException(TransportService.java:1729) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleException(SecurityInterceptor.java:410) [opensearch-security-2.14.0.0.jar:2.14.0.0]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1515) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1629) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1603) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:81) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:75) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:70) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:104) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913) [opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.14.0.jar:2.14.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.opensearch.OpenSearchException$3: Cannot invoke "org.opensearch.core.common.io.stream.NamedWriteable.getWriteableName()" because "namedWriteable" is null
	at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:710) ~[opensearch-core-2.14.0.jar:2.14.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:392) [opensearch-2.14.0.jar:2.14.0]
	... 24 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.opensearch.core.common.io.stream.NamedWriteable.getWriteableName()" because "namedWriteable" is null
	at org.opensearch.core.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1134) ~[opensearch-core-2.14.0.jar:2.14.0]
	at org.opensearch.core.common.io.stream.StreamOutput.writeNamedWriteableList(StreamOutput.java:1233) ~[opensearch-core-2.14.0.jar:2.14.0]
	at org.opensearch.search.aggregations.InternalAggregations.writeTo(InternalAggregations.java:154) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.io.stream.DelayableWriteable$Referencing.writeToBuffer(DelayableWriteable.java:147) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.io.stream.DelayableWriteable$Referencing.writeTo(DelayableWriteable.java:120) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.search.query.QuerySearchResult.writeToNoId(QuerySearchResult.java:445) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.cache.policy.CachedQueryResult.writeToNoId(CachedQueryResult.java:60) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.indices.IndicesService.lambda$loadIntoContext$24(IndicesService.java:1707) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.indices.IndicesService.lambda$cacheShardLevelResult$25(IndicesService.java:1764) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:345) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:328) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.cache.store.OpenSearchOnHeapCache.lambda$computeIfAbsent$0(OpenSearchOnHeapCache.java:98) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.cache.Cache.compute(Cache.java:470) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.cache.Cache.computeIfAbsent(Cache.java:427) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.cache.store.OpenSearchOnHeapCache.computeIfAbsent(OpenSearchOnHeapCache.java:98) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.indices.IndicesRequestCache.getOrCompute(IndicesRequestCache.java:287) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.indices.IndicesService.cacheShardLevelResult(IndicesService.java:1770) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.indices.IndicesService.loadIntoContext(IndicesService.java:1701) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:557) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:623) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:592) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89) ~[opensearch-2.14.0.jar:2.14.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.14.0.jar:2.14.0]
	... 8 more
```

**OpenSearch Version**
2.14

**Dashboards Version**
2.14

**Comment by disaster37** [comment]
I have the same issue than @franfreire but we are not the same person and we are not working on same organization. I will try to grab more useful trace on devtools like you suggest tomorrow.

**Comment by rasituum** [comment]
Hi, i have the same issue on 2.14 with Controls viz, with exactly the same stack traces than @franfreire on my opensearch client node. Works fine in 2.13.

**Comment by disaster37** [comment]
@AMoo-Miki I desn't understand what you need exactly ? I have look up on Chrom devtools, but I doesn't found more info than is already provided before by another people.

I have doing some test on fresh cluster install with Opensearch 2.14.0. It is not so easy to reproduce issue.

First, I create Index template (with data stream option) and some components templates linked for mapping.
Then I start indexation with Logstash that will create my data stream index `logs-log-default`.
I create second index with one document called `logs-test` with devtools.
I create new index pattern from Opensearch Dashboard called `logs-*`. So it match my 2 indexes (logs-log-default and logs-test).

Now I go to visualize and I create default control visu on my `logs-*`. At this time, all work fine. But after few time, when they are many doc indexed by logstash, it's start to no more working and I get the error describe by this issue. My current datastream index is not yet rolleover by ISM. So, ISM seem not be enter in the game.

Now, If create new index pattern `logs-log-*` that match only one index (logs-log-default). And I use it on Control visu, all work fine. It's the same if I remove the index `logs-test` (the `logs-*` now match only one index).

To conclude, the problem seems appear when the index-pattern target multiple index and there are many document indexed on it and I try to create visu of type Controle.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@opensearch-project/admin Could you please transfer this to the Dashboards repostiory?
