### ISSUE TITLE
[BUG] NPE in ReplicaShardBatchAllocator during node drops

### ISSUE THREAD

**Issue by SwethaGuptha** [opensearch-project/OpenSearch#13993]
### Describe the bug

```
[2024-05-28T14:34:01,627][ERROR][o.o.c.c.Coordinator      ] [66a99e3966c42f12f229f8b22da6d074] unexpected failure during [node-left]
java.lang.NullPointerException: Cannot invoke "org.opensearch.cluster.routing.ShardRouting.currentNodeId()" because "primaryShard" is null
        at org.opensearch.gateway.ReplicaShardAllocator.cancelExistingRecoveryForBetterMatch(ReplicaShardAllocator.java:108)
        at org.opensearch.gateway.ReplicaShardBatchAllocator.processExistingRecoveries(ReplicaShardBatchAllocator.java:73)
        at org.opensearch.gateway.ShardsBatchGatewayAllocator.afterPrimariesBeforeReplicas(ShardsBatchGatewayAllocator.java:198)
        at org.opensearch.cluster.routing.allocation.AllocationService.allocateAllUnassignedShards(AllocationService.java:639)
        at org.opensearch.cluster.routing.allocation.AllocationService.allocateExistingUnassignedShards(AllocationService.java:609)
        at org.opensearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:588)
        at org.opensearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:529)
        at org.opensearch.cluster.routing.allocation.AllocationService.disassociateDeadNodes(AllocationService.java:339)
        at org.opensearch.cluster.coordination.NodeRemovalClusterStateTaskExecutor.getTaskClusterTasksResult(NodeRemovalClusterStateTaskExecutor.java:123)
        at org.opensearch.cluster.coordination.NodeRemovalClusterStateTaskExecutor.execute(NodeRemovalClusterStateTaskExecutor.java:113)
        at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:882)
        at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:434)
        at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:301)
        at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:212)
        at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:209)
        at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:247)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:863)
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283)
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Related component

Cluster Manager

### To Reproduce

Perform all node drops from the cluster.

### Expected behavior

Handle the NPE.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@SwethaGuptha Thanks for creating this issue, could you create a pull request to address?

**Comment by Bukhtawar** [comment]
Re-opening as the fix adds a null check however doesn't address the underlying root cause

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/reta)]

**Comment by shwetathareja** [comment]
Thanks @Bukhtawar for re-opening the issue. Yes,swallowing the NPE here was not the right fix.

Repro steps:
Node 1 has primary shard s1
Node 2 has replica s2 recovering from primary
Node 1 leaves the cluster

Root cause:
It will result in NPE and the reason is ```processExistingRecoveries``` method in ```ReplicaShardBatchAllocator``` is iterating over batches which can be stale instead of ```RoutingAllocation``` which we use for single shard flow. 

https://github.com/opensearch-project/OpenSearch/blob/456ca97f077929ba51d53dc8578b9b770e3a2417/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L55

Why the batch cache for replica ShardRouting which is used in for loop is stale is because ```allocateAllUnassignedShards``` method in ```AllocationService``` is 3 steps - 1. Allocate unassigned primaries 2. afterPrimariesBeforeReplica step to do find better match for existing recoveries 3. Allocate unassigned replicas. But the replica cache is updated is step 3, so we shouldn't be iterating over it.

https://github.com/opensearch-project/OpenSearch/blob/456ca97f077929ba51d53dc8578b9b770e3a2417/server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java#L624-L630
