### ISSUE TITLE
[BUG] org.opensearch.cache.store.disk.EhCacheDiskCacheTests.testComputeIfAbsentConcurrently is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#14012]
### Describe the bug

The test case `org.opensearch.cache.store.disk.EhCacheDiskCacheTests.testComputeIfAbsentConcurrently` is flaky:

```
java.lang.AssertionError: expected:<1> but was:<2>
	at __randomizedtesting.SeedInfo.seed([34B953D3CEC9BD27:B50224E73086F549]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.opensearch.cache.store.disk.EhCacheDiskCacheTests.testComputeIfAbsentConcurrently(EhCacheDiskCacheTests.java:416)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Storage:Remote

### To Reproduce

```
./gradlew ':plugins:cache-ehcache:test' --tests "org.opensearch.cache.store.disk.EhCacheDiskCacheTests" -Dtests.seed=34B953D3CEC9BD27
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/39886/testReport/junit/org.opensearch.cache.store.disk/EhCacheDiskCacheTests/testComputeIfAbsentConcurrently/

**Comment by reta** [comment]
Plus thread leaks:

```
com.carrotsearch.randomizedtesting.ThreadLeakError: 3 threads leaked from SUITE scope at org.opensearch.cache.store.disk.EhCacheDiskCacheTests: 
   1) Thread[id=95, name=Ehcache [ehcacheTest]-0, state=WAITING, group=TGRP-EhCacheDiskCacheTests]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
        at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
        at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
   2) Thread[id=96, name=Ehcache [ehcachePoolDefault#b24c482e-9bd7-40c7-8a13-b5058de8186b]-0, state=WAITING, group=TGRP-EhCacheDiskCacheTests]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
        at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
        at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
   3) Thread[id=97, name=Ehcache [ehcacheTest]-1, state=WAITING, group=TGRP-EhCacheDiskCacheTests]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
        at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
        at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by reta** [comment]
Closing for now since it does not yet manifests in any merged code

**Comment by AjayRajNelapudi** [comment]
Experienced again - https://github.com/opensearch-project/OpenSearch/pull/21637

```
REPRODUCE WITH: ./gradlew ':plugins:cache-ehcache:test' --tests 'org.opensearch.cache.store.disk.EhCacheDiskCacheTests.testComputeIfAbsentConcurrently' -Dtests.seed=D358AB6C5C9068F8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=mfe-MU -Dtests.timezone=Canada/Central -Druntime.java=25

EhCacheDiskCacheTests > testComputeIfAbsentConcurrently FAILED
    java.lang.AssertionError: expected:<1> but was:<2>
        at __randomizedtesting.SeedInfo.seed([D358AB6C5C9068F8:52E3DC58A2DF2096]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.cache.store.disk.EhCacheDiskCacheTests.testComputeIfAbsentConcurrently(EhCacheDiskCacheTests.java:422)

REPRODUCE WITH: ./gradlew ':plugins:cache-ehcache:test' --tests 'org.opensearch.cache.store.disk.EhCacheDiskCacheTests.testComputeIfAbsentWithNullValueLoading' -Dtests.seed=D358AB6C5C9068F8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=mfe-MU -Dtests.timezone=Canada/Central -Druntime.java=25

EhCacheDiskCacheTests > testComputeIfAbsentWithNullValueLoading FAILED
    java.lang.IllegalArgumentException: Cache 'test1' already exists
        at __randomizedtesting.SeedInfo.seed([D358AB6C5C9068F8:381B4FA52B78D461]:0)
        at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:266)
        at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:252)
        at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:247)
        at org.opensearch.cache.store.disk.EhcacheDiskCacheManager.lambda$createCache$0(EhcacheDiskCacheManager.java:145)
        at java.****/java.security.AccessController.doPrivileged(AccessController.java:74)
        at org.opensearch.cache.store.disk.EhcacheDiskCacheManager.createCache(EhcacheDiskCacheManager.java:136)
        at org.opensearch.cache.store.disk.EhcacheDiskCache.buildCache(EhcacheDiskCache.java:241)
        at org.opensearch.cache.store.disk.EhcacheDiskCache.<init>(EhcacheDiskCache.java:183)
        at org.opensearch.cache.store.disk.EhcacheDiskCache$Builder.build(EhcacheDiskCache.java:885)
        at org.opensearch.cache.store.disk.EhcacheDiskCache$Builder.build(EhcacheDiskCache.java:759)
        at org.opensearch.cache.store.disk.EhCacheDiskCacheTests.testComputeIfAbsentWithNullValueLoading(EhCacheDiskCacheTests.java:579)
```

CI build: https://build.ci.opensearch.org/job/gradle-check/77620/console

**Comment by andrross** [comment]
Closing in favor of autocut: #16159
