### ISSUE TITLE
[BUG] Flakey test org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns

### ISSUE THREAD

**Issue by jed326** [opensearch-project/OpenSearch#14045]
### Describe the bug

Test `org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns` is flaky.

```
java.lang.AssertionError: 
Expected: "2019-01-01T01:01:01.001UTC"
     but: was "2019-01-01T01:01:01.001𞤑𞤖𞤊"
	at __randomizedtesting.SeedInfo.seed([5C18960790949CB6:B2937DCA5FB039EE]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns(JavaJodaTimeDuellingTests.java:189)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)

```

### Related component

Other

### To Reproduce

Jenkins Build: https://build.ci.opensearch.org/job/gradle-check/39912

### Expected behavior

Test should always pass

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
Thanks @jed326 , I am closing it, the offended pull request is being reverted https://github.com/opensearch-project/OpenSearch/pull/14039
