### ISSUE TITLE
[BUG] asserting error when profile is set to true and phrase queries are run on match_only_text_field

### ISSUE THREAD

**Issue by rishabhmaurya** [opensearch-project/OpenSearch#14156]
### Describe the bug

In query phase, when rewrite is called

https://github.com/opensearch-project/OpenSearch/blob/5ff50a7e00698b0f448bc4840461c8518500d591/server/src/main/java/org/opensearch/search/query/QueryPhase.java#L127

the `ContextIndexSearch` will start the timer for the query and will start noting the `rewrite()` time for all clauses in the clauses for the complete query tree. 

But if we try to use `indexSearcher.rewrite(delegateQuery)` within rewrite of any of the query, it will try to initialize the profiler and timer again and will result in the assertion error here - 

https://github.com/opensearch-project/OpenSearch/blob/200ad5d28a577877be530ecab507601898025c5c/server/src/main/java/org/opensearch/search/profile/query/AbstractQueryProfileTree.java#L48

```
»  java.lang.AssertionError
»       at org.opensearch.search.profile.query.AbstractQueryProfileTree.startRewriteTime(AbstractQueryProfileTree.java:48)
»       at org.opensearch.search.profile.query.QueryProfiler.startRewriteTime(QueryProfiler.java:80)
»       at org.opensearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:192)
»       at org.opensearch.index.query.SourceFieldMatchQuery.rewrite(SourceFieldMatchQuery.java:76)
»       at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:777)
»       at org.opensearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:196)
»       at org.opensearch.search.DefaultSearchContext.preProcess(DefaultSearchContext.java:362)
»       at org.opensearch.search.query.QueryPhase.preProcess(QueryPhase.java:127)
»       at org.opensearch.search.SearchService.createContext(SearchService.java:1053)
```

### Related component

Search

### To Reproduce

```
GET big5/_search
{
  "profile": true,
  "query": {
    "match_phrase": {
      "message": "weaver spirit"
    }
  }
}
```
run this query on an index with field `message` of type `match_only_text`. 

### Expected behavior

Expected profile output like below and not asserting error - 

```json
                "type": "SourceFieldMatchQuery",
                "description": """SourceFieldMatchQuery (delegate query: [ #message:weaver #message:spirit ], filter query: [ message:"weaver spirit"])""",
                "time_in_nanos": 274420046,
                "breakdown": {
                  "set_min_competitive_score_count": 0,
                  "match_count": 298,
                  "shallow_advance_count": 0,
                  "next_doc": 2777209,
                  "score_count": 19,
                  "compute_max_score_count": 0,
                  "advance": 0,
                  "advance_count": 0,
                  "score": 8959,
                  "shallow_advance": 0,
                  "create_weight_count": 1,
                  "build_scorer": 7353375,
                  "set_min_competitive_score": 0,
                  "match": 259317837,
                  "next_doc_count": 305,
                  "compute_max_score": 0,
                  "build_scorer_count": 14,
                  "create_weight": 4962666
                },
                "children": [
                  {
                    "type": "TermQuery",
                    "description": "message:weaver",
                    "time_in_nanos": 3292863,
                    "breakdown": {
                      "set_min_competitive_score_count": 0,
                      "match_count": 0,
                      "shallow_advance_count": 0,
                      "next_doc": 363713,
                      "score_count": 0,
                      "compute_max_score_count": 0,
                      "advance": 459067,
                      "advance_count": 3673,
                      "score": 0,
                      "shallow_advance": 0,
                      "create_weight_count": 1,
                      "build_scorer": 2468749,
                      "set_min_competitive_score": 0,
                      "match": 0,
                      "next_doc_count": 250,
                      "compute_max_score": 0,
                      "build_scorer_count": 21,
                      "create_weight": 1334
                    }
                  },
                  {
                    "type": "TermQuery",
                    "description": "message:spirit",
                    "time_in_nanos": 2067981,
                    "breakdown": {
                      "set_min_competitive_score_count": 0,
                      "match_count": 0,
                      "shallow_advance_count": 0,
                      "next_doc": 10045,
                      "score_count": 0,
                      "compute_max_score_count": 0,
                      "advance": 1298645,
                      "advance_count": 3762,
                      "score": 0,
                      "shallow_advance": 0,
                      "create_weight_count": 1,
                      "build_scorer": 758250,
                      "set_min_competitive_score": 0,
                      "match": 0,
                      "next_doc_count": 55,
                      "compute_max_score": 0,
                      "build_scorer_count": 21,
                      "create_weight": 1041
                    }
                  }
                ]
              }

```

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by rishabhmaurya** [comment]
PR - https://github.com/opensearch-project/OpenSearch/pull/14154
