### ISSUE TITLE
[BUG] org.opensearch.remotemigration.RemoteStoreMigrationTestCase has flaky test

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/OpenSearch#14220]
### Describe the bug

`org.opensearch.remotemigration.RemoteStoreMigrationTestCase.testNoShallowSnapshotInMixedMode`

https://build.ci.opensearch.org/job/gradle-check/40763/testReport/junit/org.opensearch.remotemigration/RemoteStoreMigrationTestCase/testNoShallowSnapshotInMixedMode/

```
java.lang.IllegalStateException: Exception in fetching manifest for clusterUUID: -0NKB3BISKyAhzDW0__sYg
	at __randomizedtesting.SeedInfo.seed([DBD77741D782A610:CFE8DCE79CF21994]:0)
	at org.opensearch.gateway.remote.RemoteManifestManager.getLatestManifestForAllClusterUUIDs(RemoteManifestManager.java:229)
	at org.opensearch.gateway.remote.RemoteClusterStateService.getLastKnownUUIDFromRemote(RemoteClusterStateService.java:801)
	at org.opensearch.gateway.GatewayMetaState.start(GatewayMetaState.java:174)
	at org.opensearch.node.Node.start(Node.java:1535)
	at org.opensearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:1054)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:882)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.lang.RuntimeException: failed to start nodes
		at org.opensearch.test.InternalTestCluster.startAndPublishNodesAndClients(InternalTestCluster.java:1904)
		at org.opensearch.test.InternalTestCluster.startNodes(InternalTestCluster.java:2364)
		at org.opensearch.test.InternalTestCluster.startNode(InternalTestCluster.java:2293)
		at org.opensearch.test.InternalTestCluster.startNode(InternalTestCluster.java:2279)
		at org.opensearch.remotemigration.RemoteStoreMigrationTestCase.testNoShallowSnapshotInMixedMode(RemoteStoreMigrationTestCase.java:105)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
		at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
		at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
		at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
		at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
		at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
		at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
		at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
		at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
		at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
		at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
		at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
		at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
		at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
		at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
		at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
		at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
		at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
		at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
		at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
		at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
		at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
		at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
		at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
		at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
		at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
		... 1 more
Caused by: java.lang.IllegalArgumentException: Manifest file name is corrupted
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.getManifestCodecVersion(RemoteClusterMetadataManifest.java:143)
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.getClusterMetadataManifestBlobStoreFormat(RemoteClusterMetadataManifest.java:148)
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.deserialize(RemoteClusterMetadataManifest.java:130)
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.deserialize(RemoteClusterMetadataManifest.java:32)
	at org.opensearch.gateway.remote.model.RemoteClusterStateBlobStore.read(RemoteClusterStateBlobStore.java:75)
	at org.opensearch.gateway.remote.RemoteManifestManager.fetchRemoteClusterMetadataManifest(RemoteManifestManager.java:215)
	at org.opensearch.gateway.remote.RemoteManifestManager.lambda$getLatestClusterMetadataManifest$2(RemoteManifestManager.java:180)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.opensearch.gateway.remote.RemoteManifestManager.getLatestClusterMetadataManifest(RemoteManifestManager.java:180)
	at org.opensearch.gateway.remote.RemoteManifestManager.getLatestManifestForAllClusterUUIDs(RemoteManifestManager.java:225)
	... 10 more
```

### Related component

Storage:Remote

### To Reproduce

./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotemigration.RemoteStoreMigrationTestCase.testNoShallowSnapshotInMixedMode" -Dtests.seed=DBD77741D782A610

### Expected behavior

Should always pass

**Comment by bowenlan-amzn** [comment]
@gbbafna could you help triage this as I see you make change related to remote store migration recently.

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14315
