### ISSUE TITLE
[BUG] org.opensearch.cluster.routing.remote.RemoteRoutingTableServiceTests.testGetIndicesRoutingMapDiffIndexAdded is flaky

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#14263]
### Describe the bug

The test case org.opensearch.cluster.routing.remote.RemoteRoutingTableServiceTests.testGetIndicesRoutingMapDiffIndexAdded is flaky, seems caused by `randomInt(1000)` that can give `0` but invalid when setting `number_of_shards`.  
```
java.lang.IllegalArgumentException: Failed to parse value [0] for setting [index.number_of_shards] must be >= 1
	at __randomizedtesting.SeedInfo.seed([763DAFDC445B8243:779A42EA15ED34B0]:0)
	at org.opensearch.common.settings.Setting.parseInt(Setting.java:1484)
	at org.opensearch.common.settings.Setting$IntegerParser.apply(Setting.java:1584)
	at org.opensearch.common.settings.Setting$IntegerParser.apply(Setting.java:1538)
	at org.opensearch.common.settings.Setting.get(Setting.java:483)
	at org.opensearch.common.settings.Setting.get(Setting.java:477)
	at org.opensearch.cluster.metadata.IndexMetadata$Builder.build(IndexMetadata.java:1499)
	at org.opensearch.cluster.routing.remote.RemoteRoutingTableServiceTests.testGetIndicesRoutingMapDiffIndexAdded(RemoteRoutingTableServiceTests.java:241)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Full report: https://build.ci.opensearch.org/job/gradle-check/40899/testReport/junit/org.opensearch.cluster.routing.remote/RemoteRoutingTableServiceTests/testGetIndicesRoutingMapDiffIndexAdded/

### Related component

Storage:Remote

### To Reproduce

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.cluster.routing.remote.RemoteRoutingTableServiceTests.testGetIndicesRoutingMapDiffIndexAdded" -Dtests.seed=763DAFDC445B8243 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ca-ES -Dtests.timezone=SystemV/MST7 -Druntime.java=21

### Expected behavior

The test case should always success.

**Comment by bowenlan-amzn** [comment]
https://build.ci.opensearch.org/job/gradle-check/41009/testReport/junit/org.opensearch.cluster.routing.remote/RemoteRoutingTableServiceTests/testGetIndexRoutingAsyncActionFailureInBlobRepo/

`org.opensearch.cluster.routing.remote.RemoteRoutingTableServiceTests.testGetIndexRoutingAsyncActionFailureInBlobRepo`

```
java.lang.IllegalArgumentException: Failed to parse value [0] for setting [index.number_of_shards] must be >= 1
```

**Comment by bowenlan-amzn** [comment]
Seems coming from #13870 @himshikha

**Comment by gaobinlong** [comment]
Fixed by https://github.com/opensearch-project/OpenSearch/pull/14264.
