### ISSUE TITLE
[BUG] org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata is flaky

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#14275]
### Describe the bug

The test `org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata` is flaky

### Stack Trace:
```
java.lang.IllegalArgumentException: Manifest file name is corrupted
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.getManifestCodecVersion(RemoteClusterMetadataManifest.java:143)
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.getClusterMetadataManifestBlobStoreFormat(RemoteClusterMetadataManifest.java:148)
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.deserialize(RemoteClusterMetadataManifest.java:130)
	at org.opensearch.gateway.remote.model.RemoteClusterMetadataManifest.deserialize(RemoteClusterMetadataManifest.java:32)
	at org.opensearch.gateway.remote.model.RemoteClusterStateBlobStore.read(RemoteClusterStateBlobStore.java:75)
	at org.opensearch.gateway.remote.RemoteManifestManager.fetchRemoteClusterMetadataManifest(RemoteManifestManager.java:223)
	at org.opensearch.gateway.remote.RemoteManifestManager.lambda$getLatestClusterMetadataManifest$2(RemoteManifestManager.java:188)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.opensearch.gateway.remote.RemoteManifestManager.getLatestClusterMetadataManifest(RemoteManifestManager.java:188)
	at org.opensearch.gateway.remote.RemoteClusterStateService.getLatestClusterMetadataManifest(RemoteClusterStateService.java:883)
	at org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.lambda$validateCurrentMetadata$5(RemoteStoreClusterStateRestoreIT.java:394)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1101)
	at org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.validateCurrentMetadata(RemoteStoreClusterStateRestoreIT.java:391)
	at org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata(RemoteStoreClusterStateRestoreIT.java:462)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Cluster Manager

### To Reproduce

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata" -Dtests.seed=65B308AE35ED9ED5 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=it-IT -Dtests.timezone=America/Porto_Acre -Druntime.java=21
```

### Expected behavior

Test should always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Additional context**
https://build.ci.opensearch.org/job/gradle-check/40884/testReport/junit/org.opensearch.remotestore/RemoteStoreClusterStateRestoreIT/testFullClusterRestoreGlobalMetadata/

**Comment by prudhvigodithi** [comment]
Hey @sohami closing this issue since the automation created one issue for `RemoteStoreClusterStateRestoreIT`, please check https://github.com/opensearch-project/OpenSearch/issues/14326.
@andrross @dblock @reta
