### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#1448]
**Is your feature request related to a problem? Please describe.**
Coming from https://github.com/opensearch-project/opensearch-build/issues/33

**Describe the solution you'd like**
Add Windows CI for this repo at least for the minimum gradle precommit.

**Comment by dblock** [comment]
How much of the tests is precommit running? For example, will tests in https://github.com/opensearch-project/OpenSearch/pull/4656 be exercised in CI with the change, or did we close this prematurely?

**Comment by dblock** [comment]
@saratvemulapalli ^

**Comment by saratvemulapalli** [comment]
> How much of the tests is precommit running? For example, will tests in #4656 be exercised in CI with the change, or did we close this prematurely?

@dblock thats a good point. Precommit only runs few basic checks but does not run unit/integ tests. 
I'll re-open this to add gradle check support for Windows. 

Thinking about next steps, I am worried if we do have multiple gradle checks (linux, windows) the chances of failure multiplies (unfortunately due to flaky tests). 

How about splitting platform specific tests and only run them on windows/macos etc instead of running the whole suite ? 
Also do you know how other projects take care of this?

**Comment by dblock** [comment]
AFAIK the majority of flakey tests are integration and it's a separate (albeit important) problem. I believe there's a set of unit tests that never fails and we should start with that and keep increasing coverage. Starting with platform-specific tests is a good idea, I would gladly merge just that!

**Comment by saratvemulapalli** [comment]
I've spent sometime yesterday was able to run `gradle check` on windows, tests are failing due to permissions errors. 
```
org.opensearch.index.mapper.ICUCollationKeywordFieldMapperTests > classMethod FAILED
    java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)


Suite: Test class org.opensearch.index.mapper.ICUCollationKeywordFieldMapperTests
  2> java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.test.OpenSearchTestCase
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=33, name=Thread-4, state=RUNNABLE, group=TGRP-ICUCollationKeywordFieldMapperTests]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)

Tests with failures:
 - org.opensearch.index.analysis.SimpleIcuAnalysisTests.classMethod
 - org.opensearch.index.analysis.SimpleIcuNormalizerCharFilterTests.classMethod
 - org.opensearch.index.mapper.ICUCollationKeywordFieldMapperTests.classMethod
 - org.opensearch.index.mapper.ICUCollationKeywordFieldTypeTests.classMethod
 - org.opensearch.index.analysis.AnalysisICUFactoryTests.classMethod
 - org.opensearch.index.analysis.IcuTokenizerFactoryTests.classMethod
 - org.opensearch.index.analysis.SimpleIcuCollationTokenFilterTests.classMethod
 - org.opensearch.index.mapper.CollationFieldTypeTests.classMethod
```

**Comment by saratvemulapalli** [comment]
I was able to get past the problem of permissions. Looks like we have to run as a non-root user.

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:bwc:minor:checkoutBwcBranch'.
> Process 'command 'git'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:bwc:bugfix:checkoutBwcBranch'.
> Process 'command 'git'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 54s
1275 actionable tasks: 942 executed, 333 up-to-date
PS C:\Users\Sarat\Desktop\Workspace\OpenSearch>
```

**Comment by saratvemulapalli** [comment]
Got past the problems with bwc now hitting problems with Java mmap.

```
----- Last  20 lines from daemon log file - daemon-29408.out.log -----
# Native memory allocation (mmap) failed to map 65536 bytes for Failed to commit metaspace.
# An error report file with more information is saved as:
# C:\Users\Sarat\Desktop\Workspace\OpenSearch\modules\analysis-common\build\testrun\test\hs_err_pid13212.log
# An error report file with more information is saved as:
# C:\Users\Sarat\Desktop\Workspace\OpenSearch\modules\ingest-common\build\testrun\test\hs_err_pid24072.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 65536 bytes for Failed to commit metaspace.
# An error report file with more information is saved as:
# C:\Users\Sarat\Desktop\Workspace\OpenSearch\modules\analysis-common\build\testrun\test\hs_err_pid4164.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 65536 bytes for Failed to commit metaspace.
# An error report file with more information is saved as:
# C:\Users\Sarat\Desktop\Workspace\OpenSearch\libs\core\build\testrun\test\hs_err_pid11592.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 65536 bytes for Failed to commit metaspace.
# An error report file with more information is saved as:
# C:\Users\Sarat\Desktop\Workspace\OpenSearch\modules\reindex\build\testrun\test\hs_err_pid23916.log
```

**Comment by peterzhuamazon** [comment]
Hi,

@dblock @saratvemulapalli could you guys let me know what is the reason that Gradle Check is needed for Windows?
As of current state, the existing gradle check is already running extensively long, and it only able to run on Ubuntu server.
There are also many other utilities such as docker/compose needs to be setup before we even do any testings on it.

I believe the windows ci should be the building process on Windows, which we can then use github actions to achieve, not gradle check.

Please feel free to let me know but this requires a lot of effort just to setup the runner, and the existing windows runner is not suitable for this purpose, as it is sorely built to run builds, not gradle check.

Thanks.

**Comment by peterzhuamazon** [comment]
We need to plan this from our side if we bound to add windows gradle check.
CPU limitations, dynamic runner switch, AMI creation, Docker/Compose on Windows, and many more.

**Comment by peterzhuamazon** [comment]
Also,
Gradle check already takes a long time, and every windows agent takes around 10-20min just to bootstrap on Jenkins.
Can we make sure gradle check heavyweight tasks are de-coupled before we add another gradle check?

**Comment by saratvemulapalli** [comment]
@peterzhuamazon we cannot release software which we dont test. 
We have to make sure OpenSearch on windows is being tested to release the software, the way we do is via gradle check.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon we cannot release software which we dont test. We have to make sure OpenSearch on windows is being tested to release the software, the way we do is via gradle check.

Got it. Lets talk a bit more on the requirements.
The existing Jenkins workflow can take a new param to define whether it is linux or windows, and switch runner based on the trigger.

The thing I am more concerning is the windows runner takes 2x time to complete gradle check compares to linux host.

**Comment by peterzhuamazon** [comment]
Just talked with @saratvemulapalli and @Poojita-Raj and here are the steps on high level:

1. Edit github workflow to have a new workflow file for Windows trigger, on cron, on manual. It should have a new param to enter the platform of the test.
2. Edit Jenkinsfile to take the platform param and able to switch runner on the fly.
3. Add new packer profile to create a new Windows AMI specifically for gradle check, adding docker, compose, etc.
4. Adding new windows agent profile based on the AMI in cdk.
5. Deploy the new cdk into the public jenkins.
6. Pull the 1 2 into Jenkins and try to test by manually triggering the workflow and fix until it passes.
7. Adjust parallel runs number and apply for more hardware for the task.

**Comment by vibrantvarun** [comment]
Hi,
The steps to setup OpenSearch project before running gradlew check.
1) Do not admin user cmd (Command Line prompt). Use any non-root user cmd.
2) Set java 11,8, 9, 10,,12,13,14,17 paths as JAVA_HOME, JAVA8_HOME..etc respectively in system variables and also configure all the above paths in paths environment variable
3) clone the project
4) gradlew clean
5) gradlew check

**Comment by vibrantvarun** [comment]
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:archives:darwin-arm64-tar:checkExtraction'.
> Could not read 'C:\Users\Varun\OpenSearch\distribution\archives\darwin-arm64-tar\build\distributions\opensearch-min-2.3.1-SNAPSHOT-darwin-arm64.tar.gz' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:archives:freebsd-tar:checkExtraction'.
> Could not read 'C:\Users\Varun\OpenSearch\distribution\archives\freebsd-tar\build\distributions\opensearch-min-2.3.1-SNAPSHOT-freebsd-x64.tar.gz' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:archives:darwin-tar:checkExtraction'.
> Could not read 'C:\Users\Varun\OpenSearch\distribution\archives\darwin-tar\build\distributions\opensearch-min-2.3.1-SNAPSHOT-darwin-x64.tar.gz' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
org.gradle.api.GradleException: Reaper process failed. Check log at C:\Users\Varun\OpenSearch\.gradle\reaper\build-14320\error.log for details
> Reaper process failed. Check log at C:\Users\Varun\OpenSearch\.gradle\reaper\build-14320\error.log for details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 17m 40s
2327 actionable tasks: 2272 executed, 40 from cache, 15 up-to-date

**Comment by saratvemulapalli** [comment]
Build Tools, integTest is failing. Tests look very platform specific. 
```

> Task :build-tools:integTest

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2Tar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2TarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66
```

**Comment by saratvemulapalli** [comment]
Finally I was able to run gradle check with 2+ hrs of runtime
```
Tests with failures:
 - org.opensearch.action.admin.cluster.node.tasks.ResourceAwareTasksTests.testTaskResourceTrackingDuringTaskCancellation
 - org.opensearch.action.admin.cluster.node.tasks.ResourceAwareTasksTests.classMethod

11295 tests completed, 12 failed, 31 skipped

> Task :server:test FAILED

FAILURE: Build completed with 7 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:archives:darwin-arm64-tar:checkExtraction'.
> Could not read 'C:\Users\Sarat\Desktop\Workspace\OpenSearch\distribution\archives\darwin-arm64-tar\build\distributions\opensearch-min-3.0.0-SNAPSHOT-darwin-arm64.tar.gz' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:archives:darwin-tar:checkExtraction'.
> Could not read 'C:\Users\Sarat\Desktop\Workspace\OpenSearch\distribution\archives\darwin-tar\build\distributions\opensearch-min-3.0.0-SNAPSHOT-darwin-x64.tar.gz' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:archives:freebsd-tar:checkExtraction'.
> Could not read 'C:\Users\Sarat\Desktop\Workspace\OpenSearch\distribution\archives\freebsd-tar\build\distributions\opensearch-min-3.0.0-SNAPSHOT-freebsd-x64.tar.gz' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:archives:linux-arm64-tar:checkExtraction'.
> Could not read 'C:\Users\Sarat\Desktop\Workspace\OpenSearch\distribution\archives\linux-arm64-tar\build\distributions\opensearch-min-3.0.0-SNAPSHOT-linux-arm64.tar.gz' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':build-tools:integTest'.
> There were failing tests. See the report at: file:///C:/Users/Sarat/Desktop/Workspace/OpenSearch/buildSrc/build/reports/tests/integTest/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':server:test'.
> There were failing tests. See the report at: file:///C:/Users/Sarat/Desktop/Workspace/OpenSearch/server/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
org.gradle.api.GradleException: Reaper process failed. Check log at C:\Users\Sarat\Desktop\Workspace\OpenSearch\.gradle\reaper\build-4316\error.log for details
> Reaper process failed. Check log at C:\Users\Sarat\Desktop\Workspace\OpenSearch\.gradle\reaper\build-4316\error.log for details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2h 3m 34s
2343 actionable tasks: 393 executed, 1950 up-to-date
```

**Comment by dblock** [comment]
For this specific issue, we want _some_ windows CI on GHA that runs on every PR. The complete gradle check with all integration tests is another ask.

**Comment by vibrantvarun** [comment]
**TEST Failing while othe platforms code commented.**
1)
- MultiVersionRepositoryAccessIT. classMethod
- MultiVersionRepositoryAccessIT. classMethod
- MultiVersionRepositoryAccessIT. classMethod
- MultiVersionRepositoryAccessIT. classMethod
- MultiVersionRepositoryAccessIT. testCreateAndRestoreSnapshot
- MultiVersionRepositoryAccessIT. testCreateAndRestoreSnapshot
- MultiVersionRepositoryAccessIT. testCreateAndRestoreSnapshot
- MultiVersionRepositoryAccessIT. testCreateAndRestoreSnapshot

Test failure errors:
a) java.lang.Exception: Suite timeout exceeded (>= 1800000 msec).
	at __randomizedtesting.SeedInfo.seed([6614DC617C2EB13B]:0)
b) java.lang.Exception: Test abandoned because suite timeout was reached.
	at __randomizedtesting.SeedInfo.seed([6614DC617C2EB13B]:0)
	
2) 

- RepositoryURLClientYamlTestSuiteIT. classMethod
- RepositoryURLClientYamlTestSuiteIT. classMethod
- RepositoryURLClientYamlTestSuiteIT. classMethod
- RepositoryURLClientYamlTestSuiteIT. classMethod
- RepositoryURLClientYamlTestSuiteIT. test {yaml=repository_url/10_basic/Module repository-url is loaded}
- RepositoryURLClientYamlTestSuiteIT. test {yaml=repository_url/10_basic/Module repository-url is loaded}
- RepositoryURLClientYamlTestSuiteIT. test {yaml=repository_url/10_basic/Module repository-url is loaded}
- RepositoryURLClientYamlTestSuiteIT. test {yaml=repository_url/10_basic/Module repository-url is loaded}

Test failure errors:
a) java.lang.Exception: Suite timeout exceeded (>= 1800000 msec).
	at __randomizedtesting.SeedInfo.seed([6614DC617C2EB13B]:0)
b) java.lang.Exception: Test abandoned because suite timeout was reached.
	at __randomizedtesting.SeedInfo.seed([6614DC617C2EB13B]:0)

3) 

- PercolatorClientYamlTestSuiteIT. classMethod
- PercolatorClientYamlTestSuiteIT. classMethod
- PercolatorClientYamlTestSuiteIT. classMethod
- PercolatorClientYamlTestSuiteIT. classMethod
- PercolatorClientYamlTestSuiteIT. test {yaml=/10_basic/Test percolator basics via rest}
- PercolatorClientYamlTestSuiteIT. test {yaml=/10_basic/Test percolator basics via rest}
- PercolatorClientYamlTestSuiteIT. test {yaml=/10_basic/Test percolator basics via rest}
- PercolatorClientYamlTestSuiteIT. test {yaml=/10_basic/Test percolator basics via rest}

same errors and failure as above test

4)

- ParentChildClientYamlTestSuiteIT. classMethod
- ParentChildClientYamlTestSuiteIT. classMethod
- ParentChildClientYamlTestSuiteIT. classMethod
- ParentChildClientYamlTestSuiteIT. classMethod
- ParentChildClientYamlTestSuiteIT. test {yaml=/40_aggregations/parent}
- ParentChildClientYamlTestSuiteIT. test {yaml=/40_aggregations/parent}
- ParentChildClientYamlTestSuiteIT. test {yaml=/40_aggregations/parent}
- ParentChildClientYamlTestSuiteIT. test {yaml=/40_aggregations/parent}

same errors and failure as above test

5) 

- SearchTemplateWithoutContentIT. classMethod
- SearchTemplateWithoutContentIT. classMethod
- SearchTemplateWithoutContentIT. classMethod
- SearchTemplateWithoutContentIT. classMethod
- SearchTemplateWithoutContentIT. testMultiSearchTemplateMissingBody
- SearchTemplateWithoutContentIT. testMultiSearchTemplateMissingBody
- SearchTemplateWithoutContentIT. testMultiSearchTemplateMissingBody
- SearchTemplateWithoutContentIT. testMultiSearchTemplateMissingBody

same errors and failure as above test

6) 

- IngestUserAgentClientYamlTestSuiteIT. classMethod
- IngestUserAgentClientYamlTestSuiteIT. classMethod
- IngestUserAgentClientYamlTestSuiteIT. classMethod
- IngestUserAgentClientYamlTestSuiteIT. classMethod
- IngestUserAgentClientYamlTestSuiteIT. test {yaml=ingest-useragent/30_custom_regex/Test user agent processor with custom regex file}
- IngestUserAgentClientYamlTestSuiteIT. test {yaml=ingest-useragent/30_custom_regex/Test user agent processor with custom regex file}
- IngestUserAgentClientYamlTestSuiteIT. test {yaml=ingest-useragent/30_custom_regex/Test user agent processor with custom regex file}
- IngestUserAgentClientYamlTestSuiteIT. test {yaml=ingest-useragent/30_custom_regex/Test user agent processor with custom regex file}

	
same errors and failure as above test

7) 
- ExampleRescoreClientYamlTestSuiteIT. classMethod
- ExampleRescoreClientYamlTestSuiteIT. classMethod
- ExampleRescoreClientYamlTestSuiteIT. classMethod
- ExampleRescoreClientYamlTestSuiteIT. classMethod
- ExampleRescoreClientYamlTestSuiteIT. test {yaml=example-rescore/10_basic/Plugin loaded}
- ExampleRescoreClientYamlTestSuiteIT. test {yaml=example-rescore/10_basic/Plugin loaded}
- ExampleRescoreClientYamlTestSuiteIT. test {yaml=example-rescore/10_basic/Plugin loaded}
- ExampleRescoreClientYamlTestSuiteIT. test {yaml=example-rescore/10_basic/Plugin loaded}

same errors and failures as above test

8) 
ExpertScriptClientYamlTestSuiteIT. classMethod
ExpertScriptClientYamlTestSuiteIT. classMethod
ExpertScriptClientYamlTestSuiteIT. classMethod
ExpertScriptClientYamlTestSuiteIT. classMethod
ExpertScriptClientYamlTestSuiteIT. test {yaml=script_expert_scoring/10_basic/Plugin loaded}
ExpertScriptClientYamlTestSuiteIT. test {yaml=script_expert_scoring/10_basic/Plugin loaded}
ExpertScriptClientYamlTestSuiteIT. test {yaml=script_expert_scoring/10_basic/Plugin loaded}
ExpertScriptClientYamlTestSuiteIT. test {yaml=script_expert_scoring/10_basic/Plugin loaded}

**Comment by Poojita-Raj** [comment]
Need to backport changes needed for windows CI to run to both 1.x and 1.3 branch. 

These are all the changes that have taken place - 

- [x] 1. https://github.com/opensearch-project/OpenSearch/pull/5077 - ResourceAwareTasksTests doesn't exist on 1.x and 1.3 branches so this change doesn't need to be included. 
- [ ] 2.  https://github.com/opensearch-project/OpenSearch/pull/5023 - This fix has 2 open backport PRs for 1.x and 1.3. 
- [ ] 3.  https://github.com/opensearch-project/OpenSearch/pull/4941 - This fix has already been backported to 1.3, there is an open PR for 1.x backport as well. 
- [x] 4. https://github.com/opensearch-project/OpenSearch/pull/4949 - This is to revert Dan's PR on admin access, but it was never included in 1.3 and 1.x branches so doesn't need to be backported.

**Comment by peternied** [comment]
@Poojita-Raj Is there an effort to get OpenSearch 1.3 working on Windows?  As far as I know, support for Windows in only for OpenSearch 2.4+

**Comment by peterzhuamazon** [comment]
Hi, just want to make sure this issue is closed, if all the tasks are completed.

Thanks.

**Comment by dblock** [comment]
Related issue is https://github.com/opensearch-project/OpenSearch/issues/1975. If we break up `gradle check` we can decide which sets need to run on all platforms as part of CI, and which need to be run on cron.

**Comment by mch2** [comment]
Added the following tasks still remaining.
- [ ] Fix gradle check on 1.3/1.x
- [ ] Add GH workflow for windows to gate PRs.  Add unit tests only.

**Comment by peterzhuamazon** [comment]
1.x: https://build.ci.opensearch.org/job/gradle-check/7060/
1.3: https://build.ci.opensearch.org/job/gradle-check/7061/
Both windows have some errors here.

**Comment by peterzhuamazon** [comment]
windows:
main: https://build.ci.opensearch.org/job/gradle-check/7152/
2.x: https://build.ci.opensearch.org/job/gradle-check/7153/

**Comment by CEHENKLE** [comment]
@mch2 @peterzhuamazon @Poojita-Raj @minalsha 

So what do we need to close this issue out with confidence?

**Comment by mch2** [comment]
This issue specifically is around a PR gate on windows, we have additional work required to get on-merge/nightlies to green.

The question is what to run and where.

What to run?
Ideally the entire check, but we've seen instability with our nightly runs when running the check.  I've done some experimenting in breaking this up with existing gradle tasks [here](https://github.com/opensearch-project/OpenSearch/issues/5716#issuecomment-1379276445) for 2.5. I suggest we start with :server:test as a PR gate and the rest on-merge/nightly.

Where to run?
1. Use GH runners (similar to our existing precommit wf) and run very lightweight tests.  These runners are not powerful enough to run :server:test, so we will need to further break apart the test tasks to find an appropriate subset of tests to run that it can handle.
2. Use windows runners in Jenkins to run :server:test on-PR.  From what I understand from @peterzhuamazon this will have significant (~25+ mins) preparation time right now on our CI before any job starts executing.  I would prefer to go this route and work on cutting down that prep time.

**Comment by minalsha** [comment]
@mch2  what is needed to close this issue?  Is it following pending workitems in the issue description?

**Comment by mch2** [comment]
> @mch2 what is needed to close this issue? Is it following pending workitems in the issue description?

@minalsha yes, I just cleaned up the issue description.  The first step is getting stability in our nightly runs both from jenkins & the check and trigger them from GH. Then we will be able to transition to on PR checks.  The previous issues we had about running a subset on GH i've closed as not enough of the gradle tasks would succeed to be worthwhile.
