### ISSUE TITLE
[BUG] Windows package doesn't contain a logs folder and doesn't start

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#1463]
**Describe the bug**

If logs directory doesn't exist, startup will fail with `Error opening log file 'logs/gc.log': No such file or directory`. 

**To Reproduce**

Coming from https://github.com/opensearch-project/opensearch-build/issues/33 I assembled an OpenSearch Windows distribution, extracted it, created a demo certificate, then ran `bin\opensearch.bat`.

```
C:\Users\ADMINI~1\AppData\Local\Temp\2\OpenSearch>bin\opensearch.bat
Picked up _JAVA_OPTIONS: -Xmx4096M
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.002s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.002s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
Picked up _JAVA_OPTIONS: -Xmx4096M
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.opensearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:139)
        at org.opensearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:101)
        at org.opensearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:72)
        at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:152)
        at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:110)
```

**Expected behavior**
The windows distribution to just work.

Probably the windows-zip target needs to create an empty logs folder. 

**Host/Environment (please complete the following information):**
- Windows

**Comment by spaceghostcowboy** [comment]
How do you assemble an Open Search Windows distribution? Is there a more appropriate way to discus this?
