### ISSUE TITLE
org.opensearch.plugin:opensearch-dashboards:2.3.0 has issues with opensearch-dashboards unit test 

### ISSUE THREAD

**Issue by swaruparameshpajju** [opensearch-project/OpenSearch#14688]
### Describe the bug

[root@b41ffec59270 OpenSearch]# ./gradlew :modules:opensearch-dashboards:test

> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.5.1
  OS Info               : Linux 5.4.17-2136.308.9.el8uek.x86_64 (amd64)
  JDK Version           : 17 (Oracle JDK)
  JAVA_HOME             : /opt/jdk-17.0.8
  Random Testing Seed   : C3AA90B6B5DFCDE6
  In FIPS 140 mode      : false
=======================================

> Task :modules:opensearch-dashboards:test
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

org.opensearch.dashboards.OpenSearchDashboardsPluginTests > classMethod FAILED
    java.lang.RuntimeException: can not run opensearch as root
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.test.OpenSearchTestCase
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
        Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=32, name=Thread-4, state=RUNNABLE, group=TGRP-OpenSearchDashboardsPluginTests]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)

Suite: Test class org.opensearch.dashboards.OpenSearchDashboardsPluginTests
  2> java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

org.opensearch.dashboards.OpenSearchDashboardsPluginTests > classMethod FAILED
    java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)

Suite: Test class org.opensearch.dashboards.OpenSearchDashboardsPluginTests
  2> java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.test.OpenSearchTestCase
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=32, name=Thread-4, state=RUNNABLE, group=TGRP-OpenSearchDashboardsPluginTests]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

org.opensearch.dashboards.OpenSearchDashboardsPluginTests > classMethod FAILED
    java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)

Suite: Test class org.opensearch.dashboards.OpenSearchDashboardsPluginTests
  2> java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.test.OpenSearchTestCase
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=32, name=Thread-4, state=RUNNABLE, group=TGRP-OpenSearchDashboardsPluginTests]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.test.OpenSearchTestCase
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=32, name=Thread-4, state=RUNNABLE, group=TGRP-OpenSearchDashboardsPluginTests]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)

org.opensearch.dashboards.OpenSearchDashboardsPluginTests > classMethod FAILED
    java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)

Suite: Test class org.opensearch.dashboards.OpenSearchDashboardsPluginTests
  2> java.lang.RuntimeException: can not run opensearch as root
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124)
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:105)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:257)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)

Tests with failures:
 - org.opensearch.dashboards.OpenSearchDashboardsPluginTests.classMethod

4 tests completed, 4 failed

> Task :modules:opensearch-dashboards:test FAILED

FAILURE: Build failed with an exception.

### Related component

Other

### To Reproduce

Execution failed for task ':modules:opensearch-dashboards:test'.

### Expected behavior

Execution failed for task ':modules:opensearch-dashboards:test'.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dblock** [comment]
The error says `java.lang.RuntimeException: can not run opensearch as root`, does not running as `root` work?

**Comment by swaruparameshpajju** [comment]
Before getting the above error noticed this output
[10 04:27:06.103] | Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
[10 04:27:13.302] | =======================================
[10 04:27:13.302] | OpenSearch Build Hamster says Hello!
[10 04:27:13.302] | Gradle Version        : 7.5.1
[10 04:27:13.302] | OS Info               : Linux 5.4.17-2136.308.9.el8uek.x86_64 (amd64)
[10 04:27:13.303] | JDK Version           : 17 (Oracle JDK)
[10 04:27:13.303] | JAVA_HOME             : /opt/jdk-17.0.8
[10 04:27:13.303] | Random Testing Seed   : AA17E5D2962EE45F
[10 04:27:13.303] | In FIPS 140 mode      : false
[10 04:27:13.303] | =======================================
[10 04:27:13.303] | 
[10 04:27:13.303] | FAILURE: Build failed with an exception.
[10 04:27:13.303] | 
[10 04:27:13.303] | * What went wrong:
[10 04:27:13.304] | Docker (checked [/usr/bin/docker, /usr/local/bin/docker]) is required to run the following tasks:
[10 04:27:13.304] | :distribution:docker:buildArm64DockerImage
[10 04:27:13.304] | :distribution:docker:buildDockerImage
[10 04:27:13.304] | you can address this by attending to the reported issue, or removing the offending tasks from being executed.
[10 04:27:13.304] | 
[10 04:27:13.304] | * Try:
[10 04:27:13.304] | > Run with --info or --debug option to get more log output.
[10 04:27:13.305] | 
[10 04:27:13.305] | * Exception is:
[10 04:27:13.305] | org.gradle.api.GradleException: Docker (checked [/usr/bin/docker, /usr/local/bin/docker]) is required to run the following tasks:
[10 04:27:13.305] | :distribution:docker:buildArm64DockerImage
[10 04:27:13.305] | :distribution:docker:buildDockerImage
[10 04:27:13.305] | you can address this by attending to the reported issue, or removing the offending tasks from being executed.
[10 04:27:13.305] | at org.opensearch.gradle.docker.DockerSupportService.throwDockerRequiredException(DockerSupportService.java:303)
[10 04:27:13.305] | at org.opensearch.gradle.docker.DockerSupportService.throwDockerRequiredException(DockerSupportService.java:299)
[10 04:27:13.306] | at org.opensearch.gradle.docker.DockerSupportService.failIfDockerUnavailable(DockerSupportService.java:170)
[10 04:27:13.306] | at org.opensearch.gradle.docker.DockerSupportPlugin.lambda$apply$3(DockerSupportPlugin.java:76)
[10 04:27:13.306] | at jdk.internal.reflect.GeneratedMethodAccessor690.invoke(Unknown Source)
[10 04:27:13.306] | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10 04:27:13.306] | at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingInvocationHandler$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:255)
[10 04:27:13.306] | at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:98)
[10 04:27:13.306] | at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingInvocationHandler$1.run(DefaultListenerBuildOperationDecorator.java:253)
[10 04:27:13.306] | at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
[10 04:27:13.306] | at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
[10 04:27:13.306] | at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[10 04:27:13.306] | at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[10 04:27:13.307] | at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[10 04:27:13.307] | at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[10 04:27:13.307] | at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
[10 04:27:13.307] | at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
[10 04:27:13.307] | at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingInvocationHandler.invoke(DefaultListenerBuildOperationDecorator.java:250)
[10 04:27:13.307] | at jdk.proxy1/jdk.proxy1.$Proxy79.graphPopulated(Unknown Source)
[10 04:27:13.307] | at jdk.internal.reflect.GeneratedMethodAccessor690.invoke(Unknown Source)
[10 04:27:13.307] | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10 04:27:13.307] | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[10 04:27:13.307] | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[10 04:27:13.307] | at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
[10 04:27:13.307] | at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:245)
[10 04:27:13.307] | at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:157)
[10 04:27:13.308] | at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
[10 04:27:13.308] | at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:346)
[10 04:27:13.308] | at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:249)
[10 04:27:13.308] | at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
[10 04:27:13.308] | at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
[10 04:27:13.308] | at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[10 04:27:13.308] | at jdk.proxy1/jdk.proxy1.$Proxy79.graphPopulated(Unknown Source)
[10 04:27:13.308] | at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$NotifyTaskGraphWhenReady.run(DefaultTaskExecutionGraph.java:371)

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/kotwanikunal) [4](https://github.com/lukas-vlcek/)] 
@swaruparameshpajju Thanks for filing this issue, it looks like this is due to trying to run tasks without docker installed:

```
[10 04:27:13.303] | * What went wrong:
[10 04:27:13.304] | Docker (checked [/usr/bin/docker, /usr/local/bin/docker]) is required to run the following tasks:
[10 04:27:13.304] | :distribution:docker:buildArm64DockerImage
[10 04:27:13.304] | :distribution:docker:buildDockerImage
[10 04:27:13.304] | you can address this by attending to the reported issue, or removing the offending tasks from being executed.
[10 04:27:13.304] |
```

**Comment by swaruparameshpajju** [comment]
can u give me how to explicitly remove the task which is not required to execute. currently iam running using the command
[root@b41ffec59270 OpenSearch]# ./gradlew :modules:opensearch-dashboards:test 
after git clone to repository

**Comment by dblock** [comment]
@swaruparameshpajju i think the public slack #dev channel is better suited for questions like these, give it a try?

https://opensearch.org/slack.html

Closing this for now since it doesn't look like a bug in the scripts.
