### ISSUE TITLE
[BUG] - OpenSearch Dashboard V2.15.0  - JSON.parse: bad escaped character

### ISSUE THREAD

**Issue by kksaha** [opensearch-project/OpenSearch#14836]
### Describe the bug

After upgrading from 2.13 to 2.15 Discover in Dashboards is barely usable due to the following error.

`SyntaxError: Bad escaped character in JSON at position 911476 (line 1 column 911477)
    at fetch_Fetch.fetchResponse (https://dashboards.observability-opensearch.backend.ppe.cloud/7749/bundles/core/core.entry.js:15:243032)
    at async interceptResponse (https://dashboards.observability-opensearch.backend.ppe.cloud/7749/bundles/core/core.entry.js:15:237932)
    at async https://dashboards.observability-opensearch.backend.ppe.cloud/7749/bundles/core/core.entry.js:15:240899
`

### Related component

Search

### To Reproduce

Upgrade to version 2.15.0 and it will appear in the discover.

### Expected behavior

See the following error in discover 

SyntaxError: Bad escaped character in JSON at position 911476 (line 1 column 911477)

### Additional Details

Someone already reported this issue in OpenSearch forum https://forum.opensearch.org/t/json-parse-bad-escaped-character/20211

**Comment by dblock** [comment]
@kksaha See what API is being called (maybe in dev tools) that causes this?

**Comment by kksaha** [comment]
@dblock Other than launching the Discover tab with the default index, no specific API is being called. It appears that this problem has also been encountered by other users https://forum.opensearch.org/t/json-parse-bad-escaped-character/20211/6

**Comment by dblock** [comment]
I am just trying to route this somewhere. I will move this to Dashboards for now. If you can help narrow down where the error is coming from (it's caused by parsing _something_ - what is that it's trying to parse?).
