### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: unknown setting [node] please check that any required plugins are installed

### ISSUE THREAD

**Issue by samirmajen** [opensearch-project/OpenSearch#1520]
**Describe the bug**
Running the latest version of opensearch (1.1.0) as a helm template in kubernetes gives the following error in the logs:

uncaught exception in thread [main]
java.lang.IllegalArgumentException: unknown setting [node] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:557)
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:502)
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:473)
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:444)
        at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:162)
        at org.opensearch.node.Node.<init>(Node.java:417)
        at org.opensearch.node.Node.<init>(Node.java:301)
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240)
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
        at org.opensearch.cli.Command.main(Command.java:103)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105)
For complete error details, refer to the log at /usr/share/opensearch/logs/opensearch-cluster.log

The log file /usr/share/opensearch/logs/opensearch-cluster.log is empty

**To Reproduce**
1. Run the latest helm template in kubernetes
2. View the logs in any of the nodes

**Expected behavior**
The Opensearch cluster should start up successfully

**Plugins**
Please list all plugins currently enabled.

opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-notebooks
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Kubernetes
 - Version: 1.18

**Additional context**

**Comment by anasalkouz** [comment]
@opensearch-project/transfer-request
