### ISSUE TITLE
ConnectionError: getaddrinfo EMFILE

### ISSUE THREAD

**Issue by shashank-sachan** [opensearch-project/OpenSearch#1532]
**Describe the bug**
We are trying to replace the elasticsearch NPM with opensearch NPM in our project (using AWS opensearch 1.0 cluster).
We are connecting to AWS opensearch from AWS lambda.
Now in case of high load we start getting _ConnectionError: getaddrinfo EMFILE_ error.  

`
ConnectionError: getaddrinfo EMFILE *******.us-east-1.es.amazonaws.com
    at ClientRequest.onError (/opt/nodejs/node_modules/@opensearch-project/opensearch/lib/Connection.js:126:16)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  meta: {
    body: null,
    statusCode: null,
    headers: null,
    meta: {
      context: null,
      request: {...},
      name: 'opensearch-js',
      connection: {
        url: 'https://*******.us-east-1.es.amazonaws.com/',
        id: 'https://*******.us-east-1.es.amazonaws.com/',
        headers: {},
        deadCount: 4,
        resurrectTimeout: 1636607063285,
        _openRequests: 0,
        status: 'dead',
        roles: { master: true, data: true, ingest: true }
      },
      attempts: 3,
      aborted: false
    }
  }
}
`

If I put elasticsearch NPM back then it works fine.
By looking at the error, it looks like that there is host resolution problem and doesn't seem related to opensearch. But same host works fine with elasticsearch NPM.
Also this is working fine with opensearch NPM when there is low traffic. But when there is high load it starts giving error.
Is there any internal issue with opensearch http connection management?

**Plugins**
elasticsearch: "^16.5.0"
@opensearch-project/opensearch: "^1.0.0"

**Host/Environment (please complete the following information):**
AWS lambda

**Comment by ananzh** [comment]
Hi @shashank-sachan thanks for creating this issue. I think there are some confusing parts regarding your questions. First, I see you are referring Plugins elasticsearch: “^16.5.0” which is not nodejs. Seems this plugin (only this one has the 16.5 version) ? So could you help us to confirm what is this 16.5.0 es plugin? Second, from google search, EMFILE error means that the OS is denying your program to open more files/sockets (some discussions here: https://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux). From your previous observation, nodejs client has no connection issue if load is low but see issues when load is high. So it seems a limit issue. Could you look at the above discussion link and see whether it is helpful? thanks

**Comment by shashank-sachan** [comment]
Hi @ananzh,
This is the elasticsearch npm - https://www.npmjs.com/package/elasticsearch/v/16.5.0

Now I cannot change the ulimit because I’m not running this on any Linux server. Code is running inside the AWS lambda and it’s connecting to AWS managed opensearch server (previous known as AWS managed elastic search)

**Comment by vamshin** [comment]
@shashank-sachan we do not own the elasticsearch-js client. We would recommend migrate to opensearch-js client

**Comment by shashank-sachan** [comment]
@vamshin I’m not reporting issue on elasticsearch-js. I’m reporting issue with opensearch-js only. 
If you see original issue where I have mentioned in case of high load, there is an issue with opensearch-js.

**Comment by kavilla** [comment]
Hi @shashank-sachan! I think one thing to note is that the opensearch-js client was forked from the new client where you the elasticsearch-js client you are referencing is the deprecated client. Perhaps there is an optimization somewhere in the deprecated version or there is a missing header or a leak in a new client.

Would you be able to check if the non-deprecated client works as well under a high load? If it does not work then perhaps there is a current limitation that might be slightly out of control in the open-source world or if you are able to share how your function is utilizing the client then we can see if we can debug it to see if anything was missed.

If it does work then there there was a bug and we can transfer this issue to the opensearch-js repo.

Thank you!
