### ISSUE TITLE
[BUG] Import Issue version 3.0.0-beta.5:  "Cannot find module '../api/_core/index"

### ISSUE THREAD

**Issue by MichaelPooleLF** [opensearch-project/OpenSearch#15342]
### Describe the bug

Version 3.0.0-beta.5 of @opensearch-project/opensearch has an import error when building with webpack-cli version 1.5.4. Below is the error I received when attempting to build my project:

WARNING in ./node_modules/@opensearch-project/opensearch/api/utils.js 65:36-49
Critical dependency: the request of a dependency is an expression
@ ./node_modules/@opensearch-project/opensearch/lib/OpenSearchAPI.js 18:32-55
@ ./node_modules/@opensearch-project/opensearch/lib/Client.js 49:22-48
@ ./node_modules/@opensearch-project/opensearch/index.js 32:19-42
@ ./src/services/getEsClient.ts 7:21-62
@ ./src/lambda/metricsGatherer.ts 10:22-56
 
WARNING in ./node_modules/@opensearch-project/opensearch/lib/OpenSearchAPI.js 28:26-39
Critical dependency: the request of a dependency is an expression
@ ./node_modules/@opensearch-project/opensearch/lib/Client.js 49:22-48
@ ./node_modules/@opensearch-project/opensearch/index.js 32:19-42
@ ./src/services/getEsClient.ts 7:21-62
@ ./src/lambda/metricsGatherer.ts 10:22-56

Below is the error I received when attempting to execute code in an AWS Lambda:

{
    "errorType": "Error",
    "errorMessage": "Cannot find module '../api/_core/index'",
    "code": "MODULE_NOT_FOUND",
    "stack": [
        "Error: Cannot find module '../api/_core/index'",
        "    at t (/var/task/app.js:2:268736)",
        "    at E.index (/var/task/app.js:2:268342)",
        "    at /var/task/app.js:2:511081",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async Promise.all (index 0)",
        "    at async u.handler (/var/task/app.js:2:510307)"
    ]
}

This error does not exist in @openseaerch-projejct/opensearch 2.11.0

### Related component

Build

### To Reproduce

This is not exact

1. install latest beta version of @opensearch-project/opensearch
2. install webpack and webpack-cli version 5.1.4
3. Set up webpack
4. attempt build

### Expected behavior

build will compile with warning: Critical dependency: the request of a dependency is an expression

**Comment by dblock** [comment]
Moving this to opensearch-js.
