### ISSUE TITLE
[BUG] Test failure PrimaryAllocationIT.testPrimaryReplicaResyncFailed fails with reproducible seed on main

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#15427]
### Describe the bug

From: https://build.ci.opensearch.org/job/gradle-check/45305/testReport/junit/org.opensearch.cluster.routing/PrimaryAllocationIT/testPrimaryReplicaResyncFailed/ on PR 
https://github.com/opensearch-project/OpenSearch/pull/15410#issuecomment-2310783564

seed `-Dtests.seed=6656B3A5382F367D`

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.PrimaryAllocationIT.testPrimaryReplicaResyncFailed" -Dtests.seed=6656B3A5382F367D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-LC -Dtests.timezone=IST -Druntime.java=21
```

more trace:
```
java.lang.AssertionError: 
Expected: a collection with size <4>
     but: collection size was <2>
	at __randomizedtesting.SeedInfo.seed([6656B3A5382F367D:A99394DE100FA3ED]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.cluster.routing.PrimaryAllocationIT.lambda$testPrimaryReplicaResyncFailed$13(PrimaryAllocationIT.java:715)
```

Originally failed on this PR but i have reproduced this on main locally.

### Related component

Cluster Manager

### To Reproduce

see above.

### Expected behavior

Test to pass

### Additional Details

N/A

**Comment by rajiv-kv** [comment]
[Triage - attendees [1](https://github.com/rwali-aws) [2](https://github.com/reta) [3](https://github.com/rajiv-kv)]
