### ISSUE TITLE
[BUG] DeleteSnapshotITV2.testRemoteStoreCleanupForDeletedIndexForSnapshotV2 test failure

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#15692]
### Describe the bug

from https://build.ci.opensearch.org/job/gradle-check/46927/testReport/junit/org.opensearch.snapshots/DeleteSnapshotITV2/testRemoteStoreCleanupForDeletedIndexForSnapshotV2/:

```
java.lang.AssertionError: 
Expected: a value less than <34>
     but: <34> was equal to <34>
	at __randomizedtesting.SeedInfo.seed([A93EFDFF6C85704E:5AEB444669BB009C]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.snapshots.DeleteSnapshotITV2.lambda$testRemoteStoreCleanupForDeletedIndexForSnapshotV2$3(DeleteSnapshotITV2.java:312)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1136)
	at org.opensearch.snapshots.DeleteSnapshotITV2.testRemoteStoreCleanupForDeletedIndexForSnapshotV2(DeleteSnapshotITV2.java:310)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.lang.AssertionError: 
Expected: a value less than <34>
```

### Related component

Storage:Snapshots

### To Reproduce

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.DeleteSnapshotITV2.testRemoteStoreCleanupForDeletedIndexForSnapshotV2" -Dtests.seed=A93EFDFF6C85704E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=jmc-TZ -Dtests.timezone=Zulu -Druntime.java=21
```

### Expected behavior

test to pass

**Comment by mch2** [comment]
@anshu1106 I see this was added yesterday with https://github.com/opensearch-project/OpenSearch/pull/15256, can you pls take a look thanks.

**Comment by shiv0408** [comment]
Test failed in 6 PRs already - https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2e729590-eb26-11ee-b008-6583d3dd450c',key:test_name,negate:!f,params:(query:org.opensearch.snapshots.DeleteSnapshotITV2.testRemoteStoreCleanupForDeletedIndexForSnapshotV2),type:phrase),query:(match_phrase:(test_name:org.opensearch.snapshots.DeleteSnapshotITV2.testRemoteStoreCleanupForDeletedIndexForSnapshotV2)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Gradle%20Check%20Report',viewMode:view)

Can we turn the test awaiting fix till we have a fix?

**Comment by mch2** [comment]
agreed I think we should revert given it was introduced last night and has not been backported yet to 2.x or 2.17 as far as i can tell

**Comment by mch2** [comment]
looks related https://github.com/opensearch-project/OpenSearch/commit/7b0846ecb1ec3707cf996b81e74559bff1442dd5

**Comment by mch2** [comment]
merging in that last commit, will see if this resolves

**Comment by mch2** [comment]
still breaks, ran it twice locally and already get a failure.  Muting the test.

**Comment by shourya035** [comment]
@sachinpkale It seems like you already have a PR open for this. Feel free to update the issue after the PR is merged.
