### ISSUE TITLE
[BUG] `VerifyVersionConstantsIT.testLuceneVersionConstant` is failing post Lucene upgrade to 9.12.0

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#16251]
### Describe the bug

PR builds are failing with following error:

```
VerifyVersionConstantsIT > testLuceneVersionConstant FAILED
    java.lang.AssertionError: 
    Expected: <9.12.0>
         but: was <9.11.1>
        at __randomizedtesting.SeedInfo.seed([C294434BFEC7249D:4FF17E17D9CFE7D4]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant(VerifyVersionConstantsIT.java:56)
```

Reference: https://build.ci.opensearch.org/job/gradle-check/49134/console

### Related component

Build

### To Reproduce

Raise a PR against `main`, the build will fail

### Expected behavior

Test should not fail.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
Closed by https://github.com/opensearch-project/OpenSearch/pull/16252
