### ISSUE TITLE
[BUG] OpenSearch 2.17.1 cannot compatible with legacy 7.10.2

### ISSUE THREAD

**Issue by xiaoyuan0821** [opensearch-project/OpenSearch#16740]
### Describe the bug

When ES 7.10.2 node tries to join OpenSearch 2.17, exception:
```
[2024-11-29T03:45:53,239][INFO ][o.e.c.c.JoinHelper       ] [node-2] failed to join {node-1}{0nuwicDIRjW_-XjaQbhv2w}{B76Zug2gQ5epY21nFqNbPw}{192.168.69.57}{192.168.69.57:9300}{dimr}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={node-2}{5z-2vzRdRg2jBh0vvWLfzA}{ItzicgCkTmSCNBCm2ytNsQ}{10.10.1.159}{10.10.1.159:9300}{dimr}, minimumTerm=3, optionalJoin=Optional.empty}
org.elasticsearch.transport.RemoteTransportException: [node-1][192.168.69.57:9300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: index [.kibana/rfw6HIrHQ7eic8INYKbZWA] version not supported: 2.17.1 the node version is: 7.10.2
	at org.opensearch.cluster.coordination.JoinTaskExecutor.ensureIndexCompatibility(JoinTaskExecutor.java:462) ~[?:?]
	at org.opensearch.cluster.coordination.JoinTaskExecutor.lambda$addBuiltInJoinValidators$7(JoinTaskExecutor.java:700) ~[?:?]
	at org.opensearch.cluster.coordination.Coordinator.lambda$handleJoinRequest$6(Coordinator.java:634) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1117) ~[?:?]
	at org.opensearch.cluster.coordination.Coordinator.lambda$handleJoinRequest$7(Coordinator.java:634) ~[?:?]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) ~[?:?]
	at org.opensearch.transport.ClusterConnectionManager.connectToNode(ClusterConnectionManager.java:138) ~[?:?]
	at org.opensearch.transport.TransportService.connectToNode(TransportService.java:505) ~[?:?]
	at org.opensearch.transport.TransportService.connectToNode(TransportService.java:485) ~[?:?]


```

### Related component

Other

### To Reproduce

1. start a node with version OpenSearch 2.17.1
2. start another es node with version Elasticsearch 7.10.2

### Expected behavior

Elasticsearch 7.10.2 joins the cluster

**Comment by dblock** [comment]
This is by design. See https://opensearch.org/docs/latest/upgrade-to/upgrade-to,
