### ISSUE TITLE
[BUG] Commit Failures During Node Joins with Repositories Configured Result in Persistent NullPointerExceptions

### ISSUE THREAD

**Issue by Pranshu-S** [opensearch-project/OpenSearch#16762]
### Issue Overview
During node joins, when a new node containing new repository metadata joins the cluster, the cluster-manager attempts to publish the updated cluster state that includes the node and its metadata. While during this update if the publish operation succeeds and the commit fails due to other issues (like network disruption or joining leader in term), it leads to a persistent cycle of `NullPointerExceptions` which prevents the cluster to become stable. This is because as part of the publish, the last accepted version and cluster state are updated but due to commits not run, the cluster-state appliers are not executed. This results in the repositories service not in sync with the repositories metadata in the cluster state. Now when the current cluster-manager (leader) steps down and another cluster-manager is elected:

1. The newly elected cluster-manager attempts to verify repository metadata as part of its leadership transition.
2. It checks the metadata in the cluster state for the presence of a specific repository. If the repository exists, it attempts to fetch its corresponding object from the repository service.
3. Since the repository service was not updated earlier (due to the cluster appliers not being executed), this leads to a `NullPointerException`, causing instability in the cluster-manager election and transition process.

[Logs from IT used to repro the issue]
```
[2024-12-03T17:32:27,926][INFO ][o.o.c.c.JoinHelper       ] [node_t0] failed to join {node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}, minimumTerm=1, optionalJoin=Optional[Join{term=2, lastAcceptedTerm=1, lastAcceptedVersion=8, sourceNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}, targetNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [node_t0][127.0.0.1:50328][internal:cluster/coordination/join]
Caused by: java.lang.NullPointerException: Cannot invoke "org.opensearch.repositories.Repository.getRestrictedSystemRepositorySettings()" because "repository" is null
	at org.opensearch.repositories.RepositoriesService.ensureValidSystemRepositoryUpdate(RepositoriesService.java:907) ~[main/:?]
	at org.opensearch.node.remotestore.RemoteStoreNodeService.updateRepositoriesMetadata(RemoteStoreNodeService.java:194) ~[main/:?]
	at org.opensearch.cluster.coordination.JoinTaskExecutor.execute(JoinTaskExecutor.java:210) ~[main/:?]
	at org.opensearch.cluster.coordination.JoinHelper$1.execute(JoinHelper.java:197) ~[main/:?]
	at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:917) ~[main/:?]
	at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:469) ~[main/:?]
	at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:329) [main/:?]
	at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:229) [main/:?]
	at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:206) [main/:?]
	at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:264) [main/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:932) [main/:?]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283) [main/:?]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246) [main/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

### Related component

Cluster Manager

### To Reproduce

1. Create a cluster without repositories configured and allow it to become stable.
2. Start a new node with repositories configured
3. Disrupt the cluster-manager by allowing the publish to succeed and the commit to fail

### Expected behavior

1. The repository service should remain in sync with the cluster state, even if a commit failure occurs during node joins.
2. The newly elected cluster-manager should initialise without errors and correctly fetch repository objects.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by Pranshu-S** [comment]
To understand this issue in-depth, as part of node-joins, we run the JoinTaskExecutor task to add the nodes and update the cluster state, here if the node has remote-store configured or remote-publication configured, we update the repositories metadata by reading the node-attributes of the joining node and updating the existing metadata. Notice here, we take the metadata from the current state
https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java#L197-L215

Note: The current state used here is fetched from the last accepted state from CoordinationState. The 
https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java#L1296-L1307

Moving forward, as part of [RemoteStoreNodeService::updateRepositoriesMetadata](https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java#L170), we get the repositories metadata from the joining node and for each of the RepositoriesMetadata coming from the joining node, we check if the metadata existing in our current cluster state and if so, we call [RepositoriesService::ensureValidSystemRepositoryUpdate](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/repositories/RepositoriesService.java#L898)

https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java#L170-L194

As part of ensuring valid system repositories, we fetch the corresponding repository from the repository service and face NPEs when we try to perform the `Repository::getRestrictedSystemRepositorySettings` as in our case the repository metadata is ahead of the repositories present in the repository service.

https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/repositories/RepositoriesService.java#L898-L910

To understand why our repositories are lagging behind, we see that there are two ways to update the repository in the repository service.

Method 1: updateRepositoriesMap 
→ Called by createAndVerifyRepositories
During node bootstrap - if RemoteStoreAttributes are present (node-attributes indicating repositories for remote publication or store), it calls [remoteStoreNodeService.createAndVerifyRepositories(discoveryNode)](https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java#L137)

1. Gets the repositories from nodeAttributes
2. Validates the file name of the repository
3. Creates a repository object
4. Verifies the repositories 
5. Updates the RepositoriesMap with the repository variable

https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java#L137-L163

Method 2: applyClusterState

-> Called as part of [ClusterApplierService::runTask](https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java#L453) which in-turn is triggered as part of the apply task submitted when [ApplyCommitRequest](https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java#L396) is received on the nodes

Checks if new repositories appeared in or disappeared from cluster metadata and updates current list of repositories accordingly.

1. Gets the oldMetaData (current state) and NewMetaData (incoming state)
2. For repositories in local, we update the repos with the metadata of those same repos in same.
3. For repositories in  local, we check if the newMetaData does not have these repos - we close and repository else we add it to the list of survivors 
4. For each repository in the new state, we check if the repo is present in the survivor list and if it is ... we validate and update the repos else we create it

https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/repositories/RepositoriesService.java#L537

Now since we know that the existing nodes do not have the node-attributes, we can safely assume that the only path for the existing cluster-manager node to have the state updated is through Method 2.

Since we know that the cluster-state is updated in coordinatorState as part of publish path (in handlePublishRequest), this will lead to cases wherein the cluster-state is ahead of the repository service incase the cluster-manager node fails to send the commit request

https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java#L416-L460

**Comment by rajiv-kv** [comment]
Triage Attendees [1](https://github.com/aasom143) [2](https://github.com/rajiv-kv)

Thanks @Pranshu-S for filing the issue. Please feel free to raise a fix.
