### ISSUE TITLE
[BUG] Flaky org.opensearch.search.aggregations.bucket.composite.GeoTileGridValuesSourceBuilderTests.testBWCBounds test

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#1690]
**Describe the bug**
The flaky `org.opensearch.search.aggregations.bucket.composite.GeoTileGridValuesSourceBuilderTests.testBWCBounds` (recent one) is the culprit of many build failures [1], [2], [3]

[1] https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1415.log
[2] https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1406.log
[3] https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1405.log

**To Reproduce**
1. Reproducible locally but not all the time: `gradle :server:test`

```
2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.search.aggregations.bucket.composite.GeoTileGridValuesSourceBuilderTests.testBWCBounds" -Dtests.seed=2A64EE159B04B99 -Dtests.security.manager
=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-ME -Dtests.timezone=GB -Druntime.java=17                                                                       
  2> java.lang.AssertionError:                                                                                                                                                                                     
    Expected: <BBOX (NaN, NaN, NaN, NaN)>                                                                                                                                                                          
         but: was <BBOX (44.48260982057536, -180.0, 15.216909369183995, -90.0)>                                                                                                                                    
        at __randomizedtesting.SeedInfo.seed([2A64EE159B04B99:83FAD1C89E8311B1]:0)                                                                                                                                 
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)                                                                                                                                            
        at org.junit.Assert.assertThat(Assert.java:956)                                                                                                                                                            
        at org.junit.Assert.assertThat(Assert.java:923)                                                                                                                                                            
        at org.opensearch.search.aggregations.bucket.composite.GeoTileGridValuesSourceBuilderTests.testBWCBounds(GeoTileGridValuesSourceBuilderTests.java:76)  
```

**Expected behavior**
Test should pass.

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 21.10, JDK 17

**Additional context**
N/A

**Comment by reta** [comment]
Closing, seems to be gone after https://github.com/opensearch-project/OpenSearch/commit/b74d71fb747cc2873d4c2ffae825944da4d06e1b
