### ISSUE TITLE
[BUG] PrimaryAllocationIT intermittently fails

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#1722]
**Describe the bug**

```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.PrimaryAllocationIT.testPrimaryReplicaResyncFailed" -Dtests.seed=6D4D4C998D58C02E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m -Djava.security.manager=allow" -Dtests.locale=es-CR -Dtests.timezone=Africa/Johannesburg -Druntime.java=17

org.opensearch.cluster.routing.PrimaryAllocationIT > testPrimaryReplicaResyncFailed FAILED
    java.lang.AssertionError: 
    Expected: a collection with size <4>
         but: collection size was <3>
        at __randomizedtesting.SeedInfo.seed([6D4D4C998D58C02E:A2886BE2A57855BE]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.opensearch.cluster.routing.PrimaryAllocationIT.lambda$testPrimaryReplicaResyncFailed$14(PrimaryAllocationIT.java:727)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1048)
        at org.opensearch.cluster.routing.PrimaryAllocationIT.testPrimaryReplicaResyncFailed(PrimaryAllocationIT.java:724)
```

https://github.com/opensearch-project/OpenSearch/pull/1721

https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1478.log

**Comment by kotwanikunal** [comment]
Taking a look at this issue.

**Comment by anasalkouz** [comment]
@kotwanikunal are you actively working on this issue?

**Comment by kotwanikunal** [comment]
> @kotwanikunal are you actively working on this issue?

This is currently on the backlog and I am not actively looking into it.

**Comment by adnapibar** [comment]
This seems out of data as it hasn't been reported again in the CI. Not reproducible locally.
