### ISSUE TITLE
[CI] o.o.cluster.ClusterHealthIT.testHealthOnMasterFailover test failure

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1744]
Could be a flakey test. Documenting to see if this repeatedly fails on CI.

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.ClusterHealthIT.testHealthOnMasterFailover" -Dtests.seed=58E01485FD8F1669 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m -Djava.security.manager=allow" -Dtests.locale=sr-Latn-RS -Dtests.timezone=America/Montserrat -Druntime.java=17
```

```
org.opensearch.cluster.ClusterHealthIT > testHealthOnMasterFailover FAILED
    java.util.concurrent.ExecutionException: MasterNotDiscoveredException[NodeClosedException[node closed {node_s1}{LW9HHvIqQ0qop98CQxk5og}{qu7gbOicQA6-BH7hVPBpHw}{127.0.0.1}{127.0.0.1:42515}{dimr}{shard_indexing_pressure_enabled=true}]]; nested: NodeClosedException[node closed {node_s1}{LW9HHvIqQ0qop98CQxk5og}{qu7gbOicQA6-BH7hVPBpHw}{127.0.0.1}{127.0.0.1:42515}{dimr}{shard_indexing_pressure_enabled=true}];
        at __randomizedtesting.SeedInfo.seed([58E01485FD8F1669:C60F3BA8FE650A8F]:0)
        at org.opensearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:281)
        at org.opensearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:268)
        at org.opensearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:99)
        at org.opensearch.cluster.ClusterHealthIT.testHealthOnMasterFailover(ClusterHealthIT.java:393)

        Caused by:
        MasterNotDiscoveredException[NodeClosedException[node closed {node_s1}{LW9HHvIqQ0qop98CQxk5og}{qu7gbOicQA6-BH7hVPBpHw}{127.0.0.1}{127.0.0.1:42515}{dimr}{shard_indexing_pressure_enabled=true}]]; nested: NodeClosedException[node closed {node_s1}{LW9HHvIqQ0qop98CQxk5og}{qu7gbOicQA6-BH7hVPBpHw}{127.0.0.1}{127.0.0.1:42515}{dimr}{shard_indexing_pressure_enabled=true}];
            at app//org.opensearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:275)
            at app//org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:369)
```

**Comment by nknize** [comment]
Closing as duplicate of #1693
