### ISSUE TITLE
[CI] Intermittent java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#1826]
**Describe the bug**
Intermittent test failures due to java.lang.Exception: Suite timeout exceeded (>= 1200000 msec). It seems like the issue is related to `/dev/random` entropy:

```
  2> REPRODUCE WITH: ./gradlew ':distribution:tools:plugin-cli:test' --tests "org.opensearch.plugins.InstallPluginCommandTests" -Dtests.method="testOfficialPlatformPluginStaging {p0=com.google.common.jimfs.JimfsFileSystem@1fa28a8a p1=org.opensearch.plugins.InstallPluginCommandTests$1Parameter$$Lambda$228/0x0000000800d80b90@11eae39d}" -Dtests.seed=6B54929A74743DF5 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-PH -Dtests.timezone=Africa/Casablanca -Druntime.java=15
  2> java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([6B54929A74743DF5]:0)
  2> Dec 29, 2021 5:55:14 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> WARNING: Will linger awaiting termination of 1 leaked thread(s).
  2> Dec 29, 2021 5:55:19 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> SEVERE: 1 thread leaked from SUITE scope at org.opensearch.plugins.InstallPluginCommandTests: 
  2>    1) Thread[id=36, name=TEST-InstallPluginCommandTests.testOfficialPlatformPluginStaging-seed#[6B54929A74743DF5], state=RUNNABLE, group=TGRP-InstallPluginCommandTests]
  2>         at java.base@15.0.1/java.io.FileInputStream.readBytes(Native Method)
  2>         at java.base@15.0.1/java.io.FileInputStream.read(FileInputStream.java:271)
  2>         at java.base@15.0.1/java.io.FilterInputStream.read(FilterInputStream.java:132)
  2>         at java.base@15.0.1/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
  2>         at java.base@15.0.1/sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(NativePRNG.java:441)
  2>         at java.base@15.0.1/sun.security.provider.NativePRNG.engineGenerateSeed(NativePRNG.java:226)
  2>         at java.base@15.0.1/java.security.SecureRandom.generateSeed(SecureRandom.java:857)
  2>         at app//org.bouncycastle.crypto.util.BasicEntropySourceProvider$1.getEntropy(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.ContinuousTestingEntropySource.getEntropy(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.HashSP800DRBG.getEntropy(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.HashSP800DRBG.init(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.HashSP800DRBG.<init>(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.FipsDRBG$HashDRBGProvider.get(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.DRBGPseudoRandom.lazyInitDRBG(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.DRBGPseudoRandom.generate(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.FipsSecureRandom$RandomSpi.engineNextBytes(Unknown Source)
  2>         at java.base@15.0.1/java.security.SecureRandom.nextBytes(SecureRandom.java:754)
  2>         at java.base@15.0.1/java.math.BigInteger.randomBits(BigInteger.java:702)
  2>         at java.base@15.0.1/java.math.BigInteger.<init>(BigInteger.java:691)
  2>         at app//org.bouncycastle.util.BigIntegers.createRandomInRange(Unknown Source)
  2>         at app//org.bouncycastle.math.internal.Primes.enhancedMRProbablePrimeTest(Unknown Source)
  2>         at app//org.bouncycastle.crypto.asymmetric.KeyUtils.validatedModulus(Unknown Source)
  2>         at app//org.bouncycastle.crypto.asymmetric.KeyUtils.validated(Unknown Source)
  2>         at app//org.bouncycastle.crypto.asymmetric.AsymmetricRSAPublicKey.<init>(Unknown Source)
  2>         at app//org.bouncycastle.jcajce.provider.ProvRSAPublicKey.<init>(Unknown Source)
  2>         at app//org.bouncycastle.jcajce.provider.ProvRSA$RSAKeyFactory.engineGeneratePublic(Unknown Source)
  2>         at java.base@15.0.1/java.security.KeyFactory.generatePublic(KeyFactory.java:346)
  2>         at app//org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.implGeneratePublic(Unknown Source)
  2>         at app//org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPublicKey(Unknown Source)
  2>         at app//org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentVerifierBuilderProvider$JcaPGPContentVerifierBuilder.build(Unknown Source)
  2>         at app//org.bouncycastle.openpgp.PGPSignature.init(Unknown Source)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.verifySignature(InstallPluginCommand.java:638)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests$4.verifySignature(InstallPluginCommandTests.java:951)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:600)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:306)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.installPlugins(InstallPluginCommandTests.java:316)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.installPlugin(InstallPluginCommandTests.java:311)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.assertInstallPluginFromUrl(InstallPluginCommandTests.java:1000)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.assertInstallPluginFromUrl(InstallPluginCommandTests.java:1012)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.testOfficialPlatformPluginStaging(InstallPluginCommandTests.java:1099)
  2>         at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  2>         at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  2>         at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  2>         at java.base@15.0.1/java.lang.reflect.Method.invoke(Method.java:564)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  2>         at app//org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  2>         at app//org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  2>         at app//org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  2>         at app//org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  2>         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  2>         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  2>         at app//org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  2>         at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  2>         at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  2>         at app//org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  2>         at app//org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  2>         at app//org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         a  2> t app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  2>         at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
  2> Dec 29, 2021 5:55:19 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> INFO: Starting to interrupt leaked threads:
  2>    1) Thread[id=36, name=TEST-InstallPluginCommandTests.testOfficialPlatformPluginStaging-seed#[6B54929A74743DF5], state=RUNNABLE, group=TGRP-InstallPluginCommandTests]
  2> Dec 29, 2021 5:55:22 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> SEVERE: There are still zombie threads that couldn't be terminated:
  2>    1) Thread[id=36, name=TEST-InstallPluginCommandTests.testOfficialPlatformPluginStaging-seed#[6B54929A74743DF5], state=RUNNABLE, group=TGRP-InstallPluginCommandTests]
  2>         at java.base@15.0.1/java.io.FileInputStream.readBytes(Native Method)
  2>         at java.base@15.0.1/java.io.FileInputStream.read(FileInputStream.java:271)
  2>         at java.base@15.0.1/java.io.FilterInputStream.read(FilterInputStream.java:132)
  2>         at java.base@15.0.1/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
  2>         at java.base@15.0.1/sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(NativePRNG.java:441)
  2>         at java.base@15.0.1/sun.security.provider.NativePRNG.engineGenerateSeed(NativePRNG.java:226)
  2>         at java.base@15.0.1/java.security.SecureRandom.generateSeed(SecureRandom.java:857)
  2>         at app//org.bouncycastle.crypto.util.BasicEntropySourceProvider$1.getEntropy(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.ContinuousTestingEntropySource.getEntropy(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.HashSP800DRBG.getEntropy(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.HashSP800DRBG.init(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.HashSP800DRBG.<init>(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.FipsDRBG$HashDRBGProvider.get(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.DRBGPseudoRandom.lazyInitDRBG(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.DRBGPseudoRandom.generate(Unknown Source)
  2>         at app//org.bouncycastle.crypto.fips.FipsSecureRandom$RandomSpi.engineNextBytes(Unknown Source)
  2>         at java.base@15.0.1/java.security.SecureRandom.nextBytes(SecureRandom.java:754)
  2>         at java.base@15.0.1/java.math.BigInteger.randomBits(BigInteger.java:702)
  2>         at java.base@15.0.1/java.math.BigInteger.<init>(BigInteger.java:691)
  2>         at app//org.bouncycastle.util.BigIntegers.createRandomInRange(Unknown Source)
  2>         at app//org.bouncycastle.math.internal.Primes.enhancedMRProbablePrimeTest(Unknown Source)
  2>         at app//org.bouncycastle.crypto.asymmetric.KeyUtils.validatedModulus(Unknown Source)
  2>         at app//org.bouncycastle.crypto.asymmetric.KeyUtils.validated(Unknown Source)
  2>         at app//org.bouncycastle.crypto.asymmetric.AsymmetricRSAPublicKey.<init>(Unknown Source)
  2>         at app//org.bouncycastle.jcajce.provider.ProvRSAPublicKey.<init>(Unknown Source)
  2>         at app//org.bouncycastle.jcajce.provider.ProvRSA$RSAKeyFactory.engineGeneratePublic(Unknown Source)
  2>         at java.base@15.0.1/java.security.KeyFactory.generatePublic(KeyFactory.java:346)
  2>         at app//org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.implGeneratePublic(Unknown Source)
  2>         at app//org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPublicKey(Unknown Source)
  2>         at app//org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentVerifierBuilderProvider$JcaPGPContentVerifierBuilder.build(Unknown Source)
  2>         at app//org.bouncycastle.openpgp.PGPSignature.init(Unknown Source)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.verifySignature(InstallPluginCommand.java:638)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests$4.verifySignature(InstallPluginCommandTests.java:951)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:600)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:306)
  2>         at app//org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.installPlugins(InstallPluginCommandTests.java:316)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.installPlugin(InstallPluginCommandTests.java:311)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.assertInstallPluginFromUrl(InstallPluginCommandTests.java:1000)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.assertInstallPluginFromUrl(InstallPluginCommandTests.java:1012)
  2>         at app//org.opensearch.plugins.InstallPluginCommandTests.testOfficialPlatformPluginStaging(InstallPluginCommandTests.java:1099)
  2>         at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  2>         at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  2>         at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  2>         at java.base@15.0.1/java.lang.reflect.Method.invoke(Method.java:564)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  2>         at app//org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  2>         at app//org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  2>         at app//org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  2>         at app//org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  2>         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  2>         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  2>         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  2>         at app//org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  2>         at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  2>         at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  2>         at app//org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  2>         at app//org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  2>         at app//org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  2>         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at app//com.carrotsearch.ra  2> ndomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  2>         at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
  2> java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
        at __randomizedtesting.SeedInfo.seed([6B54929A74743DF5]:0)
  2> REPRODUCE WITH: ./gradlew ':distribution:tools:plugin-cli:test' --tests "org.opensearch.plugins.InstallPluginCommandTests" -Dtests.seed=6B54929A74743DF5 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-PH -Dtests.timezone=Africa/Casablanca -Druntime.java=15
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=907, maxMBSortInHeap=7.641884560530356, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=en-PH, timezone=Africa/Casablanca
  2> NOTE: Linux 5.4.0-1045-aws amd64/AdoptOpenJDK 15.0.1 (64-bit)/cpus=72,threads=2,free=338548584,total=536870912
  2> NOTE: All tests run in this JVM: [InstallPluginCommandTests]

Tests with failures:
 - org.opensearch.plugins.InstallPluginCommandTests.testOfficialPlatformPluginStaging {p0=com.google.common.jimfs.JimfsFileSystem@1fa28a8a p1=org.opensearch.plugins.InstallPluginCommandTests$1Parameter$$Lambda$228/0x0000000800d80b90@11eae39d}
 - org.opensearch.plugins.InstallPluginCommandTests.classMethod

129 tests completed, 2 failed, 5 skipped
```

Relates to https://github.com/opensearch-project/OpenSearch/issues/1715

**To Reproduce**
See please https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1721.log

**Expected behavior**
No timeout are expected

**Plugins**
N/A

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by reta** [comment]
We have seen it on `main` and fixed in https://github.com/opensearch-project/OpenSearch/pull/1358/files, probably needs backport of the fix to the 1.x

**Comment by reta** [comment]
Closed by https://github.com/opensearch-project/OpenSearch/pull/1827
