### ISSUE TITLE
[BUG] Transport NIO test intermittently failing for large responses

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#1844]
Coming from https://github.com/opensearch-project/OpenSearch/pull/1834#issuecomment-1005036114

```
REPRODUCE WITH: ./gradlew ':plugins:transport-nio:test' --tests "org.opensearch.http.nio.NioHttpServerTransportTests.testLargeCompressedResponse" -Dtests.seed=EA1764D9DE4EEADD -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=no -Dtests.timezone=America/Maceio -Druntime.java=15

org.opensearch.http.nio.NioHttpServerTransportTests > testLargeCompressedResponse FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=183, name=opensearch[transport_worker][T#1], state=RUNNABLE, group=TGRP-NioHttpServerTransportTests]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([EA1764D9DE4EEADD]:0)
            at org.opensearch.http.nio.NioHttpServerTransportTests$3.dispatchRequest(NioHttpServerTransportTests.java:351)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=184, name=opensearch[transport_worker][T#2], state=RUNNABLE, group=TGRP-NioHttpServerTransportTests]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([EA1764D9DE4EEADD]:0)
            at org.opensearch.http.nio.NioHttpServerTransportTests$3.dispatchRequest(NioHttpServerTransportTests.java:351)
```

**Comment by adnapibar** [comment]
Not able to reproduce this locally
