### ISSUE TITLE
[BUG] Upgrade cli test failure while detecting exiting ES installations

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#1846]
Coming from https://github.com/opensearch-project/OpenSearch/pull/1834#issuecomment-1005036875

Seens like a genuine failure but a re-run went through. 
I suspect this could related to parallel runs on CI infra.

```
REPRODUCE WITH: ./gradlew ':distribution:tools:upgrade-cli:test' --tests "org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution" -Dtests.seed=1F6F70AEA6323361 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms-MY -Dtests.timezone=America/Araguaina -Druntime.java=15

org.opensearch.upgrade.DetectEsInstallationTaskTests > testTaskExecution FAILED
    java.lang.AssertionError: 
    Expected: a collection with size <0>
         but: collection size was <5>
        at __randomizedtesting.SeedInfo.seed([1F6F70AEA6323361:5575542572657CE4]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution(DetectEsInstallationTaskTests.java:53)


Suite: Test class org.opensearch.upgrade.DetectEsInstallationTaskTests
  1> [2022-01-03T14:53:51,848][INFO ][o.o.u.DetectEsInstallationTaskTests] [testTaskExecution] before test
  1> [2022-01-03T14:53:53,132][INFO ][o.o.u.DetectEsInstallationTaskTests] [testTaskExecution] after test
  2> REPRODUCE WITH: ./gradlew ':distribution:tools:upgrade-cli:test' --tests "org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution" -Dtests.seed=1F6F70AEA6323361 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms-MY -Dtests.timezone=America/Araguaina -Druntime.java=15
  2> java.lang.AssertionError: 
    Expected: a collection with size <0>
         but: collection size was <5>
        at __randomizedtesting.SeedInfo.seed([1F6F70AEA6323361:5575542572657CE4]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution(DetectEsInstallationTaskTests.java:53)
  1> [2022-01-03T14:53:53,273][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveDefaultUrlFromConfig] before test
  1> [2022-01-03T14:53:53,281][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveDefaultUrlFromConfig] after test
  1> [2022-01-03T14:53:53,304][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveUrlFromSettings] before test
  1> [2022-01-03T14:53:53,311][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveUrlFromSettings] after test
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/tools/upgrade-cli/build/testrun/test/temp/org.opensearch.upgrade.DetectEsInstallationTaskTests_1F6F70AEA6323361-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=289, maxMBSortInHeap=6.155808444014184, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ms-MY, timezone=America/Araguaina
  2> NOTE: Linux 5.4.0-1045-aws amd64/AdoptOpenJDK 15.0.1 (64-bit)/cpus=72,threads=1,free=401056352,total=536870912
  2> NOTE: All tests run in this JVM: [DetectEsInstallationTaskTests]
```

**Comment by saratvemulapalli** [comment]
Another occurrence: https://github.com/opensearch-project/OpenSearch/pull/2037

**Comment by andrross** [comment]
No reference in over a year. Closing.
