### ISSUE TITLE
[BUG] org.opensearch.common.network.InetAddressesTests.testForStringIPv6WithScopeIdInput

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#1887]
**Describe the bug**
```
org.opensearch.common.network.InetAddressesTests > testForStringIPv6WithScopeIdInput FAILED
243 | java.net.UnknownHostException: no scope_id found
244 | at __randomizedtesting.SeedInfo.seed([D7519A98383FCD86:F581D4F66795B2D5]:0)
245 | at java.base/java.net.Inet6Address.deriveNumericScope(Inet6Address.java:538)
246 | at java.base/java.net.Inet6Address$Inet6AddressHolder.init(Inet6Address.java:247)
247 | at java.base/java.net.Inet6Address.initif(Inet6Address.java:495)
248 | at java.base/java.net.Inet6Address.initstr(Inet6Address.java:485)
249 | at java.base/java.net.Inet6Address.<init>(Inet6Address.java:404)
250 | at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1356)
251 | at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
252 | at java.base/java.net.InetAddress.getByName(InetAddress.java:1251)
253 | at org.opensearch.common.network.InetAddressesTests.testForStringIPv6WithScopeIdInput(InetAddressesTests.java:157)
254

```
**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.common.network.InetAddressesTests.testForStringIPv6WithScopeIdInput" -Dtests.seed=D7519A98383FCD86 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ja-JP -Dtests.timezone=Pacific/Fakaofo -Druntime.java=17
```

**Comment by reta** [comment]
Fixing this one, found the cause
