### ISSUE TITLE
[BUG] org.opensearch.gateway.QuorumGatewayIT > testQuorumRecovery FAILED

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#1908]
**Describe the bug**
Caught on PR https://github.com/opensearch-project/OpenSearch/issues/1906

```
org.opensearch.gateway.QuorumGatewayIT > testQuorumRecovery FAILED
    java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([5B60BE42A81D1B47:BE5F82910960CC5C]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1019)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:958)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:947)
        at org.opensearch.gateway.QuorumGatewayIT.testQuorumRecovery(QuorumGatewayIT.java:111)
```

Log: https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1923.log
Report: https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1923_reports.zip

**To Reproduce**
Another failure that can't be reproduced :(

**Expected behavior**
Test should pass all the time

**Plugins**
 All core opensearch

**Screenshots**

**Host/Environment (please complete the following information):**
- https://github.com/opensearch-project/OpenSearch/pull/1906

**Additional context**
N/A

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/5143

**Comment by minalsha** [comment]
Closing the issue since fix is merged with https://github.com/opensearch-project/OpenSearch/pull/5651.
