### ISSUE TITLE
[BUG] org.opensearch.cluster.routing.allocation.IndexShardHotSpotTests.testSkewedClusterScaleOut intermittent failure

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#2091]
**Describe the bug**

```
> Task :server:test

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.cluster.routing.allocation.IndexShardHotSpotTests.testSkewedClusterScaleOut" -Dtests.seed=75E02AFCC6453F60 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nl -Dtests.timezone=America/Knox_IN -Druntime.java=17

org.opensearch.cluster.routing.allocation.IndexShardHotSpotTests > testSkewedClusterScaleOut FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([75E02AFCC6453F60:A184949F2E2E9485]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.cluster.routing.allocation.IndexShardHotSpotTests.testSkewedClusterScaleOut(IndexShardHotSpotTests.java:66)
WARNING: A terminally deprecated method in java.lang.System has been called

```

**Comment by tlfeng** [comment]
The failed assertion for this test was https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardHotSpotTests.java#L66
