### ISSUE TITLE
Improve visibility of problems during shard recovery 

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#2167]
The default logging level on production systems is INFO, which fails to log actual issues. In this case shard relocation due to version upgrade was stuck from src version 6.8 due to limit `index.mapping.nested_objects.limit]` introduced in 7.x which isn't present in 6.8 causing translog recovery on 7.x and higher versions to fail

Changing the log level and retrying the recovery logged the actual problem which was otherwise hidded

```
[2022-02-17T06:06:13,870][DEBUG][o.e.i.r.PeerRecoveryTargetService] [3e89ccfc62cace6b33800009c25] delaying recovery due to missing mapping changes
MapperParsingException[The number of nested documents has exceeded the allowed limit of [10000]. This limit can be set by changing the [index.mapping.nested_ob
jects.limit] index level setting.]
        at org.elasticsearch.index.mapper.ParseContext$InternalParseContext.addDoc(ParseContext.java:385)
        at org.elasticsearch.index.mapper.ParseContext$FilterParseContext.addDoc(ParseContext.java:217)
        at org.elasticsearch.index.mapper.ParseContext.createNestedContext(ParseContext.java:548)
        at org.elasticsearch.index.mapper.DocumentParser.nestedContext(DocumentParser.java:454)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:383)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:482)
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:502)
        at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:592)
        at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:544)
        at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:417)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:395)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:482)
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:502)

```

The APIs like `/_cat/recovery` fail to spit out the error and show recovery as stuck which makes debugging really hard.

**Comment by CEHENKLE** [comment]
@Bukhtawar Is there a more general solution you have in mind, or are you looking to fix only this particular error?  

Thanks!

**Comment by Bukhtawar** [comment]
In general we should revisit all non-retryable classes of exception and log them appropriately, the logging is usually too silent
