### ISSUE TITLE
[BUG] ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimits assertion error

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#2241]
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimits" -Dtests.seed=D6BACFF135EA7C0B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=bg -Dtests.timezone=Asia/Novosibirsk -Druntime.java=17
...
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([D6BACFF135EA7C0B:44EAAEC902695D33]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testCoordinatingPrimaryThreadedUpdateToShardLimits(ShardIndexingPressureConcurrentExecutionTests.java:74)
```

❌   Gradle Check failure https://github.com/opensearch-project/OpenSearch/commit/9e413b424e9832118cb552e9e2b6faba216540a6
[Log 2773](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_2773.log)

[Reports 2773](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_2773_reports.zip)

Identified in https://github.com/opensearch-project/OpenSearch/pull/2238

**Comment by andrross** [comment]
Another failure here: https://build.ci.opensearch.org/job/gradle-check/6616/
