### ISSUE TITLE
[BUG] OpenSearch 1.2.4 is crashing in the aarch64

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/OpenSearch#2295]
**Describe the bug**
OpenSearch 1.2.4 was crashed in the aarch64

openJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int org.conscrypt.NativeCrypto.EVP_has_aes_hardware()'
        at org.conscrypt.NativeCrypto.EVP_has_aes_hardware(Native Method)
        at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:831)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:60)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:53)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:49)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
ElasticSearch server with pid 8630 has already terminated with rc: 1
2022-02-28 19:00:34,416 run-es [MILESTONE] pid(8572):thr(281472862265360): Try to delete certs files when exiting........

**To Reproduce**
1. Go to 'var/output/logs'
2. There is no elastic.log, the supervisord.es.log have exception above

**Expected behavior**
OpenSearch 1.24 should up and have elastic.log

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/33105471/156219045-4e56e401-d602-4600-9a7d-56d2fbc79341.png">

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS]: Linux 64bit
 - Version [e.g. 22] Linux 5.4.176-91.338.amzn2.aarch64

**Additional context**

**Comment by CEHENKLE** [comment]
This appears to be an issue in the AOS build.  Resolving here for now, but if it turns out to be in the open source, feel free to reopen.
