### ISSUE TITLE
[BUG] o.o.search.SearchCancellationIT.testCancellationDuringFetchPhaseUsingRequestParameter

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2311]
Non-reproducible test failure caught on #2262

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchCancellationIT.testCancellationDuringFetchPhaseUsingRequestParameter" -Dtests.seed=6C5BC8BF8BF27536 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr-BE -Dtests.timezone=Europe/Astrakhan -Druntime.java=17
```

```
  2> java.lang.AssertionError: At least one shard should have failed. Actual: 0
        at __randomizedtesting.SeedInfo.seed([6C5BC8BF8BF27536:ECD39451EE78990B]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failEquals(Assert.java:187)
        at org.junit.Assert.assertNotEquals(Assert.java:201)
        at org.opensearch.search.SearchCancellationIT.ensureSearchWasCancelled(SearchCancellationIT.java:167)
        at org.opensearch.search.SearchCancellationIT.testCancellationDuringFetchPhaseUsingRequestParameter(SearchCancellationIT.java:301)
```

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/2886#issuecomment-1098122125
