### ISSUE TITLE
[CI] o.o.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureEnforcedEnabledDisabledSetting

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2348]
Caught non-reproducible test failure on #2335 

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureEnforcedEnabledDisabledSetting" -Dtests.seed=22A65A59009482EF -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-ME -Dtests.timezone=Pacific/Majuro -Druntime.java=17
```

```
org.opensearch.index.ShardIndexingPressureSettingsIT > testShardIndexingPressureEnforcedEnabledDisabledSetting FAILED
    java.lang.AssertionError: expected:<0> but was:<2>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.index.ShardIndexingPressureSettingsIT.lambda$waitForTwoOutstandingRequests$13(ShardIndexingPressureSettingsIT.java:929)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1060)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1033)
        at org.opensearch.index.ShardIndexingPressureSettingsIT.waitForTwoOutstandingRequests(ShardIndexingPressureSettingsIT.java:928)
        at org.opensearch.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureEnforcedEnabledDisabledSetting(ShardIndexingPressureSettingsIT.java:406)

    java.lang.AssertionError: shard [test_index][0] on node [node_t1] has pending operations:
     --> BulkShardRequest [[test_index][0]] containing [80] requests
```

**Comment by saratvemulapalli** [comment]
cc: @Rishikesh1159

**Comment by reta** [comment]
Closing in favour of https://github.com/opensearch-project/OpenSearch/issues/14331
