### ISSUE TITLE
[BUG] org.opensearch.snapshots.ConcurrentSnapshotsIT > testQueuedOperationsAndBrokenRepoOnMasterFailOver

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#2353]
**Describe the bug**
Caught on https://github.com/opensearch-project/OpenSearch/pull/2325#issuecomment-1059411816.
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.ConcurrentSnapshotsIT.testQueuedOperationsAndBrokenRepoOnMasterFailOver" -Dtests.seed=3F66F49CFB1DE3E7 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sv -Dtests.timezone=Etc/UTC -Druntime.java=17
```

```
org.opensearch.snapshots.ConcurrentSnapshotsIT > testQueuedOperationsAndBrokenRepoOnMasterFailOver FAILED
    [index-one/PLuL9e5PQNeOZPzNlgS0OA] ResourceAlreadyExistsException[index [index-one/PLuL9e5PQNeOZPzNlgS0OA] already exists]
        at __randomizedtesting.SeedInfo.seed([3F66F49CFB1DE3E7:A124037963D26431]:0)
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:203)
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1213)
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:374)
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:429)
        at org.opensearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:335)
        at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:63)
        at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:804)
        at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:378)
        at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:249)
        at org.opensearch.cluster.service.MasterService.access$000(MasterService.java:86)
        at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:173)
        at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:174)
        at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:212)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733)
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:275)
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:238)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by andrross** [comment]
Similar failure reported here #2347

**Comment by owaiskazi19** [comment]
We close this as it's a duplicate of https://github.com/opensearch-project/OpenSearch/issues/2347.
