### ISSUE TITLE
[BUG] org.opensearch.upgrades.FullClusterRestartIT > testEmptyShard FAILED

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#2359]
**Describe the bug**
```
REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testEmptyShard" -Dtests.seed=3DE5D0AB12901A69 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-AE -Dtests.timezone=America/Dawson -Druntime.java=17

```

````
org.opensearch.upgrades.FullClusterRestartIT > testEmptyShard FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:37365], URI [/test_empty_shard], status line [HTTP/1.1 200 OK]
    {"acknowledged":true,"shards_acknowledged":true,"index":"test_empty_shard"}
        at __randomizedtesting.SeedInfo.seed([3DE5D0AB12901A69:719E0773EEA935FC]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
        at app//org.opensearch.upgrades.FullClusterRestartIT.testEmptyShard(FullClusterRestartIT.java:670)
````

     

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by nknize** [comment]
This is fixed by [this commit](https://github.com/opensearch-project/OpenSearch/pull/2400/commits/13a592d561965f177f167b6771c6b007402a1bc3)

In short, the `index.translog.retention.size` setting is deprecated and only applied in `testEmptyIndex` for Legacy 6.x indexes (which are no longer supported in 2.0). This should've been removed #2225 but I missed it.
