### ISSUE TITLE
Unable to Rollback OpenSearch 1.2.3 from OpenSearch 1.2.4

### ISSUE THREAD

**Issue by balar06** [opensearch-project/OpenSearch#2405]
**Describe the bug**
Unable to Rollback OpenSearch 1.2.3 from OpenSearch 1.2.4

Test Case:
1. Deploy OpenSearch 1.2.3
2. Upgrade OpenSearch 1.2.4
3. Rollback to previous version of OpenSearch 1.2.3
4. Rollback failed with below error message

[2022-03-08T12:01:59.059Z][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [eric-data-search-engine-data-1] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: cannot downgrade a node from version [1.2.4] to version [1.2.3]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.2.3.jar:1.2.3]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.2.3.jar:1.2.3]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.2.3.jar:1.2.3]
Caused by: java.lang.IllegalStateException: cannot downgrade a node from version [1.2.4] to version [1.2.3]
	at org.opensearch.env.NodeMetadata.upgradeToCurrentVersion(NodeMetadata.java:105) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:464) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.node.Node.<init>(Node.java:414) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.2.3.jar:1.2.3]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.2.3.jar:1.2.3]
	... 6 more
java.lang.IllegalStateException: cannot downgrade a node from version [1.2.4] to version [1.2.3]
	at org.opensearch.env.NodeMetadata.upgradeToCurrentVersion(NodeMetadata.java:105)
	at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:464)
	at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357)
	at org.opensearch.node.Node.<init>(Node.java:414)
	at org.opensearch.node.Node.<init>(Node.java:319)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)

**Expected behavior**
Rollback should work.
Is it mentioned in the documentation or release notes?

**Host/Environment (please complete the following information):**
 - OS: linux

**Comment by dblock** [comment]
At the very least this needs to be (better) documented. I don't see anything in https://opensearch.org/faq. Care to open issues in documentation-website and project-website @balar06, please?

**Comment by balar06** [comment]
Hi @dblock ,
Thanks a lot for quick reply.
Does rollback supports between this two version OpenSearch 1.2.4 to OpenSearch 1.2.3?

**Comment by dblock** [comment]
AFAIK Elasticsearch never supported downgrade on a single node environment and the recommendation has always been to snapshot your data and restore if you need to downgrade. Is that correct @saratvemulapalli? If so we should start by documenting it, and turn this issue into a feature request to support easy (easier) downgrading.

If you're doing a rolling upgrade I believe you can still abort the upgrade and bring up older nodes as long as you haven't upgraded the last one. I would add tests for this and document it clearly.

**Comment by saratvemulapalli** [comment]
@dblock  Correct. Elasticsearch/OpenSearch never supported downgrades including multi cluster nodes. 
The way it works is, when the leader (alias master) node is upgraded to newer version it cannot be downgraded. Old leader node can communicate with new data nodes but not vice versa. 

The only way this is possible is via taking a snapshot and restoring it on a fresh new downgraded cluster. 

+1 to the question, why are you attempting to downgrade?

**Comment by balar06** [comment]
It's a major test case in our environment and should support both rollbacks and upgrade.

**Comment by dblock** [comment]
> It's a major test case in our environment and should support both rollbacks and upgrade.

Care to please elaborate? What's your environment? Why is snapshot -> rollback not an acceptable solution?

**Comment by balar06** [comment]
@dblock 
Environment: K8 
In this case, there will be downtime in the OpenSearch rollback and restore backup option, due to the service downtime, we are facing the loss of data ingestion in the OpenSearch index.
How to keep the high service availability and reduce the risk of the loss of data ingestion in rollback?

helm rollback OS 1.2.4 to 1.2.3 , 
Rollback ends up in an error if a rollback is tried.
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: cannot downgrade a node from version [1.2.4] to version [1.2.3]

**Comment by saratvemulapalli** [comment]
@balar06 rollback in OpenSearch is not supported without having a down time. 
I understand its a test case where you'd like to make sure the systems are setup to roll it back. 

I see couple of paths forward:
1. A possible path is to setup a new cluster, verify and take snapshot on old cluster, restore it on the new one. If you see problems you can continue to use the old cluster (a.k.a blue/green). Ofcourse there has be some kind of external traffic management.
2. We can take this as a feature request to support rollbacks in OpenSearch and possibly work on it for future releases.

**Comment by dblock** [comment]
I've updated this from bug to enhancement/feature request.

**Comment by eslam-gomaa** [comment]
Hi team, 
any update on this feature request?
