### ISSUE TITLE
org.opensearch.upgrades.FullClusterRestartIT.testEmptyShard

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#2434]
I can see current gradle failures happening due to this issue. 

Failure trace
```
REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.4.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testEmptyShard" -Dtests.seed=CFDACBBA3F54FD83 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=is -Dtests.timezone=Asia/Almaty -Druntime.java=17

org.opensearch.upgrades.FullClusterRestartIT > testEmptyShard FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:33109], URI [/test_empty_shard], status line [HTTP/1.1 200 OK]
    Warnings: [Translog retention settings [index.translog.retention.age] and [index.translog.retention.size] are deprecated and effectively ignored. They will be removed in a future version.]
    {"acknowledged":true,"shards_acknowledged":true,"index":"test_empty_shard"}
        at __randomizedtesting.SeedInfo.seed([CFDACBBA3F54FD83:83A11C62C36DD216]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:973)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
        at app//org.opensearch.upgrades.FullClusterRestartIT.testEmptyShard(FullClusterRestartIT.java:670)
```

❌   Gradle Check failure https://github.com/opensearch-project/OpenSearch/commit/c5141ef5ea6e20f736fc8781b44e3bb44bd93315
[Log 3234](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3234.log)

[Reports 3234](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3234_reports.zip)

**Comment by owaiskazi19** [comment]
Hey @dreamer-89. This looks like a duplicate of https://github.com/opensearch-project/OpenSearch/issues/2359.

**Comment by dreamer-89** [comment]
Thanks @owaiskazi19 for pointing out. Closing this in favour of #2359
