### ISSUE TITLE
[BUG] - java.util.concurrent.CompletionException: java.lang.RuntimeException] without root cause in 1.0, 1.1 and in 1.2

### ISSUE THREAD

**Issue by gubendran-tech** [opensearch-project/OpenSearch#2436]
We migrated to openSearch 1.1 from ElasticSearch. We often see java.lang.RuntimeException in **java.lang.NullPointerException: null
	at org.opensearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1569)** when we try to send multiple request from our Springboot java application. We use Java High-level rest client.

**To Reproduce**
1. Have OpenSearch cluster 1.0 or 1.1 (AWS) loaded with indices.
2. Use Java high-level rest client
3. Make multiple requests to openSearch cluster. 
4. The hit is not coming to openSearch cluster (Server) and it fails with exception in client without the root cause. 

**Expected behavior**
Exact error should be thrown with root cause when the errors throws from the RestHighLevelClient.

**Screenshots**
threw exception [Request processing failed; nested exception is java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: java.lang.RuntimeException] with root cause
java.lang.NullPointerException: null
	at org.opensearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1569)
	at org.opensearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:657)
	at org.opensearch.client.RestClient$1.completed(RestClient.java:399)
	at org.opensearch.client.RestClient$1.completed(RestClient.java:383)
	at datadog.trace.instrumentation.apachehttpasyncclient.TraceContinuedFutureCallback.completeDelegate(TraceContinuedFutureCallback.java:97)
	at datadog.trace.instrumentation.apachehttpasyncclient.TraceContinuedFutureCallback.completed(TraceContinuedFutureCallback.java:52)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:834)
**Host/Environment (please complete the following information):**
 - OS: centOS 7 (Linux)
 - Version OpenSearch 1.0 or 1.1

**Comment by dblock** [comment]
Looks like a bug. Do you have a repro that we can look at, or maybe want to help turn it into a unit test in this project?

Looking at https://github.com/opensearch-project/OpenSearch/blob/main/client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java#L1571 there's probably a response that causes this exception that should be reproducible.

**Comment by reta** [comment]
@gubendran-tech could you please share the code snippet how exactly you send the requests from the application? I suspect the action listener passed to search request could be `null`. Thank you.

**Comment by gubendran-tech** [comment]
> @gubendran-tech could you please share the code snippet of how exactly you send the requests from the application? I suspect the action listener passed to search request could be `null`. Thank you.

You are perfectly correct @reta. We fixed our code by not pushing null to search requests in the action listener. Thank you. Having said in ES 5.6 this wasn't an issue. If I pass null I get no response.

**Comment by reta** [comment]
Thank you @gubendran-tech , we could probably fix this edge case, I will send the pull request shortly
