### ISSUE TITLE
[CI] flaky test faiure - o.o.indices.recovery.IndexRecoveryIT.testRerouteRecovery

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#2502]
Caught from PR https://github.com/opensearch-project/OpenSearch/pull/2415#issuecomment-1066331257

:x: &nbsp; Gradle Check failure 0d66c0cb53fcc1200d1b930457e31d452eef4ef2
[Log 3314](<https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3314.log>)

[Reports 3314](<https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3314_reports.zip>)

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.recovery.IndexRecoveryIT.testRerouteRecovery" -Dtests.seed=F231651D93AD15B9 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-PY -Dtests.timezone=Africa/Mogadishu -Druntime.java=17

org.opensearch.indices.recovery.IndexRecoveryIT > testRerouteRecovery FAILED
    java.lang.AssertionError: 
    Expected: not <DONE>
         but: was <DONE>
        at __randomizedtesting.SeedInfo.seed([F231651D93AD15B9:5F9AD649A6F577FB]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.indices.recovery.IndexRecoveryIT.assertOnGoingRecoveryState(IndexRecoveryIT.java:249)
        at org.opensearch.indices.recovery.IndexRecoveryIT.testRerouteRecovery(IndexRecoveryIT.java:697)
```

**Comment by tlfeng** [comment]
Close the issue because the flaky test hasn't occurred again ever since found for the first time.
