### ISSUE TITLE
[CI] flaky test faiure - o.o.upgrades.IndexingIT.testAutoIdWithOpTypeCreate - in v1.3.0#oneThirdUpgradedTest

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#2522]
Caught from PR https://github.com/opensearch-project/OpenSearch/pull/902#issuecomment-871903730 and https://github.com/opensearch-project/OpenSearch/pull/2519#issuecomment-1073114124

:x: &nbsp; Gradle Check failure eec54ae9ed7fce079e90a16a94bab609bb74bfbd
[Log 3563](<https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3563.log>)

[Reports 3563](<https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3563_reports.zip>)

```
> Task :qa:rolling-upgrade:v1.3.0#oneThirdUpgradedTest

REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v1.3.0#oneThirdUpgradedTest' --tests "org.opensearch.upgrades.IndexingIT.testAutoIdWithOpTypeCreate" -Dtests.seed=512653CB7D65CBC7 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP -Dtests.timezone=Antarctica/Rothera -Druntime.java=17

org.opensearch.upgrades.IndexingIT > testAutoIdWithOpTypeCreate FAILED
    java.lang.AssertionError: there are still running tasks:
    {time_in_queue=389ms, time_in_queue_millis=389, source=shard-started StartedShardEntry{shardId [[recover_and_create_leases_in_promotion][4]], allocationId [gt3B9PnTSYePRTVS4QZdFA], primary term [1], message [after peer recovery]}, executing=true, priority=URGENT, insert_order=301}
    {time_in_queue=388ms, time_in_queue_millis=388, source=shard-started StartedShardEntry{shardId [[recover_and_create_leases_in_promotion][0]], allocationId [yN6_RNTSQViP8oogDc5dQw], primary term [2], message [after peer recovery]}, executing=false, priority=URGENT, insert_order=302}
        at __randomizedtesting.SeedInfo.seed([512653CB7D65CBC7:11BDA0F374A0169E]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.rest.OpenSearchRestTestCase.lambda$waitForClusterStateUpdatesToFinish$7(OpenSearchRestTestCase.java:783)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1060)
        at org.opensearch.test.rest.OpenSearchRestTestCase.waitForClusterStateUpdatesToFinish(OpenSearchRestTestCase.java:774)
        at org.opensearch.test.rest.OpenSearchRestTestCase.cleanUpCluster(OpenSearchRestTestCase.java:358)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by andrross** [comment]
No updates in over a year. Closing.
