### ISSUE TITLE
[CI] o.o.discovery.SnapshotDisruptionIT.testDisruptionAfterFinalization failure

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2538]
Found on #2531. Unable to reproduce. Looks like the master node died randomly in jenkins (force killed?).

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.discovery.SnapshotDisruptionIT.testDisruptionAfterFinalization" -Dtests.seed=9C7BEE2E6A009383 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-QA -Dtests.timezone=America/Tijuana -Druntime.java=17
```

```
org.opensearch.discovery.SnapshotDisruptionIT > testDisruptionAfterFinalization FAILED
    java.util.concurrent.TimeoutException: Timeout waiting for task.
        at org.opensearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:252)
        at org.opensearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:77)
        at org.opensearch.snapshots.AbstractSnapshotIntegTestCase.awaitClusterState(AbstractSnapshotIntegTestCase.java:552)
        at org.opensearch.snapshots.AbstractSnapshotIntegTestCase.awaitNoMoreRunningOperations(AbstractSnapshotIntegTestCase.java:519)
        at org.opensearch.discovery.SnapshotDisruptionIT.testDisruptionAfterFinalization(SnapshotDisruptionIT.java:137)

    MasterNotDiscoveredException[NotMasterException[no longer master. source: [remove repository cleanup task [test-repo][4]]]]; nested: NotMasterException[no longer master. source: [remove repository cleanup task [test-repo][4]]];
```

Opening issue to monitor recurrence.

**Comment by dblock** [comment]
Labeled as [Flakey Random Test Failure](https://github.com/opensearch-project/OpenSearch/labels/Flakey%20Random%20Test%20Failure), my fav tag.

**Comment by dreamer-89** [comment]
Closing this ticket as not failure instance reported in last 2 months. Used script to determine failure. 
https://github.com/opensearch-project/OpenSearch/issues/1715#issuecomment-1335981772
