### ISSUE TITLE
[CI] o.o.aliases.IndexAliasesIT.testSameAlias failure

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2580]
Caught on PR #2574 this test was not reproducible and looks like a one off CI blip. Documenting for posterity:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.aliases.IndexAliasesIT.testSameAlias" -Dtests.seed=D759B90667E7AFC3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sl -Dtests.timezone=Etc/GMT+12 -Druntime.java=17
```

```
2> java.lang.AssertionError: AcknowledgedResponse failed - not acked
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([D759B90667E7AFC3:551A0CCCC00FF5E5]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.opensearch.test.hamcrest.OpenSearchAssertions.assertAcked(OpenSearchAssertions.java:127)
        at org.opensearch.test.hamcrest.OpenSearchAssertions.assertAcked(OpenSearchAssertions.java:115)
        at org.opensearch.aliases.IndexAliasesIT.lambda$testSameAlias$52(IndexAliasesIT.java:803)
        at org.opensearch.aliases.IndexAliasesIT.assertAliasesVersionIncreases(IndexAliasesIT.java:1489)
        at org.opensearch.aliases.IndexAliasesIT.assertAliasesVersionIncreases(IndexAliasesIT.java:1480)
        at org.opensearch.aliases.IndexAliasesIT.testSameAlias(IndexAliasesIT.java:801)
```

**Comment by kartg** [comment]
Not sure why this was tagged for `2.1.0` or `2.2.0`. There are no recent references to this particular flakey test failure directly, but I do see a similar issue open for a different test - https://github.com/opensearch-project/OpenSearch/issues/1561

**Comment by owaiskazi19** [comment]
Ran this test in isolation for 400 times and wasn't able to reproduce it.

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.aliases.IndexAliasesIT.testSameAlias" -Dtests.seed=D759B90667E7AFC3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sl -Dtests.timezone=Etc/GMT+12 -Druntime.java=17 -Dtests.iters=400

> Task :buildSrc:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :buildSrc:compileGroovy
Note: /home/ubuntu/OpenSearch/buildSrc/src/main/groovy/org/opensearch/gradle/test/TestWithSslPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :buildSrc:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.6
  OS Info               : Linux 5.11.0-1020-aws (amd64)
  Runtime JDK Version   : 17 (Oracle JDK)
  Runtime java.home     : /usr/lib/jvm/java-17/jdk-17.0.1
  Gradle JDK Version    : 17 (Oracle JDK)
  Gradle java.home      : /usr/lib/jvm/java-17/jdk-17.0.1
  Random Testing Seed   : D759B90667E7AFC3
  In FIPS 140 mode      : false
=======================================

> Task :server:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test:framework:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :server:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :server:compileInternalClusterTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :server:internalClusterTest
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/home/ubuntu/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/home/ubuntu/.gradle/wrapper/dists/gradle-7.6-all/9f832ih6bniajn45pbmqhk2cw/gradle-7.6/lib/plugins/gradle-testing-base-7.6.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 15m 24s
43 actionable tasks: 28 executed, 9 from cache, 6 up-to-date
