### ISSUE TITLE
[BUG] :test:logger-usage:test failure flakey test

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/OpenSearch#2893]
**Describe the bug**
:test:logger-usage:test failure

```
java.lang.RuntimeException: unable to install test security manager
        at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:190)
        at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:251)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)

        Caused by:
        java.lang.NullPointerException: Cannot invoke "String.length()" because "input" is null
            at java.base/sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
            at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
            at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:275)
            at org.opensearch.common.io.PathUtils.get(PathUtils.java:73)
            at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:134)
            ... 4 more
```

Appeared in 
https://github.com/opensearch-project/OpenSearch/pull/2726#issuecomment-1086957605
https://github.com/opensearch-project/OpenSearch/pull/1096#issuecomment-1018841935

**Comment by dbwiddis** [comment]
Stack trace related to [JDK Bug 8254876](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8254876), fix in JDK16 just throws the NPE earlier.

Cause is passing a null as `first` in `PathUtils.get()`:
https://github.com/opensearch-project/OpenSearch/blob/ea1cc9d054b2d7cf0046438ecc57777e29112c2b/libs/core/src/main/java/org/opensearch/common/io/PathUtils.java#L62-L74

This argument is `System.getProperty("tests.config")` which is length-checked by `Strings.hasLength()`:
https://github.com/opensearch-project/OpenSearch/blame/ea1cc9d054b2d7cf0046438ecc57777e29112c2b/test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java#L133C24-L135

But this should return `false` for null:
https://github.com/opensearch-project/OpenSearch/blob/ea1cc9d054b2d7cf0046438ecc57777e29112c2b/server/src/main/java/org/opensearch/common/Strings.java#L125-L127

https://github.com/opensearch-project/OpenSearch/blob/ea1cc9d054b2d7cf0046438ecc57777e29112c2b/server/src/main/java/org/opensearch/common/Strings.java#L101-L103

**Comment by dbwiddis** [comment]
Failed to reproduce in 1000 test runs.  

The only possible source of failure is a change in the system property between the null check (line 133) and retrieving the property again (line 134).  Submitted #5645 to save the initial property value to ensure the null check is of the same String being passed later.
