### ISSUE TITLE
[BUG] Physical memory size could not be determined exception

### ISSUE THREAD

**Issue by vladaman** [opensearch-project/OpenSearch#2937]
**Describe the bug**
Opensearch does not start on a Virtual Instance due to an exception: Physical memory size could not be determined

* Opensearch 1.3.1
* Ubuntu

```
$free
              total        used        free      shared  buff/cache   available
Mem:       12582912      361144     8440248      119920     3781520    12101848
Swap:             0           0           0
```

I get following error:
```
[2022-04-16T17:40:47,824][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [vp003] uncaught exception in thread [main]
java.lang.IllegalStateException: Physical memory size could not be determined
	at org.opensearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:374)
	at org.opensearch.knn.index.KNNSettings.lambda$knnMemoryCircuitBreakerSetting$5(KNNSettings.java:360)
	at org.opensearch.common.settings.Setting.getDefault(Setting.java:422)
	at org.opensearch.knn.index.KNNSettings.getSettingValue(KNNSettings.java:289)
	at org.opensearch.knn.index.KNNSettings.getCircuitBreakerLimit(KNNSettings.java:337)
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.initialize(NativeMemoryCacheManager.java:77)
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.<init>(NativeMemoryCacheManager.java:55)
	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.getInstance(NativeMemoryCacheManager.java:65)
	at org.opensearch.knn.index.KNNCircuitBreaker.initialize(KNNCircuitBreaker.java:60)
	at org.opensearch.knn.plugin.KNNPlugin.createComponents(KNNPlugin.java:168)
	at org.opensearch.node.Node.lambda$new$15(Node.java:661)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.opensearch.node.Node.<init>(Node.java:675)
	at org.opensearch.node.Node.<init>(Node.java:319)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
```

**Comment by VachaShah** [comment]
Looks like a knn setting from the stack trace. @opensearch-project/k-nn any ideas as to why this might be happening?
