### ISSUE TITLE
[SDK] Add support for createComponent extension points

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#2981]
**Is your feature request related to a problem? Please describe.**

For every extension points, SDK should have a TransportRequest to communicate with OpenSearch. This issue focuses on the below extension point:

- [ ] [createComponents](https://github.com/opensearch-project/OpenSearch/blob/1.3/server/src/main/java/org/opensearch/plugins/Plugin.java#L138)

This covers
1. clusterState
2. clusterSettings
2. LocalNode

This extensions will also cover a part of communication of [sql](https://github.com/opensearch-project/sql/blob/1.3/plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java) plugin with OpenSearch and make the plugin extensible.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by owaiskazi19** [comment]
The workflow to create interface for any extension point is:

1. OpenSearch will send a request to initialize all the plugins listening on a pre-defined port. 
2. Once the initialization is successful then OpenSearch will send a request to see if any of the the plugin requires the extension points present in the SDK.
3. If it does, then a TransportRequest will be send from OpenSearch to the plugin which is registered by the SDK. 
4.  After the registration, the following extension point will be invoke on the OpenSearch end and an acknowledgment will be send to the plugin to mention that the work has been done.

Steps to achieve the above workflow:
1. Create a TransportRequest for the extension point which initializes the required parameters in OpenSearch.
2. Implement the extension point in [PluginOrchestrator](https://github.com/opensearch-project/OpenSearch/blob/feature/extensions/server/src/main/java/org/opensearch/plugins/PluginsOrchestrator.java) 
2. Register the TransportRequest in plugin.
3. Create a TransportResponse for the extension point to send the acknowledgment to the extension.

**Comment by owaiskazi19** [comment]
Design for createComponent with SQL plugin.

SQL plugin requires [ClusterState](https://github.com/opensearch-project/sql/blob/main/plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java#L110) and [ClusterSettings](https://github.com/opensearch-project/sql/blob/main/plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java#L111) for createComponent extension point.
The design needs to be change for this extension point. SQL plugin can send a TransportRequest to OpenSearch to get the ClusterState and ClusterSettings as ClusterState keeps on changing in OpenSearch. OpenSearch will register the request and provide the ClusterState and ClusterSettings as response to SQL plugin.

**Comment by owaiskazi19** [comment]
As mentioned in the above comment, because of the change in the design we can try using [sendRequest](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/transport/RemoteConnectionManager.java#L199) from RemoteConnectionManager to send a TransportRequest from SDK to OpenSearch to add the node in the RemoteConnectionManager mao.

**Comment by owaiskazi19** [comment]
Changing the node [here](https://github.com/opensearch-project/OpenSearch/blob/feature/extensions/server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java#L181) to localNode of OpenSearch resolved the error. Moved the sendRequest in handlePluginRequest for a better approach. 
Currently looking into
```
Caused by: java.lang.IllegalStateException: Message not fully read (request) for requestId [3], action [internal:discovery/createcomponent], available [0]; resetting
        at org.opensearch.transport.InboundHandler.checkStreamIsFullyConsumed(InboundHandler.java:311) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundHandler.handleRequest(InboundHandler.java:239) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:127) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:109) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:761) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:170) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:145) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:110) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]

**Comment by owaiskazi19** [comment]
Resolved the above issue. It was mainly because of using Enum in the CreateComponentRequest. Currently looking into https://github.com/opensearch-project/opensearch-sdk/issues/6

**Comment by owaiskazi19** [comment]
Resolved https://github.com/opensearch-project/opensearch-sdk/issues/6. The issue was because of creating a new transport object for the new CreateComponentRequest which resulted in a new ConnectionManagerMap.
