### ISSUE TITLE
How to install plugin ik analyzer

### ISSUE THREAD

**Issue by crystal-lee** [opensearch-project/OpenSearch#3098]
when i install ik analyzer plugin ,it has error.
```
[opensearch@opensearch-cluster-master-0 bin]$ opensearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.1.2/elasticsearch-analysis-ik-8.1.2.zip
-> Installing https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.1.2/elasticsearch-analysis-ik-8.1.2.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.1.2/elasticsearch-analysis-ik-8.1.2.zip
[=================================================] 100%?? 
-> Failed installing https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.1.2/elasticsearch-analysis-ik-8.1.2.zip
-> Rolling back https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.1.2/elasticsearch-analysis-ik-8.1.2.zip
-> Rolled back https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.1.2/elasticsearch-analysis-ik-8.1.2.zip
Exception in thread "main" java.lang.IllegalArgumentException: property [opensearch.version] is missing for plugin [analysis-ik]
        at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:250)
        at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:811)
        at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

Where can I find ik plugin for opensearch offical? https://github.com/soosinha/opensearch-analysis-ik ?

**Comment by saratvemulapalli** [comment]
@crystal-lee analysis-ik plugin you are trying to install is built for Elasticsearch, and cannot be installed in OpenSearch.

We do not have an official plugin supported by the project. We would be more than happy if you'd like to contribute one. 

Side note: @elfisher is this something worth pulling into the project and maintain it? (assuming community contributes)

**Comment by elfisher** [comment]
> Side note: @elfisher is this something worth pulling into the project and maintain it? (assuming community contributes)

Definitely.

**Comment by crystal-lee** [comment]
some one has already finish it.    https://github.com/soosinha/opensearch-analysis-ik
only need update the dependency of opensearch and complie. it worked ok

**Comment by deltaguita** [comment]
@crystal-lee  
How to update and compile?
Thx!
