### ISSUE TITLE
[BUG] Build issue for OpenSearch 1.3.2

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/OpenSearch#3105]
**Describe the bug**
Our distribution build is currently broken because of an OpenSearch build failure. 
Context: 
```
+ mkdir -p builds/maven/org/opensearch
+ ./gradlew publishToMavenLocal -Dbuild.snapshot=false -Dbuild.version_qualifier=

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

2022-04-28 21:46:03 ERROR    Error building OpenSearch, retry with: ./build.sh manifests/1.3.2/opensearch-1.3.2.yml --component OpenSearch
Traceback (most recent call last):
  File "./src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 68, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/builder_from_source.py", line 55, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /var/jenkins/workspace/distribution-build-opensearch/scripts/components/OpenSearch/build.sh -v 1.3.2 -p linux -a x64 -d rpm -s false -o builds' returned non-zero exit status 1.
```

**To Reproduce**
`./build.sh manifests/1.3.2/opensearch-1.3.2.yml --component OpenSearch --snapshot` from opensearch-build repo.

**Expected behavior**
This should build successfully.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peterzhuamazon** [comment]
This is caused by 1.3.2 not having JAVA_HOME defined in manifest, close now.
