### ISSUE TITLE
[BUG] Core-Plugins installation does not support qualifier fully

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#3168]
```
% ./opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/2.0.0/repository-s3-2.0.0-rc1.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.opensearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:450)
	at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:527)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:318)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:272)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

```

As you can see despite the zip is `2.0.0-rc1` zip, OpenSearch core still points to `2.0.0` folder to download the zip.
I am not sure if this is a bug or expected to be `2.0.0` folder for `2.0.0-rc1`.
As of now we will hardcode native plugin deployment in production to `2.0.0`.

Thanks.

**Comment by peterzhuamazon** [comment]
@nknize @dblock @saratvemulapalli 
Thanks.

**Comment by dblock** [comment]
Looks like a bug to me 😢

**Comment by saratvemulapalli** [comment]
+1 it is a bug. 
I could reproduce the problem via 2.0.0-rc1 tarball. 
Opened up a PR #3193 to fix this.
