### ISSUE TITLE
[BUG] org.opensearch.discovery.DiscoveryDisruptionIT > testNodeNotReachableFromMaster FAILED

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#3272]
```
> Task :server:internalClusterTest

org.opensearch.discovery.DiscoveryDisruptionIT > testNodeNotReachableFromMaster FAILED
    MasterNotDiscoveredException[NotMasterException[no longer cluster-manager. source: [cluster_health (wait_for_events [LANGUID])]]]; nested: NotMasterException[no longer cluster-manager. source: [cluster_health (wait_for_events [LANGUID])]];
        at __randomizedtesting.SeedInfo.seed([B0C860CDD2E62A02:6F852B021DB9C19]:0)
        at org.opensearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:277)
        at org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:370)
        at org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:287)
        at org.opensearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:692)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)

        Caused by:
        NotMasterException[no longer cluster-manager. source: [cluster_health (wait_for_events [LANGUID])]]

```

https://github.com/opensearch-project/OpenSearch/pull/3260#issuecomment-1121460251

**Comment by Pranshu-S** [comment]
Taking a look

**Comment by andrross** [comment]
No linked re-occurrences in the past year. Closing and will rely on automation to open a new issue if this happens again.
