### ISSUE TITLE
[BUG] org.opensearch.action.admin.cluster.tasks.PendingTasksBlocksIT > testPendingTasksWithClusterNotRecoveredBlock FAILED

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#3273]
```
org.opensearch.action.admin.cluster.tasks.PendingTasksBlocksIT > testPendingTasksWithClusterNotRecoveredBlock FAILED
    java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([F19D942E1E4110F4:5F2076E19A98425]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:979)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:918)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:907)
        at org.opensearch.action.admin.cluster.tasks.PendingTasksBlocksIT.testPendingTasksWithClusterNotRecoveredBlock(PendingTasksBlocksIT.java:111)
```

https://github.com/opensearch-project/OpenSearch/pull/3259#issuecomment-1121460572

**Comment by dbwiddis** [comment]
This is one of a few different tests where I've seen an unreadable (truncated with large length) [deprecation log message in the failure trace](https://build.ci.opensearch.org/job/gradle-check/8572/testReport/junit/org.opensearch.action.admin.cluster.tasks/PendingTasksBlocksIT/testPendingTasksWithClusterNotRecoveredBlock/):
```
[2022-12-29T09:26:34,355][INFO ][o.o.a.a.c.t.PendingTasksBlocksIT] [testPendingTasksWithClusterNotRecoveredBlock] [PendingTasksBlocksIT#testPendingTasksWithClusterNotRecoveredBlock]: setting up test
[2022-12-29T09:26:34,536][DEPRECATION][o.o.d.c.s.Settings       ] [node_s0] [index.force_memory_term_dictionary] setting was dep
...[truncated 1376351 chars]...
eS8W-VsYrMCZy5A}{Ur513a1IRy24HkBPUMqLPw}{127.0.0.1}{127.0.0.1:42445}{imr}{shard_indexing_pressure_enabled=true}}, term: 4, version: 14, reason: ApplyCommitRequest{term=4, version=14, sourceNode={node_s0}
```

The setting comes from `Store.java`:
https://github.com/opensearch-project/OpenSearch/blob/57d44859bdf26d381688f37ec55afe50b46c98df/server/src/main/java/org/opensearch/index/store/Store.java#L151-L162

Flakiness is introduced as part of `setRandomIndexSettings()` in `OpenSearchIntegTestCase`:
https://github.com/opensearch-project/OpenSearch/blob/57d44859bdf26d381688f37ec55afe50b46c98df/test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java#L474-L476

But similar messages are on completely different log messages on [completely unrelated tests](https://build.ci.opensearch.org/job/gradle-check/7272/testReport/junit/org.opensearch.cluster/ClusterHealthIT/testHealthOnClusterManagerFailover/):
```
[2022-11-23T10:30:18,307][INFO ][o.
...[truncated 1171668 chars]...
ansport.TransportService.sendRequest(TransportService.java:718) [main/:?]
	at org.opensearch.cluster.coordination.FollowersChecker$FollowerChecker.handleWakeUp(FollowersChecker.java:348) [main/:?]
	at org.opensearch.cluster.coordination.FollowersChecker$FollowerChecker.start(FollowersChecker.java:336) [main/:?]
	at org.opensearch.cluster.coordination.FollowersChecker.lambda$setCurrentNodes$2(FollowersChecker.java:178) [main/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]

<and more...>
```

**Comment by sandeshkr419** [comment]
Test hasn't been reported flaky in over 2 years I guess, closing this out. Will be automatically opened if the issue persists.
