### ISSUE TITLE
[BUG] Trying to upgrade from elasticsearch 7.0. ” Received message from unsupported version”

### ISSUE THREAD

**Issue by DoctorOgg** [opensearch-project/OpenSearch#3276]
**Describe the bug**

Trying to upgrade from elasticsearch 7.0. ” Received message from unsupported version”

Im working on trying to upgrade an existing cluster (es 7.0.0) to OpenSearch, by using a rolling upgrade process, I have a new OpenSearch node built running 1.3.1 (also tried 1.3.2), and when I start the node up, I'm getting and “Received message from unsupported version” message.

I’m sure I’m missing something obvious here.

log output: 

```
[2022-05-05T11:19:48,867][INFO ][o.o.c.c.JoinHelper       ] [os-staging-01.duh-stage] failed to join {ip-10-49-1-181.us-west-2.compute.internal}{SbdvE2nbRC-Sa34AAsJrYA}{2A0qVPcGR3KzLNxZeSD9Fw}{10.49.1.181}{10.49.1.181:9300}{dim}{ml.machine_memory=33072087040, rack=us-west-2a, ml.max_open_jobs=20, xpack.installed=true} with JoinRequest{sourceNode={os-staging-01.duh-stage}{ebEUk3R2RVmRnxKOtQxEew}{nHIFHs4HR7GpbT5U9eeF_w}{10.49.1.136}{10.49.1.136:9300}{dim}{rack=us-west-2a, shard_indexing_pressure_enabled=true}, minimumTerm=4, optionalJoin=Optional.empty}
org.opensearch.transport.RemoteTransportException: [ip-10-49-1-181.us-west-2.compute.internal][10.49.1.181:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.transport.ConnectTransportException: [os-staging-01.duh-stage][10.49.1.136:9300] general node connection failure
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener$1.onFailure(TcpTransport.java:1284) ~[?:?]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:138) ~[?:?]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:115) ~[?:?]
	at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:975) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[?:?]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:967) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:942) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.IllegalStateException: Received message from unsupported version: [35.24.79-beta2] minimal compatible version is: [6.7.0]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:139) ~[?:?]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:115) ~[?:?]
	at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:975) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[?:?]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:967) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:942) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2022-05-05T11:19:48,872][INFO ][o.o.c.c.JoinHelper       ] [os-staging-01.duh-stage] failed to join {ip-10-49-1-181.us-west-2.compute.internal}{SbdvE2nbRC-Sa34AAsJrYA}{2A0qVPcGR3KzLNxZeSD9Fw}{10.49.1.181}{10.49.1.181:9300}{dim}{ml.machine_memory=33072087040, rack=us-west-2a, ml.max_open_jobs=20, xpack.installed=true} with JoinRequest{sourceNode={os-staging-01.duh-stage}{ebEUk3R2RVmRnxKOtQxEew}{nHIFHs4HR7GpbT5U9eeF_w}{10.49.1.136}{10.49.1.136:9300}{dim}{rack=us-west-2a, shard_indexing_pressure_enabled=true}, minimumTerm=4, optionalJoin=Optional.empty}
org.opensearch.transport.RemoteTransportException: [ip-10-49-1-181.us-west-2.compute.internal][10.49.1.181:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.transport.ConnectTransportException: [os-staging-01.duh-stage][10.49.1.136:9300] general node connection failure
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener$1.onFailure(TcpTransport.java:1284) ~[?:?]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:138) ~[?:?]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:115) ~[?:?]
	at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:975) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[?:?]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:967) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:942) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.IllegalStateException: Received message from unsupported version: [35.24.79-beta2] minimal compatible version is: [6.7.0]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:139) ~[?:?]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:115) ~[?:?]
	at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:975) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[?:?]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:967) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:942) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]

```

**To Reproduce**

1. create elastic oss cluster v7.0
2. create new os 1.3.2 node and try to join it to the existing es cluster.

**Expected behavior**
the os node would be expect to joing the es cluster such that i can move migrate data to it.

**Plugins**
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-observability
opensearch-reports-scheduler
opensearch-sql
repository-s3

**Host/Environment (please complete the following information):**
 - OS: debian
 - Version 11.2

**Comment by adnapibar** [comment]
@DoctorOgg Just wanted to make sure, did you follow the steps outlined in the documentation -https://opensearch.org/docs/latest/upgrade-to/upgrade-to/ ?

**Comment by DoctorOgg** [comment]
yes, i was following, however was cut short due to the new node not being able to join the cluster

**Comment by dblock** [comment]
This error is on the ES master? Anything on the node?

What is `35.24.79-beta2`?! Where's that coming from?

**Comment by DoctorOgg** [comment]
good question I assumed 35.24.79-beta2 is from OpenSearch, and the log sample submitted is from OpenSearch node I was trying to join.

**Comment by dblock** [comment]
> good question I assumed 35.24.79-beta2 is from OpenSearch, and the log sample submitted is from OpenSearch node I was trying to join.

Nope. This smells like something gone wrong parsing a version number and coming up with  35.24.79-beta2 (as in `6_0_0_beta2`). Do you have time to replicate this from scratch by booting a 7.0 version out of the box without plugins, then roll-upgrading it to OpenSearch and seeing if it's the same error? If it is, I would roll that to 7.10 first and then to OpenSearch and see if it's a bug in version parsing between 7.0 and 7.10.

**Comment by saratvemulapalli** [comment]
Looks like #669 is related.  
From 1.3.x line, here is the code which handles min compatibility version: 
https://github.com/opensearch-project/OpenSearch/blob/d69b3440e88c3291771166b4738193f0d729ed41/server/src/main/java/org/opensearch/transport/TransportHandshaker.java#L132

As long its running ES 7.x or 6.8 OpenSearch still responds with ES 7.10.2, and let the cluster formation happen. 
Some how ES is receiving the min compatibility version as 1.0.0 which probably translates to `35.24.79-beta2`. 
The stacktrace also confirms that the error is being thrown by org.elasticsearch:
```
java.lang.IllegalStateException: Received message from unsupported version: [35.24.79-beta2] minimal compatible version is: [6.7.0]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:139) ~[?:?]
	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:115) ~[?:?]
```

@DoctorOgg couple of questions:
- How can one reproduce this, could help list down the steps?
- Is this an existing production cluster and you are trying to migrate to OpenSearch?
- Did you consider other upgrade options (assuming a production cluster) like snapshot, restart etc?

**Comment by DoctorOgg** [comment]
- How can one reproduce this, could you help list down the steps?

steps are listed in the intial bug report

- Is this an existing production cluster and you are trying to migrate to OpenSearch?

this is a staging clusgter, and is exiting, this was a trial run before prod deployment 


- Did you consider other upgrade options (assuming a production cluster) like snapshot, restart etc?

snaptshots are not an option for an production cluster upgrage as downtime for this is not an option.

**Comment by dblock** [comment]
> ah yah, should be clear, as part of our stadard for rolling upgrads, we add NEW nodes, instead of upgrading the software inplace. As its easer for us, and allows for os udates as well.

This could be different but I have not tried. @saratvemulapalli or @DoctorOgg is either of you trying a clean setup?

**Comment by DoctorOgg** [comment]
alright, was able to clone the cluster, and try an in-place upgrade, which does work, however, quite labor-intensive, it really would be much easier to be able to add new OS nodes to an existing cluster with our tooling than an in-place upgrade. So, i guess I'm off to sort scripting this.  I would still consider this a bug, as adding and replacing machines with ES is an accepted route to upgrade a cluster.

**Comment by dblock** [comment]
> alright, was able to clone the cluster, and try an in-place upgrade, which does work, however, quite labor-intensive, it really would be much easier to be able to add new OS nodes to an existing cluster with our tooling than an in-place upgrade. So, i guess I'm off to sort scripting this. I would still consider this a bug, as adding and replacing machines with ES is an accepted route to upgrade a cluster.

Yes, let's leave this open to track down what the limitation is here and fix it. Feel free to contribute!

**Comment by akomlik** [comment]
Trying to upgrade ES 7.9.1 cluster to OS 2.4.0 using rolling upgrade I get same error.
Config:  
- working 3 x master + 2 data nodes ES 7.9.1 cluster
- Trying to re-image (Azure) first data node VM (with local data disk so all data is lost) to OS node

When OS starts it can establish SSL connection to existing master nodes but then fails with "general node connection failure"
```
[2022-12-28T19:35:01,022][DEBUG][i.n.h.s.SslHandler       ] [es-data000000] [id: 0xb0409661, L:/10.120.10.8:35162 - R:es-master000000/10.120.10.5:9300] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
[2022-12-28T19:35:01,030][DEBUG][i.n.h.s.SslHandler       ] [es-data000000] [id: 0x92634260, L:/10.120.10.8:55514 - R:es-master000002/10.120.10.7:9300] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
[2022-12-28T19:35:01,040][DEBUG][o.o.d.PeerFinder         ] [es-data000000] Peer{transportAddress=10.120.10.7:9300, discoveryNode=null, peersRequestInFlight=false} connection failed
org.opensearch.transport.ConnectTransportException: [][10.120.10.7:9300] general node connection failure

Caused by: java.lang.IllegalStateException: Received message from unsupported version: [7.9.1] minimal compatible version is: [7.10.0]

```

I have the setting
`compatibility.override_main_response_version: true
`

**Comment by dblock** [comment]
Does going to 7.10 first work?

**Comment by akomlik** [comment]
we have multiple deployed 7.9.1 clusters and our deployment framework (Terraform) calls for full automation so I did not even consider manual upgrade route in case of rolling upgrades.  Entire VM is immutable object and our upgrade path is replace VM one-by-one in a cluster.
This means I'd have to perform two rolling upgrades:
- first ES to 7.10
- second to OS 2.4
I estimated downtime resulting will be similar to restore from snapshot method

**Comment by dblock** [comment]
@akomlik I am just trying to narrow it down. Reading https://opensearch.org/docs/latest/upgrade-to/upgrade-to/ we recommended you upgrade to latest ODFE (7.10) first because otherwise results may be unpredictable. I think it would be safer than modifying code to support rolling 7.9.x directly, and will give you a checkpoint.

**Comment by akomlik** [comment]
Well, as it turns out I can not possibly upgrade to. later ODFE even to try it since its impossible do download any of OpenDistro plugins anymore.
I can only upgrade basic  elasticsearch-oss to 7.10.2 but without OpenDistro plugins it's useless

the only potential path for companies like ours stuck with ODFE < 1.13 clusters would be to first do rolling upgrade to OD 1.3.7 (which shows 6.8 as minimum version) and then next rolling upgrade to OD 2.4

Our single node ES lab deployments upgrade to OD 2.4 fine as it picks up existing data from disk.

**Comment by dblock** [comment]
@akomlik See https://forum.opensearch.org/t/open-distro-artifacts/10493/3, drop a note to opensearch at amazon dot com and we'll help you locate those artifacts to enable the upgrade path.

**Comment by s1191994586-max** [comment]
I have some questions I'd like to ask.
I want to migrate from Elasticsearch 7.10.2 to OpenSearch 3.x, but the official documentation says it requires downtime or an in-place upgrade. Is there a solution for smoothly migrating two clusters and then switching the access address?
Does the reindex method support migrating data to a new Opensearch cluster while the source Elasticsearch cluster is still readable and writable?
References：
1.https://opensearch.org/blog/announcing-data-prepper-2-5-0/
2.https://docs.opensearch.org/docs/latest/install-and-configure/upgrade-opensearch/index/#compatibility 
3.https://docs.opensearch.org/2.8/upgrade-to/upgrade-to/
