### ISSUE TITLE
[BUG] Max concurrent requests per node changed from default 5 to 1 in Elasticsearch 7.10/Opensearch 1.0

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#3363]
**Describe the bug**
Max concurrent search requests per node was changed from default value of 5 earlier to 1 in Elasticsearch 7.10/Opensearch 1.0 as part of [this commit](https://github.com/elastic/elasticsearch/commit/3d69b5c41e235d7962b6dc315aba8b2f4cbe0ef9). This can lead to ShardNotFoundException if the single node has multiple shards for an index, and shards relocate while the coordinator executes single request batches on data nodes, especially during B/G in Amazon Opensearch service

**To Reproduce**
1. Create node with multiple shards
2. Relocate shards to another node during search request
3. Search request should fail with ShardNotFoundException

**Expected behavior**
The default behavior should keep 5 concurrent requests per node to avoid this regression.

**Screenshots**
```
RemoteTransportException[[76bbf5b90a0e3fe668805d61884db93d][172.16.70.171:9300][indices:data/read/search[phase/query]]]; nested: ShardNotFoundException[no such shard];
Caused by: [users/GK-cv0TRRPO_1ag32E7NKA][[users][224]] ShardNotFoundException[no such shard]
        at org.opensearch.index.IndexService.getShard(IndexService.java:301)
        at org.opensearch.search.SearchService.getShard(SearchService.java:429)
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:394)
        at org.opensearch.action.search.SearchTransportService.lambda$registerRequestHandler$6(SearchTransportService.java:333)
        at com.amazonaws.elasticsearch.iam.IamTransportRequestHandler.messageReceived(IamTransportRequestHandler.java:68)
        at com.amazonaws.elasticsearch.ccs.CrossClusterRequestInterceptor$CrossClusterRequestHandler.messageReceived(CrossClusterRequestInterceptor.java:155)
        at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:138)
        at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:64)
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:85)
        at org.opensearch.transport.InboundHandler.handleRequest(InboundHandler.java:220)
        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:120)
        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102)
        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:713)
        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:155)
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:130)
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:95)
```

**Comment by jkowall** [comment]
This is why massive commits are a big problem. No one can review that PR that you posted.

**Comment by Bukhtawar** [comment]
Not sure if it was reviewed in smaller chunks and then stashed together, but that always carries a risk of missing out on tiny but crucial details

**Comment by jainankitk** [comment]
This issue can be closed after backports are merged in favor of separate issue for adding test #3384

**Comment by adnapibar** [comment]
PR and associated backports are merged, closing the issue
