### ISSUE TITLE
[BUG] Test Failure org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT#testLuceneVersionConstant

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#3565]
```
REPRODUCE WITH: ./gradlew ':qa:verify-version-constants:v2.1.0#integTest' --tests "org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant" -Dtests.seed=C273360AD153BA9B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-BH -Dtests.timezone=Australia/Eucla -Druntime.java=17

org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT > testLuceneVersionConstant FAILED
    java.lang.AssertionError: 
    Expected: <9.3.0>
         but: was <9.2.0>
        at __randomizedtesting.SeedInfo.seed([C273360AD153BA9B:4F160B56F65B79D2]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant(VerifyVersionConstantsIT.java:56)


Suite: Test class org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT
  1> [2022-06-13T12:50:10,071][INFO ][o.o.q.v.VerifyVersionConstantsIT] [testLuceneVersionConstant] before test
  1> [2022-06-13T12:50:10,202][INFO ][o.o.q.v.VerifyVersionConstantsIT] [testLuceneVersionConstant] initializing REST clients against [http://[::1]:46351, http://127.0.0.1:38677]
  1> [2022-06-13T12:50:10,482][INFO ][o.o.q.v.VerifyVersionConstantsIT] [testLuceneVersionConstant] after test
  2> REPRODUCE WITH: ./gradlew ':qa:verify-version-constants:v2.1.0#integTest' --tests "org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant" -Dtests.seed=C273360AD153BA9B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-BH -Dtests.timezone=Australia/Eucla -Druntime.java=17
  2> java.lang.AssertionError: 
    Expected: <9.3.0>
         but: was <9.2.0>
        at __randomizedtesting.SeedInfo.seed([C273360AD153BA9B:4F160B56F65B79D2]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
WARNING: A terminally deprecated method in java.lang.System has been called
        at org.junit.Assert.assertThat(Assert.java:930)
WARNING: System::setSecurityManager has been called by         at org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant(VerifyVersionConstantsIT.java:56)
org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/home/ubuntu/.gradle/wrapper/dists/gradle-7.4.2-all/9uukhhbclvbegdvsww0j0cr3p/gradle-7.4.2/lib/plugins/gradle-testing-base-7.4.2.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/qa/verify-version-constants/build/testrun/v2.1.0#integTest/temp/org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT_C273360AD153BA9B-004
  2> NOTE: test params are: codec=Asserting(Lucene92): {}, docValues:{}, maxPointsInLeafNode=1235, maxMBSortInHeap=5.8963441188103864, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ar-BH, timezone=Australia/Eucla
  2> NOTE: Linux 5.13.0-1014-aws amd64/Eclipse Adoptium 17.0.3 (64-bit)/cpus=72,threads=1,free=484429776,total=536870912
  2> NOTE: All tests run in this JVM: [VerifyVersionConstantsIT]

Tests with failures:
 - org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant
```

**Comment by Bukhtawar** [comment]
Possibly relates to https://github.com/opensearch-project/OpenSearch/pull/3537
/cc @nknize
