### ISSUE TITLE
[BUG] org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#3603]
**Describe the bug**
New flaky test after https://github.com/opensearch-project/OpenSearch/pull/3563 got merged:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness" -Dtests.seed=CD3B9289D31206B8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nl -Dtests.timezone=Asia/Katmandu -Druntime.java=17

org.opensearch.cluster.allocation.AwarenessAllocationIT > testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness FAILED
    java.lang.AssertionError: unexpected
        at org.opensearch.test.InternalTestCluster.removeExclusions(InternalTestCluster.java:1912)
        at org.opensearch.test.InternalTestCluster.stopNodesAndClients(InternalTestCluster.java:1777)
        at org.opensearch.test.InternalTestCluster.stopNodesAndClient(InternalTestCluster.java:1764)
        at org.opensearch.test.InternalTestCluster.stopRandomNode(InternalTestCluster.java:1672)
        at org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness(AwarenessAllocationIT.java:425)

        Caused by:
        java.util.concurrent.ExecutionException: MasterNotDiscoveredException[null]
            at org.opensearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:286)
            at org.opensearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:273)
            at org.opensearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:104)
            at org.opensearch.test.InternalTestCluster.removeExclusions(InternalTestCluster.java:1910)
            ... 4 more

            Caused by:
            MasterNotDiscoveredException[null]
                at app//org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction$2.onTimeout(TransportClusterManagerNodeAction.java:282)
                at app//org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:394)
                at app//org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:294)
                at app//org.opensearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:697)
                at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:739)
                at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

    MasterNotDiscoveredException[null]
        at app//org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction$2.onTimeout(TransportClusterManagerNodeAction.java:282)
        at app//org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:394)
        at app//org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:294)
        at app//org.opensearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:697)
        at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:739)
        at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

```

**To Reproduce**
```
/gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness" -Dtests.seed=CD3B9289D31206B8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nl -Dtests.timezone=Asia/Katmandu -Druntime.java=17
```

**Expected behavior**
On CI, the test is  flaky, see please https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6061.log for example.,

**Plugins**
Standard.

**Screenshots**

**Host/Environment (please complete the following information):**
  - CI

**Additional context**

**Comment by dreamer-89** [comment]
Seed for repro steps
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness" -Dtests.seed=6191C1DB4D571AC -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=lv -Dtests.timezone=Asia/Anadyr -Druntime.java=17
```

**Comment by nknize** [comment]
@imRishN Can you have a look at this test? Do we need 15 nodes for this test or could we scale it back to something like 12? three nodes per AZ?  This is pretty demanding for an integration test and I'm wondering if that's what's causing these intermediate timeout failures?

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/5143

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/5283

**Comment by imRishN** [comment]
I'll take a look to this test and try to fix it

**Comment by Bukhtawar** [comment]
@imRishN lets take a look and get back

**Comment by andrross** [comment]
Another failure here: https://github.com/opensearch-project/OpenSearch/pull/6333#issuecomment-1442520331

**Comment by andrross** [comment]
Another failure: https://github.com/opensearch-project/OpenSearch/pull/7170#issuecomment-1509437495

**Comment by sohami** [comment]
Adding one more: https://github.com/opensearch-project/OpenSearch/pull/7203#issuecomment-1512357074

**Comment by ashking94** [comment]
Another failure : https://github.com/opensearch-project/OpenSearch/pull/8758#issuecomment-1665393556

**Comment by shwetathareja** [comment]
Another failure here - https://github.com/opensearch-project/OpenSearch/pull/10777#issuecomment-1774550373

**Comment by peternied** [comment]
- Impacted PR #11711, see [test report](https://build.ci.opensearch.org/job/gradle-check/31618/testReport/).

**Comment by imRishN** [comment]
Investigated this issue. OpenSearch in a way follows greedy approach while allocating shards and doesn't compute the optimal allocation for all the shards that needs to be allocated. This approach based on certain filters and rules tries to control nodes where shards are assigned.

The unassigned shards causing test failure is due to the same above reason where a node where the shard was supposed to be assigned created a conflict with the awareness allocation decider. Hence, it is stuck in a state, waiting for space to allocate the unassigned shard because it cannot assign it to the only node with space. This also seemed more likely to happen in this particular test case because it is creating a 15 nodes cluster and over 120 shards which increases the probability of landing up in such a case. A smaller cluster with lesser shards would be less likely to land up in such a case.

This also seem to be a known issue after scrolling open issues in ElasticSearch/OpenSearch

Also added same in #7401

**Comment by imRishN** [comment]
Closing the issue, test has been muted and will be fixed and enabled back after the fix in allocator

**Comment by peternied** [comment]
This issue isn't fixed - the test is disabled.  If we were to delete the test I'd be happy to close this issue; however, I suspect that we want to fix the underlying issue.  If there is another issue tracking the scroll issue please link it here.

**Comment by imRishN** [comment]
@peternied, the merged PR which is muting the test links it to actual underlying issue. This is the merged PR muting the test - https://github.com/opensearch-project/OpenSearch/pull/11767. And the PR links the test to actual issue - https://github.com/opensearch-project/OpenSearch/issues/5908.

Feel free to close the issue if this suffices, else we can keep this opened

**Comment by andrross** [comment]
Closing in favor of #17930
