### ISSUE TITLE
[BUG] Performance test fail for OpenSearch core

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#3628]
**Describe the bug**
Performance test for OpenSearch core are failing with the exception

```
SyntaxError: Unexpected token ?\n'
b'    at Module._compile (internal/modules/cjs/loader.js:723:23)\n'
b'    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n'
b'    at Module.load (internal/modules/cjs/loader.js:653:32)\n'
b'    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n'
b'    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n'
b'    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n'
b'    at startup (internal/bootstrap/node.js:283:19)\n'
b'    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)\n'
```

**To Reproduce**
Steps to reproduce the behavior: Start the execution of any performance test

**Expected behavior**
Performance test completes successfully and returns the results

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by kotwanikunal** [comment]
The root cause for the failure seems to be a combination of the environment and dependencies. 
Infrastructure setup is done using the latest `aws-cdk` which is running on a node 10 environment. This configuration is causing failures similar to the ones mentioned [here](https://github.com/aws/aws-cdk/issues/20678) and [here](https://github.com/aws/aws-cdk/issues/20739).

One of the solutions is to upgrade to node 16. With the current setup of the [existing agent image](https://github.com/kotwanikunal/opensearch-build/blob/main/jenkins/opensearch/perf-test.jenkinsfile#L10) we are restricted with an older node version.

Upgrading to a newer node version will help resolve this issue

**Comment by kotwanikunal** [comment]
Submitted a request for an image with node 16 support - https://github.com/opensearch-project/opensearch-build/issues/2211
