### ISSUE TITLE
[BUG] Simple query string with too many characters can cause stack to overflow

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#3760]
**Describe the bug**
```
[2022-06-28T15:47:21,021][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] fatal error in thread [opensearch][search][T#1]], exiting
java.lang.StackOverflowError: null
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:243) ~[lucene-core-9.1.0.jar:9.1.0 5b522487ba8e0f1002b50a136817ca037aec9686 - jtibs - 2022-03-16 10:32:40]
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:277) ~[lucene-core-9.1.0.jar:9.1.0 5b522487ba8e0f1002b50a136817ca037aec9686 - jtibs - 2022-03-16 10:32:40]
        at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:791) ~[lucene-core-9.1.0.jar:9.1.0 5b522487ba8e0f1002b50a136817ca037aec9686 - jtibs - 2022-03-16 10:32:40]
        at org.opensearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:182) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.search.DefaultSearchContext.preProcess(DefaultSearchContext.java:322) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.search.query.QueryPhase.preProcess(QueryPhase.java:125) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.search.SearchService.createContext(SearchService.java:845) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:510) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:483) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:798) ~[opensearch-2.0.0.jar:2.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
fatal error in thread [opensearch][search][T#1]], exiting
java.lang.StackOverflowError
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:243)
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:277)
        at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:791)
        at org.opensearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:182)
        at org.opensearch.search.DefaultSearchContext.preProcess(DefaultSearchContext.java:322)
        at org.opensearch.search.query.QueryPhase.preProcess(QueryPhase.java:125)
        at org.opensearch.search.SearchService.createContext(SearchService.java:845)
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:510)
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:483)
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73)
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:798)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by mch2** [comment]
Have been trying to reproduce this but getting overflow before rewrite step. 

```java
java.lang.StackOverflowError
	at __randomizedtesting.SeedInfo.seed([CCA1BD11AE45204F:6D234C71AA287AF7]:0)
	at org.apache.lucene.core@9.3.0-SNAPSHOT/org.apache.lucene.index.Term.hashCode(Term.java:150)
	at org.apache.lucene.core@9.3.0-SNAPSHOT/org.apache.lucene.search.TermQuery.hashCode(TermQuery.java:272)
	at java.base/java.util.Objects.hashCode(Objects.java:103)
	at java.base/java.util.HashMap$Node.hashCode(HashMap.java:299)
	at java.base/java.util.AbstractMap.hashCode(AbstractMap.java:526)
	at org.apache.lucene.core@9.3.0-SNAPSHOT/org.apache.lucene.search.Multiset.hashCode(Multiset.java:118)
	at java.base/java.util.EnumMap.entryHashCode(EnumMap.java:710)
	at java.base/java.util.EnumMap.hashCode(EnumMap.java:702)
	at java.base/java.util.Arrays.hashCode(Arrays.java:4499)
	at java.base/java.util.Objects.hash(Objects.java:133)
	at org.apache.lucene.core@9.3.0-SNAPSHOT/org.apache.lucene.search.BooleanQuery.computeHashCode(BooleanQuery.java:624)
	at org.apache.lucene.core@9.3.0-SNAPSHOT/org.apache.lucene.search.BooleanQuery.hashCode(BooleanQuery.java:641)
```

Queries with 1024 or less clauses should succeed, but this fails when the queries are nested further.

For example this unit test will succeed:
```java
  public void testSimpleQueryParserWithTooManyClauses() throws IOException {
    StringBuilder queryString = new StringBuilder("foo");
    for (int i = 0; i < 1024; i++) {
      queryString.append(" | bar").append(i);
    }
  }
```

At 1025+ iterations it will fail gracefully with `org.apache.lucene.search.IndexSearcher$TooManyClauses: maxClauseCount is set to 1024`

Where this fails with SO:

```java
  public void testSimpleQueryParserWithTooManyClauses() throws IOException {
    StringBuilder queryString = new StringBuilder("foo");
    for (int i = 0; i < 1024; i++) {
      queryString.append(" | bar")
              .append(i)
              .append(" + baz");
    }
    parse(queryString.toString());
}
```

I'd expect this to also hit the clause limit.  I don't think there is anything graceful we can do on our end other than catching the error.  I've raised https://issues.apache.org/jira/browse/LUCENE-10651 to see if this could be fixed upstream.
