### ISSUE TITLE
[BUG]The master node does not join the cluster

### ISSUE THREAD

**Issue by lliu0947** [opensearch-project/OpenSearch#3798]
**Describe the bug**
Deploy an opensearch cluster with 3 master nodes using helm chart，However, through the _cat/nodes api query, there is only one master node, and when the machine where the master node is located goes down, the remaining two master nodes will not be re-elected, and the entire cluster will be unavailable.
**To Reproduce**
1. master.yaml
clusterName: "opensearch"
nodeGroup: "master"
masterService: "opensearch-master"
replicas: 3
roles:
  - master
persistence:
  storageClass: "local-path"
envFrom:
  - secretRef:
      name: opensearch-auth
2. data.yaml
clusterName: "opensearch"
nodeGroup: "data"
masterService: "opensearch-master"
roles:
  - data
replicas: 3
persistence:
  storageClass: "local-path"
  size: 20Gi
envFrom:
  - secretRef:
      name: opensearch-auth

3. helm install opensearch-master . -f master.yaml
4. helm install opensearch-data . -f data.yaml
4. GET _cat/nodes
10.244.90.133  62  8 0 0.10 0.18 0.21 m * opensearch-master-0
10.244.17.194  67 10 1 0.12 0.26 0.17 d - opensearch-data-1
10.244.17.196  20 10 1 0.12 0.26 0.17 r - opensearch-coordinate-0
10.244.90.132  58 12 0 0.10 0.18 0.21 d - opensearch-data-0
10.244.102.197 24 11 0 0.13 0.11 0.09 d - opensearch-data-2

The result shows that there is only one master node

helm chart version：2.0.0
opensearch：2.0.0

**Expected behavior**
The result shows that there is only one master node, there should be 3 master nodes

**Additional context**
opensearch-master-1 logs:
[2022-07-07T02:16:43,064][INFO ][o.k.p.h.c.PerformanceAnalyzerConfigAction] [opensearch-master-1] PerformanceAnalyzer Enabled: false
[2022-07-07T02:16:43,109][INFO ][o.k.n.Node               ] [opensearch-master-1] initialized
[2022-07-07T02:16:43,109][INFO ][o.k.n.Node               ] [opensearch-master-1] starting ...
[2022-07-07T02:16:43,238][INFO ][o.k.t.TransportService   ] [opensearch-master-1] publish_address {10.244.102.200:9300}, bound_addresses {0.0.0.0:9300}
[2022-07-07T02:16:43,489][INFO ][o.k.b.BootstrapChecks    ] [opensearch-master-1] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2022-07-07T02:16:43,870][INFO ][o.k.c.c.Coordinator      ] [opensearch-master-1] setting initial configuration to VotingConfiguration{sLiCGB1hR-uKm8lLLJHPTQ,{bootstrap-placeholder}-opensearch-master-0,vvusU5McQ6CjbZWLeABHfQ}
[2022-07-07T02:16:44,156][INFO ][o.k.c.s.MasterService    ] [opensearch-master-1] elected-as-cluster-manager ([2] nodes joined)[{opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10.244.102.200}{10.244.102.200:9300}{m}{shard_indexing_pressure_enabled=true} elect leader, {opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard_indexing_pressure_enabled=true} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 2, version: 1, delta: cluster-manager node changed {previous [], current [{opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10.244.102.200}{10.244.102.200:9300}{m}{shard_indexing_pressure_enabled=true}]}, added {{opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard_indexing_pressure_enabled=true}}
[2022-07-07T02:16:44,125][INFO ][o.k.c.c.JoinHelper       ] [opensearch-master-1] failed to join {opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10.244.102.200}{10.244.102.200:9300}{m}{shard_indexing_pressure_enabled=true}, minimumTerm=0, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10.244.102.200}{10.244.102.200:9300}{m}{shard_indexing_pressure_enabled=true}, targetNode={opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [opensearch-master-2][10.244.17.198:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: incoming term 1 does not match current term 2
        at org.opensearch.cluster.coordination.CoordinationState.handleJoin(CoordinationState.java:256) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.cluster.coordination.Coordinator.handleJoin(Coordinator.java:1166) ~[opensearch-2.0.0.jar:2.0.0]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.opensearch.cluster.coordination.Coordinator.processJoinRequest(Coordinator.java:639) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.cluster.coordination.Coordinator.lambda$handleJoinRequest$7(Coordinator.java:602) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:80) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.transport.ClusterConnectionManager.connectToNode(ClusterConnectionManager.java:138) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.transport.TransportService.connectToNode(TransportService.java:428) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.transport.TransportService.connectToNode(TransportService.java:412) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.cluster.coordination.Coordinator.handleJoinRequest(Coordinator.java:587) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.cluster.coordination.JoinHelper.lambda$new$1(JoinHelper.java:179) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceivedDecorate(SecuritySSLRequestHandler.java:193) ~[?:?]
        at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:283) ~[?:?]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:153) ~[?:?]
        at org.opensearch.security.opensearchSecurityPlugin$7$1.messageReceived(opensearchSecurityPlugin.java:651) ~[?:?]
        at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:118) ~[?:?]
        at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:103) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:798) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.0.0.jar:2.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-07-07T02:16:44,348][INFO ][o.k.c.c.CoordinationState] [opensearch-master-1] cluster UUID set to [6u3_EAJ4TJShN_5eXsxOKg]
[2022-07-07T02:16:44,533][INFO ][o.k.c.s.ClusterApplierService] [opensearch-master-1] cluster-manager node changed {previous [], current [{opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10.244.102.200}{10.244.102.200:9300}{m}{shard_indexing_pressure_enabled=true}]}, added {{opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard_indexing_pressure_enabled=true}}, term: 2, version: 1, reason: Publication{term=2, version=1}
[2022-07-07T02:16:44,584][WARN ][o.k.c.c.Coordinator      ] [opensearch-master-1] failed to validate incoming join request from node [{opensearch-data-2}{DNkKLNyiS-eVJvMlduVPbg}{-HLr-y3OR5aVILgWGw-nDA}{10.244.102.197}{10.244.102.197:9300}{d}{shard_indexing_pressure_enabled=true}]
org.opensearch.transport.RemoteTransportException: [opensearch-data-2][10.244.102.197:9300][internal:cluster/coordination/join/validate]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid 6u3_EAJ4TJShN_5eXsxOKg than local cluster uuid e5DWxprxQpWT8V3r8PeZiA, rejecting
        at org.opensearch.cluster.coordination.JoinHelper.lambda$new$4(JoinHelper.java:208) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceivedDecorate(SecuritySSLRequestHandler.java:193) ~[?:?]
        at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:283) ~[?:?]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:153) ~[?:?]
        at org.opensearch.security.opensearchSecurityPlugin$7$1.messageReceived(opensearchSecurityPlugin.java:651) ~[?:?]
        at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:118) ~[?:?]
        at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:103) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:798) ~[opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.0.0.jar:2.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-07-07T02:16:44,603][WARN ][o.k.c.c.Coordinator      ] [opensearch-master-1] failed to validate incoming join request from node [{opensearch-data-0}{ZyBHf2PXRLqOu0KVfKZIIQ}{V-2hn9gPTMikL6jNPwff-Q}{10.244.90.132}{10.244.90.132:9300}{d}{shard_indexing_pressure_enabled=true}]
org.opensearch.transport.RemoteTransportException: [opensearch-data-0][10.244.90.132:9300][internal:cluster/coordination/join/validate]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid 6u3_EAJ4TJShN_5eXsxOKg than local cluster uuid e5DWxprxQpWT8V3r8PeZiA, rejecting

opensearch-master-2 logs:
[2022-07-07T02:16:44,217][INFO ][o.k.c.c.JoinHelper       ] [opensearch-master-2] failed to join {opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard
_indexing_pressure_enabled=true} with JoinRequest{sourceNode={opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard_indexing_pressure_enabled=true}, min
imumTerm=0, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{sh
ard_indexing_pressure_enabled=true}, targetNode={opensearch-master-2}{sLiCGB1hR-uKm8lLLJHPTQ}{P-JhXI-dTXWxPZids2l_8A}{10.244.17.198}{10.244.17.198:9300}{m}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [opensearch-master-2][10.244.17.198:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: became follower
        at org.opensearch.cluster.coordination.JoinHelper$CandidateJoinAccumulator.lambda$close$3(JoinHelper.java:551) [opensearch-2.0.0.jar:2.0.0]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) [?:?]
        at org.opensearch.cluster.coordination.JoinHelper$CandidateJoinAccumulator.close(JoinHelper.java:551) [opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.cluster.coordination.Coordinator.becomeFollower(Coordinator.java:737) [opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.cluster.coordination.Coordinator.onFollowerCheckRequest(Coordinator.java:340) [opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.cluster.coordination.FollowersChecker$2.doRun(FollowersChecker.java:228) [opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:798) [opensearch-2.0.0.jar:2.0.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.0.0.jar:2.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-07-07T02:16:44,366][INFO ][o.k.c.c.CoordinationState] [opensearch-master-2] cluster UUID set to [6u3_EAJ4TJShN_5eXsxOKg]
[2022-07-07T02:16:44,400][INFO ][o.k.c.s.ClusterApplierService] [opensearch-master-2] cluster-manager node changed {previous [], current [{opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10
.244.102.200}{10.244.102.200:9300}{m}{shard_indexing_pressure_enabled=true}]}, added {{opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10.244.102.200}{10.244.102.200:9300}{m}{shard_indexing_
pressure_enabled=true}}, term: 2, version: 1, reason: ApplyCommitRequest{term=2, version=1, sourceNode={opensearch-master-1}{vvusU5McQ6CjbZWLeABHfQ}{NXv1rrpJR_CZCixs-3srhQ}{10.244.102.200}{10.244.102.200:9300}{m
}{shard_indexing_pressure_enabled=true}}
[2022-07-07T02:16:44,420][INFO ][o.k.a.u.d.DestinationMigrationCoordinator] [opensearch-master-2] Detected cluster change event for destination migration
[2022-07-07T02:16:44,445][INFO ][o.k.a.c.ADClusterEventListener] [opensearch-master-2] Cluster is not recovered yet.
[2022-07-07T02:16:44,464][INFO ][o.k.h.AbstractHttpServerTransport] [opensearch-master-2] publish_address {10.244.17.198:9200}, bound_addresses {0.0.0.0:9200}
[2022-07-07T02:16:44,465][INFO ][o.k.n.Node               ] [opensearch-master-2] started
[2022-07-07T02:16:44,465][INFO ][o.k.s.opensearchSecurityPlugin] [opensearch-master-2] Node started
[2022-07-07T02:16:44,465][INFO ][o.k.s.c.ConfigurationRepository] [opensearch-master-2] Will attempt to create index .opendistro_security and default configs if they are absent
[2022-07-07T02:16:44,466][INFO ][o.k.s.c.ConfigurationRepository] [opensearch-master-2] Background init thread started. Install default config?: true
[2022-07-07T02:16:44,467][INFO ][o.k.s.opensearchSecurityPlugin] [opensearch-master-2] 0 opensearch Security modules loaded so far: []
[2022-07-07T02:16:44,660][WARN ][o.k.p.c.s.h.ConfigOverridesClusterSettingHandler] [opensearch-master-2] Config override setting update called with empty string. Ignoring.
[2022-07-07T02:16:44,699][INFO ][o.k.a.u.d.DestinationMigrationCoordinator] [opensearch-master-2] Detected cluster change event for destination migration
[2022-07-07T02:16:44,702][INFO ][o.k.a.c.HashRing         ] [opensearch-master-2] Node added: [sLiCGB1hR-uKm8lLLJHPTQ, vvusU5McQ6CjbZWLeABHfQ]
[2022-07-07T02:16:44,717][INFO ][o.k.a.c.HashRing         ] [opensearch-master-2] All nodes with known AD version: {sLiCGB1hR-uKm8lLLJHPTQ=ADNodeInfo{version=2.0.0, isEligibleDataNode=false}, vvusU5McQ6CjbZWLeABHfQ=ADNodeInfo{version=2.0.0, isEligibleDataNode=false}}
[2022-07-07T02:16:44,718][INFO ][o.k.a.c.HashRing         ] [opensearch-master-2] Rebuild AD hash ring for realtime AD with cooldown, nodeChangeEvents size 0
[2022-07-07T02:16:44,718][INFO ][o.k.a.c.HashRing         ] [opensearch-master-2] Build AD version hash ring successfully
[2022-07-07T02:16:44,719][INFO ][o.k.a.c.ADClusterEventListener] [opensearch-master-2] Init AD version hash ring successfully
[2022-07-07T02:16:45,153][INFO ][o.k.a.u.d.DestinationMigrationCoordinator] [opensearch-master-2] Detected cluster change event for destination migration
[2022-07-07T02:16:45,174][INFO ][o.k.s.c.ConfigurationRepository] [opensearch-master-2] Index .opendistro_security already exists
[2022-07-07T02:16:45,174][INFO ][o.k.s.c.ConfigurationRepository] [opensearch-master-2] Node started, try to initialize it. Wait for at least yellow cluster state....
[2022-07-07T02:17:44,654][INFO ][o.k.c.s.ClusterSettings  ] [opensearch-master-2] updating [plugins.index_state_management.template_migration.control] from [0] to [-1]
[2022-07-07T02:17:44,655][INFO ][o.k.a.u.d.DestinationMigrationCoordinator] [opensearch-master-2] Detected cluster change event for destination migration

**Comment by marcio-pessoa** [comment]
Hi dears. What can I do to solve this issue?

**Comment by dblock** [comment]
@marcio-pessoa are you having the same problem? If you're using a configuration out of the box, open a new issue in https://github.com/opensearch-project/helm-charts please.

**Comment by dblock** [comment]
@lliu0947 Did you solve your problem? How?

**Comment by marcio-pessoa** [comment]
> @marcio-pessoa are you having the same problem? If you're using a configuration out of the box, open a new issue in https://github.com/opensearch-project/helm-charts please.

Hello dears, the problem happened when I updated the cluster from version 1.3.4 to 2.1.0. After a few minutes, the problem was fixed automatically.

**Comment by mosajjal** [comment]
hey @dblock, is there a document somewhere for upgrading Opensearch from version X to version Y, and what's the best compatibility path? we used to have a bunch of good docs for ES-OSS to ODFE and ODFE to Opensearch 1.x but nothing onwards

**Comment by dblock** [comment]
Upgrade docs are always in https://opensearch.org/docs/latest/upgrade-to/upgrade-to/. If that's insufficient, open an issue in documentation-website that explains what you're looking for?

**Comment by mosajjal** [comment]
yes those docs are mostly for ES to Opensearch, they could use some work for 1.x to 2.x etc. Will open an issue in docs repo, thanks.
