### ISSUE TITLE
[BUG] General error during semantic analysis: Unsupported class file major version 61

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#3814]
This happens on old branches with gradle 6.6.1 and jdk17.
It somehow would go away if you reset JAVA_HOME.
Not very consistent fix it happens to me once but then happens multiple times on gradle check by just running
`./gradlew clean`.

https://build.ci.opensearch.org/job/gradle-check/267/console
https://build.ci.opensearch.org/job/gradle-check/270/console
......

```

Start gradlecheck
Downloading https://services.gradle.org/distributions/gradle-6.6.1-all.zip
.............10%..............20%..............30%..............40%..............50%..............60%.............70%..............80%..............90%..............100%

Welcome to Gradle 6.6.1!

Here are the highlights of this release:
 - Experimental build configuration caching
 - Built-in conventions for handling credentials
 - Java compilation supports --release flag

For more details see https://docs.gradle.org/6.6.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Settings file '/var/jenkins/workspace/gradle-check/search/settings.gradle'

* What went wrong:
Could not compile settings file '/var/jenkins/workspace/gradle-check/search/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
 java.lang.IllegalArgumentException: Unsupported class file major version 61
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
  	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
  	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
  	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
  	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:79)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:70)
  	at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:57)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode$2.get(DecompiledClassNode.java:234)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode$2.get(DecompiledClassNode.java:231)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createMethodNode(DecompiledClassNode.java:242)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:199)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
```

**Comment by reta** [comment]
@peterzhuamazon Gradle 6.6.x  does not support jdk-17 :(

**Comment by dblock** [comment]
You're running this on an older version of the code, @peterzhuamazon ?

**Comment by peterzhuamazon** [comment]
Some feature branches is having 6.6.1.

**Comment by peterzhuamazon** [comment]
This now seems like an issue where feature branches are old and no-supported we should remove the useless feature branch as some of them have not been touches for 6months.

Will close, thanks.
