### ISSUE TITLE
OS neither starting on Mac M1 nor on Linux

### ISSUE THREAD

**Issue by zopyx** [opensearch-project/OpenSearch#3918]
`docker-compose up``

Mac M1:

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[27076] Failed to execute script docker-compose
```

Linux/Ubuntu (reproduced on 2 different systems):

`OpenSearch Dashboards server is not ready yet`:

```
opensearch-node1         | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
opensearch-node1         | ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-cluster.log
opensearch-node1         | [2022-07-15T08:09:28,912][INFO ][o.o.s.a.r.AuditMessageRouter] [opensearch-node1] Closing AuditMessageRouter
opensearch-node1         | [2022-07-15T08:09:28,913][INFO ][o.o.s.a.s.SinkProvider   ] [opensearch-node1] Closing InternalOpenSearchSink
opensearch-node1         | [2022-07-15T08:09:28,914][INFO ][o.o.s.a.s.SinkProvider   ] [opensearch-node1] Closing DebugSink
opensearch-node1         | [2022-07-15T08:09:28,914][INFO ][o.o.n.Node               ] [opensearch-node1] stopping ...
opensearch-node1         | [2022-07-15T08:09:28,941][INFO ][o.o.n.Node               ] [opensearch-node1] stopped
opensearch-node1         | [2022-07-15T08:09:28,942][INFO ][o.o.n.Node               ] [opensearch-node1] closing ...
opensearch-node1         | [2022-07-15T08:09:28,954][INFO ][o.o.s.a.i.AuditLogImpl   ] [opensearch-node1] Closing AuditLogImpl
opensearch-node1         | [2022-07-15T08:09:28,963][INFO ][o.o.n.Node               ] [opensearch-node1] closed
opensearch-node1         | Killing performance analyzer process 34
opensearch-node2 exited with code 0
opensearch-node1         | OpenSearch exited with code 78
opensearch-node1         | Performance analyzer exited with code 143
opensearch-node1 exited with code 0
opensearch-dashboards    | {"type":"log","@timestamp":"2022-07-15T08:09:29Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo EAI_AGAIN opensearch-node1"}
opensearch-dashboards    | {"type":"log","@timestamp":"2022-07-15T08:09:32Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo EAI_AGAIN opensearch-node1"}
opensearch-dashboards    | {"type":"log","@timestamp":"2022-07-15T08:09:34Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo EAI_AGAIN opensearch-node1"}
opensearch-dashboards    | {"type":"log","@timestamp":"2022-07-15T08:09:37Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo EAI_AGAIN opensearch-node1"}
opensearch-dashboards    | {"type":"log","@timestamp":"2022-07-15T08:09:39Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo EAI_AGAIN opensearch-node1"}
```

**Comment by lukas-vlcek** [comment]
Hi @zopyx 

I think the first issue to address would be
> max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

Did you consult https://opensearch.org/downloads.html specifically https://opensearch.org/docs/latest/opensearch/install/important-settings/ ?

**Comment by zopyx** [comment]
Doubt...the M1 issue has nothing to do with memory (as the traceback indicates) and my Docker installation has 8 GB configured.

**Comment by owaiskazi19** [comment]
Looks like OpenSearch is working on M1. @zopyx can we close this issue?

**Comment by minalsha** [comment]
@zopyx  we are closing thisissue but please feel free to reopen if there are any open issue with it. Thanks
