### ISSUE TITLE
[Segment Replication] [BUG] SegmentReplicationTargetServiceTests.testReplicationOnDone flaky test failure

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#4268]
**Describe the bug**
I have seen this issue on CI server multiple times. This test might succeeding on retries but need to make it more consistent. 

e.g. https://build.ci.opensearch.org/job/gradle-check/1943
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testReplicationOnDone" -Dtests.seed=7C5D31ACA05B2F46 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fi-FI -Dtests.timezone=America/Tortola -Druntime.java=17

org.opensearch.indices.replication.SegmentReplicationTargetServiceTests > testReplicationOnDone FAILED
    org.mockito.exceptions.verification.TooFewActualInvocations: 
    segmentReplicationTargetService.onNewCheckpoint(
        ReplicationCheckpoint{shardId=[index][0], primaryTerm=40, segmentsGen=2, seqNo=-1, version=7},
        <any>
    );
    Wanted 2 times:
    -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testReplicationOnDone(SegmentReplicationTargetServiceTests.java:257)
    But was 1 time:
    -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testReplicationOnDone(SegmentReplicationTargetServiceTests.java:251)
        at app//org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testReplicationOnDone(SegmentReplicationTargetServiceTests.java:257)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=152, name=opensearch[org.opensearch.indices.replication.SegmentReplicationTargetServiceTests][generic][T#1], state=RUNNABLE, group=TGRP-SegmentReplicationTargetServiceTests]
```

**Comment by mch2** [comment]
Closing - this test was replaced in https://github.com/opensearch-project/OpenSearch/issues/4225
