### ISSUE TITLE
Login issue in opensearch-dashboard

### ISSUE THREAD

**Issue by zakirpcs** [opensearch-project/OpenSearch#4373]
I build customized rpm of opensearch & opensearch-dashboads now i am facing to start opensearch-dashboard service using systemd script.

I am getting below error message during service startup.

opensearch-dashboards[533384]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
opensearch-dashboards[533384]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
opensearch-dashboards[533384]:     at internal/main/run_main_module.js:17:47 {
opensearch-dashboards[533384]:   code: 'MODULE_NOT_FOUND',
opensearch-dashboards[533384]:   requireStack: []
opensearch-dashboards[533384]: }
systemd[1]: opensearch-dashboards.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: opensearch-dashboards.service: Failed with result 'exit-code'.
-- Subject: Unit failed

How can i resolved this issue. Can anyone help me on this or is it possible to share spec file with me so that i can customized the rpm as per my requirements.

Regards,
Zakir

**Comment by xuezhou25** [comment]
Transfer this issue to Dashboard repo.
