### ISSUE TITLE
SQLPlugin can declare geo module as compileOnly dependency

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/OpenSearch#4461]
**Is your feature request related to a problem? Please describe.**
* SQLPlugin build failed after [geo aggregation move to geo module](https://github.com/opensearch-project/OpenSearch/pull/4180 ).
* SQLPlugin declare as geo module as a dependency, but IT failed.
https://github.com/opensearch-project/sql/runs/8255337793?check_suite_focus=true
```
»  java.lang.NoClassDefFoundError: org/opensearch/geo/search/aggregations/bucket/geogrid/GeoGridAggregationBuilder
»       at org.opensearch.sql.legacy.query.AggregationQueryAction.<init>(AggregationQueryAction.java:47)
»       at org.opensearch.sql.legacy.query.planner.converter.SQLToOperatorConverter.scroll(SQLToOperatorConverter.java:74)
»       at org.opensearch.sql.legacy.query.planner.converter.SQLToOperatorConverter.visit(SQLToOperatorConverter.java:52)
»       at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock.accept0(MySqlSelectQueryBlock.java:255)
»       at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock.accept0(MySqlSelectQueryBlock.java:246)
»       at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40)
»       at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:62)
»       at com.alibaba.druid.sql.ast.statement.SQLSelect.accept0(SQLSelect.java:85)
»       at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40)
»       at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:62)
»       at com.alibaba.druid.sql.ast.expr.SQLQueryExpr.accept0(SQLQueryExpr.java:55)
»       at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40)
»       at org.opensearch.sql.legacy.query.planner.core.BindingTupleQueryPlanner.<init>(BindingTupleQueryPlanner.java:30)
»       at org.opensearch.sql.legacy.query.OpenSearchActionFactory.create(OpenSearchActionFactory.java:118)
»       at org.opensearch.sql.legacy.plugin.SearchDao.explain(SearchDao.java:52)
»       at org.opensearch.sql.legacy.plugin.RestSqlAction.explainRequest(RestSqlAction.java:208)
»       at org.opensearch.sql.legacy.plugin.RestSqlAction.lambda$prepareRequest$1(RestSqlAction.java:164)
»       at org.opensearch.sql.opensearch.executor.Scheduler.lambda$withCurrentContext$0(Scheduler.java:30)
»       at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
»       at java.base/java.lang.Thread.run(Thread.java:832)
»  Caused by: java.lang.ClassNotFoundException: org.opensearch.geo.search.aggregations.bucket.geogrid.GeoGridAggregationBuilder
»       at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
»       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
»       at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:855)
»       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
»       ... 22 more
```
* I think the root cause is plugin and module use different ClassLoader when PluginService loadBundle. Currently only [ExtendedPluginClassLoader works](https://github.com/opensearch-project/OpenSearch/blob/31a360fc87419cd3a6d5621754f8ad9e8819f1e8/libs/plugin-classloader/src/main/java/org/opensearch/plugins/ExtendedPluginsClassLoader.java), but `Plugin [opensearch-sql] cannot extend non-extensible plugin [geo]`.
* Currently, SQLPlugin has workaround to declare geo as implementation dependency.

**Describe the solution you'd like**
* Plugin could declare module as dependency, e.g. dependencyModule. similar as [extendedPlugins](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L125). [The class loader could load dependency module.](https://github.com/opensearch-project/OpenSearch/blob/14704b30cafadcfdcd7cd81961ee07452804b0c3/server/src/main/java/org/opensearch/plugins/PluginsService.java#L195)

**Describe alternatives you've considered**
* N/A

**Additional context**

**Comment by saratvemulapalli** [comment]
Thanks @penghuo for the issue. Seems like a classpath doesnt have the modules. 
We should fix this to avoid bundling multiple jars in the same distribution.
