### ISSUE TITLE
[BUG] The GET _script_language request returns a NullPointerException

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/OpenSearch#4534]
**Describe the bug**
The GET _script_language call returns a NullPointerException:  Cannot invoke "java.util.Set.stream()" because the return value of "org.opensearch.script.ScriptEngine.getSupportedContexts()" is null

**To Reproduce**
1. Either go to the DevTools on Dashboards or use curl
2. Send the GET _script_language request to OpenSearch
4. The response contains a NullPointerException:
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : "Cannot invoke \"java.util.Set.stream()\" because the return value of \"org.opensearch.script.ScriptEngine.getSupportedContexts()\" is null"
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : "Cannot invoke \"java.util.Set.stream()\" because the return value of \"org.opensearch.script.ScriptEngine.getSupportedContexts()\" is null"
  },
  "status" : 500
}`
The log:
`| [2022-09-16T13:54:52,502][WARN ][r.suppressed             ] [opensearch] path: /_script_language, params: {pretty=true}
opensearch               | java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "org.opensearch.script.ScriptEngine.getSupportedContexts()" is null
opensearch               |      at org.opensearch.script.ScriptService.lambda$getScriptLanguages$8(ScriptService.java:669) ~[opensearch-2.2.0.jar:2.2.0]
opensearch               |      at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
opensearch               |      at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553) ~[?:?]
opensearch               |      at org.opensearch.script.ScriptService.getScriptLanguages(ScriptService.java:666) ~[opensearch-2.2.0.jar:2.2.0]
opensearch               |      at org.opensearch.action.admin.cluster.storedscripts.TransportGetScriptLanguageAction.doExecute(TransportGetScriptLanguageAction.java:59) ~[opensearch-2.2.0.jar:2.2.0]
opensearch               |      at org.opensearch.action.admin.cluster.storedscripts.TransportGetScriptLanguageAction.doExecute(TransportGetScriptLanguageAction.java:48) ~[opensearch-2.2.0.jar:2.2.0]
`
**Expected behavior**
Expected to get a list of script languages.

**Plugins**
Default list.

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 10

**Additional context**
GET _script_context works as expected

**Comment by dbwiddis** [comment]
Unable to repro on macOS:
> ➜  curl -X GET localhost:9200/_script_language
{"types_allowed":["inline","stored"],"language_contexts":[{"language":"expression","contexts":["aggregation_selector","aggs","bucket_aggregation","field","filter","number_sort","score","terms_set"]},{"language":"mustache","contexts":["template"]},{"language":"painless","contexts":["aggregation_selector","aggs","aggs_combine","aggs_init","aggs_map","aggs_reduce","analysis","bucket_aggregation","field","filter","ingest","interval","moving-function","number_sort","painless_test","processor_conditional","score","script_heuristic","similarity","similarity_weight","string_sort","template","terms_set","update"]}]}%

**Comment by dbwiddis** [comment]
This may be a bug in the KNNScoringScriptEngine:
https://github.com/opensearch-project/k-NN/blob/02c30cb9e1e175af73220ddd04ba77e086b79113/src/main/java/org/opensearch/knn/plugin/script/KNNScoringScriptEngine.java#L46-L48

FYI: @jmazanec15 @vamshin @VijayanB

**Comment by kolchfa-aws** [comment]
@alicejw-aws also has the same behavior on Mac.

**Comment by dbwiddis** [comment]
> @alicejw-aws also has the same behavior on Mac.

Can you isolate it to the K-NN plugin?

**Comment by kolchfa-aws** [comment]
@dbwiddis I'm not set up to run with debugging, I'm only using OpenSearch as a user...

**Comment by dbwiddis** [comment]
@kolchfa-aws Got it.  I've confirmed the k-NN plugin has the bug and submitted a PR to fix, but I'm not sure if there are any others out there. The way a user could test would be to temporarily [remove that plugin](https://opensearch.org/docs/latest/opensearch/install/plugins#remove).  (And put it back after testing.)

**Comment by dbwiddis** [comment]
Confirmed the issue is isolated to k-NN plugin.  After repro in this comment, executed these commands on the opensearch node:
```
sh-4.2$ /usr/share/opensearch/bin/opensearch-plugin remove opensearch-knn
-> removing [opensearch-knn]...
sh-4.2$ /usr/share/opensearch/bin/opensearch restart
```
Then executed `GET /_script_language`:
```json
{
  "types_allowed" : [
    "inline",
    "stored"
  ],
  "language_contexts" : [
    {
      "language" : "expression",
      "contexts" : [
        "aggregation_selector",
        "aggs",
        "bucket_aggregation",
        "field",
        "filter",
        "number_sort",
        "score",
        "terms_set"
      ]
    },
    {
      "language" : "mustache",
      "contexts" : [
        "template"
      ]
    },
    {
      "language" : "opensearch_query_expression",
      "contexts" : [
        "aggs",
        "filter"
      ]
    },
    {
      "language" : "painless",
      "contexts" : [
        "aggregation_selector",
        "aggs",
        "aggs_combine",
        "aggs_init",
        "aggs_map",
        "aggs_reduce",
        "analysis",
        "bucket_aggregation",
        "field",
        "filter",
        "ingest",
        "interval",
        "moving-function",
        "number_sort",
        "painless_test",
        "processor_conditional",
        "score",
        "script_heuristic",
        "similarity",
        "similarity_weight",
        "string_sort",
        "template",
        "terms_set",
        "trigger",
        "update"
      ]
    }
  ]
}
```
