### ISSUE TITLE
[Opensearch fails while performing bulk request for new index]

### ISSUE THREAD

**Issue by anantsingh09** [opensearch-project/OpenSearch#4643]
**Describe the bug**
While i try to do a bulk upload to the opensearch , it fails with error: 
Exception in thread "main" java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}

**To Reproduce**
1. [Opensearch rest](opensearch-rest-high-level-client:1.3.0)
2.  BulkResponse resp = client.bulk(bulk, RequestOptions.DEFAULT);
3. i tried even with client.bulkAsync(bulk, RequestOptions.DEFAULT, new ActionListener(){}
4. Error:
Exception in thread "main" java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1781)
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1728)
	at
org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696)
	at org.opensearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:363)
	at elasticsearch.Uploader.main(Uploader.java:77)

**Expected behavior**
i expect my bulk request  to be processed as it was there while i was using the elasticsearch instead of opensearch.
The same code works fine with elastcisearch and elasticsearch-rest-high-level-client:7.5.1

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
Attaching the screenshot of the complete error.

<img width="1363" alt="Screenshot 2022-09-30 at 11 24 05 AM" src="https://user-images.githubusercontent.com/48406485/193200272-f00e72a7-7463-4b21-869e-d6df4d428d5e.png">

**Host/Environment (please complete the following information):**
 - OS:  MacOS Monterey 
 - Version : 12.5.1

**Additional context**

**Comment by anasalkouz** [comment]
Could you provide more details related about your OpenSearch and Elasticsearch cluster versions? are you using elasticsearch-rest-high-level-client:7.5.1 to communicate with OpenSearch?

**Comment by anantsingh09** [comment]
@anasalkouz 
Can you please re-open the issue ?
i have tried using elasticsearch-rest-high-level-client:7.5.1 as well as opensearch-rest-high-level-client:2.3.0
i got the bulk upload failure as i stated.
currently i am using opensearch-rest-high-level-client:1.3.0 and opensearch version 1.3.0 and the bulk upload works fine.

**Comment by dblock** [comment]
@anantsingh09 I can reopen. Sounds like client 1.3.0 <> server 1.3.0 works. Which combination of client/server doesn't?
