### ISSUE TITLE
OpenSearchJsonLayout logs newlines in json

### ISSUE THREAD

**Issue by svenso** [opensearch-project/OpenSearch#4673]
**Describe the bug**
Using the OpenSearchJsonLayout for logging out of a docker container adds newlines in the generated json-string when a stack-trace is appended. This makes it unnecessarily hard to process the logs by a line based log-agent.

**To Reproduce**
Use the following log4j2 config: 
```status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = OpenSearchJsonLayout
appender.console.layout.type_name = server

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
```
which generates logs like this:
```
{ ... "cluster.uuid": "KK8EloHiQGCbVCUO3RPkmg", "node.id": "HTVcLMDtRLSgVqq2w5l0UA" ,
"stacktrace": ["java.lang.NullPointerException: Cannot invoke \"String.length()\" because \"other\" is null",
"at org.apache.lucene.search.spell.LevenshteinDistance.getDistance(LevenshteinDistance.java:62)"
...
"at java.lang.Thread.run(Thread.java:833) [?:?]"] }
```

**Expected behavior**
Not adding unnecessary newlines.

The newlines are injected here:
https://github.com/opensearch-project/OpenSearch/blob/10bff0c9f5b9ca78b3dc50f5c704dabf41b9d535/server/src/main/java/org/opensearch/common/logging/JsonThrowablePatternConverter.java

Is there any reason for those or can they get removed?

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04 (docker)

**Comment by dblock** [comment]
I am wild-guessing that this was added for readability of the logs when debugging. Not sure how we can have it both ways 🤔

**Comment by svenso** [comment]
That's true. But usually, JSON is not the best format, if you plan to read it as is.

Other solutions might be, that we implement flags like in JSONLayout of log4j2 (compact=true for example), but I understand, that this is a quite manual job (due to missing jackson-databind library & security considerations we cannot use JSONLayout directly as far as I understand).

**Comment by saratvemulapalli** [comment]
I was just chatting @dbwiddis, we came up with idea of a configurable setting which spits out logs in machine readable format or human readable format. 
As @dblock suggested do you have a proposal to move the needle here?

**Comment by svenso** [comment]
I will have a look at it. But for me, the main question stays: 
if someone is switching from the default (readable) PatternLayout to OpenSearchJsonLayout, do we really need to keep a "readability"? 
But I am also not quite happy, how the JSON is generated (string concatenation). 
Let me test some things and I'll come back.

**Comment by svenso** [comment]
I made a first draft with some optimizations how it'd be useful for our usecase.  It should be back compatible to the old behavior when no configuration is used.

I am not a java developer and it's the first time I am contributing in an opensource project... I hope I didn't do everything wrong...

**Comment by minalsha** [comment]
@svenso could you please address above comment from @dbwiddis ? Thanks

**Comment by dblock** [comment]
@svenso Let's have any discussions on the PR in https://github.com/opensearch-project/OpenSearch/pull/4783

**Comment by PeterKnopp-ETECTURE** [comment]
Hello,
is there any ongoing work on this topic? 

I would appreciate the requested changes in our environment, too. 
We are using opensearch in a kubernetes cluster and watch our logs in opensearch-dashboard. 
Logs with Exception send from the opensearch server are not readable there because the lines are shown in random order.

I agree to the opinion of @svenso that when choosing the JSON-format you don't expect good readability on STDOUT.

**Comment by Jakob3xD** [comment]
+1

**Comment by WeslyG** [comment]
I think if you include logs in JSON format, it is obvious that they are being read by a machine and not by a human. What's the point of taking care of readability, and breaking the only thing that should work - automated structured delivery to the endpoint (victorialogs,opensearch, datadog, etc.)

**Comment by WeslyG** [comment]
use this vector config if you need json logs delivery
```
sources:
  opensearch_files_input:
    type: file
    include:
      - /var/log/opensearch/*json
    multiline:
      start_pattern: '^\{'
      condition_pattern: '^[^{]'
      mode: continue_through
      timeout_ms: 1000
```

**Comment by dforste** [comment]
This still seems to be an issue and it looks like the PR died. Can someone take another start on it? 

Also @msfroh contributed this on slack which might be a good help to someone looking for it. 
```
appender.console.layout.alwaysWriteExceptions = false
appender.console.layout.pattern = {"level":"%p","timestamp":"%d{ISO8601}","thread":"%t","file":"%F","line":"%L","message":"%notEmpty{%enc{%marker}{JSON}}%enc{%m}{JSON}"%notEmpty{,"stacktrace":["%throwable{separator(",")}"]}}%n
```

**Comment by msfroh** [comment]
Oh... this is neat. As @dforste called out, I had a similar problem in my job, so I just used that `PatternLayout`.

It turns out that the `OpenSearchJsonLayout` is mostly a wrapper around `PatternLayout` anyway, but I was thinking of adding a parameter to turn off the newlines in stacktraces. Looks like @svenso already did that in https://github.com/opensearch-project/OpenSearch/pull/4783. 

I'm going to make an effort to revive that PR, so we can get that change in, since there are at least two of us affected.

**Comment by msfroh** [comment]
@KarstenSchnitter had a good follow-up to the Slack conversation, where he highlighted the potential risk of "JSON injection" with a `PatternLayout`. My reading of the log4j documentation is that the `%enc{<something>}{JSON}` part is supposed to take care of escaping any JSON characters in `<something>` that could change the JSON structure. (I'm definitely a log4j n00b, so I might be misunderstanding, though.)

It looks like my pattern above fails to encode the stacktrace itself. The tricky thing is that we're relying on the `","` part of the `"%throwable{separator(",")}"` expression to inject JSON structure (that is, we're closing the quotes for one stack frame, adding the comma list-separator, and opening the quotes for the next stack frame). So, while I haven't tried it, I'm guessing that  something like `%enc{{"%throwable{separator(",")}"}{JSON}` would escape the quotes that I was trying to put in. Anyway, fixing that pattern isn't the right solution -- we need to fix `OpenSearchJsonLayout` as in https://github.com/opensearch-project/OpenSearch/pull/4783.

**Comment by KarstenSchnitter** [comment]
I had a look at how stacktrace are generated in the main branch now. The stacktrace lines are correctly escaped using Jackson:

<https://github.com/opensearch-project/OpenSearch/blob/93ae8db31122b71bdbba311829e7e55d696cb0b2/server/src/main/java/org/opensearch/common/logging/JsonThrowablePatternConverter.java#L112-L115>

The original issue might be connected to the code a few lines above the escaping:

<https://github.com/opensearch-project/OpenSearch/blob/93ae8db31122b71bdbba311829e7e55d696cb0b2/server/src/main/java/org/opensearch/common/logging/JsonThrowablePatternConverter.java#L101-L110>

The StringJoiner adds hard newlines in the formatted messages. I think, this is the point, that @svenso is taking issue with.
