### ISSUE TITLE
[Searchable Snapshot] Recovery path not working

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#4778]
**Describe the bug**
A searchable snapshot index fails to be created if number of replicas is set to a value greater than zero.

**To Reproduce**
Edit [SearchableSnapshotIT](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java#L51) by adding `internalCluster().ensureAtLeastNumDataNodes(2);` and changing the `IndexMetadata.SETTING_NUMBER_OF_REPLICAS` setting value to `"1"`. The replica shard will be created using the recovery path and will encounter a failure with the translog:

```
[2022-10-13T15:13:06,502][WARN ][o.o.i.r.PeerRecoveryTargetService] [node_s1] error while reading global checkpoint from translog, resetting the starting sequence number from -2 to unassigned and recovering as if there are none
org.opensearch.index.translog.TranslogCorruptedException: translog from source [/private/var/folders/n4/c5knrs8j5cd_y5607fn0p3900000gs/T/org.opensearch.snapshots.SearchableSnapshotIT_7963C1AD002894AF-001/tempDir-002/node_s1/nodes/0/indices/7FHBsKpiSNOO_UD1vxIKXA/0/translog/translog.ckp] is corrupted
	at org.opensearch.index.translog.Checkpoint.read(Checkpoint.java:210) ~[classes/:?]
	at org.opensearch.index.translog.Translog.readCheckpoint(Translog.java:1934) ~[classes/:?]
	at org.opensearch.index.translog.Translog.readCheckpoint(Translog.java:1952) ~[classes/:?]
	at org.opensearch.index.translog.Translog.readGlobalCheckpoint(Translog.java:1947) ~[classes/:?]
	at org.opensearch.indices.recovery.PeerRecoveryTargetService.getStartRecoveryRequest(PeerRecoveryTargetService.java:324) [classes/:?]
	at org.opensearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:251) [classes/:?]
	at org.opensearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:599) [classes/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) [classes/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Expected behavior**
The index should be created and the integration test should pass when modified as described above.

**Comment by andrross** [comment]
I think there are just two places to update to fix this:

1. In [PeerRecoveryTargetService#doRecovery](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java#L247-L257), do not verify the translog if this is a searchable snapshot (similar to the remote translog case).
2. In [RecoveryTarget#cleanFiles](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java#L358-L361), reuse the translog UUID from the store if this is a searchable snapshot index (similar to the segrep case).
