### ISSUE TITLE
[BUG] org.opensearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testQueryFiltering test failure

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#4789]
**Describe the bug**
A test failure, possibly flakey - Noticed with #4786 

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testQueryFiltering" -Dtests.seed=31AC51DE66176DE -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nl-BE -Dtests.timezone=America/Boa_Vista -Druntime.java=17
```

**Expected behavior**
- Test should pass.

**Plugins**
- None

**Screenshots**
```
org.opensearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests > testQueryFiltering FAILED
    java.lang.AssertionError: 
    Expected: within <10.0> percent of <125.0>
         but: was <111.1025641025641>
        at __randomizedtesting.SeedInfo.seed([31AC51DE66176DE:C77329D1892D88C7]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.lambda$testQueryFiltering$11(MedianAbsoluteDeviationAggregatorTests.java:154)
        at org.opensearch.search.aggregations.AggregatorTestCase.testCase(AggregatorTestCase.java:619)
        at org.opensearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testAggregation(MedianAbsoluteDeviationAggregatorTests.java:255)
        at org.opensearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testAggregation(MedianAbsoluteDeviationAggregatorTests.java:245)
        at org.opensearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testQueryFiltering(MedianAbsoluteDeviationAggregatorTests.java:149)
```

**Host/Environment (please complete the following information):**
 - Jenkins build/check environment

**Additional context**
N/A

**Comment by andrross** [comment]
A quick investigation suggests that when [this random call generates a value less than 21](https://github.com/opensearch-project/OpenSearch/blob/05a58192433f6e007ade61b4b4f21d0f068d50e0/server/src/test/java/org/opensearch/search/aggregations/metrics/MedianAbsoluteDeviationAggregatorTests.java#L241) for the random double, then the test will fail.

**Comment by SohamRatnaparkhi** [comment]
Hey @andrross, I would like to work on this issue. Can you assign it to me?

**Comment by andrross** [comment]
@SohamRatnaparkhi So changing the `20` to a `21` [in this test case](https://github.com/opensearch-project/OpenSearch/blob/05a58192433f6e007ade61b4b4f21d0f068d50e0/server/src/test/java/org/opensearch/search/aggregations/metrics/MedianAbsoluteDeviationAggregatorTests.java#L241) would likely fix the test failure, but it would be better (and is much harder :) ) to answer the question of _why_ a value below 21 causes the test to fail. It could be that the original test author just miscalculated a bit, or it could be a bug. Answering this question requires digging into exactly what the test is intending to do.

**Comment by SohamRatnaparkhi** [comment]
Okay, I will try and find out the reason too along with changing 20 to a 21.

**Comment by SohamRatnaparkhi** [comment]
Hi, tried searching in the code base as to why code breaks at value = 20. Anyways, So I am making a PR by changing 20 to 21.

**Comment by austintlee** [comment]
I can get it to fail with 21 and 22.  Any progress on this?  Can I take this on?

**Comment by andrross** [comment]
@austintlee For some reason GitHub does not allow me to add you in the assignee field, but please feel free to take this on. Thanks!

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/OpenSearch/pull/7317
