### ISSUE TITLE
[BUG] Unable to opensearch-plugin install when plugin repo does not contain .zip of plugin

### ISSUE THREAD

**Issue by sbabigian** [opensearch-project/OpenSearch#4823]
**Describe the bug**
When trying to install a plugin that does not have a .zip of the plugin in [the maven repo](https://repo1.maven.org/maven2/org/opensearch/plugin/ingest-user-agent/2.3.0/), it will not install as expected. 

**To Reproduce**
1. Run `./bin/opensearch-plugin install org.opensearch.plugin:ingest-user-agent:2.3.0`
2. Receive the following 404 error: `Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/org/opensearch/plugin/ingest-user-agent/2.3.0/ingest-user-agent-2.3.0.zip`

**Expected behavior**
According to [the docs](https://opensearch.org/docs/1.1/opensearch/install/plugins/#install-a-plugin) and the cli help, you can pass a maven repo uri to `opensearch-plugin install`. That plugin needs to be a .zip file (according to the cli help). The only files available [in the repo](https://repo1.maven.org/maven2/org/opensearch/plugin/ingest-user-agent/2.3.0/) are .jar and .pom files. 

**Plugins**
Default.

**My console output**
```
./bin/opensearch-plugin install org.opensearch.plugin:ingest-user-agent:2.3.0
-> Installing org.opensearch.plugin:ingest-user-agent:2.3.0
-> Downloading org.opensearch.plugin:ingest-user-agent:2.3.0 from maven central
-> Failed installing org.opensearch.plugin:ingest-user-agent:2.3.0
-> Rolling back org.opensearch.plugin:ingest-user-agent:2.3.0
-> Rolled back org.opensearch.plugin:ingest-user-agent:2.3.0
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/org/opensearch/plugin/ingest-user-agent/2.3.0/ingest-user-agent-2.3.0.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.opensearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:455)
	at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:532)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:326)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:272)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

**Host/Environment (please complete the following information):**
 - OS: Debian
 - Version: 11

**Comment by sbabigian** [comment]
I believe I have just learned that `ingest-user-agent` is bundled as a module, so it needn't be installed as a plugin. For anyone in the future, you can see existing modules in the `modules/` dir.

Would be great to see some feedback from `opensearch-plugin install` that says something like: `Is the plugin you're trying to install already a bundled module?`

**Comment by saratvemulapalli** [comment]
Thanks @sbabigian are you open for contributing this change?
