### ISSUE TITLE
[BUG] Fluent-bit simple post to opensearch throws 'not an ssl/tls record' error

### ISSUE THREAD

**Issue by moorthi07** [opensearch-project/OpenSearch#4864]
Case 1:
/fluent-bit/bin/fluent-bit -i cpu -t cpu -o http -p Host=192.168.64.9 -p Port=9200 -p uri /log/ingest -m * -p Format json tls on
fbit Log:
[2022/10/20 21:01:26] [error] [http_client] broken connection to 192.168.64.9:9200 ?

[2022/10/20 21:01:26] [error] [output:http:http.0] could not flush records to 192.168.64.9:9200 (http_do=-1)

[2022/10/20 21:01:26] [ warn] [engine] failed to flush chunk '1-1666299685.592007836.flb', retry in 9 seconds: task_id=0, input=cpu.0 > output=http.0 (out_id=0)

OS log:
2022-10-20T21:02:25.615497392Z Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 504f5354202f20485454502f312e310d0a486f73743a203139322e3136382e36342e393a393230300d0a436f6e74656e742d4c656e6774683a203138390d0a436f6e74656e742d547970653a206170706c69636174696f6e2f6d73677061636b0d0a557365722d4167656e743a20466c75656e742d4269740d0a0d0a92d7006351b75a25d1ead889a56370755f70cb0000000000000000a6757365725f70cb0000000000000000a873797374656d5f70cb0000000000000000aa637075302e705f637075cb0000000000000000ab637075302e705f75736572cb0000000000000000ad637075302e705f73797374656dcb0000000000000000aa637075312e705f637075cb0000000000000000ab637075312e705f75736572cb0000000000000000ad637075312e705f73797374656dcb0000000000000000

2022-10-20T21:02:25.615531392Z at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1215) ~[netty-handler-4.1.79.Final.jar:4.1.79.Final]

2022-10-20T21:02:25.615561092Z at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.79.Final.jar:4.1.79.Final]

2022-10-20T21:02:25.615590892Z at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]

2022-10-20T21:02:25.615629892Z at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]

2022-10-20T21:02:25.615673292Z ... 16 more

**Comment by dblock** [comment]
https://docs.fluentbit.io/manual/v/1.0/configuration/tls_ssl says to turn on TLS it's `-p tls=on -p tls.verify=off`, that doesn't seem to match the above command line?

**Comment by moorthi07** [comment]
Tried all permutation combinations already. Bye the way -p is for plugin parameter and tls is general config parameter (refer:  https://docs.fluentbit.io/manual/v/1.0/output/http)

**Comment by dblock** [comment]
I assume `curl` works to your OpenSearch instance? `curl -XGET --insecure https://192.168.64.9:9200`

**Comment by moorthi07** [comment]
Good suggestion. Tried
 curl -XGET --insecure https://192.168.64.9:9200
returns :
Unauthorized

Any ways to add credentials in curl or opensearch plugin for fbit?

**Comment by dblock** [comment]
Reading https://docs.fluentbit.io/manual/pipeline/outputs/opensearch it says `Http_User` and `http_Passwd`? Set those to `admin` and `admin`?

**Comment by moorthi07** [comment]
yes . I found that . I get ,
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argum>
Oct 21 03:24:06 docker-dev fluent-bit[3707]:

**Comment by dblock** [comment]
Ok, this is a new problem: OpenSearch 2.x deprecated the whole `_type` business, so this is a version compatibility problem. I would do the following:

1. Ensure you got latest fluentbit.
2. Try with OpenSearch 1.x, just to confirm.
3. Open an issue with Fluentbit for OpenSearch 2.x compatibility if such thing doesn't exist (e.g. by using a newer version).

**Comment by moorthi07** [comment]
Same thought here. Great. Thx.
Did you let know the fluent-bit team as well!

**Comment by moorthi07** [comment]
Also this doc and relevant git repo need to be updated.
https://opensearch.org/docs/latest/observability-plugin/log-analytics/

**Comment by dblock** [comment]
@moorthi07 Care to contribute? That's https://github.com/opensearch-project/documentation-website

**Comment by moorthi07** [comment]
Sure. I will update after testing its all working.
