### ISSUE TITLE
[BUG] PitIT.testDeleteAllAndListAllPits test failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#5030]
See failure here: https://build.ci.opensearch.org/job/gradle-check/6141/consoleFull

Not reproducible.

FYI @bharath-techie this looks like a test you recently introduced.

```
REPRODUCE WITH: ./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.opensearch.client.PitIT.testDeleteAllAndListAllPits" -Dtests.seed=3700C98642C555AA -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-CN -Dtests.timezone=Greenwich -Druntime.java=17

org.opensearch.client.PitIT > testDeleteAllAndListAllPits FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([3700C98642C555AA:7FE4D212C031630F]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.client.PitIT.testDeleteAllAndListAllPits(PitIT.java:128)
```

**Comment by andrross** [comment]
Looks like this was fixed but not backported: https://github.com/opensearch-project/OpenSearch/pull/4632

**Comment by andrross** [comment]
Backports done

**Comment by andrross** [comment]
Reopening as this has failed again: https://github.com/opensearch-project/OpenSearch/pull/8901#issuecomment-1652715751

```
REPRODUCE WITH: ./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.opensearch.client.PitIT.testDeleteAllAndListAllPits" -Dtests.seed=9165726883A8686F -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-AE -Dtests.timezone=Africa/Asmera -Druntime.java=20

org.opensearch.client.PitIT > testDeleteAllAndListAllPits FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=686, name=httpclient-dispatch-2, state=RUNNABLE, group=TGRP-PitIT]
        at __randomizedtesting.SeedInfo.seed([9165726883A8686F:D98169FC015C5ECA]:0)

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([9165726883A8686F]:0)
            at org.junit.Assert.fail(Assert.java:87)
            at org.junit.Assert.assertTrue(Assert.java:42)
            at org.junit.Assert.assertTrue(Assert.java:53)
            at org.opensearch.client.PitIT$2.onResponse(PitIT.java:118)
            at org.opensearch.client.PitIT$2.onResponse(PitIT.java:114)
```

**Comment by shwetathareja** [comment]
Failed here as well - https://build.ci.opensearch.org/job/gradle-check/22214/

**Comment by ketanv3** [comment]
Another occurrence: https://build.ci.opensearch.org/job/gradle-check/23442/

**Comment by Gaganjuneja** [comment]
https://build.ci.opensearch.org/job/gradle-check/23719/

**Comment by shwetathareja** [comment]
Failed here again - https://build.ci.opensearch.org/job/gradle-check/28293/

**Comment by peternied** [comment]
Fixed in https://github.com/opensearch-project/OpenSearch/pull/10946
