### ISSUE TITLE
[BUG][Searchable Snapshot] Failed to run 'range' query in a large index with error "SearchPhaseExecutionException: all shards failed" through OpenSearch-Benchmark

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#5172]
**Describe the bug**
The bug occurs when running benchmark for Searchable Snapshot feature, through [OpenSearch-Benchmark](https://github.com/opensearch-project/opensearch-benchmark) tool. Appears in the current `2.4` branch (https://github.com/opensearch-project/OpenSearch/commits/2.4?until=2022-11-08).
For an index that backed by remote snapshot, which with a large amount of data, `range` query performed on the index will take a long time and finally failed.

Take the queries that used in "[nyc_taxis](https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis)" workload of OpenSearch-Benchmark as an example:
The query with 0 error rate (succeeded): "[default](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis/operations/default.json#L29-L36)", "[distance_amount_agg](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis/operations/default.json#L52-L72)"
The query with 100% error rate: "[range](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis/operations/default.json#L37-L50)", "[autohisto_agg](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis/operations/default.json#L74-L96)" , "[date_histogram_agg](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis/operations/default.json#L98-L121)"
The failed queries are all in the type of `range`.

**To Reproduce**
The bug can be reproduced by executing performance test by OpenSearch-Benchmark tool.

Steps to run benchmark with Searchable Snapshot feature: https://github.com/opensearch-project/OpenSearch/issues/4797#issuecomment-1301606437

Rough procedures of the benchmark tool:
1. assemble OpenSearch version 2.4.0 from source
2. enable the feature flag for Searchable Snapshot
3. start an OpenSearch node
4. ingest `nyc_taxis` data to an index
5. create a snapshot repository
6. create a snapshot for the index.
7. delete the index
8. restore the snapshot, with storage type "remote_snapshot" to use Searchable Snapshot feature.
9. execute some types of query, such as `range` query

The console output of OpenSearch when executing `range` query:
(https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis/operations/default.json#L37-L50)
```
[2022-11-09T00:25:00,313][WARN ][r.suppressed             ] [ip-172-31-15-168] path: /nyc_taxis/_search, params: {index=nyc_taxis}
org.opensearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:661) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:371) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:696) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:469) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:293) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:753) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.transport.TransportService$6.handleException(TransportService.java:759) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1379) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1493) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1467) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:79) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:71) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:70) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opensearch.tasks.TaskCancelledException: cancelled task with reason: channel closed
	at org.opensearch.search.query.QueryPhase.lambda$executeInternal$1(QueryPhase.java:269) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.internal.ContextIndexSearcher$MutableQueryTimeout.checkCancelled(ContextIndexSearcher.java:423) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.internal.ExitableDirectoryReader$ExitablePointTree.visitDocIDs(ExitableDirectoryReader.java:260) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.apache.lucene.index.PointValues.intersect(PointValues.java:350) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.index.PointValues.intersect(PointValues.java:357) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.index.PointValues.intersect(PointValues.java:357) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.index.PointValues.intersect(PointValues.java:357) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.index.PointValues.intersect(PointValues.java:357) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.index.PointValues.intersect(PointValues.java:357) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.index.PointValues.intersect(PointValues.java:337) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.search.PointRangeQuery$1$4.get(PointRangeQuery.java:343) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.search.PointRangeQuery$1.scorer(PointRangeQuery.java:372) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:166) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.apache.lucene.search.IndexOrDocValuesQuery$1.bulkScorer(IndexOrDocValuesQuery.java:146) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.opensearch.search.internal.ContextIndexSearcher$1.bulkScorer(ContextIndexSearcher.java:325) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:276) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:250) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:519) ~[lucene-core-9.4.1.jar:9.4.1 810817993e0956e63e29906e78a245949501b77d - ivera - 2022-10-20 15:29:24]
	at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:349) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWithCollector(QueryPhase.java:443) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:432) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:275) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:152) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:530) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:594) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:563) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
	... 8 more
```

**Expected behavior**
No error occurs when searching data stored in an index that backed by remote snapshot.

**Plugins**
repository-s3

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**
curl command to run a range query:
``` shell
curl -XGET http://localhost:9200/nyc_taxis/_search\?pretty --header 'Content-Type: application/json' -d '{
"query": {
          "range": {
            "total_amount": {
              "gte": 5,
              "lt": 15
            }
          }
        }
}'
```

**Comment by tlfeng** [comment]
It's not a bug. Currently Searchable Snapshot is an experimental feature, it lacks optimization for the search speed. I will update more detail.

**Comment by tlfeng** [comment]
It's not a bug. Currently Searchable Snapshot is an experimental feature, it lacks optimization for the search speed. I will update more detail.
