### ISSUE TITLE
[BUG] ShardIndexingPressureIT.testShardIndexingPressureTrackingDuringBulkWrites failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#5176]
Not reproducible:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.index.ShardIndexingPressureIT.testShardIndexingPressureTrackingDuringBulkWrites" -Dtests.seed=567CA44C57BDC19B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-Latn-ME -Dtests.timezone=Pacific/Palau -Druntime.java=19

org.opensearch.index.ShardIndexingPressureIT > testShardIndexingPressureTrackingDuringBulkWrites FAILED
    java.lang.AssertionError: 
    Expected: <22616L>
         but: was <22954L>
        at __randomizedtesting.SeedInfo.seed([567CA44C57BDC19B:DC58B8B44B77E953]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.index.ShardIndexingPressureIT.testShardIndexingPressureTrackingDuringBulkWrites(ShardIndexingPressureIT.java:209)
```

**Comment by gbbafna** [comment]
@shourya035 is looking into this.
