### ISSUE TITLE
How to use esrally test the performance of opensearch[BUG]

### ISSUE THREAD

**Issue by opencmit1** [opensearch-project/OpenSearch#5213]
How to test the performance of opensearch？
I used the esrally tool to test the performance of opensearch, and found it unavailable. The official website suggested using esrally, but it could not be used. The error screenshot is as follows:
[suwei@tdocker ~]$ esrally race \
>   --track=geonames \
>   --target-hosts=192.168.1.200:20001 \
>   --pipeline=benchmark-only \
>   --track-params="number_of_shards:3, number_of_replicas:1" \
>   --user-tag="version:ARM_4C16G_1T*3" \
>   --client-options="basic_auth_user:'admin', basic_auth_password:'admin'"

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Race id is [dfb73830-92fc-484f-9502-eb37f3d01d13]
[ERROR] Cannot race. Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/esrally/actor.py", line 92, in guard
    return f(self, msg, sender)
  File "/usr/local/python3/lib/python3.8/site-packages/esrally/racecontrol.py", line 110, in receiveMsg_Setup
    self.coordinator.setup(sources=msg.sources)
  File "/usr/local/python3/lib/python3.8/site-packages/esrally/racecontrol.py", line 186, in setup
    distribution_version = mechanic.cluster_distribution_version(self.cfg)
  File "/usr/local/python3/lib/python3.8/site-packages/esrally/mechanic/mechanic.py", line 280, in cluster_distribution_version
    client.wait_for_rest_layer(es)
  File "/usr/local/python3/lib/python3.8/site-packages/esrally/client.py", line 299, in wait_for_rest_layer
    es.cluster.health(wait_for_nodes=">={}".format(expected_node_count))
  File "/usr/local/python3/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/elasticsearch/client/cluster.py", line 66, in health
    return self.transport.perform_request(
  File "/usr/local/python3/lib/python3.8/site-packages/elasticsearch/transport.py", line 413, in perform_request
    _ProductChecker.raise_error(self._verified_elasticsearch)
  File "/usr/local/python3/lib/python3.8/site-packages/elasticsearch/transport.py", line 630, in raise_error
    raise UnsupportedProductError(message)
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product

**Comment by minalsha** [comment]
@opencmit1  esrally is an Elasticsearch product. For OpenSearch, we use OpenSearch Benchmark. Please see the blog on this: https://opensearch.org/blog/update/2021/12/introducing-opensearch-benchmark/.
