### ISSUE TITLE
Can revert of "Cluster manager task throttling feature" be forward ported to 2.x and main?

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/OpenSearch#5287]
We are seeing failure for k-NN of backwards compatibility tests (2.1-2.5): https://github.com/opensearch-project/k-NN/actions/runs/3475055465/jobs/5824919899. 

```
> Task :qa:rolling-upgrade:testAgainstTwoThirdsUpgradedCluster

org.opensearch.knn.bwc.IndexingIT > testKNNDefaultIndexSettings FAILED
    org.opensearch.client.ResponseException: method [PUT], host [http://[::1]:33417], URI [_cluster/settings], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"illegal value can't update [cluster_manager.throttling.thresholds.] from [{}] to [{}]"}],"type":"illegal_argument_exception","reason":"illegal value can't update [cluster_manager.throttling.thresholds.] from [{}] to [{}]","caused_by":{"type":"illegal_argument_exception","reason":"All the nodes in cluster should be on version later than or equal to 2.4.0"}},"status":400}
        at __randomizedtesting.SeedInfo.seed([D1CA7E7E74CEB5B:E996EB0D8D75EE2B]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:345)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.knn.KNNRestTestCase.updateClusterSettings(KNNRestTestCase.java:510)
        at app//org.opensearch.knn.KNNRestTestCase.clearCache(KNNRestTestCase.java:678)
        at app//org.opensearch.knn.KNNRestTestCase.cleanUpCache(KNNRestTestCase.java:134)
        at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

I believe changes causing this were reverted for 2.4: https://github.com/opensearch-project/OpenSearch/pull/5203. Can this revert be forward ported to 2.x and main?

**Comment by Bukhtawar** [comment]
cc: @dhwanilpatel

**Comment by jmazanec15** [comment]
@Bukhtawar @dhwanilpatel Any update on this? This is blocking our CI for k-NN. Instead of fixing in #5305, can we revert the change in 2.x and main so that we are unblocked faster? We have several PRs currently blocked on this.

cc: @vamshin

**Comment by dhwanilpatel** [comment]
@jmazanec15 we have merged fix in both main and 2.x. Let us know if you still face any issue in CI.

**Comment by jmazanec15** [comment]
Thanks!
