### ISSUE TITLE
RestHighLevelClient#bulk error: [org.opensearch.common.ParsingException: Failed to parse object: expecting field with name [error] but found [message]]

### ISSUE THREAD

**Issue by jainankitk** [opensearch-project/OpenSearch#545]
**Describe the bug**
See the following exception for few request on the cluster:

```
07 Dec 2020 23:17:14,184 [ERROR] (main) com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor:228: Caught an exception while processing an event
org.opensearch.OpenSearchStatusException: Unable to parse response body
at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1686) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:477) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.indexBulkRequest(RodeoDataStreamProcessor.java:161) ~[OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.indexBulkRequestByPod(RodeoDataStreamProcessor.java:124) ~[OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.lambda$processDynamoDBRecordByPods$0(RodeoDataStreamProcessor.java:97) ~[OBRodeoLambda-1.0.jar:?]
at java.util.HashMap.forEach(HashMap.java:1289) [?:1.8.0_201]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.processDynamoDBRecordByPods(RodeoDataStreamProcessor.java:97) [OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.processDynamoDBRecord(RodeoDataStreamProcessor.java:81) [OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.handler.KinesisEventForwarder.handleRequest(KinesisEventForwarder.java:52) [OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.handler.KinesisEventForwarder.handleRequest(KinesisEventForwarder.java:21) [OBRodeoLambda-1.0.jar:?]
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
Suppressed: org.opensearch.common.ParsingException: Failed to parse object: expecting field with name [error] but found [message]
at org.opensearch.common.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:50) ~[opensearch-7.1.1.jar:7.1.1]
at org.opensearch.opensearchException.failureFromXContent(opensearchException.java:587) ~[opensearch-7.1.1.jar:7.1.1]
at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[opensearch-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1706) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1683) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:477) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.indexBulkRequest(RodeoDataStreamProcessor.java:161) ~[OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.indexBulkRequestByPod(RodeoDataStreamProcessor.java:124) ~[OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.lambda$processDynamoDBRecordByPods$0(RodeoDataStreamProcessor.java:97) ~[OBRodeoLambda-1.0.jar:?]
at java.util.HashMap.forEach(HashMap.java:1289) [?:1.8.0_201]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.processDynamoDBRecordByPods(RodeoDataStreamProcessor.java:97) [OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.kinesis.RodeoDataStreamProcessor.processDynamoDBRecord(RodeoDataStreamProcessor.java:81) [OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.handler.KinesisEventForwarder.handleRequest(KinesisEventForwarder.java:52) [OBRodeoLambda-1.0.jar:?]
at com.amazon.obrodeolambda.lambda.handler.KinesisEventForwarder.handleRequest(KinesisEventForwarder.java:21) [OBRodeoLambda-1.0.jar:?]
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
Caused by: org.opensearch.client.ResponseException: method [POST], host [https://vpc-ob-rodeo-es-iad-prod-pod9-ko5hju3dh4ehuwlggiqjn2pdoi.us-east-1.es.amazonaws.com], URI [/_bulk?timeout=1m], status line [HTTP/1.1 500 Server Error]
{"message":null}
at org.opensearch.client.RestClient.convertResponse(RestClient.java:260) ~[opensearch-rest-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestClient.performRequest(RestClient.java:238) ~[opensearch-rest-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestClient.performRequest(RestClient.java:212) ~[opensearch-rest-client-7.1.1.jar:7.1.1]
at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[opensearch-rest-high-level-client-7.1.1.jar:7.1.1]
... 18 more

```

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by itiyamas** [comment]
Can you clearly mention what is the client version that you are using here? 
A clear set of steps to reproduce this error would also help!

**Comment by dblock** [comment]
I am going to close this. @jainankitk if you can still reproduce this in OpenSearch 1.0 please provide more detail on how.
