### ISSUE TITLE
[BUG] OpenSearch failed to start cluster on 1.3.7 Windows

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch#5470]
[BUG] OpenSearch failed to start cluster on 1.3.7 Windows

https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.7/6644/windows/x64/zip/dist/opensearch/opensearch-1.3.7-windows-x64.zip
(Include security plugin)

See log:

```

PS C:\Users\Administrator\1.3.7\opensearch-1.3.7> .\opensearch-windows-install.bat
"OPENSEARCH_HOME: C:\Users\Administrator\1.3.7\opensearch-1.3.7"
"OPENSEARCH_PATH_CONF: C:\Users\Administrator\1.3.7\opensearch-1.3.7\config"
"Running Security Plugin Install Demo Configuration"
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************

OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **

Basedir: C:\Users\Administrator\1.3.7\opensearch-1.3.7\
OpenSearch install type: .zip on Windows_NT
OpenSearch config dir: C:\Users\Administrator\1.3.7\opensearch-1.3.7\config\
OpenSearch config file: C:\Users\Administrator\1.3.7\opensearch-1.3.7\config\opensearch.yml
OpenSearch bin dir: C:\Users\Administrator\1.3.7\opensearch-1.3.7\bin\
OpenSearch plugins dir: C:\Users\Administrator\1.3.7\opensearch-1.3.7\plugins\
OpenSearch lib dir: C:\Users\Administrator\1.3.7\opensearch-1.3.7\lib\
Detected OpenSearch Version: 1.3.7.jar
Detected OpenSearch Security Version: 1.3.7.0.jar
### Success
### Execute this script now on all your nodes and then start all nodes
### OpenSearch Security will be automatically initialized.
### If you like to change the runtime configuration
### change the files in ../../../config/opensearch-security and execute:

C:\Users\Administrator\1.3.7\opensearch-1.3.7\plugins\opensearch-security\tools\securityadmin.bat -cd C:\Users\Administrator\1.3.7\opensearch-1.3.7\config\opensearch-security -icl -key C:\Users\Administrator\1.3.7\opensearch-1.3.7\config\kirk-key.pem -cert C:\Users\Administrator\1.3.7\opensearch-1.3.7\config\kirk.pem -cacert C:\Users\Administrator\1.3.7\opensearch-1.3.7\config\root-ca.pem -nhnv
### or run ./securityadmin_demo.bat
### To use the Security Plugin ConfigurationGUI
The system cannot find the file specified.
### [Ignore the SSL certificate warning because we installed self-signed demo certificates]
"Set KNN Dylib Path for Windows systems"
Start OpenSearch
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.002s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.002s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.opensearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:139)
        at org.opensearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:101)
        at org.opensearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:72)
        at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:152)
        at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:110)
PS C:\Users\Administrator\1.3.7\opensearch-1.3.7> java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
PS C:\Users\Administrator\1.3.7\opensearch-1.3.7>
```

Thanks.

**Comment by mch2** [comment]
We are missing some important backports to 1.3 - 

https://github.com/opensearch-project/OpenSearch/pull/5473 - fixes this specific issue.
https://github.com/opensearch-project/OpenSearch/pull/4362

**Comment by peterzhuamazon** [comment]
I confirm after above two PRs backported the issues have been fixed:
```

Administrator@<> MINGW64 ~
$ curl https://localhost:9200 -u admin:admin --insecure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   571  100   571    0     0   1075      0 --:--:-- --:--:-- --:--:--  1077{
  "name" : "EC2AMAZ-S5RJAB6",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "DIN1HdFHQjWNFotRGsOfUw",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.3.7",
    "build_type" : "zip",
    "build_hash" : "db18a0d5a08b669fb900c00d81462e221f4438ee",
    "build_date" : "2022-12-07T01:30:06.884244700Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

```

**Comment by peterzhuamazon** [comment]
Hi @xuezhou25 @mch2 please advice if there are more PRs required to merge.
Or this issue can be closed.

Thanks.

**Comment by minalsha** [comment]
Hi @peterzhuamazon , no more PRs are required to merge and this issue can be closed. Thanks
