### ISSUE TITLE
[BUG] Plugin installation fails due to jar hell

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/OpenSearch#5526]
**Describe the bug**
Plugin installation fails due to jar hell:
When executing the plugin install action on main of security repo, the process fails due to `Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-security due to jar hell`. It may relate to the new changes introduced by https://github.com/opensearch-project/OpenSearch/pull/5366.
``` 
-> Rolled back file:/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-security.zip
Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-security due to jar hell
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:681)
	at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:862)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:830)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:66)
Caused by: java.lang.IllegalStateException: jar hell!
class: com.fasterxml.jackson.annotation.JacksonAnnotation
jar1: /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-3.0.0-SNAPSHOT/lib/jackson-annotations-2.14.1.jar
jar2: /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-3.0.0-SNAPSHOT/plugins/.installing-158779103[190](https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/3662825779/jobs/6192193255#step:9:195)93454201/jackson-annotations-2.13.4.jar
	at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:314)
	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:213)
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:679)
	... 11 more
```

**To Reproduce**
1. Run integration test on security repo
2. This error will happen during the step of download and install security plugin into core

**Expected behavior**
The plugin can be successfully installed into core

**Plugins**
Security plugin

**Host/Environment (please complete the following information):**
GitHub Action

**Additional context**
The original log of this error: https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/3662825779/jobs/6192193255#step:9:178

**Comment by reta** [comment]
@RyanL1997 sadly this is because of https://github.com/opensearch-project/OpenSearch/commit/c6663fd7f4e74b3ed1b6ad70e758b3e6bd21f816, the cure - make `jackson-databind` and `jackson-annotations` runtime only dependency, fe https://github.com/opensearch-project/sql/pull/1159/files#diff-520f178549fabd7e74f5b1fedb7275a1434a2ac153fc49e0212455ceeef38e37R110

**Comment by RyanL1997** [comment]
Hi @reta, thanks for the confirmation! We will implement a fix for that.

**Comment by RyanL1997** [comment]
Closing this issue according to the above fixes. Thanks for all the support!
