### ISSUE TITLE
[BUG] Use of EC TLS key results in NoSuchMethodError processing the pem

### ISSUE THREAD

**Issue by jimsnab** [opensearch-project/OpenSearch#5587]
**Describe the bug**
Set https TLS to use a cert generated with EC. Upon startup, opensearch will crash in bouncycastle. (May not be opensearch's fault but perhaps version dependency issue or dependency bug.)

**To Reproduce**
1. Create a TLS certificate that uses an Elliptic Curve key
2. Store the cert in a kubesecret in the namespace to hold opensearch
3. Create Helm values.yaml. Workarounds are required to get past Java access denied issue. The `opensearch.yaml` is mostly defaults but since individual setting control is lacking, it all has to be specified.

```
extraVolumes:
  - name: certificates-data
    emptyDir: {}

  - name: opensearch-certs
    secret:
      defaultMode: 0644
      secretName: "my_tls_secret_name"

extraInitContainers:
  - name: prepcert
    image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
    imagePullPolicy: "IfNotPresent"
    command:
      - /bin/bash
      - -ec
      - |
        cp /certs/* /certs-copy
        chown -R 1000:1000 /certs-copy
    volumeMounts:
      - mountPath: /certs
        name: opensearch-certs
      - mountPath: /certs-copy
        name: certificates-data

extraVolumeMounts:
  - name: certificates-data
    mountPath: /usr/share/opensearch/config/certs

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    plugins:
      security:
        ssl:
          transport:
            pemcert_filepath: esnode.pem
            pemkey_filepath: esnode-key.pem
            pemtrustedcas_filepath: root-ca.pem
            enforce_hostname_verification: false
          # RELEVANT CHANGES HERE IN HTTP
          http:
            enabled: true
            pemcert_filepath: /usr/share/opensearch/config/certs/tls.crt
            pemkey_filepath: /usr/share/opensearch/config/certs/tls.key
            pemtrustedcas_filepath: /usr/share/opensearch/config/certs/root-ca-cert.pem
        allow_unsafe_democertificates: true
        allow_default_init_securityindex: true
        authcz:
          admin_dn:
            - CN=kirk,OU=client,O=client,L=test,C=de
        audit.type: internal_opensearch
        enable_snapshot_restore_privilege: true
        check_snapshot_restore_write_privileges: true
        restapi:
          roles_enabled: ["all_access", "security_rest_api_access"]
        system_indices:
          enabled: true
          indices:
            [
              ".opendistro-alerting-config",
              ".opendistro-alerting-alert*",
              ".opendistro-anomaly-results*",
              ".opendistro-anomaly-detector*",
              ".opendistro-anomaly-checkpoints",
              ".opendistro-anomaly-detection-state",
              ".opendistro-reports-*",
              ".opendistro-notifications-*",
              ".opendistro-notebooks",
              ".opendistro-asynchronous-search-response*",
            ]
    ######## End OpenSearch Security Demo Configuration ########
```

4. Deploy the Helm chart
5. Look at the container log of opensearch and notice the error

**Expected behavior**
ECDSA PEM properly processed

**Plugins**
n/a

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
 - OS: Kubernetes on Google Cloud 
 - Version 1.23.13-gke.900

**Additional context**
Stack:

```
uncaught exception in thread [main]                                                                                                                                          
java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]                                                              
Likely root cause: java.lang.NoSuchMethodError: 'org.bouncycastle.asn1.ASN1Object org.bouncycastle.asn1.sec.ECPrivateKey.getParametersObject()'                              
    at org.bouncycastle.openssl.PEMParser$ECDSAKeyPairParser.parse(Unknown Source)                                                                                           
    at org.bouncycastle.openssl.PEMParser$KeyPairParser.parseObject(Unknown Source)                                                                                          
    at org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)                                                                                                         
    at io.netty.handler.ssl.BouncyCastlePemReader.getPrivateKey(BouncyCastlePemReader.java:154)                                                                              
    at io.netty.handler.ssl.BouncyCastlePemReader.getPrivateKey(BouncyCastlePemReader.java:137)                                                                              
    at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1127)                                                                                                    
    at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:384)                                                                                         
    at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:120)                                                                                          
    at org.opensearch.security.ssl.DefaultSecurityKeyStore.buildSSLServerContext(DefaultSecurityKeyStore.java:899)                                                           
    at org.opensearch.security.ssl.DefaultSecurityKeyStore.initHttpSSLConfig(DefaultSecurityKeyStore.java:525)                                                               
    at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:262)                                                                   
    at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:177)                                                                          
    at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218)                                                                  
    at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:263)                                                                            
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                              
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)                                                       
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                               
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)                                                                                   
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)                                                                                             
    at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:781)                                                                                             
    at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:730)                                                                                             
    at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:532)                                                                                            
    at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195)                                                                                                 
    at org.opensearch.node.Node.<init>(Node.java:426)                                                                                                                        
    at org.opensearch.node.Node.<init>(Node.java:353)                                                                                                                        
    at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)                                                                                                       
    at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)                                                                                                          
    at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)                                                                                                           
    at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)                                                                                                         
    at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)                                                                                                      
    <<<truncated>>> 
```

**Comment by minalsha** [comment]
@davidlago @peternied  I think this would fall under Security radar. Any inputs from your end?
