### ISSUE TITLE
[BUG] OpenSearch 1.4 is non-trivial different from 1.3

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#5703]
**Describe the bug**
The Security plugin is cleaning up its 1.x branch by merging all its 1.3 changes that were missed during backports.  We are seeing jar hell errors when attempting to install the plugin against version 1.4 of OpenSearch.  I would not expect to see any build difference between these versions.

```
Error: Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-security due to jar hell
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:678)
	at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:857)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:825)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
Caused by: java.lang.IllegalStateException: jar hell!
class: com.fasterxml.jackson.dataformat.smile.PackageVersion
jar1: /home/runner/work/security/security/opensearch-1.4.0-SNAPSHOT/lib/jackson-dataformat-smile-2.14.1.jar
jar2: /home/runner/work/security/security/opensearch-1.4.0-SNAPSHOT/plugins/.installing-14354378[209](https://github.com/opensearch-project/security/actions/runs/3841239671/jobs/6541226088#step:8:214)95936419/jackson-dataformat-smile-2.14.1.jar
	at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:317)
	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:[212](https://github.com/opensearch-project/security/actions/runs/3841239671/jobs/6541226088#step:8:217))
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:676)
	... 11 more
```

Upon inspection of OpenSearch's branches, it appears there are sustainable differences between 1.3 and 1.x that need to be resolved, possibly being responsible for the jar hell error I am seeing.

```
git diff origin/1.3 origin/1.x --stat
...
 113 files changed, 2819 insertions(+), 785 deletions(-)
```

Can someone look into these difference and resolve them?

**Comment by saratvemulapalli** [comment]
@peternied jar hell is because of jackson bump in 1.x, you would either want to remove explicit dependency from security plugin or consume opensearch version. 

Also 1.x is expected to have quite a lot of changes because we have been releasing 1.3.x patches for quite a while (which are impacting CVEs) where as next minor has non-security fixes as well incase we would like to release 1.4.0 (at this point its very unlikely as 1.x is in maintenance mode)

```
jar1: /home/runner/work/security/security/opensearch-1.4.0-SNAPSHOT/lib/jackson-dataformat-smile-2.14.1.jar
jar2: /home/runner/work/security/security/opensearch-1.4.0-SNAPSHOT/plugins/.installing-14354378[209](https://github.com/opensearch-project/security/actions/runs/3841239671/jobs/6541226088#step:8:214)95936419/jackson-dataformat-smile-2.14.1.jar
```

**Comment by peternied** [comment]
> jar hell is because of jackson bump in 1.x[1], you would either want to remove explicit dependency from security plugin or consume opensearch version.

In the pull request this issue is coming from the only difference are the version numbers - the change that could create the jar hell issue should be in both opensearch 1.3 and opensearch 1.x, therefore security 1.3 should build, and if security 1.x is the same except for the version number it should also build.  Since these are not the case I am confused.

Could you check that OpenSearch 1.x has built into maven with the latest changes, and those changes are inclusive of everything in 1.3?

**Comment by saratvemulapalli** [comment]
> Could you check that OpenSearch 1.x has built into maven with the latest changes, and those changes are inclusive of everything in 1.3?

All changes in 1.3 are included in 1.x.
