### ISSUE TITLE
Windows Gradle check fails on 2.x.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#5716]
Nightly gradle checks have been consistently failing on Windows 2.x line.  Example: https://build.ci.opensearch.org/job/gradle-check/8810/#showFailuresLink.  Check should pass.

Failing Tests:
- [ ] [org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/70_response_filtering/Search results filtered using both includes and excludes filters}](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_70_response_filtering_Search_results_filtered_using_both_includes_and_excludes_filters_/)
- [ ] [org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.classMethod](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/classMethod/)
- [ ] [org.opensearch.action.admin.cluster.stats.ClusterStatsIT.testValuesSmokeScreen](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.action.admin.cluster.stats/ClusterStatsIT/testValuesSmokeScreen/)
- [ ] [org.opensearch.cluster.ClusterHealthIT.testHealthOnClusterManagerFailover](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.cluster/ClusterHealthIT/testHealthOnClusterManagerFailover/)
- [ ] [org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.cluster.allocation/AwarenessAllocationIT/testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness/)
- [ ] [org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT.testNodesRemovedAfterZoneDecommission_ClusterManagerNotInToBeDecommissionedZone](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.cluster.coordination/AwarenessAttributeDecommissionIT/testNodesRemovedAfterZoneDecommission_ClusterManagerNotInToBeDecommissionedZone/)
- [ ] [org.opensearch.cluster.node.DiscoveryNodeRoleIT.testExplicitlyHasAdditionalRoles](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.cluster.node/DiscoveryNodeRoleIT/testExplicitlyHasAdditionalRoles/)
- [ ] [org.opensearch.cluster.node.DiscoveryNodeRoleIT.testDefaultHasAdditionalRole](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.cluster.node/DiscoveryNodeRoleIT/testDefaultHasAdditionalRole/)
- [ ] [org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.search.backpressure/SearchBackpressureIT/testSearchShardTaskCancellationWithHighCpu/)
- [ ] [org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighHeapUsage](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.search.backpressure/SearchBackpressureIT/testSearchShardTaskCancellationWithHighHeapUsage/)

**Comment by saratvemulapalli** [comment]
Thanks @mch2 for opening this up. I'll take a look. 
Trying to look at the latest runs:

https://build.ci.opensearch.org/job/gradle-check/8899/
https://build.ci.opensearch.org/job/gradle-check/8897/

**Comment by saratvemulapalli** [comment]
Opened up an issue to get notified on failures: https://github.com/opensearch-project/OpenSearch/issues/5736

**Comment by mch2** [comment]
I've re-run these three and they all pass on Windows 10.
```
[org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.search.backpressure/SearchBackpressureIT/testSearchShardTaskCancellationWithHighCpu/)
 [org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighHeapUsage](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.search.backpressure/SearchBackpressureIT/testSearchShardTaskCancellationWithHighHeapUsage/)
[org.opensearch.action.admin.cluster.stats.ClusterStatsIT.testValuesSmokeScreen](https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.action.admin.cluster.stats/ClusterStatsIT/testValuesSmokeScreen/)
```

**Comment by minalsha** [comment]
https://build.ci.opensearch.org/job/gradle-check/8810/testReport/junit/org.opensearch.cluster/ClusterHealthIT/testHealthOnClusterManagerFailover/ -- test is passing on local as @vibrantvarun

**Comment by saratvemulapalli** [comment]
Update: Yaml tests are running fine in local, feels like the infrastructure is seeing problems when we run the whole suit together.

**Comment by Poojita-Raj** [comment]
Update - `org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT.testNodesRemovedAfterZoneDecommission_ClusterManagerNotInToBeDecommissionedZone` passing on local

**Comment by vibrantvarun** [comment]
All the tests are working fine on my local machine.

**Comment by mch2** [comment]
I've split apart check and run the following against 2.5 locally:

1. yamlRestTest - passes. (this occasionally fails when run with check because the suite times out after 30m. We can bump the timeout here or run it by itself)
2. :server:internalClusterTest - has ~2 failures per run, usually different tests.  When running the failed tests individually they pass.
3. internalClusterTest -x :server:internalClusterTest - passes. This is all the other internalClusterTests not in server project.
3. :server:test without internalClusterTests - passes
4. check without :server:test, internalClusterTest, yamlRestTest - passes (this includes bwc & everything else)

So :server:internalClusterTest is the issue right now.  On my last run the two tests failing were:
ClusterStatsIT. testValuesSmokeScreen
IndexStatsIT. testFilterCacheStats

I have also seen this test fail occasionally because it can't clean up - TranslogTransferManagerTests:

``
java.io.IOException: Could not remove the following files (in the order of attempts): C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753008-001.ckp: java.nio.file.AccessDeniedException: C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753008-001.ckp C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753008-001.tlog: java.nio.file.AccessDeniedException: C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753008-001.tlog C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753008-002.tlog: java.nio.file.AccessDeniedException: C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753008-002.tlog C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753009-001.ckp: java.nio.file.AccessDeniedException: C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753009-001.ckp C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753009-001.tlog: java.nio.file.AccessDeniedException: C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753009-001.tlog C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753009-002.tlog: java.nio.file.AccessDeniedException: C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001\translog-6958809543753753009-002.tlog C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001: java.nio.file.DirectoryNotEmptyException: C:\Users\Administrator\OpenSearch\server\build\testrun\test\temp\org.opensearch.index.translog.transfer.TranslogTransferManagerTests_E68AEF178E965295-001 at __randomizedtesting.SeedInfo.seed([E68AEF178E965295]:0) at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341) at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209) at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31) at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43) at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44) at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60) at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47) at org.junit.rules.RunRules.evaluate(RunRules.java:20) at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368) at java.base/java.lang.Thread.run(Thread.java:833)
``

**Comment by minalsha** [comment]
@mch2  Thank you for sharing the details above. What are the next steps post this analysis to achieve state of notification of tests failing and achieving a green CI?

**Comment by mch2** [comment]
I am no longer seeing the failures originally cut with this ticket.  
These the the test failures I see on manual runs:
- https://github.com/opensearch-project/OpenSearch/issues/5930
- https://github.com/opensearch-project/OpenSearch/issues/5923

These are also next steps from CI set up:
https://github.com/opensearch-project/opensearch-build-libraries/issues/113
https://github.com/opensearch-project/opensearch-build-libraries/issues/114

**Comment by minalsha** [comment]
@ryanbogan  could you please update on the status for below as mentioned by https://github.com/opensearch-project/OpenSearch/issues/5716#issuecomment-1402297697 : 

1. https://github.com/opensearch-project/OpenSearch/issues/5930
2. https://github.com/opensearch-project/OpenSearch/issues/5923

**Comment by mch2** [comment]
The reindex test exists on the 1.x line - https://github.com/opensearch-project/OpenSearch/blob/1.3/modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/90_remote.yml#L384

The TranslogTransferManagerTests are not in 1.x.

**Comment by kotwanikunal** [comment]
@mch2 I am assigning this issue to you. Please re-assign if you aren't looking into it anymore.

**Comment by minalsha** [comment]
@kotwanikunal  are these tests failing in recent nightly gradle checks for 2.x?

**Comment by kotwanikunal** [comment]
@minalsha I was assigned this issue when I was the release manager for 2.5 but @mch2 was looking into it. I just reassigned it to Marc for any further updates.
Let me check if there are any changes/updates.

**Comment by mch2** [comment]
I've updated the issue description with the remaining tests that are still failing.  We can close this issue once those are resolved.  We may encounter more failures on the path to green, once CI issues are resolved - https://github.com/opensearch-project/opensearch-build-libraries/issues/113

**Comment by scrawfor99** [comment]
Is this issue good to be closed?

**Comment by kotwanikunal** [comment]
I think so. Closing it out. @mch2 Please re-open if needed.
