### ISSUE TITLE
[BUG] OpenSearch 1.3.7 is not recognizing OPENSEARCH_PATH_CONF

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/OpenSearch#5738]
**Describe the bug**
I am a technical writer for the OpenSearch Project, tasked with crafting upgrade documentation.

As part of the process, I am standing up a small OS cluster in a VPC using EC2 instances. I used the following script when bootstrapping the EC2 instance:

```b
#!/bin/bash
sudo swapoff -a
echo -e 'vm.max_map_count=262144' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
wget https://artifacts.opensearch.org/releases/bundle/opensearch/1.3.7/opensearch-1.3.7-linux-x64.tar.gz
sudo tar -C /opt/ -xvf opensearch-1.3.7-linux-x64.tar.gz
sudo rm opensearch-1.3.7-linux-x64.tar.gz
wget https://artifacts.opensearch.org/releases/bundle/opensearch/2.4.1/opensearch-2.4.1-linux-x64.tar.gz
sudo tar -C /opt/ -xvf opensearch-2.4.1-linux-x64.tar.gz
sudo rm opensearch-2.4.1-linux-x64.tar.gz
sudo mkdir /etc/opensearch
sudo cp -r /opt/opensearch-1.3.7/config/* /etc/opensearch/
sudo chown -R ec2-user:ec2-user /etc/opensearch
echo -e '# ======================== OpenSearch Configuration =========================' | sudo tee /etc/opensearch/opensearch.yml
echo -e 'cluster.name: os-dev-cluster' | sudo tee -a /etc/opensearch/opensearch.yml
echo -e 'node.name: os-node-01' | sudo tee -a /etc/opensearch/opensearch.yml
echo -e 'bootstrap.memory_lock: true' | sudo tee -a /etc/opensearch/opensearch.yml
echo -e 'network.host: 0.0.0.0' | sudo tee -a /etc/opensearch/opensearch.yml
echo -e 'discovery.seed_hosts: ["10.0.1.101", "10.0.1.102", "10.0.1.103", "10.0.1.104"]' | sudo tee -a /etc/opensearch/opensearch.yml
echo -e 'cluster.initial_master_nodes: ["10.0.1.101", "10.0.1.102", "10.0.1.103", "10.0.1.104"]' | sudo tee -a /etc/opensearch/opensearch.yml
echo -e 'plugins.security.disabled: true' | sudo tee -a /etc/opensearch/opensearch.yml
sudo /opt/opensearch-1.3.7/bin/opensearch-plugin install --batch discovery-ec2
echo -e 'OPENSEARCH_PATH_CONF=/etc/opensearch' | sudo tee /etc/profile.d/script.sh
sudo reboot
```

After the host comes back online, I confirm that the variable is set:

```
[ec2-user@ip-10-0-1-101 bin]$ echo $OPENSEARCH_PATH_CONF
/etc/opensearch
```

However, you can see from the stack trace that OpenSearch is ignoring the environment variable...

```
[ec2-user@ip-10-0-1-101 bin]$ ./opensearch
[2023-01-06T20:52:47,714][INFO ][o.o.n.Node               ] [ip-10-0-1-101.us-west-2.compute.internal] version[1.3.7], pid[3929], build[tar/db18a0d5a08b669fb900c00d81462e221f4438ee/2022-12-07T22:59:20.186520Z], OS[Linux/5.10.157-139.675.amzn2.x86_64/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/11.0.17/11.0.17+8]
[2023-01-06T20:52:47,720][INFO ][o.o.n.Node               ] [ip-10-0-1-101.us-west-2.compute.internal] JVM home [/opt/opensearch-1.3.7/jdk], using bundled JDK [true]
[2023-01-06T20:52:47,721][INFO ][o.o.n.Node               ] [ip-10-0-1-101.us-west-2.compute.internal] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-5989015192751382868, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/opt/opensearch-1.3.7, -Dopensearch.path.conf=/opt/opensearch-1.3.7/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2023-01-06T20:52:48,931][WARN ][stderr                   ] [ip-10-0-1-101.us-west-2.compute.internal] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2023-01-06T20:52:48,932][WARN ][stderr                   ] [ip-10-0-1-101.us-west-2.compute.internal] SLF4J: Defaulting to no-operation (NOP) logger implementation
[2023-01-06T20:52:48,932][WARN ][stderr                   ] [ip-10-0-1-101.us-west-2.compute.internal] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2023-01-06T20:52:48,948][INFO ][o.o.s.s.t.SSLConfig      ] [ip-10-0-1-101.us-west-2.compute.internal] SSL dual mode is disabled
[2023-01-06T20:52:48,949][INFO ][o.o.s.OpenSearchSecurityPlugin] [ip-10-0-1-101.us-west-2.compute.internal] OpenSearch Config path is /opt/opensearch-1.3.7/config
[2023-01-06T20:52:49,215][INFO ][o.o.s.s.DefaultSecurityKeyStore] [ip-10-0-1-101.us-west-2.compute.internal] JVM supports TLSv1.3
[2023-01-06T20:52:49,217][INFO ][o.o.s.s.DefaultSecurityKeyStore] [ip-10-0-1-101.us-west-2.compute.internal] Config directory is /opt/opensearch-1.3.7/config/, from there the key- and truststore files are resolved relatively
[2023-01-06T20:52:49,329][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [ip-10-0-1-101.us-west-2.compute.internal] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.3.7.jar:1.3.7]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.3.7.jar:1.3.7]
Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:792) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.node.Node.<init>(Node.java:396) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.7.jar:1.3.7]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:783) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.node.Node.<init>(Node.java:396) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.7.jar:1.3.7]
	... 6 more
Caused by: org.opensearch.OpenSearchException: plugins.security.ssl.transport.keystore_filepath or plugins.security.ssl.transport.server.pemcert_filepath and plugins.security.ssl.transport.client.pemcert_filepath must be set if transport ssl is requested.
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:423) ~[?:?]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:259) ~[?:?]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:180) ~[?:?]
	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218) ~[?:?]
	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:253) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:783) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.node.Node.<init>(Node.java:396) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.7.jar:1.3.7]
	... 6 more
uncaught exception in thread [main]
java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
Likely root cause: OpenSearchException[plugins.security.ssl.transport.keystore_filepath or plugins.security.ssl.transport.server.pemcert_filepath and plugins.security.ssl.transport.client.pemcert_filepath must be set if transport ssl is requested.]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:423)
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:259)
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:180)
	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218)
	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:253)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:783)
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728)
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530)
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193)
	at org.opensearch.node.Node.<init>(Node.java:396)
	at org.opensearch.node.Node.<init>(Node.java:319)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
For complete error details, refer to the log at /opt/opensearch-1.3.7/logs/opensearch.log
```

When I pass the environment variable with the command to start OpenSearch, it succeeds:

```
[ec2-user@ip-10-0-1-101 bin]$ OPENSEARCH_PATH_CONF=/etc/opensearch ./opensearch
[2023-01-06T21:08:34,602][INFO ][o.o.n.Node               ] [os-node-01] version[1.3.7], pid[4158], build[tar/db18a0d5a08b669fb900c00d81462e221f4438ee/2022-12-07T22:59:20.186520Z], OS[Linux/5.10.157-139.675.amzn2.x86_64/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/11.0.17/11.0.17+8]
[2023-01-06T21:08:34,610][INFO ][o.o.n.Node               ] [os-node-01] JVM home [/opt/opensearch-1.3.7/jdk], using bundled JDK [true]
[2023-01-06T21:08:34,610][INFO ][o.o.n.Node               ] [os-node-01] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-256186444766481754, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/opt/opensearch-1.3.7, -Dopensearch.path.conf=/etc/opensearch, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2023-01-06T21:08:35,783][WARN ][stderr                   ] [os-node-01] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2023-01-06T21:08:35,783][WARN ][stderr                   ] [os-node-01] SLF4J: Defaulting to no-operation (NOP) logger implementation
[2023-01-06T21:08:35,784][WARN ][stderr                   ] [os-node-01] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2023-01-06T21:08:35,796][INFO ][o.o.s.s.t.SSLConfig      ] [os-node-01] SSL dual mode is disabled
[2023-01-06T21:08:35,798][WARN ][o.o.s.OpenSearchSecurityPlugin] [os-node-01] OpenSearch Security plugin installed but disabled. This can expose your configuration (including passwords) to the public.
```

**To Reproduce**
1. Download and unpack OpenSearch 1.3.7 tarball on EC2 instance to /opt/opensearch-1.3.7/
2. Move the config directory to `/etc/opensearch/` and chown to `ec2-user:ec2-user`
3. Set the config path `export OPENSEARCH_PATH_CONF=/etc/opensearch`
4. Confirm the environment variable `echo $OPENSEARCH_PATH_CONF`
5. Attempt to start the service `/opt/opensearch-1.3.7/bin/opensearch`

**Expected behavior**
OpenSearch should start successfully and read the configuration files from `/etc/opensearch`

**Plugins**
`discovery-ec2`

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux 2
 - Kernel: 5.10.157-139.675.amzn2.x86_64

**Additional context**
n/a

**Comment by JeffH-AWS** [comment]
Thanks! I apologize that the bash script is a little bare bones. I'm currently troubleshooting EC2 discovery and as I learn more about the process it seems there is some configuration missing from `opensearch.yml` such as `discovery.seed_providers: ec2`. I don't believe that has any impact on the issue though.

**Comment by saratvemulapalli** [comment]
@JeffH-AWS I dont think having mis-config in `opensearch.yml` is the problem. 

The first run has not picked up the env variable we could see from JVM args `-Dopensearch.path.conf=/opt/opensearch-1.3.7/config` which is set by `opensearch-env`
```
[2023-01-06T20:52:47,721][INFO ][o.o.n.Node               ] [ip-10-0-1-101.us-west-2.compute.internal] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-5989015192751382868, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/opt/opensearch-1.3.7, -Dopensearch.path.conf=/opt/opensearch-1.3.7/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
```

**Comment by saratvemulapalli** [comment]
`echo -e 'OPENSEARCH_PATH_CONF=/etc/opensearch'` doesn't set the variable. 
Probably you'd want to modify the script to `export OPENSEARCH_PATH_CONF=/etc/opensearch`

**Comment by JeffH-AWS** [comment]
@saratvemulapalli I know that doesn't set the variable. Adding it to `/etc/profile.d/script.sh` and rebooting the system does. Please look at the full commands I use.

**Comment by saratvemulapalli** [comment]
Ah that makes sense. I wonder why variable is not being picked up.
