### ISSUE TITLE
Autocut when on-merge gradle check fails.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#5799]
**Is your feature request related to a problem? Please describe.**
Many of the on-merge gradle checks shown [here](https://github.com/opensearch-project/OpenSearch/commits/main) are failing.  A green check is incorrectly appearing now even on runs where gradle check fails.

I suggest we autocut an issue on these failures so they can be looked at to determine if they should be treated as a flaky failure or if a larger issue was introduced.

**Comment by reta** [comment]
@mch2 interesting error observer with the GA [1]:

```
Run dblock/create-a-github-issue@v3
⬤  debug     Reading from file .github/ISSUE_TEMPLATE/failed_check.md
ℹ  info      Front matter for .github/ISSUE_TEMPLATE/failed_check.md is {
  title: '[AUTOCUT] Gradle Check Failure on push to {{ env.branch_name }}',
  labels: '>test-failure, bug'
}
⬤  debug     Templates compiled {
  body: 'Gradle check has failed on push of your commit 83dccad312faa7d9350ffa6672e51d02d36ad06f.\n' +
    'Please examine the workflow log [https://build.ci.opensearch.org/job/gradle-check/10777/.\n](https://build.ci.opensearch.org/job/gradle-check/10777/n)' +
    'Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?\n',
  title: '[AUTOCUT] Gradle Check Failure on push to ',
  labels: [ '>test-failure', 'bug' ]
}
ℹ  info      Creating new issue [AUTOCUT] Gradle Check Failure on push to 
✖  error     An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/ISSUE_TEMPLATE/failed_check.md!
✖  error     HttpError: Validation Failed: {"value":"SonalMahambrey1","resource":"Issue","field":"assignees","code":"invalid"} 
    at /home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:6038:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createAnIssue (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:37971:23)
Error: An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/ISSUE_TEMPLATE/failed_check.md!

Validation Failed: {"value":"SonalMahambrey1","resource":"Issue","field":"assignees","code":"invalid"}
```

[1] https://github.com/opensearch-project/OpenSearch/actions/runs/4114574598/jobs/7102120698
