### ISSUE TITLE
[BUG] [Dev Setup] Assertion failure while restoring an index from a remote store

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#5872]
**Describe the bug**
While restoring an index from remote store, following exception is thrown.

```
» Exception in thread "Attach Listener" Agent failed to start!
»  fatal error in thread [opensearch[runTask-0][clusterManagerService#updateTask][T#1]], exiting
»  java.lang.AssertionError: remote store recovery [r22xEsBpRZeDFT6ZK-N1KA]
»       at org.opensearch.cluster.routing.allocation.IndexMetadataUpdater.updateInSyncAllocations(IndexMetadataUpdater.java:205)
»       at org.opensearch.cluster.routing.allocation.IndexMetadataUpdater.applyChanges(IndexMetadataUpdater.java:145)
»       at org.opensearch.cluster.routing.allocation.RoutingAllocation.updateMetadataWithRoutingChanges(RoutingAllocation.java:269)
»       at org.opensearch.cluster.routing.allocation.AllocationService.buildResult(AllocationService.java:178)
»       at org.opensearch.cluster.routing.allocation.AllocationService.buildResultAndLogHealthChange(AllocationService.java:167)
»       at org.opensearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:511)
»       at org.opensearch.snapshots.RestoreService$1.execute(RestoreService.java:277)
»       at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:65)
»       at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:867)
»       at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:424)
»       at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:295)
»       at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:206)
»       at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:190)
»       at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:228)
»       at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747)
»       at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282)
»       at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
»       at java.base/java.lang.Thread.run(Thread.java:829)

```

***Assert statement which leads to exeception***
```
assert recoverySource instanceof RecoverySource.SnapshotRecoverySource : recoverySource;
```

**To Reproduce**
1. Follow this guide to create an index with remote store enabled - https://opensearch.org/docs/latest/opensearch/remote
2. When you restore the index from remote store, you get the above exception

**Expected behavior**
No exception should be raised and index restore should be successful.

**Comment by linuxpi** [comment]
From initial analysis, the instance of `recoverySource` is of type `RemoteStoreRecoverySource`, we should be able to fix this just by adding a OR condition for `RemoteStoreRecoverySource` in the assert.

**Comment by sachinpkale** [comment]
Thanks @linuxpi for reporting this.

**Comment by sachinpkale** [comment]
Fixed as part of https://github.com/opensearch-project/OpenSearch/pull/6067
