### ISSUE TITLE
[BUG] [Dev Setup] Assertion failure while deleting index with remote_store.enabled=true

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#5919]
**Describe the bug**

While deleting a remote store backed index in developer setup, following exception is thrown.

```
java.lang.AssertionError: shard [my-index-1][0] is not locked
	at __randomizedtesting.SeedInfo.seed([5CA33FB52BB9420E]:0)
	at org.opensearch.env.NodeEnvironment.deleteShardDirectoryUnderLock(NodeEnvironment.java:561)
	at org.opensearch.indices.IndicesService.deleteShardStore(IndicesService.java:1208)
	at org.opensearch.index.IndexService.onShardClose(IndexService.java:638)
	at org.opensearch.index.IndexService$StoreCloseListener.accept(IndexService.java:761)
	at org.opensearch.index.IndexService$StoreCloseListener.accept(IndexService.java:748)
	at org.opensearch.index.store.Store.closeInternal(Store.java:549)
	at org.opensearch.index.store.Store$1.closeInternal(Store.java:189)
	at org.opensearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:76)
	at org.opensearch.index.store.Store.decRef(Store.java:522)
	at org.opensearch.index.store.Store.close(Store.java:529)
	at org.opensearch.index.IndexService.closeShard(IndexService.java:619)
	at org.opensearch.index.IndexService.removeShard(IndexService.java:587)
	at org.opensearch.index.IndexService.close(IndexService.java:373)
	at org.opensearch.indices.IndicesService.removeIndex(IndicesService.java:1044)
	at org.opensearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:350)
	at org.opensearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:280)
	at org.opensearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:606)
	at org.opensearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:593)
	at org.opensearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:561)
	at org.opensearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:484)
	at org.opensearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:186)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747)
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282)
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sachinpkale** [comment]
Fixed in https://github.com/opensearch-project/OpenSearch/pull/5918
