### ISSUE TITLE
SearchWeightedRoutingIT.testSearchAggregationWithNetworkDisruption_FailOpenEnabled is flaky

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#5957]
See https://build.ci.opensearch.org/job/gradle-check/9665/

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchWeightedRoutingIT.testSearchAggregationWithNetworkDisruption_FailOpenEnabled" -Dtests.seed=4A8AE0253E5B26DF -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar -Dtests.timezone=Antarctica/Syowa -Druntime.java=19

org.opensearch.search.SearchWeightedRoutingIT > testSearchAggregationWithNetworkDisruption_FailOpenEnabled FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([4A8AE0253E5B26DF:BDF0C0BD22B9D3D6]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.search.SearchWeightedRoutingIT.assertSearchInAZ(SearchWeightedRoutingIT.java:553)
        at org.opensearch.search.SearchWeightedRoutingIT.testSearchAggregationWithNetworkDisruption_FailOpenEnabled(SearchWeightedRoutingIT.java:646)
```

@anshu1106 FYI, looks like this test was introduced fairly recently.

**Comment by gbbafna** [comment]
One more occurrence : https://github.com/opensearch-project/OpenSearch/pull/6378

**Comment by amkhar** [comment]
One more : https://build.ci.opensearch.org/job/gradle-check/16642/testReport/junit/org.opensearch.search/SearchWeightedRoutingIT/testSearchAggregationWithNetworkDisruption_FailOpenEnabled/
