### ISSUE TITLE
[BUG] TSVB fails to load in "edit" mode after upgrading from Opensearch 1.2 to 1.3

### ISSUE THREAD

**Issue by varunrao** [opensearch-project/OpenSearch#6006]
**Describe the bug**
We are using AWS Opensearch service. The initial upgrade was from Elasticsearch 7.10 to 1.2. The worked without any issues. We then upgraded to 1.3 and since then the TSVB visuals are failing to load in the "EDIT" mode. They work fine in the "display" mode.

Browser console shows the following error. I am using SerialDiff and custom script in my TSVB visual.

osd-ui-shared-deps.js:438 TypeError: Cannot read properties of undefined (reading 'links')
    at SerialDiffAgg (visTypeTimeseries.chunk.2.js:1:240120)
    at ua (osd-ui-shared-deps.js:438:59332)
    at Ms (osd-ui-shared-deps.js:438:104414)
    at gl (osd-ui-shared-deps.js:438:90018)
    at fl (osd-ui-shared-deps.js:438:89943)
    at ol (osd-ui-shared-deps.js:438:87291)
    at osd-ui-shared-deps.js:438:45733
    at t.unstable_runWithPriority (osd-ui-shared-deps.js:446:3462)
    at Hi (osd-ui-shared-deps.js:438:45442)
    at Gi (osd-ui-shared-deps.js:438:45678)

**Expected behavior**
The "Edit" mode should show up without any errors. 

**Plugins**
All default plugins that come with OpenSearch.

**Screenshots**

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1559391/214502922-52a86da4-7dc1-4025-8bd3-add8e0db323d.png">

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Version [e.g. 12.5]
 - Google Chrome: Version 109.0.5414.87

**Comment by dblock** [comment]
Is this reproducible in the open-source distribution? Have you opened a ticket with AWS support yet (if not, please do)?
