### ISSUE TITLE
[BUG] Flaky Test failure GeoTileGridIT.testGeoShapes

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#6054]
```
REPRODUCE WITH: ./gradlew ':modules:geo:internalClusterTest' --tests "org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT.testGeoShapes" -Dtests.seed=DCE20E20A42AFD34 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=und -Dtests.timezone=America/Yakutat -Druntime.java=19

org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT > testGeoShapes FAILED
    java.lang.AssertionError: Geotile 3/7/4 has wrong doc count  expected:<46> but was:<1>
        at __randomizedtesting.SeedInfo.seed([DCE20E20A42AFD34:365FB6EF2B56AE29]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT.testGeoShapes(GeoTileGridIT.java:78)
```

https://build.ci.opensearch.org/job/gradle-check/10078/consoleFull
https://github.com/opensearch-project/OpenSearch/pull/5898#issuecomment-1407128379

**Comment by mch2** [comment]
https://build.ci.opensearch.org/job/gradle-check/10076/

**Comment by minalsha** [comment]
Issue moved to [opensearch-project/geospatial #212](https://github.com/opensearch-project/geospatial/issues/212) via [**Zenhub**](https://www.zenhub.com/)
