### ISSUE TITLE
[BUG] Create Issue on Push Failure Failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6085]
See https://github.com/opensearch-project/OpenSearch/actions/runs/4041386235/jobs/6947907209

```
Run dblock/create-a-github-issue@v3
⬤  debug     Reading from file .github/ISSUE_TEMPLATE/failed_check.md
Error: a line break is expected at line 2, column 10:
    labels: >test-failure bug
             ^
✖  fatal     YAMLException: a line break is expected at line 2, column 10: 
    labels: >test-failure bug
             ^
    at generateError (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:8925:10)
    at throwError (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:8931:9)
    at readLineBreak (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:9115:5)
    at readBlockScalar (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:9592:5)
    at composeNode (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:10121:35)
    at readBlockMapping (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:9847:11)
    at composeNode (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:10117:12)
    at readDocument (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:10283:3)
    at loadDocuments (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:10346:5)
    at load (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:10372:19)
```

**Comment by andrross** [comment]
@mch2 FYI
