### ISSUE TITLE
[BUG] Opensearch version 1.2.4 fails  java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9

### ISSUE THREAD

**Issue by Yafaa** [opensearch-project/OpenSearch#6105]
**Describe the bug**
running opensearch 1.2.4 from docker-compose.yml file leads to error java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9

**To Reproduce**
1. Just use docker compose up with docker-compose.yml

**Expected behavior**
openseach should be running without errors

**Host/Environment (please complete the following information):**
 - OS:  Windows 10 Entreprise & Rancher Desktop 
 - Version:  Windows 10  & Rancher Desktop 1.6.2

**Additional context**

**docker-compose.yml file :**
```
version: "3.8"
services:
  opensearch-node:
    image: opensearchproject/opensearch:1.2.4
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_master_nodes=opensearch-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.ssl.http.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "127.0.0.1:${OPENSEARCH_NODE_PORT_HOST}:${OPENSEARCH_NODE_PORT_CONTAINER}"
      - "127.0.0.1:${OPENSEARCH_PERFORMANCE_ANALYZER_PORT_HOST}:${OPENSEARCH_PERFORMANCE_ANALYZER_PORT_CONTAINER}"
    networks:
      - pipeline-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    ports:
      - "127.0.0.1:${OPENSEARCH_DASHBOARD_PORT_HOST}:${OPENSEARCH_DASHBOARD_PORT_CONTAINER}"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node:${OPENSEARCH_NODE_PORT_CONTAINER}"]'
    networks:
      - pipeline-net

volumes:
  opensearch-data1:

networks:
  pipeline-net:
```

**docker compose up logs :**
```

opensearch-node        | [2023-01-31T09:00:15,428][INFO ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node] Clustername: opensearch-cluster
opensearch-node        | [2023-01-31T09:00:15,433][WARN ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node] Directory /usr/share/opensearch/config has insecure file permissions (should be 0700)
opensearch-node        | [2023-01-31T09:00:15,433][WARN ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node] File /usr/share/opensearch/config/kirk-key.pem has insecure file permissions (should be 0600)
opensearch-node        | [2023-01-31T09:00:15,434][WARN ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node] File /usr/share/opensearch/config/root-ca.pem has insecure file permissions (should be 0600)
opensearch-node        | [2023-01-31T09:00:15,434][WARN ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node] File /usr/share/opensearch/config/kirk.pem has insecure file permissions (should be 0600)
opensearch-node        | [2023-01-31T09:00:15,434][WARN ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node] File /usr/share/opensearch/config/esnode.pem has insecure file permissions (should be 0600)
opensearch-node        | [2023-01-31T09:00:15,434][WARN ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node] File /usr/share/opensearch/config/esnode-key.pem has insecure file permissions (should be 0600)
opensearch-node        | [2023-01-31T09:00:15,571][INFO ][o.o.p.c.PluginSettings   ] [opensearch-node] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true, batch-metrics-retention-period-minutes: 7, rpc-port: 9650, webservice-port 9600
opensearch-node        | [2023-01-31T09:00:16,035][INFO ][o.o.i.r.ReindexPlugin    ] [opensearch-node] ReindexPlugin reloadSPI called
opensearch-node        | [2023-01-31T09:00:16,036][INFO ][o.o.i.r.ReindexPlugin    ] [opensearch-node] Unable to find any implementation for RemoteReindexExtension
opensearch-node        | [2023-01-31T09:00:16,051][INFO ][o.o.j.JobSchedulerPlugin ] [opensearch-node] Loaded scheduler extension: opendistro-index-management, index: .opendistro-ism-config
opensearch-node        | [2023-01-31T09:00:16,055][INFO ][o.o.j.JobSchedulerPlugin ] [opensearch-node] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
opensearch-node        | [2023-01-31T09:00:16,080][INFO ][o.o.j.JobSchedulerPlugin ] [opensearch-node] Loaded scheduler extension: reports-scheduler, index: .opendistro-reports-definitions
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [aggs-matrix-stats]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [analysis-common]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [geo]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [ingest-common]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [ingest-geoip]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [ingest-user-agent]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [lang-expression]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [lang-mustache]
opensearch-node        | [2023-01-31T09:00:16,083][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [lang-painless]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [mapper-extras]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [opensearch-dashboards]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [parent-join]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [percolator]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [rank-eval]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [reindex]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [repository-url]
opensearch-node        | [2023-01-31T09:00:16,084][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded module [transport-netty4]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-alerting]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-anomaly-detection]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-asynchronous-search]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-cross-cluster-replication]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-index-management]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-job-scheduler]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-knn]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-observability]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-performance-analyzer]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-reports-scheduler]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-security]
opensearch-node        | [2023-01-31T09:00:16,085][INFO ][o.o.p.PluginsService     ] [opensearch-node] loaded plugin [opensearch-sql]
opensearch-node        | [2023-01-31T09:00:16,118][DEPRECATION][o.o.d.c.s.Settings       ] [opensearch-node] [node.max_local_storage_nodes] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
opensearch-node        | [2023-01-31T09:00:16,136][INFO ][o.o.e.NodeEnvironment    ] [opensearch-node] using [1] data paths, mounts [[/usr/share/opensearch/data (/dev/sdb)]], net usable_space [229.8gb], net total_space [250.9gb], types [ext4]
opensearch-node        | [2023-01-31T09:00:16,137][INFO ][o.o.e.NodeEnvironment    ] [opensearch-node] heap size [512mb], compressed ordinary object pointers [true]
opensearch-node        | [2023-01-31T09:00:16,179][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch-node] uncaught exception in thread [main]
opensearch-node        | org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        | Caused by: java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9
opensearch-node        |         at org.apache.lucene.index.SegmentInfos.<init>(SegmentInfos.java:169) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:327) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |         at org.opensearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:302) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:441) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.node.Node.<init>(Node.java:414) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |         ... 6 more
opensearch-node        |         Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (df1bd64c). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/usr/share/opensearch/data/nodes/0/_state/segments_5")))
opensearch-node        |                 at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:466) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:434) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
opensearch-node        |                 at org.opensearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:302) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:441) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.node.Node.<init>(Node.java:414) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        |                 at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.2.4.jar:1.2.4]
opensearch-node        | uncaught exception in thread [main]
opensearch-node        | java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9opensearch-node        |         at org.apache.lucene.index.SegmentInfos.<init>(SegmentInfos.java:169)
opensearch-node        |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:327)
opensearch-node        |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
opensearch-node        |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64)
opensearch-node        |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61)
opensearch-node        |         at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720)
opensearch-node        |         at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84)
opensearch-node        |         at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64)opensearch-node        |         at org.opensearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:302)
opensearch-node        |         at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:441)
opensearch-node        |         at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357)
opensearch-node        |         at org.opensearch.node.Node.<init>(Node.java:414)
opensearch-node        |         at org.opensearch.node.Node.<init>(Node.java:319)
opensearch-node        |         at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
opensearch-node        |         at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
opensearch-node        |         at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
opensearch-node        |         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
opensearch-node        |         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)opensearch-node        |         at org.opensearch.cli.Command.main(Command.java:101)
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
opensearch-node        |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
opensearch-node        | For complete error details, refer to the log at /usr/share/opensearch/logs/opensearch-cluster.log
opensearch-dashboards  | {"type":"log","@timestamp":"2023-01-31T09:00:17Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 172.18.0.2:9200"}



```

**Comment by Yafaa** [comment]
Yes I Created an index with opensearch 2.x but I deleted the docker image and container and cleaned the docker cache, and started the docker compose a second time with version 1.2.0

**Comment by Yafaa** [comment]
There is a way to reset the volume or remove this index ?

**Comment by andrross** [comment]
The [Docker documentation](https://docs.docker.com/storage/volumes/) should be able to help you. `docker volume rm opensearch-data1` may well be what you need but please don't run that command if you have data you want to keep in that volume.

**Comment by andrross** [comment]
Closing this issue. Please reopen if you think there is a bug or issue in OpenSearch.
