### ISSUE TITLE
[BUG] Assertion failure in IndexShard.updateGlobalCheckpointOnReplica() when remote translog is enabled

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#6193]
`PublishCheckpointAction` fails with following stacktrace.

```
java.lang.AssertionError: supposedly in-sync shard copy received a global checkpoint [4] that is higher than its local checkpoint [-1]
	at __randomizedtesting.SeedInfo.seed([16C715B7EF601310]:0)
	at org.opensearch.index.shard.IndexShard.updateGlobalCheckpointOnReplica(IndexShard.java:3044)
	at org.opensearch.index.shard.IndexShard.lambda$innerAcquireReplicaOperationPermit$40(IndexShard.java:3763)
	at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130)
	at org.opensearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:309)
	at org.opensearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:254)
	at org.opensearch.index.shard.IndexShard.lambda$acquireReplicaOperationPermit$38(IndexShard.java:3698)
	at org.opensearch.index.shard.IndexShard.innerAcquireReplicaOperationPermit(IndexShard.java:3818)
	at org.opensearch.index.shard.IndexShard.acquireReplicaOperationPermit(IndexShard.java:3692)
	at org.opensearch.action.support.replication.TransportReplicationAction.acquireReplicaOperationPermit(TransportReplicationAction.java:1204)
	at org.opensearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:849)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.action.support.replication.TransportReplicationAction.handleReplicaRequest(TransportReplicationAction.java:697)
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106)
	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by sachinpkale** [comment]
Draft PR is created but could not get reviewed/merged. Moving to 2.7.0 release.

**Comment by DarshitChanpura** [comment]
Hey @sachinpkale. Is it safe to close this issue as completed since the backport #6978 was merge in `2.x` line and is ready to be released for `v2.7.0`
