### ISSUE TITLE
[BUG] Assertion failure in replica promotion using remote translog

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#6195]
```
java.lang.AssertionError: global checkpoint [-1] lower than initial gcp [9]
	at __randomizedtesting.SeedInfo.seed([6F1D99B1F5816104]:0)
	at org.opensearch.index.translog.TranslogWriter.lambda$create$0(TranslogWriter.java:188)
	at org.opensearch.index.translog.TranslogWriter.syncNeeded(TranslogWriter.java:374)
	at org.opensearch.index.translog.TranslogWriter.syncUpTo(TranslogWriter.java:482)
	at org.opensearch.index.translog.TranslogWriter.sync(TranslogWriter.java:365)
	at org.opensearch.index.translog.RemoteFsTranslog.syncToDisk(RemoteFsTranslog.java:271)
	at org.opensearch.index.translog.RemoteFsTranslog.sync(RemoteFsTranslog.java:281)
	at org.opensearch.index.translog.RemoteFsTranslog.close(RemoteFsTranslog.java:307)
	at org.opensearch.core.internal.io.IOUtils.close(IOUtils.java:89)
	at org.opensearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:179)
	at org.opensearch.index.translog.InternalTranslogManager.close(InternalTranslogManager.java:449)
	at org.opensearch.core.internal.io.IOUtils.close(IOUtils.java:89)
	at org.opensearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:179)
	at org.opensearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:169)
	at org.opensearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:157)
	at org.opensearch.index.engine.InternalEngine.<init>(InternalEngine.java:354)
	at org.opensearch.index.engine.InternalEngine.<init>(InternalEngine.java:222)
	at org.opensearch.index.engine.NRTReplicationEngineFactory.newReadWriteEngine(NRTReplicationEngineFactory.java:23)
	at org.opensearch.index.shard.IndexShard.resetEngineToGlobalCheckpoint(IndexShard.java:4304)
	at org.opensearch.index.shard.IndexShard.lambda$updateShardState$3(IndexShard.java:649)
	at org.opensearch.index.shard.IndexShard$5.onResponse(IndexShard.java:3646)
	at org.opensearch.index.shard.IndexShard$5.onResponse(IndexShard.java:3616)
	at org.opensearch.index.shard.IndexShard.lambda$asyncBlockOperations$35(IndexShard.java:3567)
	at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:80)
	at org.opensearch.index.shard.IndexShardOperationPermits$1.doRun(IndexShardOperationPermits.java:156)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sachinpkale** [comment]
Moving to 2.7.0

**Comment by DarshitChanpura** [comment]
Hey @sachinpkale This issue will be marked for next-release `v2.8.0` on Apr 17 as that is the [code-freeze](https://opensearch.org/releases.html) date for `v2.7.0`. Please let me know if otherwise.

**Comment by DarshitChanpura** [comment]
Tagging it for next release: `v2.8.0`
