### ISSUE TITLE
[BUG] Flaky test org.opensearch.action.admin.ClientTimeoutIT.testSegmentReplicationStatsWithTimeout

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#6255]
**Describe the bug**
- Getting following error:

```
  2> java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([CA9A15EE7B62C96A:56C5C8CB0C0195B3]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1001)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:932)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:921)
        at org.opensearch.action.admin.ClientTimeoutIT.testSegmentReplicationStatsWithTimeout(ClientTimeoutIT.java:177)
```

**To Reproduce**
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.action.admin.ClientTimeoutIT.testSegmentReplicationStatsWithTimeout" -Dtests.seed=CA9A15EE7B62C96A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=is-IS -Dtests.timezone=Africa/Monrovia -Druntime.java=19
```

**Comment by sachinpkale** [comment]
cc: @Rishikesh1159

**Comment by Rishikesh1159** [comment]
Thanks @sachinpkale for opening the issue, looks like a flaky test went in my recent PR. I will try to put out a fix for this quickly until then I am muting this test with PR: https://github.com/opensearch-project/OpenSearch/pull/6256. Please review this PR if you can

**Comment by Rishikesh1159** [comment]
Closing this issue. PR:https://github.com/opensearch-project/OpenSearch/pull/6268 fixed this issue.
