### ISSUE TITLE
[BUG] {dot,}files in plugin directory cause startup failure

### ISSUE THREAD

**Issue by tgurr** [opensearch-project/OpenSearch#626]
**Describe the bug**
While trying to package OpenSearch, I've come across the issue that first OpenSearch failed to start because of the plugin directory not being present as our packaging policy prevents installing empty directories.

```
[2021-04-28T10:41:13,181][ERROR][o.o.b.Bootstrap          ] [localhost] Exception
java.lang.IllegalStateException: Unable to access 'path.home' (/usr/share/opensearch/plugins)
[...]
```
Our usual way of solving this is creating a dotfile in the "empty" directories we need to install.
```
/usr/share/opensearch/plugins/.keep_web-apps_opensearch-0
```
which for example works fine for the data directory.

This results in OpenSearch failing to start with:
```
[2021-04-28T10:44:00,953][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [localhost] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [.keep_web-apps_opensearch-0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) ~[opensearch-cli-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.cli.Command.main(Command.java:103) ~[opensearch-cli-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [.keep_web-apps_opensearch-0]
        at org.opensearch.plugins.PluginsService.readPluginBundle(PluginsService.java:420) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.findBundles(PluginsService.java:405) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.getPluginBundles(PluginsService.java:398) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:169) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        ... 6 more
Caused by: java.nio.file.FileSystemException: /usr/share/opensearch/plugins/.keep_web-apps_opensearch-0/plugin-descriptor.properties: Ist kein Verzeichnis
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:375) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:426) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
        at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
        at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:170) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.readPluginBundle(PluginsService.java:417) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.findBundles(PluginsService.java:405) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.getPluginBundles(PluginsService.java:398) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:169) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0-beta1-SNAPSHOT.jar:1.0.0-beta1-SNAPSHOT]
        ... 6 more
```

**To Reproduce**
1. touch /usr/share/opensearch/plugins/.test
2. systemctl start opensearch.service
3. See error

**Expected behavior**
See OpenSearch starting successfully.

**Plugins**
None as there aren't any included in the opensearch-1.0.0-beta1-linux-x64.tar.gz tarball artifact

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version: opensearch-1.0.0-beta1

**Additional context**
Seeing there's actual code in the plugin directory in the repository https://github.com/opensearch-project/OpenSearch/tree/1.x/plugins is there any additional plugin artifact to fetch and install with opensearch by default? That way the plugin directory wouldn't be empty to begin with.

**Comment by tlfeng** [comment]
Hi @tgurr, thank you for providing the steps to reproduce.

Could you explain more that under what circumstance the error `Unable to access 'path.home' (/usr/share/opensearch/plugins)` occurs?

I tried to package OpenSearch by command `./gradlew distribution:packages:deb:assemble` or `./gradlew distribution:packages:rpm:assemble` in both `master` and `1.x` branch, then the packages can be installed and OpenSearch can be started without error.
I noticed that the location `/usr/share/opensearch/plugins` is empty by default, and the location `/usr/share/elasticsearch/plugins` is also empty for Elasticsearch 7.10.2

I confirm there will be an error when putting a "dot file" into the `plugins` directory, but I would like to know the reason of putting the "dot file".

The plugins in https://github.com/opensearch-project/OpenSearch/tree/1.x/plugins are part of OpenSearch project, and are delivered at the same time as OpenSearch, but they are not installed in the distributions by default.

**Comment by dblock** [comment]
It's pretty common to put a `.keep` file in an empty directory. Doesn't feel like we should fail to start on something like this unless there's a really good reason.

**Comment by tlfeng** [comment]
Hi @tgurr, thanks for the detail! I get your point. 
Combining with @dblock's opinion, I think this can be an improvement of OpenSearch.
If you have got ideas to resolve the issue, we are willing to see your contribution 😄. Otherwise, I will try to find a solution.

**Comment by tlfeng** [comment]
I found that prior to Elasticsearch 6.0, hidden files are allowed to exist in the "plugins" directory, the leniency was removed, see the [commit](https://github.com/elastic/elasticsearch/commit/9056e0cb49ed1fe0d56a9e02a91cc47c557b0189) and the [document](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html#_ignoring_hidden_folders) for breaking change. 
The reason was stated in the PR of that commit that it was hard to debug when allowing hidden folders.

While later on, there was a [commit](https://github.com/elastic/elasticsearch/commit/6722b9c4a2f5917d73272ff86e3ff80a30305511) added leniency on macOS only to skip `.DS_Store` file.
Thus, in my opinion, even adding leniency on hidden files (but only folders) doesn't harm. I would like to hear more ideas.

**Comment by tgurr** [comment]
@tlfeng sounds like a sensible solution to only allow hidden files but not directories.

I just want to add this is not a pressing issue for me anymore as with `1.0.0-rc1` I've switched our opensearch package from the `core` to the `bundle` tarball which comes with the default plugins so the directory won't be empty anymore.

**Comment by tlfeng** [comment]
@tgurr Thank you for your feedback! 😁 We will consider allowing hidden files but not directories in `plugins` directory.

Glad to hear you using the bundle that having the various plugins 👍.

**Comment by CEHENKLE** [comment]
@ryanbogan Can we resolve this?  Thanks!

**Comment by ryanbogan** [comment]
@CEHENKLE Yeah we can
