### ISSUE TITLE
[BUG] Flaky test SegmentReplicationStatsIT.testSegmentReplicationStatsResponse

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#6261]
**Describe the bug**
The test `org.opensearch.indices.replication.SegmentReplicationStatsIT.testSegmentReplicationStatsResponse` introduced with #5718 is flaky -
```
Error Message
java.lang.AssertionError: 
Expected: <DONE>
     but: was <FINALIZE_REPLICATION>
Stacktrace
java.lang.AssertionError: 
Expected: <DONE>
     but: was <FINALIZE_REPLICATION>
	at __randomizedtesting.SeedInfo.seed([B2577B0DE18AD5BB:FB9EF53F6589927D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.indices.replication.SegmentReplicationStatsIT.testSegmentReplicationStatsResponse(SegmentReplicationStatsIT.java:50)
```

**To Reproduce**
Check autocut issue - https://github.com/opensearch-project/OpenSearch/issues/6258

**Expected behavior**
Test should pass all the time

**Comment by ashking94** [comment]
cc @Rishikesh1159
