### ISSUE TITLE
[BUG] Refactor unnecessary dependency on TestGeoShapeFieldMapperPlugin tests

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/OpenSearch#6322]
**Describe the bug**

The comment for this class says it all:

https://github.com/opensearch-project/OpenSearch/blob/ac322595eb1838b68e4d9a46cf97cbe56b811aed/test/framework/src/main/java/org/opensearch/test/TestGeoShapeFieldMapperPlugin.java#L44-L47

The issue seems to be that if the testing class extends `AbstractQueryTestCase` then no matter if the functionality has to do anything with `geo-shape` or not the test will fail if `TestGeoShapeFieldMapperPlugin` plugin is not included as well.

There are many examples in existing code where the plugin is just arbitrary included to mitigate this error.
Typical symptom of this problem is that `getPlugins()` method implementation looks like this:

```java
    @Override
    protected Collection<Class<? extends Plugin>> getPlugins() {
        return Arrays.asList(Important_Plugin_XYZ.class, TestGeoShapeFieldMapperPlugin.class);
    }
```

Otherwise the following exception is thrown:
```
Failed to parse mapping [_doc]: No handler for type [geo_shape] declared on field [mapped_geo_shape]
MapperParsingException[Failed to parse mapping [_doc]: No handler for type [geo_shape] declared on field [mapped_geo_shape]]; nested: MapperParsingException[No handler for type [geo_shape] declared on field [mapped_geo_shape]];
	at app//org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:441)
	at app//org.opensearch.index.mapper.MapperService.merge(MapperService.java:417)
	at app//org.opensearch.test.AbstractBuilderTestCase$ServiceHolder.<init>(AbstractBuilderTestCase.java:437)
	at app//org.opensearch.test.AbstractBuilderTestCase.lambda$beforeTest$0(AbstractBuilderTestCase.java:258)
...
```

It is confusing and figuring out why this exception was thrown may require detailed code debugging. It is not obvious.

**Comment by minalsha** [comment]
@vamshin  can you respond to this issue? Thanks

**Comment by vamshin** [comment]
Removed **bug** label as this is a test refactor scenario and not affecting features.

**Comment by minalsha** [comment]
@vamshin  removing untriaged label for this issue since you already triaged it. feel free to add the label if you think otherwise. Thanks
