### ISSUE TITLE
[BUG] Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.EOFException

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#637]
**Describe the bug**

Build succeeds but shows an exception.

```
./gradlew build

BUILD SUCCESSFUL in 12m 10s
2767 actionable tasks: 2731 executed, 36 up-to-date
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.EOFException: No input provided for project
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.EOFException: No input provided for project
        at org.apache.tools.ant.Project.defaultInput(Project.java:1293)
        at org.apache.tools.ant.Project.demuxInput(Project.java:1315)
        at org.apache.tools.ant.DemuxInputStream.read(DemuxInputStream.java:73)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
        ... 1 more
```

**To Reproduce**

```
git clone git@github.com:opensearch-project/OpenSearch.git
cd OpenSearch
./gradlew build
```

**Expected behavior**

Build successful. No errors.

**Host/Environment (please complete the following information):**
 - OS: ubuntu

**Additional context**

Currently on 1-x branch.

**Comment by tlfeng** [comment]
When testing my recent PR (#816), I also saw this exception several times, even in `main` branch.

**Comment by minalsha** [comment]
@dblock @tlfeng  is this still an issue? Do we need to follow up on this?
