### ISSUE TITLE
[BUG] java.io.OptionalDataException upon calls to opensearch 

### ISSUE THREAD

**Issue by PailaGH** [opensearch-project/OpenSearch#6384]
**Describe the bug**
When trying to create index we get following exception:

<html>
<body>

```
ERROR 1 d.r.i.RestHighLevelClientIndexRepository : Failed to create index. name=xxxxxxx  
org.opensearch.OpenSearchStatusException: OpenSearch exception [type=exception, reason=java.io.OptionalDataException] 
at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:207) ~[opensearch-2.5.0.jar!/:2.5.0] 	
at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2228) ~[opensearch-rest-high-level-client-2.5.0.jar!/:2.5.0] 	
at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2205) ~[opensearch-rest-high-level-client-2.5.0.jar!/:2.5.0] 	
at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1924) ~[opensearch-rest-high-level-client-2.5.0.jar!/:2.5.0] 	
at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1894) ~[opensearch-rest-high-level-client-2.5.0.jar!/:2.5.0] 	
at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1858) ~[opensearch-rest-high-level-client-2.5.0.jar!/:2.5.0] 	
at org.opensearch.client.IndicesClient.create(IndicesClient.java:159) ~[opensearch-rest-high-level-client-2.5.0.jar!/:2.5.0]
```
--

We also observed the same exception for other calls like alias, delete, set to readonly index. Some times it is successful upon retry.

</body>
</html>

**To Reproduce**
we tried both in **2.1 and 2.5** versions

**Comment by kartg** [comment]
Is it possible to provide more information on how we can reproduce this behavior? Unfortunately, the stack trace above doesn't give us enough useful information to root-cause the problem. Given that the calls sometimes succeed on retry, any information you can give us on the configuration of your cluster would also be useful.
