### ISSUE TITLE
Is there way to increase max length in opensearch?

### ISSUE THREAD

**Issue by type-kimchi** [opensearch-project/OpenSearch#6401]
Opensearch version : 2.4.0
failed to execute bulk item (index) index {$indexname} 
, source[n/a, actual length: [10.8kb], max length: 2kb]}
org.opensearch.index.mapper.MapperParsingException: failed to parse
        at org.opensearch.index.mapper.DocumentParser.wrapInMapperParsingException(DocumentParser.java:201) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:94) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:253) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.shard.IndexShard.prepareIndex(IndexShard.java:938) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:895) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:836) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:354) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:216) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:280) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:169) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:102) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:223) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) [opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.4.0.jar:2.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at org.opensearch.index.mapper.DocumentParser.getMapper(DocumentParser.java:995) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:531) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:439) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:414) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:513) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:552) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:439) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:414) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:513) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:534) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:439) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:414) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:513) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:534) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:439) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:414) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:513) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:534) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:624) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:576) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:441) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:414) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:513) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:534) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:439) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:414) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:513) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:534) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:439) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:414) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:136) ~[opensearch-2.4.0.jar:2.4.0]
        at org.opensearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:91) ~[opensearch-2.4.0.jar:2.4.0]

How can i increase max length?
Or do i need mapping correctly?

**Comment by andrross** [comment]
> How can i increase max length?

The short answer is that you cannot, because [it is hard coded to 2kb](https://github.com/opensearch-project/OpenSearch/blob/9b9158e4cb692dfe04315225ce2b5f9c6c453307/server/src/main/java/org/opensearch/action/index/IndexRequest.java#L99-L104).

Can you provide more details about your use case and where you're running into this problem?
