### ISSUE TITLE
[BUG] YAML XContent Parse Failure (jackson bug?)

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#6411]
Documenting this for posterity. Found this on #5902 but the failure exists prior to the refactor.

 It's unlikely this will occur in practice as the problem lies in a random generated ascii character failing to deserialize / read properly from `YAMLParser#nextToken` in either `jackson-dataformat-yaml` or `snakeyaml` dependency.

The string is the auto-generated field name of a `highlightField` in an inner hit of a `SearchHit`. The culprit is the third character ascii value (array index `2`).

Expected String: `[-26, -58, -123, -94, -95, -56, -3, -15, -85, -46]`
Parsed String    :    `[-26, -58, 32, -94, -95, -56, -3, -15, -85, -46]`

Dependency versions:  

jackson-dataformat-yaml:2.14.2
snakeyaml:1.32

```
./gradlew ':server:test' --tests "org.opensearch.search.SearchHitsTests.testFromXContent" -Dtests.seed=E04047FFE6CB5DFD -Dtests.security.manager=true
```

```
2> java.lang.AssertionError: expected:<org.opensearch.search.SearchHits@f24410c2> but was:<org.opensearch.search.SearchHits@1abbeddc>
        at __randomizedtesting.SeedInfo.seed([E04047FFE6CB5DFD:C12872E76F6CBD27]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.test.AbstractWireTestCase.assertEqualInstances(AbstractWireTestCase.java:110)
        at org.opensearch.test.AbstractSerializingTestCase.lambda$testFromXContent$0(AbstractSerializingTestCase.java:62)
        at org.opensearch.test.AbstractXContentTestCase$XContentTester.test(AbstractXContentTestCase.java:156)
        at org.opensearch.test.AbstractSerializingTestCase.testFromXContent(AbstractSerializingTestCase.java:64)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by nknize** [comment]
If anyone wants to take a stab at this to verify you should be able to isolate this failure to an explicit `XContentType.YAML` parse test with a single text field using the byte array above as the field name. Write the `expected` string to a field, serialize/deserialize and compare.

**Comment by RamakrishnaChilaka** [comment]
@nknize the Unicode control characters are not honoured by YAMLParser and were being replaced by white space. The current approach relies on removing all the control characters. However, this type of behaviour can occur in the future function test cases as well where randomised strings are generated by randomRealisticUnicodeOfCodepointLengthBetween/randomRealisticUnicodeOfCodepointLength. My initial thoughts on this were to replace control characters directly in the randomRealisticUnicodeOfCodepoint* with an underscore "_", I believe this would be a long-term fix but may affect a lot of test cases, as these functions are heavily used.

**Comment by saratvemulapalli** [comment]
thanks @RamakrishnaChilaka for contributing a fix. 
@nknize trying to understand, are we saying the auto generated strings sometimes have control characters which could not be interpreted ? I wonder why we didn't see this multiple times.

**Comment by RamakrishnaChilaka** [comment]
@saratvemulapalli @nknize, I think this was happening [before](https://github.com/opensearch-project/OpenSearch/blob/main/client/rest-high-level/src/test/java/org/opensearch/client/indices/PutIndexTemplateRequestTests.java#L82) as well. Yes, this [function](https://github.com/opensearch-project/OpenSearch/blob/9b9158e4cb692dfe04315225ce2b5f9c6c453307/test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java#L871) is generating across the Unicode range, which involves control characters [too](https://en.wikipedia.org/wiki/Unicode_control_characters).
