### ISSUE TITLE
[BUG] DiskThresholdDeciderIT.testIndexCreateBlockIsRemovedWhenAnyNodesNotExceedHighWatermarkWithAutoReleaseEnabled flaky test

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6445]
https://github.com/opensearch-project/OpenSearch/pull/6443#issuecomment-1440688303

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testIndexCreateBlockIsRemovedWhenAnyNodesNotExceedHighWatermarkWithAutoReleaseEnabled" -Dtests.seed=C6B411190A22D5ED -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-OM -Dtests.timezone=ROK -Druntime.java=19

org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT > testIndexCreateBlockIsRemovedWhenAnyNodesNotExceedHighWatermarkWithAutoReleaseEnabled FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([C6B411190A22D5ED:7F63CA47EA88CD72]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.lambda$testIndexCreateBlockIsRemovedWhenAnyNodesNotExceedHighWatermarkWithAutoReleaseEnabled$7(DiskThresholdDeciderIT.java:254)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1051)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testIndexCreateBlockIsRemovedWhenAnyNodesNotExceedHighWatermarkWithAutoReleaseEnabled(DiskThresholdDeciderIT.java:252)
```

/cc @RS146BIJAY

**Comment by andrross** [comment]
Another instance: https://github.com/opensearch-project/OpenSearch/pull/6350#issuecomment-1442738909

**Comment by RS146BIJAY** [comment]
Checking. Will mute this test incase unable to fix this.
