### ISSUE TITLE
[BUG] Snapshots fail due to error serializing IndexMetadata mapping

### ISSUE THREAD

**Issue by jed326** [opensearch-project/OpenSearch#6453]
**Describe the bug**
I am an engineer on the managed storage team for AWS OpenSearch and we recently encountered an issue with snapshots (and subsequently UltraWarm migrations) failing while serializing the IndexMetadata mapping.

Redacted sample error log:
```
[2022-06-19T18:22:50,960][WARN ][o.e.r.b.BlobStoreRepository] [XXXX] [XXXX] Failed to initialize snapshot
com.fasterxml.jackson.core.JsonGenerationException: Unmatched second part of surrogate pair (XXXX)
        at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
        at com.fasterxml.jackson.dataformat.smile.SmileGenerator._throwIllegalSurrogate(SmileGenerator.java:2123)
        at com.fasterxml.jackson.dataformat.smile.SmileGenerator._shortUTF8Encode2(SmileGenerator.java:1940)
        at com.fasterxml.jackson.dataformat.smile.SmileGenerator._shortUTF8Encode(SmileGenerator.java:1905)
        at com.fasterxml.jackson.dataformat.smile.SmileGenerator._writeFieldName(SmileGenerator.java:714)
        at com.fasterxml.jackson.dataformat.smile.SmileGenerator.writeFieldName(SmileGenerator.java:470)
        at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeFieldName(JsonXContentGenerator.java:183)
        at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:284)
        at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:886)
        at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:822)
        at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:888)
        at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:822)
        at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:888)
        at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:870)
        at org.elasticsearch.cluster.metadata.IndexMetaData$Builder.toXContent(IndexMetaData.java:1255)
        at org.elasticsearch.cluster.metadata.IndexMetaData.toXContent(IndexMetaData.java:660)
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.write(ChecksumBlobStoreFormat.java:213)
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.write(ChecksumBlobStoreFormat.java:204)
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.writeTo(ChecksumBlobStoreFormat.java:177)
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.write(ChecksumBlobStoreFormat.java:151)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.initializeSnapshot(BlobStoreRepository.java:418)
        at org.elasticsearch.snapshots.SnapshotsService$2.doRun(SnapshotsService.java:568)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:760)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
                at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1002)
                at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.write(ChecksumBlobStoreFormat.java:211)
                ... 10 more 
        Caused by: java.io.IOException: Unclosed object or array found
                at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:469)
                at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1000)
                ... 11 more 
```

Based on the errors this is most likely caused by index mappings that have an open parenthesis but not a close one, like the one below:
```
"Counters_Fault_\u0010\u000FD{\u0004^?" : {
            "type" : "scaled_float",
            "scaling_factor" : 1000.0
          },
```

**Expected behavior**
It seems like there should be a check to prevent or ignore these incorrect field names. I raised this as a bug issue but happy to recreate/change it to a feature request as needed.

**Comment by andrross** [comment]
@jed326 thanks for the bug report. The stack trace you shared is for Elasticsearch. Any chance you could try to reproduce this with OpenSearch (preferably with a recent 2.x version) to verify it is still a problem?

**Comment by jed326** [comment]
Ah apologies for the Elasticsearch stack trace. Will work on reproducing this in 2.x+ OpenSearch.

**Comment by jed326** [comment]
Apologies for the delayed follow-up. I was able to reproduce this in OS 2.5 like so:
1. Create index
2. Put mappings with special charactesr
3. Index a doc
4. Take a snapshot
And this results in the snapshot failing like the original post.

I haven't identified what specific mappings are causing the failure because the indices I have come across with this behavior all have a very large number of mappings and it's difficult to test each one in isolation. Here are some sample mappings:
```
        "ts" : {
          "type" : "date"
        },
        "streamstderr" : {
          "type" : "long"
        },
        "\u00047\rkubern" : {
          "type" : "long"
        },
        "\u0000\u0000\u0000\u0002" : {
          "type" : "long"
        },
        "\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0002\u0000d" : {
          "type" : "long"
        }
```

**Comment by neetikasinghal** [comment]
The mapping that causes this issue: 
`"ퟀ\uDD6Dlog_processeddetail٣{r" : {
              "type" : "long"
            },`

This mapping has broken surrogate pair because of which the encoding in SMILE is failing to happen leading to snapshot failures.
A similar issue in elasticsearch: https://github.com/elastic/elasticsearch/issues/9538
