### ISSUE TITLE
[Segment Replication] SegmentReplicationRelocationIT.testNewlyAddedReplicaIsUpdated flaky test failure.  

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#6459]
Flaky test failure due to timeout while waiting for cluster health response. Reported in https://github.com/opensearch-project/OpenSearch/pull/6455#issuecomment-1442084445

Gradle Check: https://build.ci.opensearch.org/job/gradle-check/11633

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationRelocationIT.testNewlyAddedReplicaIsUpdated" -Dtests.seed=A3D21C76F7A36009 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CU -Dtests.timezone=Africa/Algiers -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationRelocationIT > testNewlyAddedReplicaIsUpdated FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([A3D21C76F7A36009:E5CCE64E0859A9D0]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.opensearch.indices.replication.SegmentReplicationRelocationIT.testNewlyAddedReplicaIsUpdated(SegmentReplicationRelocationIT.java:432)
```

**Comment by mch2** [comment]
Another one - https://build.ci.opensearch.org/job/gradle-check/11604/testReport/junit/org.opensearch.indices.replication/SegmentReplicationRelocationIT/testNewlyAddedReplicaIsUpdated/

**Comment by mch2** [comment]
This test is timing out in CI because we only wait 2s for the shard to finish initializing, updating to use `ensureYellowAndNoInitializingShards` that will wait 30s should fix this.
