### ISSUE TITLE
Test failure: LocalTranslogTests.testWithRandomException

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6625]
This is reproducible with the seed below.

https://build.ci.opensearch.org/job/gradle-check/12272/consoleFull

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.translog.LocalTranslogTests.testWithRandomException" -Dtests.seed=4736E0CC7306EBDA -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-DO -Dtests.timezone=GMT -Druntime.java=19

org.opensearch.index.translog.LocalTranslogTests > testWithRandomException FAILED
    java.lang.AssertionError: expected:<null> but was:<java.lang.RuntimeException: simulated>
        at __randomizedtesting.SeedInfo.seed([4736E0CC7306EBDA:21EE8BD308E265CB]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.index.translog.LocalTranslogTests.testWithRandomException(LocalTranslogTests.java:3235)
```

**Comment by mitrofmep** [comment]
Can I take it?
