### ISSUE TITLE
[Test Failure] org.opensearch.action.bulk.BulkRequestTests > testBulkTerminatedByNewline

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#6658]
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.action.bulk.BulkRequestTests.testBulkTerminatedByNewline" -Dtests.seed=990003161995B586 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-AU -Dtests.timezone=Asia/Choibalsan -Druntime.java=19

org.opensearch.action.bulk.BulkRequestTests > testBulkTerminatedByNewline FAILED
    junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([990003161995B586:3D250D1DF53CDB99]:0)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2864)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2850)
        at org.opensearch.action.bulk.BulkRequestTests.testBulkTerminatedByNewline(BulkRequestTests.java:363)

**Comment by owaiskazi19** [comment]
This failure was due to the EOL in json file. Handled it [here](https://github.com/opensearch-project/OpenSearch/pull/6657/commits/c1c837fccec8643a52871f05e10f9cf6a1ed3e3b)
