### ISSUE TITLE
[BUG] org.opensearch.indices.replication.SegmentReplicationRelocationIT.testPrimaryRelocation is flaky

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#6665]
**Describe the bug**
```
Error Message

java.lang.AssertionError: expected:<true> but was:<false>

Stacktrace

java.lang.AssertionError: expected:<true> but was:<false>
	at __randomizedtesting.SeedInfo.seed([588BB72E6B7BB51A:E08380FC4812E6F4]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.indices.replication.SegmentReplicationRelocationIT.testPrimaryRelocation(SegmentReplicationRelocationIT.java:96)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
CI Build: https://build.ci.opensearch.org/job/gradle-check/12415/

I am able to reproduce it on local using following command:
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationRelocationIT.testPrimaryRelocation" -Dtests.seed=588BB72E6B7BB51A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=is -Dtests.timezone=America/New_York
```

**Expected behavior**
 The test should pass all the time

**Plugins**
Standard

**Host/Environment (please complete the following information):**
- CI (Jenkins)

**Comment by sachinpkale** [comment]
cc: @dreamer-89 @mch2

**Comment by Rishikesh1159** [comment]
Thanks @sachinpkale for opening the issue. I also caught this test failing when running locally. This PR: https://github.com/opensearch-project/OpenSearch/pull/6637 should  fix the issue.

**Comment by Rishikesh1159** [comment]
Verified locally by running 500 iterations, this PR: https://github.com/opensearch-project/OpenSearch/pull/6637 fixes the issue
