### ISSUE TITLE
[BUG] Logstash cannot submit events to OpenSearch since version change

### ISSUE THREAD

**Issue by shdubsh** [opensearch-project/OpenSearch#667]
**Describe the bug**
Since 0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0, logstash-output-elasticsearch (from logstash-oss-7.10.0) is unable to submit events to OpenSearch.

Interestingly, OpenSearch prior to 0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0 (7.10.3-SNAPSHOT) did not have this problem.  My guess is that Logstash is doing a version check and formatting the event in the format a 1.x cluster expects.

**To Reproduce**
1. Install and configure OpenSearch 1.0.0-SNAPSHOT and Logstash-OSS 7.10.x
2. Send events to an input.
3. Observe Logstash logs:
```
[2021-05-06T20:08:12,426][INFO ][logstash.outputs.elasticsearch][main] ES Output version determined {:es_version=>1}
(...)
[2021-05-06T20:12:20,173][WARN ][logstash.outputs.elasticsearch][main][output/elasticsearch/ecs_1.7.0-1] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"ecs-1.7.0-1-default-2021.18", :_routing=>nil, :_type=>"doc"}, #<LogStash::Event:0x356d5866>], :response=>{"index"=>{"_index"=>"ecs-1.7.0-1-default-2021.18", "_type"=>"doc", "_id"=>"pNVPQ3kBYCRrp24ASdQ8", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"mapper [log.level] cannot be changed from type [keyword] to [text]"}}}}
```
4. Observe OpenSearch logs:
```
[2021-05-06T20:12:24,680][INFO ][o.o.a.b.TransportShardBulkAction] [default] [ecs-1.7.0-1-default-2021.18][0] mapping update rejected by primary
java.lang.IllegalArgumentException: mapper [log.level] cannot be changed from type [keyword] to [text]
        at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:103) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:74) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:548) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:508) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:535) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:311) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:508) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:306) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.Mapping.merge(Mapping.java:123) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:294) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:484) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:435) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.MapperService.merge(MapperService.java:375) ~[opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:305) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:188) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:233) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:139) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:98) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:192) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:756) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Expected behavior**
Events should be successfully indexed and stored by OpenSearch.

**Plugins**
None

**Screenshots**
N/A

**Host/Environment**
 - Debian 10 Buster

**Additional context**
Logstash is configured to install and use an [ECS 1.7.0 mapping template](https://github.com/elastic/ecs/blob/v1.7.0/generated/elasticsearch/7/template.json).

**Comment by CEHENKLE** [comment]
I think this is related to #693.  Thanks for reporting!

**Comment by dblock** [comment]
Whichever way we fix this, we need to remember to contribute integration tests against OpenSearch to https://github.com/logstash-plugins/logstash-output-elasticsearch. It currently runs against multiple versions of ES.

**Comment by shdubsh** [comment]
I found this possibly related to the ElasticSearch 6.0 deprecation of mapping types.  Inspecting the _bulk POSTs showed the `_type` field was equal to `type` in the document which led to mapping issues as there are no document type definitions in my mapping templates.

Logstash 7 is helping with the deprecation by [overwriting this field when ES version is > 6.](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L449-L471)

Fortunately, logstash-output-elasticsearch still supports the `document_type` parameter.  I found that if `document_type => "_doc"`, Logstash is again able to write to OpenSearch.

**Comment by shdubsh** [comment]
Confirmed #847 resolves this issue when `compatibility.override_main_response_version: true` in opensearch.yml.

**Comment by shdubsh** [comment]
FWIW, #847 also fixes the same issue with elasticsearch curator (tested version 5.8.1).
```
2021-06-23 21:51:40,284 ERROR     Elasticsearch version 1.0.0 incompatible with this version of Curator (5.8.1)
2021-06-23 21:51:40,284 ERROR     Elasticsearch version 1.0.0 incompatible with this version of Curator (5.8.1)
2021-06-23 21:51:40,285 CRITICAL  Curator cannot continue due to version incompatibilites. Exiting
```

**Comment by dblock** [comment]
This is resolved with a [backwards compatibility setting](https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/).
