### ISSUE TITLE
[BUG] org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#6686]
**Describe the bug**

New test failure: 
```
EPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse" -Dtests.seed=91AB376F4EA0A90 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-NI -Dtests.timezone=America/Thule -Druntime.java=19
  2> java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([91AB376F4EA0A90:54EDA28D5C95D6DF]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1001)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:932)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:921)
        at org.opensearch.snapshots.SearchableSnapshotIT.restoreSnapshotAndEnsureGreen(SearchableSnapshotIT.java:326)
        at org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse(SearchableSnapshotIT.java:562)
```

**To Reproduce**
See please https://build.ci.opensearch.org/job/gradle-check/12473/

**Expected behavior**
Test should always pass

**Plugins**
Standart

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**

**Comment by kotwanikunal** [comment]
@tlfeng Can you please take a look at this?
