### ISSUE TITLE
[BUG]Version Compatibility failure  when OpenSearch node tries to join ElasticSearch node[7.10 version]

### ISSUE THREAD

**Issue by Gaurav614** [opensearch-project/OpenSearch#669]
**Describe the bug**
We have one node ElasticSearch 7.10 cluster and added a another node with Opensearch 1.0.0 version. Found that the added node fails to join the cluster with following exception trace.

`Caused by: java.lang.IllegalStateException: Received message from unsupported version: [35.21.78-beta2] minimal compatible version is: [6.8.0]
        at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:134) ~[?:?]
        at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:110) ~[?:?]
        at org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:253) ~[?:?]
        at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:245) ~[?:?]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133) ~[?:?]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) ~[?:?]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) ~[?:?]
        at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) ~[?:?]
        at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) ~[?:?]
        at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) ~[?:?]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]`

**To Reproduce**
1. Create a single node cluster with ElasticSearch 7.10 version
2. Add a OpenSearch node to the cluster
3. The added node will fail to join the cluster

**Expected behavior**
The Opensearch node should have backward version compatibility with ElasticSearch node. It should be able to join the cluster which are having ES nodes in the cluster.

**Comment by dblock** [comment]
Thanks for reporting this. Deciding whether we want to support this is probably big deal, @CEHENKLE who should track this one?

**Comment by shwetathareja** [comment]
```
Version(int id, org.apache.lucene.util.Version luceneVersion) {
    // flip the 28th bit of the ID; identify as an opensearch vs legacy system:
    // we start from version 1 for opensearch, so ignore the 0 (empty) version
        if(id != 0) {
            this.id = id ^ MASK;
```
OpenSearch 1.0.0 node sends the masked Id as 135217827 to the ES 7.10 node during the handshake and Elasticsearch code is unaware of this masking logic and uses this Id to generate the Version object and this breaks the minCompatibilityVersion logic and 35.21.78 is being treated as minCompatibleVersion for 1.0.0 and hence nodes are failing to connect.

minCompatibilityVersion logic
```
        } else if (major >= 7) {
            // all major versions from 7 onwards are compatible with last minor series of the previous major
            Version bwcVersion = null;

            for (int i = DeclaredVersionsHolder.DECLARED_VERSIONS.size() - 1; i >= 0; i--) {
                final Version candidateVersion = DeclaredVersionsHolder.DECLARED_VERSIONS.get(i);
                if (candidateVersion.major == major - 1 && candidateVersion.isRelease() && after(candidateVersion)) {
                    if (bwcVersion != null && candidateVersion.minor < bwcVersion.minor) {
                        break;
                    }
                    bwcVersion = candidateVersion;
                }
            }
            return bwcVersion == null ? this : bwcVersion;
        }

        return Version.min(this, fromId(maskId((int) major * 1000000 + 0 * 10000 + 99)));
```

**Comment by shwetathareja** [comment]
@nknize , can you please take a look?

**Comment by krishna-ggk** [comment]
Good find. This is an issue for cross-cluster connectivity between ES 7.x and OS 1.x as the same version compatibility matching is used. Essentially this breaks cross-cluster search and [cross-cluster replication](https://github.com/opendistro-for-elasticsearch/cross-cluster-replication) between ES 7.10 and OS 1.0.

**Comment by nknize** [comment]
@shwetathareja the proposal looks good to me. Can you open a PR with the proposed fix? In the meantime we need to enable Backwards Compatibility testing w/ ES nodes. This will require some changes to DistributionDownloader so we'll get a separate PR open get those taken care of.

**Comment by shwetathareja** [comment]
Thanks @nknize, I will take it up.

**Comment by dblock** [comment]
Linking to https://github.com/opensearch-project/OpenSearch/issues/640

**Comment by dblock** [comment]
I believe this can be closed?

**Comment by nknize** [comment]
fixed by #775

**Comment by DoctorOgg** [comment]
so, this may still be an issue: https://forum.opensearch.org/t/trying-to-upgrade-from-elastic-search-received-message-from-unsupported-version/9488/4

**Comment by DoctorOgg** [comment]
sure, the details are in the forum post, however I will open a new issue
