### ISSUE TITLE
[BUG] [Segment Replication] Handle closed indices on segrep source 

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#6724]
Handle closed indices on source. ClosedIndexIT.testNoopPeerRecoveriesWhenIndexClosed is sample example IT.

On source it fails while fetching reference of index service.
```
Suppressed: RemoteTransportException[[node_s1][127.0.0.1:60473][internal:index/shard/replication/get_checkpoint_info]]; nested: NullPointerException[Cannot invoke "org.opensearch.index.IndexService.getShard(int)" because "indexService" is null];
Caused by: java.lang.NullPointerException: Cannot invoke "org.opensearch.index.IndexService.getShard(int)" because "indexService" is null
at org.opensearch.indices.replication.OngoingSegmentReplications.getCachedCopyState(OngoingSegmentReplications.java:84)
at org.opensearch.indices.replication.OngoingSegmentReplications.prepareForReplication(OngoingSegmentReplications.java:149)
at org.opensearch.indices.replication.SegmentReplicationSourceService$CheckpointInfoRequestHandler.messageReceived(SegmentReplicationSourceService.java:137)
at org.opensearch.indices.replication.SegmentReplicationSourceService$CheckpointInfoRequestHandler.messageReceived(SegmentReplicationSourceService.java:118)
at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106)
at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453)
at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.lang.Thread.run(Thread.java:833)
```

**Comment by dreamer-89** [comment]
Marking this as closed with https://github.com/opensearch-project/OpenSearch/pull/6795
