### ISSUE TITLE
[BUG] org.opensearch.snapshots.SearchableSnapshotIT.testPruneFileCacheOnIndexDeletion is flaky

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#6738]
**Describe the bug**
Test failure - 
```
Error Message
java.lang.AssertionError: timed out waiting for green state
Stacktrace
java.lang.AssertionError: timed out waiting for green state
	at __randomizedtesting.SeedInfo.seed([1ED65DC09068BADB:C6BEB40884E3C77A]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1001)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:932)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:921)
	at org.opensearch.snapshots.SearchableSnapshotIT.createIndexWithDocsAndEnsureGreen(SearchableSnapshotIT.java:279)
	at org.opensearch.snapshots.SearchableSnapshotIT.testPruneFileCacheOnIndexDeletion(SearchableSnapshotIT.java:534)
```

**To Reproduce**
https://build.ci.opensearch.org/job/gradle-check/12588/

**Expected behavior**
Test should pass.

**Comment by Rishikesh1159** [comment]
Another occurance in : https://github.com/opensearch-project/OpenSearch/pull/6741

**Comment by Poojita-Raj** [comment]
> Another occurance in : #6741

2 more occurrences in the same PR
