### ISSUE TITLE
[Segment Replication] Flaky test testDropPrimaryDuringReplication

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#6762]
Flaky test testDropPrimaryDuringReplication. The failure shows assertion failure [here](https://github.com/opensearch-project/OpenSearch/blob/7628de883c1009f8d6fe52263ec628ba29bc8a4b/server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java#L155) to ensure temporary file exists on target during file copy operation 

Gradle check link: https://build.ci.opensearch.org/job/gradle-check/12493/

Failure stack trace
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationIT.testDropPrimaryDuringReplication" -Dtests.seed=63A5C40F1C2620BA -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nl -Dtests.timezone=Europe/Vienna -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationIT > testDropPrimaryDuringReplication FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=569, name=opensearch[node_t4][generic][T#4], state=RUNNABLE, group=TGRP-SegmentReplicationIT]
        at __randomizedtesting.SeedInfo.seed([63A5C40F1C2620BA:CEE16747ABB69910]:0)

        Caused by:
        java.lang.AssertionError: expected: [replication.E-7smM8hQyW1ug6zx-t3mA._1.cfs] in [segments_5, write.lock]
            at __randomizedtesting.SeedInfo.seed([63A5C40F1C2620BA]:0)
            at org.opensearch.indices.recovery.MultiFileWriter.innerWriteFileChunk(MultiFileWriter.java:158)
            at org.opensearch.indices.recovery.MultiFileWriter$FileChunkWriter.writeChunk(MultiFileWriter.java:242)
            at org.opensearch.indices.recovery.MultiFileWriter.writeFileChunk(MultiFileWriter.java:92)
            at org.opensearch.indices.replication.SegmentReplicationTarget.writeFileChunk(SegmentReplicationTarget.java:136)
            at org.opensearch.indices.replication.common.ReplicationTarget.handleFileChunk(ReplicationTarget.java:259)
            at org.opensearch.indices.replication.SegmentReplicationTargetService$FileChunkTransportRequestHandler.messageReceived(SegmentReplicationTargetService.java:383)
            at org.opensearch.indices.replication.SegmentReplicationTargetService$FileChunkTransportRequestHandler.messageReceived(SegmentReplicationTargetService.java:373)
            at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106)
            at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453)
            at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at java.****/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.****/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
            at java.****/java.lang.Thread.run(Thread.java:1589)
```

**Comment by dreamer-89** [comment]
Given test does not fail with/without provided seed on local in `1000` runs (still on-going).

**Comment by dreamer-89** [comment]
From test logs, don't see any logs which would point to any issues. This failure happens on an existing replica when the primary node is stopped 
```
  2> mrt 15, 2023 9:00:51 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[#569,opensearch[node_t4][generic][T#4],5,TGRP-SegmentReplicationIT]
  2> java.lang.AssertionError: expected: [replication.E-7smM8hQyW1ug6zx-t3mA._1.cfs] in [segments_5, write.lock]
  2> 	at __randomizedtesting.SeedInfo.seed([63A5C40F1C2620BA]:0)
  2> 	at org.opensearch.indices.recovery.MultiFileWriter.innerWriteFileChunk(MultiFileWriter.java:158)
  2> 	at org.opensearch.indices.recovery.MultiFileWriter$FileChunkWriter.writeChunk(MultiFileWriter.java:242)
  2> 	at org.opensearch.indices.recovery.MultiFileWriter.writeFileChunk(MultiFileWriter.java:92)
  2> 	at org.opensearch.indices.replication.SegmentReplicationTarget.writeFileChunk(SegmentReplicationTarget.java:136)
  2> 	at org.opensearch.indices.replication.common.ReplicationTarget.handleFileChunk(ReplicationTarget.java:259)
  2> 	at org.opensearch.indices.replication.SegmentReplicationTargetService$FileChunkTransportRequestHandler.messageReceived(SegmentReplicationTargetService.java:383)
  2> 	at org.opensearch.indices.replication.SegmentReplicationTargetService$FileChunkTransportRequestHandler.messageReceived(SegmentReplicationTargetService.java:373)
  2> 	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106)
  2> 	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453)
  2> 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
  2> 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
  2> 	at java.****/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  2> 	at java.****/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  2> 	at java.****/java.lang.Thread.run(Thread.java:1589)
```

**Comment by dreamer-89** [comment]
This is a failover scenario bug where promoted replica with an ongoing round of segment replication cleans up its store, including temporary copied over files which conflict with segrep process responsbile for copying files.  

Timeline
node_t2 is started as replica which performs segrep with older primary on `node_t1`. 
```
[2023-04-07T19:10:23,524][INFO ][o.o.i.r.SegmentReplicationTarget] [node_t2] [test-idx-1][0] [31206] Replication diff for checkpoint ReplicationCheckpoint{shardId=[test-idx-1][0], primaryTerm=1, segmentsGen=3, version=11, size=93731, codec=Lucene95} RecoveryDiff{identical=[], different=[], missing=[name [_1.cfs], length [56235], checksum [1vl1wuo], writtenBy [9.6.0], name [_0.cfe], length [479], checksum [1gnw71m], writtenBy [9.6.0], name [_0.si], length [318], checksum [97u0s0], writtenBy [9.6.0], name [_1.cfe], length [479], checksum [qmaym9], writtenBy [9.6.0], name [_1.si], length [318], checksum [1bqh7cs], writtenBy [9.6.0], name [_0.cfs], length [35902], checksum [vzl70q], writtenBy [9.6.0]]}
```

Meanwhile older primary is stopped which promotes `node_t2` as new primary. During `node_t2` promotion, engine is [reset](https://github.com/opensearch-project/OpenSearch/blob/0db20d99d4e06ddb261429466a8072501cc15941/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L663), where replica commit its latest processed checkpoint, followed by store [clean up](https://github.com/opensearch-project/OpenSearch/blob/0db20d99d4e06ddb261429466a8072501cc15941/server/src/main/java/org/opensearch/index/store/Store.java#L948). This clean up deletes all files not referenced in latest commit on store, thus deletes the temporary replication files.

```
[2023-04-07T19:10:23,657][INFO ][i.s.deletes              ] [node_t2][test-idx-1][0] [31196] After commit: delete file replication.teSJpKFuT-6pgtOxNsffsA._0.cfe
[2023-04-07T19:10:23,658][INFO ][i.s.deletes              ] [node_t2][test-idx-1][0] [31196] After commit: delete file replication.teSJpKFuT-6pgtOxNsffsA._0.cfs
[2023-04-07T19:10:23,658][INFO ][i.s.deletes              ] [node_t2][test-idx-1][0] [31196] After commit: delete file replication.teSJpKFuT-6pgtOxNsffsA._0.si
[2023-04-07T19:10:23,659][INFO ][i.s.deletes              ] [node_t2][test-idx-1][0] [31196] After commit: delete file replication.teSJpKFuT-6pgtOxNsffsA._1.cfe
[2023-04-07T19:10:23,659][INFO ][i.s.deletes              ] [node_t2][test-idx-1][0] [31196] After commit: delete file replication.teSJpKFuT-6pgtOxNsffsA._1.cfs
```

The on-going replication process on replica is not aware of this clean up and thus fails while validating post file copy.
```
[2023-04-07T19:10:23,663][INFO ][o.o.i.r.SegmentReplicationTarget] [node_t2] [test-idx-1][0] [31206] --> Failure reported, current list of files [segments_5, write.lock]
java.lang.AssertionError: expected: [replication.teSJpKFuT-6pgtOxNsffsA._1.cfs] in [segments_5, write.lock]
...
```
