### ISSUE TITLE
[BUG] [Remote Store] Remote store restore fails for shards intermittently while reading/parsing segment metadata files

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#6824]
**Describe the bug**
While doing a restore from Remote Store for an index, the restore fails intermittently while parsing segment metadata files. We have observed this happening on large indices and works for indices with 100-200 docs.

**To Reproduce**
Since this is intermittent, reproduction might not work with following steps. But if you index size is large then its highly likely you'll be able to reproduce.

1. Create an index with 0 replica and remote store enabled
2. Index few GBs of data
3. Kill one of the nodes where any one shard is assigned for this index
4. Close the index
5. Try to restore from Remote store. Few shards would fail with following exception

```
[2023-03-23T10:52:12,653][INFO ][o.o.i.s.RemoteStoreRefreshListener] [node-2] Exception while deleting stale commits from remote segment store, will retry delete post next commit
org.apache.lucene.index.CorruptIndexException: misplaced codec footer (file extended?): remaining=63, expected=16, fp=16247 (resource=BufferedChecksumIndexInput(metadata__1__4__KwQRDocBjhV-QdRrrU7C))
        at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:578) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:432) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
        at org.opensearch.common.io.VersionedCodecStreamWrapper.checkFooter(VersionedCodecStreamWrapper.java:84) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.io.VersionedCodecStreamWrapper.readStream(VersionedCodecStreamWrapper.java:53) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.store.RemoteSegmentStoreDirectory.readMetadataFile(RemoteSegmentStoreDirectory.java:138) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.store.RemoteSegmentStoreDirectory.deleteStaleSegments(RemoteSegmentStoreDirectory.java:424) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.shard.RemoteStoreRefreshListener.deleteStaleCommits(RemoteStoreRefreshListener.java:236) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.shard.RemoteStoreRefreshListener.afterRefresh(RemoteStoreRefreshListener.java:103) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.apache.lucene.search.ReferenceManager.notifyRefreshListenersRefreshed(ReferenceManager.java:275) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:182) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:240) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
```

**Expected behavior**
Remote store restore should not fail and all shards should be assigned and initialized after restore

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version OS_2.5

**Comment by DarshitChanpura** [comment]
@linuxpi This issue will be marked for next-release `v2.8.0` on (Apr 17) as that is the [code-freeze](https://opensearch.org/releases.html) date for `v2.7.0`. Please let me know if otherwise.

**Comment by DarshitChanpura** [comment]
@linuxpi Is this issue still on track to be merged for `v2.7.0`. If so, can you please create a backport of #6931 to 2.x line and get it merged by EOD today (code-freeze for 2.7)?

**Comment by linuxpi** [comment]
https://github.com/opensearch-project/OpenSearch/issues/6824

Already backported. Closing the bug
