### ISSUE TITLE
[BUG] Incorrect SearchBackpressureMode can corrupt cluster state

### ISSUE THREAD

**Issue by dgilling** [opensearch-project/OpenSearch#6832]
**Describe the bug**

**To Reproduce**
1. Update Cluster settings with an invalid enum type for `search_backpressure` like below.
2. For example, instead of `monitor_only`, `monitor-only` was incorrectly used. 
```PUT localhost:9200/_cluster/settings
{
    "persistent": {
        "search_backpressure": {
            "mode": "monitor-only"
      }
    }
}
```
3. The cluster state will get corrupted. This can put the cluster in an unrecoverable state as no master eligible mode can be voted as current master. All master eligible nodes are out of comission. 

**Expected behavior**
The API call should error out as `monitor-only` is an invalid value. The incorrect value should not get propagated through the nodes. 

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
```
 java.lang.IllegalArgumentException: Invalid SearchBackpressureMode: monitor-only
 	at org.opensearch.search.backpressure.settings.SearchBackpressureMode.fromName(SearchBackpressureMode.java:50) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.search.backpressure.settings.SearchBackpressureSettings.lambda$new$0(SearchBackpressureSettings.java:124) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.settings.Setting$Updater.apply(Setting.java:1238) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:696) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:232) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:556) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:484) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:186) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245) [opensearch-2.5.0.jar:2.5.0]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
 	at java.lang.Thread.run(Thread.java:833) [?:?]
 [2023-03-25T04:37:43,478][WARN ][o.o.c.s.ClusterApplierService] [416d7c37938c] failed to apply updated cluster state in [0s]:

```

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] Ubunutu
 - Version [e.g. 22] OS 2.5

**Additional context**

**Comment by austintlee** [comment]
@dgilling how do you recover from the bad state?  I reproduced this in my docker container and now even with a different docker image the cluster gets corrupted.

**Comment by dgilling** [comment]
@austintlee , the only option I found was to recreate and restore. It's also possible wiping out the cluster state via `opensearch-node detach-cluster` might work.

**Comment by austintlee** [comment]
@anasalkouz curious why you marked this issue "good first issue".  It is easy to reproduce with a YAML REST test case.  But I think a fix is not so straightforward.

We can do a simple input validation in the REST handler layer specific to the SearchBackpressureMode.  Would that be OK?  Is there a single place where we do all input validation on _cluster/settings PUT calls?

This particular bug is quite nasty.  It gets persisted and the cluster manage can't recover as it is not able to de-serialize the persisted ClusterState due to an invalid mode.  This can happen with any persisted (cluster) setting and I think we need a more generic fix that prevents that from happening.

**Comment by anasalkouz** [comment]
Thanks @austintlee for the deep dive. yeah, seems this is not straight forward as I thought. I thought a simple validation should be enough. +1 for the generic long-term fix.

**Comment by austintlee** [comment]
Can you suggest a short-term mitigation fix?  This seems like a high severity bug given how easy it is to happen and the damage it can cause.  I can look into a quick fix and put a TODO comment saying we'll work on a long term fix.

**Comment by dblock** [comment]
Looks like @shwetathareja opened https://github.com/opensearch-project/OpenSearch/issues/7598 to have a documented way to fix cluster state. 

Is it possible to override this option via opensearch.yml as a workaround?
