### ISSUE TITLE
[BUG] Flaky Test IndexShardTests.testRestoreLocalHistoryFromTranslogOnPromotion

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#6873]
**Describe the bug**
Found 
`org.opensearch.index.shard.IndexShardTests.testRestoreLocalHistoryFromTranslogOnPromotion` failing on gradle check [here](https://github.com/opensearch-project/OpenSearch/pull/6850#issuecomment-1489160152).  Verified that this test fails consistently on main with seed -Dtests.seed=2A0B8EBB6B3C284B.

`REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.shard.IndexShardTests.testRestoreLocalHistoryFromTranslogOnPromotion" -Dtests.seed=2A0B8EBB6B3C284B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sq-AL -Dtests.timezone=Pacific/Apia -Druntime.java=19`
```

java.lang.AssertionError: 
Expected: <-1L>
     but: was <0L>
	at __randomizedtesting.SeedInfo.seed([2A0B8EBB6B3C284B:9AC1F01A9AFD1CB2]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.index.shard.IndexShardTests.testRestoreLocalHistoryFromTranslogOnPromotion(IndexShardTests.java:1429)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

**To Reproduce**
Run the test with -Dtests.seed=2A0B8EBB6B3C284B in main branch.

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by owaiskazi19** [comment]
@RamakrishnaChilaka any reason to assign the bug to me?
