### ISSUE TITLE
[BUG] testCacheFilesAreClosedAfterUse flaky test failure

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#6891]
Gradle check: https://build.ci.opensearch.org/job/gradle-check/13056/
Identified in PR: https://github.com/opensearch-project/OpenSearch/pull/6765#issuecomment-1489412523

Failure trace
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse" -Dtests.seed=11EA2EA92BD684CA -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=be -Dtests.timezone=Zulu -Druntime.java=19

org.opensearch.snapshots.SearchableSnapshotIT > testCacheFilesAreClosedAfterUse FAILED
    java.lang.AssertionError: Cache file path isn't deleted.
        at __randomizedtesting.SeedInfo.seed([11EA2EA92BD684CA:4C1D3F5283A95885]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse(SearchableSnapshotIT.java:564)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/home/ubuntu/.gradle/wrapper/dists/gradle-8.0.2-all/25ipb77ce0ypy3f9xdton1ae6/gradle-8.0.2/lib/plugins/gradle-testing-****-8.0.2.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release
```

**Comment by kotwanikunal** [comment]
Closing in favor of #6888
