### ISSUE TITLE
[BUG] Repository Plugins Broken after XContent Base Clase Refactor

### ISSUE THREAD

**Issue by dgilling** [opensearch-project/OpenSearch#6912]
**Describe the bug**
Looks like [Refactor XContent base classes from xcontent to core library ](https://github.com/opensearch-project/OpenSearch/pull/5902) broke the installation of the repository plugins.

**To Reproduce**
1. Start with snapshot 2.7.0 based on after commit [cb402cb867d05dc6e33a7b19f8d95548cfb3d445](https://github.com/opensearch-project/OpenSearch/commit/cb402cb867d05dc6e33a7b19f8d95548cfb3d445)
2. Try to install a repo plugin `opensearch-plugin install file:repository-s3-2.7.0.zip` or `opensearch-plugin install file:repository-azure-2.7.0.zip`
3. You'll get an exception on installation:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/opensearch/core/xcontent/ToXContentFragment
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.opensearch.cli.CommandLoggingConfigurator.configureLoggingWithoutConfig(CommandLoggingConfigurator.java:54)
	at org.opensearch.cli.Command.main(Command.java:98)
	at org.opensearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:56)
Caused by: java.lang.ClassNotFoundException: org.opensearch.core.xcontent.ToXContentFragment
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by kotwanikunal** [comment]
@dgilling Is the plugin built locally as well? 

Tagging @nknize as well.

**Comment by dgilling** [comment]
Yes, this was built locally using `opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2`. I could also be doing something as well wrong. However, the flow worked fine up until [this commit](cb402cb867d05dc6e33a7b19f8d95548cfb3d445](https://github.com/opensearch-project/OpenSearch/commit/cb402cb867d05dc6e33a7b19f8d95548cfb3d445). Reverting to previous one fixes the issue.

**Comment by tlfeng** [comment]
I attempted to build OpenSearch and the 2 plugins from 2.x branch directly with `Gradle` command, and the native plugins can be installed properly, although I didn't use the [docker image](https://hub.docker.com/layers/opensearchstaging/ci-runner/ci-runner-centos7-opensearch-build-v2.4/images/sha256-3195a1ff36386241be5bb4e904ae56b60d622e0638768ba671c1b08042572025?context=explore) you mentioned.

```
./gradlew :distribution:archives:linux-tar:assemble
./gradlew :plugins:repository-s3:assemble
./gradlew :plugins:repository-azure:assemble
```
```
bin/opensearch-plugin install file:///home/user/Downloads/opensearch/2.7.0/repository-s3-2.7.0-SNAPSHOT.zip
-> Installing file:///home/user/Downloads/opensearch/2.7.0/repository-s3-2.7.0-SNAPSHOT.zip
-> Downloading file:///home/user/Downloads/opensearch/2.7.0/repository-s3-2.7.0-SNAPSHOT.zip
[=================================================] 100%   
...

Continue with installation? [y/N]y
-> Installed repository-s3 with folder name repository-s3
```

**Comment by dgilling** [comment]
My fault, after looking at it, my Dockerfile missed including the updated opensearch-cli jar
