### ISSUE TITLE
[BUG] [Searchable Snapshot] Failed to download file

### ISSUE THREAD

**Issue by dgilling** [opensearch-project/OpenSearch#6996]
**Describe the bug**

**To Reproduce**
1. Set up a cluster with both data and search nodes
2. Restore large indices (over 1GB) as remote backed/searchable snapshot
3.  Perform a very simple query:

```
curl localhost:9200/my_index/_search -d '{}'
```

Some indices will error out on missing files. Happens only after upgrading to:
* Build 7489
* OpenSearch 2.x commit 5cf4c5d3bcfb0f1150779bba9819f13b163e9609
* Has both #6927 and #6914 PRs

```
 [2023-04-05T06:46:37,974][WARN ][o.o.i.s.r.u.TransferManager] [5fdf542a5a92] Failed to download /usr/share/opensearch/data/nodes/0/cache/0/wHcZP047QQ2WBVhvDBnRZw/0/RemoteLocalStore/_1bv_Lucene90_0.dvd.648
 java.nio.file.NoSuchFileException: /usr/share/opensearch/data/nodes/0/cache/0/wHcZP047QQ2WBVhvDBnRZw/0/RemoteLocalStore/_1bv_Lucene90_0.dvd.648
 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
 	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
 	at org.opensearch.index.store.remote.utils.TransferManager.downloadBlockLocally(TransferManager.java:105) ~[opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.utils.TransferManager.lambda$fetchBlob$0(TransferManager.java:61) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.utils.cache.LRUCache.compute(LRUCache.java:178) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.utils.cache.SegmentedCache.compute(SegmentedCache.java:95) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.filecache.FileCache.compute(FileCache.java:64) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.utils.TransferManager.lambda$fetchBlob$1(TransferManager.java:58) [opensearch-2.7.0.jar:2.7.0]
 	at java.security.AccessController.doPrivileged(AccessController.java:318) [?:?]
 	at org.opensearch.index.store.remote.utils.TransferManager.fetchBlob(TransferManager.java:57) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.fetchBlock(OnDemandBlockSnapshotIndexInput.java:147) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.demandBlock(OnDemandBlockIndexInput.java:340) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.seekInternal(OnDemandBlockIndexInput.java:311) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.seek(OnDemandBlockIndexInput.java:209) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.seek(OnDemandBlockSnapshotIndexInput.java:28) [opensearch-2.7.0.jar:2.7.0]
 	at org.apache.lucene.codecs.lucene90.IndexedDISI.advanceBlock(IndexedDISI.java:484) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
 	at org.apache.lucene.codecs.lucene90.IndexedDISI.advance(IndexedDISI.java:442) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
 	at org.apache.lucene.codecs.lucene90.Lucene90DocValuesProducer$SparseNumericDocValues.advance(Lucene90DocValuesProducer.java:448) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
 	at org.apache.lucene.search.ConstantScoreScorer$DocIdSetIteratorWrapper.advance(ConstantScoreScorer.java:48) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
 	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:252) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
 	at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71) [opensearch-2.7.0.jar:2.7.0]
 	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
 	at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:279) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:250) [opensearch-2.7.0.jar:2.7.0]
 	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:551) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
 	at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:336) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWithCollector(QueryPhase.java:414) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:403) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:262) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:149) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:526) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:590) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:559) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) [opensearch-2.7.0.jar:2.7.0]
 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.7.0.jar:2.7.0]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
 	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dgilling** [comment]
FYI @kotwanikunal @andrross

**Comment by andrross** [comment]
@dgilling Is this consistent or intermittent? Does it happen on all of your large indexes?

Any chance you could paste a snapshot of the stats from `GET _nodes/stats/file_cache` around when this happens?

**Comment by dgilling** [comment]
@andrross , it was consistent, but only about 60% of indices would hit this issue. After I cleared the data/cache directory and restarted the `search` nodes, haven't seen it for 12 hrs. My thinking is something got corrupted. We'll continue to monitor.

**Comment by andrross** [comment]
@dgilling Is it possible you had exiting data on disk from a version of the software that defined a different block size? The code today doesn't handle that case.

**Comment by dgilling** [comment]
No, they were brand new VMs. 

For context, we were initially testing with a custom build that had the two patches (#6927 and # 6914) on top of [this commit](https://github.com/opensearch-project/OpenSearch/commit/8b476109964c90b5dfc2c8a722459c94e86e4a72) from last week (before fixes were merged).

We did see a weird issue where the `search` nodes would stop responding to certain cluster commands like the stats API even though still part of cluster and could still execute other commands. i.e. `localhost:9200/_nodes/5c8565afee28/stats` would respond with 

```
{"_nodes":{"total":1,"successful":0,"failed":1,"failures":[{"type":"failed_node_exception","reason":"Failed node [e2Lm1TxM12R4eWAcnmihGO]","node_id":"e2Lm1TxM12R4eWAcnmihGO","caused_by":{"type":"receive_timeout_transport_exception","reason":"[c85655afee28][10.10.0.2:9300][cluster:monitor/nodes/stats[n]] request_id [63271493] timed out after [30023ms]"}}]},"cluster_name":"elasticsearch-test-script-patch","nodes":{}}
```

So we upgraded the nodes to latest 2.7 snapshot with [commit 5cf4c5d3bcfb0f1150779bba9819f13b163e9609]( https://github.com/opensearch-project/OpenSearch/commit/5cf4c5d3bcfb0f1150779bba9819f13b163e9609) from Dockerhub. So far, haven't seen the hang anymore but then saw the file error last night. Perhaps by upgrading from last weeks commit to latest commit caused it (but we didnt see any large changes related to file cache).

**Comment by dgilling** [comment]
@anasalkouz @andrross 

We wiped and looks like it started happening again after about 24hrs running. Don't yet see a pattern on why/when it happens as its not every index but seems random. 
I don't see any HTTP errors on the repository side. 

Boot time was `2023-04-05T07:04:00`
First log below at `2023-04-06T09:01:55`

```
[2023-04-06T09:01:55,628][WARN ][o.o.i.s.r.u.TransferManager] [dfe5b4ea68f0] Failed to download /usr/share/opensearch/data/nodes/0/cache/0/GO8MGPXyQ9aiV5F9atyXRA/0/RemoteLocalStore/_4r4.fdt.163
java.nio.file.NoSuchFileException: /usr/share/opensearch/data/nodes/0/cache/0/GO8MGPXyQ9aiV5F9atyXRA/0/RemoteLocalStore/_4r4.fdt.163
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
	at org.opensearch.index.store.remote.utils.TransferManager.downloadBlockLocally(TransferManager.java:105) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.utils.TransferManager.lambda$fetchBlob$0(TransferManager.java:61) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.utils.cache.LRUCache.compute(LRUCache.java:178) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.utils.cache.SegmentedCache.compute(SegmentedCache.java:95) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.filecache.FileCache.compute(FileCache.java:64) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.utils.TransferManager.lambda$fetchBlob$1(TransferManager.java:58) [opensearch-2.7.0.jar:2.7.0]
	at java.security.AccessController.doPrivileged(AccessController.java:318) [?:?]
	at org.opensearch.index.store.remote.utils.TransferManager.fetchBlob(TransferManager.java:57) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.fetchBlock(OnDemandBlockSnapshotIndexInput.java:147) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.demandBlock(OnDemandBlockIndexInput.java:340) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.seekInternal(OnDemandBlockIndexInput.java:311) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.seek(OnDemandBlockIndexInput.java:209) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.seek(OnDemandBlockSnapshotIndexInput.java:28) [opensearch-2.7.0.jar:2.7.0]
	at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.serializedDocument(Lucene90CompressingStoredFieldsReader.java:608) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.document(Lucene90CompressingStoredFieldsReader.java:630) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.SegmentReader.document(SegmentReader.java:253) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.FilterCodecReader.document(FilterCodecReader.java:90) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.FilterLeafReader.document(FilterLeafReader.java:404) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.FilterLeafReader.document(FilterLeafReader.java:404) [lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.opensearch.search.fetch.FetchPhase.loadStoredFields(FetchPhase.java:563) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.search.fetch.FetchPhase.prepareNonNestedHitContext(FetchPhase.java:337) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.search.fetch.FetchPhase.prepareHitContext(FetchPhase.java:298) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.search.fetch.FetchPhase.execute(FetchPhase.java:169) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.search.SearchService.lambda$executeFetchPhase$3(SearchService.java:761) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) [opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.7.0.jar:2.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by andrross** [comment]
Thanks @dgilling, we're looking into this.

If you get a few minutes, can you share some details about your test setup? Specifically, I'm interested in:
- Number of searchable snapshot indexes
- Estimate on the total size of the indexes in the remote repository
- Number of search nodes, and the configured cache size
- Whether search nodes are dedicated or also configured as data nodes
- Maybe a brief description of the type of search load being executed against the searchable snapshot indexes

Thanks again for all your help here!

**Comment by dgilling** [comment]
I also see "Error removing items from cache during shard deletion" just before the failed download errors creep up. Could be that deletion of indices is messing things up or inadvertently clearing cache. Let me disable this and test.

**Comment by andrross** [comment]
I think the fix to clean up empty directories [that were left after an index is deleted from a node](https://github.com/opensearch-project/OpenSearch/issues/6532) has unintended consequence of blowing away the whole index directory in the cache when a shard is removed. That does not work in the case that a node has multiple shards for the same index, which will be in that directory. We should be deleting the whole index cache directory on the "index removed" event, and only delete the shard path on the "index shard deleted" events.

**Comment by dgilling** [comment]
Confirmed that reverting PR #6856 on 2.x branch looks to have fixed the issue.
