### ISSUE TITLE
Guice error when installing OpenSearch plugin on an extension

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/OpenSearch#7016]
I have been attempting to modify the OpenSearch gradle plugin to work with extensions in order to build an integration test framework.  When the gradle plugin is applied in the SDK `build.gradle` file, gradle check passes but starting any extensions fails with the following error: 
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Stopwatch
        at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:64)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at org.opensearch.sdk.ExtensionsRunner.<init>(ExtensionsRunner.java:221)
        at org.opensearch.sdk.ExtensionsRunner.run(ExtensionsRunner.java:726)
        at org.opensearch.sdk.sample.helloworld.HelloWorldExtension.main(HelloWorldExtension.java:82)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Stopwatch
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more
```

Per discussion with @dbwiddis, this error used to occur in the older versions of Guice, prior to version 5.1.0, which we are using on the SDK.  However, in the OpenSearch repository, we are using a vendored version of Guice, so it is not imported anywhere and may still be on a previous version.  I have tried downgrading the version to 5.0, but that still causes the error, and we are using new methods from the 5.x versions of Guice so we cannot downgrade to 4.x.  I also checked to ensure that the guava versions are consistent for both OpenSearch and the SDK, which both use guava 31.1-jre.  Is there a way to upgrade the vendored Guice on OpenSearch to the 5.1 functionality, or is there another way that this issue can be mitigated?

**Comment by ryanbogan** [comment]
@dblock @reta Have you seen anything like this before?

**Comment by reta** [comment]
> @dblock @reta Have you seen anything like this before?

Nope, not yet

**Comment by peternied** [comment]
@ryanbogan Do you have a branch on a fork or pull request where this is reproduced?

**Comment by dbwiddis** [comment]
Some debugging details:
 - the stack trace line causing the error, `com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:64)` is associated with current Guice version that we are importing and was part of Guice 5.0.0 (and later).
 - Guice has a transitive dependency on guava 31.0.1-jre
 - the `com/google/common/base/Stopwatch` class not being found on the classpath is a longstanding part of Guava (since version 15)

My suspicion is something is happening in the OpenSearch gradle plugin that is interfering with Guava being on the class path.

**Comment by ryanbogan** [comment]
We were able to get past the NoClassDefinitionFoundErrors by adding the following explicit dependencies:
```
implementation("com.google.guava:guava:${guavaVersion}")
implementation('javax.inject:javax.inject:1')
implementation('com.google.guava:failureaccess:1.0.1')
implementation('aopalliance:aopalliance:1.0')
```
It seems that there is some transitive issue related to modules where the dependencies are not being accessed properly through the gradle plugin.  The new error that I'm seeing is this:
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) 
throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @336eb6ed
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.google.inject.internal.cglib.core.$ReflectUtils$1.run(ReflectUtils.java:61)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:52)
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
        ... 65 more
```

This points to a problem with Java Modules (JPMS) that I am still debugging.  Does anyone know something about modules that could be causing this?

**Comment by ryanbogan** [comment]
I was able to compile and run the extension on JDK 11, which unblocks me for now.

**Comment by dbwiddis** [comment]
Digging deeper it seems like Guice may be incompatible with JDK17 due to access constraints (JEP 304).  I haven't confirmed this but see various complaints around the internet about Guice being abandonware, etc.

One possible solution is to change our injection to `org.opensearch.inject` using the same current injection model as plugins, but I feel _really_ iffy about adding another tightly integrated OpenSearch dependency to the SDK.

@nknize @dblock @reta @andrross Any thoughts/ideas?

**Comment by dbwiddis** [comment]
To be more clear, it's not Guice itself but the Guava dependency that is apparently shaded, that seems to be why we were seeing classpath issues.

I have fought (and lost) JPMS vs. shaded dependency battles in the past, and really don't know the next step here.

**Comment by dbwiddis** [comment]
And one more post for absolute clarity on what the ask is:

1. SDK project depends on Guice. This works fine for manual testing.
2. As part of setting up IT, @ryanbogan is trying to use the OpenSearch Gradle Plugin
3. Simply including the OpenSearch Gradle Plugin into our build.gradle breaks Guice transitive dependencies
   - Working around the transitive dependency issues by declaring them ourselves results in JDK access issues associated with java internal classes (JEP 304) that fail on JDK 17+
   - Further research indicates Guice has worked around these with a shaded JAR

What we need help with:
1. Does anyone know why the OpenSearch Gradle Plugin is removing the dependencies or how to fix it?
2. If we can't fix the plugin via step 1, an alternative is to switch our dependency injection to the internal OpenSearch implementation.  Are there any reasons we should _not_ do this?

**Comment by dbwiddis** [comment]
So it looks like excluding transitive dependencies is by-design in the OpenSearchJava plugin:
https://github.com/opensearch-project/OpenSearch/blob/0db20d99d4e06ddb261429466a8072501cc15941/buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java#L144

I presume this is done in order to have reproducible tests that don't fail randomly with new transitive dependencies.  

So the solution is to add the correct transitive dependencies to the plugin configuration, which @ryanbogan has done and works with JDK <= 16.  This is still causing issues associated with the Guava dependency.  So a partial answer to 1 but no progress on "how to fix it" and the question still stands on whether using the OpenSearch injection implementation is a "safe" path forward.

**Comment by saratvemulapalli** [comment]
Hey @ryanbogan what are the next steps for this issue?
