### ISSUE TITLE
[BUG][Segment Replication] Failing tests with segment replication enabled due to codec check 

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#7058]
**Describe the bug**
Certain test suites (such as searchableSnapshotIT) are failing due to a change introducing a codec compatibility check in #6730. Can see the below error in logs: 
```
Caused by: org.opensearch.common.util.CancellableThreads$ExecutionCancelledException: ParameterizedMessage[messagePattern=Requested unsupported codec version {}, stringArgs=[Lucene95], throwable=null]
	at org.opensearch.indices.replication.OngoingSegmentReplications.prepareForReplication(OngoingSegmentReplications.java:154) ~[main/:?]
	at org.opensearch.indices.replication.SegmentReplicationSourceService$CheckpointInfoRequestHandler.messageReceived(SegmentReplicationSourceService.java:137) ~[main/:?]
	at org.opensearch.indices.replication.SegmentReplicationSourceService$CheckpointInfoRequestHandler.messageReceived(SegmentReplicationSourceService.java:118) ~[main/:?]
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[main/:?]
	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453) ~[main/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[main/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
```

**To Reproduce**
1. Enable segment replication and run tests

**Expected behavior**
Tests should pass with no execution cancelled exception. 

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dreamer-89** [comment]
@Poojita-Raj : Any update on this issue ? Do we need to revert https://github.com/opensearch-project/OpenSearch/pull/6730

**Comment by Poojita-Raj** [comment]
The tests are failing with segment replication enabled because for these test suites, there's logic during setup that overrides the default codec setup with a random codec. This causes a ReplicationFailedException due to unsupported codec versions. 

For example, below you can see that the test parameters includes codec as Asserting(Lucene95) when we are expecting Lucene95.  This is what  is causing a mismatch. 

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SearchableSnapshotIT.testSearchableSnapshotAllocationForLocalAndRemoteShardsOnSameNode" -Dtests.seed=80CAAD5B4779CE40 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-Latn-RS -Dtests.timezone=Africa/Banjul -Druntime.java=17
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SearchableSnapshotIT.testSearchableSnapshotAllocationForLocalAndRemoteShardsOnSameNode" -Dtests.seed=80CAAD5B4779CE40 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-Latn-RS -Dtests.timezone=Africa/Banjul -Druntime.java=17
NOTE: leaving temporary files on disk at: /Users/poojiraj/OpenSearch/server/build/testrun/internalClusterTest/temp/org.opensearch.snapshots.SearchableSnapshotIT_80CAAD5B4779CE40-001
NOTE: test params are: codec=Asserting(Lucene95): {index_uuid=PostingsFormat(name=Asserting), type=Lucene90}, docValues:{}, maxPointsInLeafNode=112, maxMBSortInHeap=6.8884812655460355, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=sr-Latn-RS, timezone=Africa/Banjul
NOTE: Mac OS X 12.3.1 x86_64/Eclipse Adoptium 17.0.6 (64-bit)/cpus=8,threads=1,free=221359304,total=536870912
NOTE: All tests run in this JVM: [SearchableSnapshotIT]
``` 

Found this while looking into why adding this annotation - 
```
@OpenSearchIntegTestCase.ClusterScope(scope = OpenSearchIntegTestCase.Scope.TEST, numDataNodes = 0) 
```
to searchablesnapshotIT class reduces failures. And that's because OpenSearchIntegTestCase extends OpenSearchTestCase that suppresses a list of most codecs.

**Comment by Poojita-Raj** [comment]
Segment replication is not causing any failures. 
It is due to the picking of a random codec by the test suites and overriding the default codec during setup of test suite.
