### ISSUE TITLE
[BUG] [Segment Replication] Timer already stopped during failover

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#7063]
Spotted this failure while working on #6762, where test `testDropPrimaryDuringReplication` fails with timer [already stopped](https://github.com/opensearch-project/OpenSearch/blob/0db20d99d4e06ddb261429466a8072501cc15941/server/src/main/java/org/opensearch/indices/replication/common/ReplicationTimer.java#L82) on older primary. This is not a flaky test failure but a probable concurrency issue, revealed with this test.

This failure happened after ~2k runs while validating https://github.com/opensearch-project/OpenSearch/pull/7062 fix
```
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.indices.replication.SegmentReplicationIT.testDropPrimaryDuringReplication" -Dtests.seed=708484E484F0A9F4 -Dtests.locale=is-IS -Dtests.timezone=America/Guatemala -Druntime.java=17

com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=404592, name=opensearch[node_t1][generic][T#8], state=RUNNABLE, group=TGRP-SegmentReplicationIT]

	at __randomizedtesting.SeedInfo.seed([708484E484F0A9F4:DDC027AC3360105E]:0)
Caused by: java.lang.AssertionError: already stopped
	at __randomizedtesting.SeedInfo.seed([708484E484F0A9F4]:0)
	at org.opensearch.indices.replication.common.ReplicationTimer.stop(ReplicationTimer.java:82)
	at org.opensearch.indices.replication.SegmentReplicationSourceHandler.lambda$sendFiles$4(SegmentReplicationSourceHandler.java:131)
	at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88)
	at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:82)
	at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:126)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
	at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120)
	at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112)
	at org.opensearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:160)
	at org.opensearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:141)
	at org.opensearch.action.StepListener.innerOnResponse(StepListener.java:77)
	at org.opensearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:55)
	at org.opensearch.indices.recovery.MultiChunkTransfer.onCompleted(MultiChunkTransfer.java:175)
	at org.opensearch.indices.recovery.MultiChunkTransfer.handleItems(MultiChunkTransfer.java:144)
	at org.opensearch.indices.recovery.MultiChunkTransfer$1.write(MultiChunkTransfer.java:98)
	at org.opensearch.common.util.concurrent.AsyncIOProcessor.processList(AsyncIOProcessor.java:129)
	at org.opensearch.common.util.concurrent.AsyncIOProcessor.drainAndProcessAndRelease(AsyncIOProcessor.java:117)
	at org.opensearch.common.util.concurrent.AsyncIOProcessor.put(AsyncIOProcessor.java:95)
	at org.opensearch.indices.recovery.MultiChunkTransfer.addItem(MultiChunkTransfer.java:109)
	at org.opensearch.indices.recovery.MultiChunkTransfer.lambda$handleItems$3(MultiChunkTransfer.java:151)
	at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:80)
	at org.opensearch.action.ActionListener$6.onResponse(ActionListener.java:299)
	at org.opensearch.action.ActionListener$4.onResponse(ActionListener.java:180)
	at org.opensearch.action.ActionListener$6.onResponse(ActionListener.java:299)
	at org.opensearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:181)
	at org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:69)
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1381)
	at org.opensearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:393)
	at org.opensearch.transport.InboundHandler.lambda$handleResponse$1(InboundHandler.java:387)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mch2** [comment]
Closing this, should also be fixed with https://github.com/opensearch-project/OpenSearch/commit/3d7d33bdbc02ec8e363c5394a9d89451f76e979a by moving timer.stop() out of finalize step.
