### ISSUE TITLE
[BUG] Install of analysi-icu plugin fails in beta1

### ISSUE THREAD

**Issue by janhoy** [opensearch-project/OpenSearch#709]
**Describe the bug**
Trying to do install analysis-icu plugin from docker container fails with HTTP 403

**To Reproduce**
1. `docker run -ti opensearchproject/opensearch:1.0.0-beta1 bash`
2. `bin/opensearch-plugin install analysis-icu`
3. See error

```
-> Installing analysis-icu
-> Downloading analysis-icu from opensearch
-> Failed installing analysis-icu
-> Rolling back analysis-icu
-> Rolled back analysis-icu
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/analysis-icu/1.0.0/analysis-icu-1.0.0-beta1.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.opensearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:438)
	at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:515)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:306)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60
```

**Expected behavior**
Plugin installed

**Plugins**
(none)

**Screenshots**
(None)

**Host/Environment (please complete the following information):**
Docker (macos)

**Additional context**
(none)

**Comment by CEHENKLE** [comment]
I suspect this may be related to https://github.com/opensearch-project/OpenSearch/issues/693?  

Thanks,
/C

**Comment by janhoy** [comment]
I think it is simply the artifacts.opensearch.org site that requires some authorization. Try to download that plug-in zip from your browser and you get same 403 response. Perhaps it is some firewall rules that allow requests from inside Amazon networks but not from outside?

**Comment by peterzhuamazon** [comment]
We dont have plugins zips on `artifacts.opensearch.org` yet. Need @nknize or @dblock to help explain what is the purpose of this plugin and usages.

**Comment by nknize** [comment]
It integrates the Lucene ICU analysis module which process extended Unicode support using the [ICU libraries](http://site.icu-project.org). It's extremely useful and well done.  I think the holdup here is more related to figuring out how the plugin artifacts will be made available (maven, bundle, individual archives, bundle archives, etc.)

**Comment by janhoy** [comment]
Ok thanks, guess I cannot test-drive OpenSearch in my project yet then..

**Comment by dblock** [comment]
@peterzhuamazon is this expected to work with GA?
