### ISSUE TITLE
[BUG] Unable to parse response body for Response during `UpdateRequest

### ISSUE THREAD

**Issue by onsah** [opensearch-project/OpenSearch#7365]
**Describe the bug**
```
java.io.IOException: Unable to parse response body for Response{requestLine=POST /foo_index/_update/7a7a2e40-ed56-40dd-a40c-cfd8a20120c6?timeout=1m HTTP/1.1, host=<REDACTED> response=HTTP/1.1 200 OK}
```
Cause stack trace:
```
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116)
        at org.elasticsearch.action.update.UpdateResponse.<init>(UpdateResponse.java:54)
        at org.elasticsearch.action.update.UpdateResponse$Builder.build(UpdateResponse.java:161)
        at org.elasticsearch.action.update.UpdateResponse.fromXContent(UpdateResponse.java:125)
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
        at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:1595)
        ...
```

**To Reproduce**
1. Make a request using Elastic Search Java REST Client
2. Response parsing fails

**Expected behavior**
Expected the client to be able to parse the `Response`.

**Plugins**
No plugins

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Mac & Linux (I got the same error on both environments)
 - OpenSearch Version: 2.5
 - Client Version: Elastic Search Java REST client 7.10.1 

**Additional context**
I am using Elastic Search High Level REST API, not OpenSearch one.

I tracked the cause, it seems like because `type` is removed from the API. The Java client still expects `type` to be present
```
public DocWriteResponse(ShardId shardId, String type, String id, long seqNo, long primaryTerm, long version, Result result) {
        this.shardId = Objects.requireNonNull(shardId);
        this.type = Objects.requireNonNull(type);
        this.id = Objects.requireNonNull(id);
        this.seqNo = seqNo;
        this.primaryTerm = primaryTerm;
        this.version = version;
        this.result = Objects.requireNonNull(result);
    }
```

**Comment by dbwiddis** [comment]
Hey @onsah this seems expected?  While OpenSearch 1.x was compatible with ES, there may be breaking changes in 2.x that don't permit the same clients to work.  Can you use the OpenSearch Java REST client?

**Comment by andrross** [comment]
Resolving as the elasticsearch client is not supported. Please reopen if you believe there is a bug in OpenSearch.
