### ISSUE TITLE
[BUG] Flaky org.opensearch.indices.replication.SegmentReplicationIT.testScrollCreatedOnReplica test

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#7556]
**Describe the bug**
Flaky org.opensearch.indices.replication.SegmentReplicationIT.testScrollCreatedOnReplica

**To Reproduce**
https://build.ci.opensearch.org/job/gradle-check/15383

**Expected behavior**
The test shall always pass.

**Plugins**
NA

**Comment by ashking94** [comment]
@dreamer-89  do take a look at this.

**Comment by andrross** [comment]
Another failure here: #7892

**Comment by tlfeng** [comment]
Detailed message in the above test runs:
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationIT.testScrollCreatedOnReplica" -Dtests.seed=5E8BE4AC6E063D80 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-ES -Dtests.timezone=Asia/Yekaterinburg -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationIT > testScrollCreatedOnReplica FAILED
    java.lang.AssertionError: Files should be preserved
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.opensearch.indices.replication.SegmentReplicationIT.testScrollCreatedOnReplica(SegmentReplicationIT.java:948)

    java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
        at org.opensearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:71)
        at org.opensearch.test.OpenSearchTestCase.lambda$ensureAllSearchContextsReleased$10(OpenSearchTestCase.java:656)
...
```
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationIT.testScrollCreatedOnReplica" -Dtests.seed=E856C16957444948 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=mk-MK -Dtests.timezone=Africa/Asmara -Druntime.java=20

org.opensearch.indices.replication.SegmentReplicationIT > testScrollCreatedOnReplica FAILED
    java.lang.AssertionError: Files should be preserved
        at __randomizedtesting.SeedInfo.seed([E856C16957444948:F58512EE41EB063D]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.opensearch.indices.replication.SegmentReplicationIT.testScrollCreatedOnReplica(SegmentReplicationIT.java:950)
```

**Comment by tlfeng** [comment]
I added the above logs in the code and ran the test locally.
I ran the whole integration test suite `SegmentReplicationIT` in a loop of 5k times, there were 3 failures with the error message `java.lang.AssertionError: Files should be preserved`. I will post the detail for further investigation.
