### ISSUE TITLE
[BUG] StartupException jar hell

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/OpenSearch#7577]
**Describe the bug**
Can't start OpenSearch freshly built from `main`.

**To Reproduce**
1. Checkout `main` @ 6f65afbd3
2. Build `./gradlew :distribution:archives:linux-tar:assemble` or `.\gradlew.bat :distribution:archives:linux-tar:assemble`
3. Unpack archive
4. Start

```
uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: jar hell!
class: org.opensearch.common.Numbers
jar1: /mnt/c/GitHub/cluster/3.0.0-l/lib/opensearch-3.0.0-SNAPSHOT.jar
jar2: /mnt/c/GitHub/cluster/3.0.0-l/lib/opensearch-common-3.0.0-SNAPSHOT.jar
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: jar hell!
class: org.opensearch.common.Numbers
jar1: /mnt/c/GitHub/cluster/3.0.0-l/lib/opensearch-3.0.0-SNAPSHOT.jar
jar2: /mnt/c/GitHub/cluster/3.0.0-l/lib/opensearch-common-3.0.0-SNAPSHOT.jar
        at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316) ~[opensearch-common-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215) ~[opensearch-common-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:102) ~[opensearch-common-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        ... 6 more
uncaught exception in thread [main]
java.lang.IllegalStateException: jar hell!
class: org.opensearch.common.Numbers
jar1: /mnt/c/GitHub/cluster/3.0.0-l/lib/opensearch-3.0.0-SNAPSHOT.jar
jar2: /mnt/c/GitHub/cluster/3.0.0-l/lib/opensearch-common-3.0.0-SNAPSHOT.jar
        at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316)
        at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215)
        at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:102)
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
For complete error details, refer to the log at /mnt/c/GitHub/cluster/3.0.0-l/logs/opensearch.log
```

**Comment by reta** [comment]
Thanks @Yury-Fridlyand , I believe it was cause by numerous refactorings & conflict resolutions, looking into it now

**Comment by reta** [comment]
@Yury-Fridlyand could you please run `clean` task as well: `./gradlew clean :distribution:archives:linux-tar:assemble` ?

**Comment by Yury-Fridlyand** [comment]
I had to clean gradle cache and m2 cache too to make things working.
Did you publish modified jars without bumping the version?

**Comment by reta** [comment]
> Did you publish modified jars without bumping the version?

What you mean? We publish snapshot periodically

**Comment by Yury-Fridlyand** [comment]
This constantly causes troubles for all modules which depends on these snapshots.
The approach should be changed as it is discussed in #7326.
