### ISSUE TITLE
[BUG] Not able to run OpenSearch via ./gradlew run on mac due to CommonAnalysisModulePlugin

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#7579]
**Describe the bug**
Not able to run OpenSearch via ./gradlew run on mac due to CommonAnalysisModulePlugin

**To Reproduce**
1. Checkout this repository's main branch.
2. Run ./gradlew run

**Expected behavior**
OpenSearch should be able to start.

**Plugins**
No custom plugin. All plugins provided in this repo.

**Logs**
```
uncaught exception in thread [main]
OpenSearchException[Unable to load plugin class [org.opensearch.analysis.common.CommonAnalysisModulePlugin]]; nested: ClassNotFoundException[org.opensearch.analysis.common.CommonAnalysisModulePlugin];
Likely root cause: java.lang.ClassNotFoundException: org.opensearch.analysis.common.CommonAnalysisModulePlugin
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:904)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.opensearch.plugins.PluginsService.loadPluginClass(PluginsService.java:758)
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:719)
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533)
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195)
	at org.opensearch.node.Node.<init>(Node.java:450)
	at org.opensearch.node.Node.<init>(Node.java:377)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
For complete error details, refer to the log at /Users/navneev/workplace/OpenSearch/build/testclusters/runTask-0/logs/runTask.log
```

**Host/Environment (please complete the following information):**
 - OS: Mac OS

**Additional context**

**Comment by dblock** [comment]
Odd. Works on my machine (M1).

**Comment by navneet1v** [comment]
Can you remove all the gradle cache and maven local repository, and then try @dblock

**Comment by dblock** [comment]
Still works.

```
$ ./gradlew clean
$ rm -rf ~/.m2/repository/
$ ./gradlew run
```

```
$ curl -v http://127.0.0.1:9200
*   Trying 127.0.0.1:9200...
* Connected to 127.0.0.1 (127.0.0.1) port 9200 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:9200
> User-Agent: curl/7.87.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 498
< 
{
  "name" : "runTask-0",
  "cluster_name" : "runTask",
  "cluster_uuid" : "a8l6xANsQey85BThG2LoSg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "3.0.0",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "unknown",
    "build_snapshot" : true,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "2.8.0",
    "minimum_index_compatibility_version" : "2.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by navneet1v** [comment]
./gradlew clean doesn't clean the gradle cache.

You need to remove the folder:
`~/.gradle/caches`

**Comment by dblock** [comment]
Still runs for me. I'm not saying there's no problem somewhere, I just think you may be chasing a red herring.

**Comment by navneet1v** [comment]
I will close this issue. I am not facing any issue now. Seems like something with setup. I agree that was a red herring
