### ISSUE TITLE
[BUG] The build fails with java.lang.OutOfMemoryError: Java heap space 

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#7746]
**Describe the bug**

The `java.lang.OutOfMemoryError: Java heap space ` is back

```
Could not read standard output of command '/usr/lib/jvm/temurin-17-jdk-amd64/bin/java'.
java.lang.OutOfMemoryError: Java heap space
	at java.****/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.****/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.****/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:67)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.****/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.****/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.****/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
https://build.ci.opensearch.org/job/gradle-check/16255/.

**Comment by minalsha** [comment]
@reta  could you please add some details? Thanks

**Comment by reta** [comment]
There aren't much - the builds fail, you could see the error in the description, everything else has to be investigated sadly ....

**Comment by reta** [comment]
> Is there any way we can enable `-XX:+HeapDumpOnOutOfMemoryError` on the builds to get more information in the logs?

It is there [1] but it is not available as Jenkins artifact (as it supposed to [2]), so the dump is not accessible

[1] https://github.com/opensearch-project/OpenSearch/issues/3973#issuecomment-1227886974
[2] https://github.com/opensearch-project/opensearch-build/pull/2515
