### ISSUE TITLE
[BUG] org.opensearch.remotestore.ReplicaToPrimaryPromotionIT.testPromoteReplicaToPrimary is flaky

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#7791]
**Describe the bug**
org.opensearch.remotestore.ReplicaToPrimaryPromotionIT.testPromoteReplicaToPrimary is flaky

```
[127.0.0.1:33059][indices:admin/refresh[s][p]]]; nested: RetryOnPrimaryException[shard is not in primary mode]; nested: ShardNotInPrimaryModeException[CurrentState[STARTED] shard is not in primary mode]; ]]
Expected: <0>
     but: was <4>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertNoFailures(OpenSearchAssertions.java:374)
	at org.opensearch.test.OpenSearchIntegTestCase.refresh(OpenSearchIntegTestCase.java:1415)
	at org.opensearch.remotestore.ReplicaToPrimaryPromotionIT.testPromoteReplicaToPrimary(ReplicaToPrimaryPromotionIT.java:115)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
```

#### Additional Context
https://build.ci.opensearch.org/job/gradle-check/16411/

**Comment by sachinpkale** [comment]
This does not seem to be a problem with main branch. Ran the test 100 times successfully. Seems to be issue with https://github.com/opensearch-project/OpenSearch/pull/7777. Fixing it as part of the PR.

**Comment by sachinpkale** [comment]
Ran the test 200+ times on local without any failures.

**Comment by mch2** [comment]
Re-opening - https://build.ci.opensearch.org/job/gradle-check/37390/

**Comment by linuxpi** [comment]
[Storage Triage - attendees [1](https://github.com/ashking94/) [2](https://github.com/sachinpkale/) [3](https://github.com/gbbafna/) [4](https://github.com/astute-decipher/) [5](https://github.com/skumawat2025/) [6](https://github.com/shourya035/) [7](https://github.com/vikasvb90/) [8](https://github.com/BhumikaSaini-Amazon/) [9](https://github.com/ltaragi/) [10](https://github.com/lukas-vlcek/) [11](https://github.com/reta/) [12](https://github.com/sachinpkale/)]

@sachinpkale Please check if this is the same issue, else we can open a new one and close this.

**Comment by sandeshkr419** [comment]
Duplicate: https://github.com/opensearch-project/OpenSearch/issues/16160
