### ISSUE TITLE
[BUG] NoSuchFileException during performance runs with remote store enabled

### ISSUE THREAD

**Issue by raghuvanshraj** [opensearch-project/OpenSearch#7815]
**Describe the bug**
- Using repository-s3 plugin
- Remote segment and remote translog store enabled
- The following stacktrace shows up in logs during performance runs with multiple iterations:
```
[2023-05-29T14:56:03,908][WARN ][o.o.i.s.RemoteStoreRefreshListener] [node-3] Exception while uploading new segments to the remote segment store
java.nio.file.NoSuchFileException: /home/ec2-user/opensearch-3.0.0-SNAPSHOT/data/nodes/0/indices/uFqyS_KvTSi_QauIfVr-FA/5/index/segments_7
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:304) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:363) ~[?:?]
	at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
	at org.opensearch.index.store.FsDirectoryFactory$HybridDirectory.openInput(FsDirectoryFactory.java:166) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
	at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:156) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:298) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
	at org.opensearch.index.shard.RemoteStoreRefreshListener.syncSegments(RemoteStoreRefreshListener.java:225) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.shard.RemoteStoreRefreshListener.lambda$afterSegmentsSync$4(RemoteStoreRefreshListener.java:340) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
```

**To Reproduce** [WIP]

**Expected behavior**
If the file is deleted in local directory, attempts should not be made to upload it to remote store.

**Plugins**
repository-s3

**Host/Environment (please complete the following information):**
```
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Additional context**
A single iteration during these runs involves creating and index, ingesting ~30GB of data on it, then deleting the index. At the end of the run, there is only one index, corresponding to the last run. Output of `_cat/indices?v` at the end of the run:
```
health status index uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   so    uFqyS_KvTSi_QauIfVr-FA   6   1   36062278            0     61.7gb         30.8gb
```

**Comment by ashking94** [comment]
This should not happen as we acquire lock for the segment infos and that ensures that the referenced files are not deleted or merged away.

**Comment by linuxpi** [comment]
I think i have seen this happen when the File Descriptors limit is reached on the node. @raghuvanshraj do you have the data around FDs around that time?

**Comment by ashking94** [comment]
Saw this issue while running on docker setup. I was able to validate that the file does not exist in the local while get segment infos snapshot is returning this file. We will need to debug this further -
```
opensearch-node1    | [2023-06-04T07:03:15,967][WARN ][o.o.i.s.RemoteStoreRefreshListener] [opensearch-node1] Exception while uploading new segments to the remote segment store
opensearch-node1    | java.nio.file.NoSuchFileException: /usr/share/opensearch/data/nodes/0/indices/v1_nAJqMSjuNs-fu7IR8jA/0/index/segments_3
opensearch-node1    | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
opensearch-node1    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
opensearch-node1    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
opensearch-node1    | 	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224) ~[?:?]
opensearch-node1    | 	at java.nio.channels.FileChannel.open(FileChannel.java:308) ~[?:?]
opensearch-node1    | 	at java.nio.channels.FileChannel.open(FileChannel.java:367) ~[?:?]
opensearch-node1    | 	at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
opensearch-node1    | 	at org.opensearch.index.store.FsDirectoryFactory$HybridDirectory.openInput(FsDirectoryFactory.java:166) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
opensearch-node1    | 	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
opensearch-node1    | 	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
opensearch-node1    | 	at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:156) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
opensearch-node1    | 	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:298) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
opensearch-node1    | 	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289) ~[lucene-core-9.7.0-snapshot-4d1ed9e.jar:9.7.0-snapshot-4d1ed9e 4d1ed9ef9f69ebd032538ff4324fe8f6c8356f9a - 2023-05-19 14:51:47]
opensearch-node1    | 	at org.opensearch.index.shard.RemoteStoreRefreshListener.syncSegments(RemoteStoreRefreshListener.java:229) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
opensearch-node1    | 	at org.opensearch.index.shard.RemoteStoreRefreshListener.lambda$afterRefresh$0(RemoteStoreRefreshListener.java:179) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
opensearch-node1    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) [?:?]
opensearch-node1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
opensearch-node1    | 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
opensearch-node1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
opensearch-node1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
opensearch-node1    | 	at java.lang.Thread.run(Thread.java:1623) [?:?]
```

**Comment by raghuvanshraj** [comment]
> I think i have seen this happen when the File Descriptors limit is reached on the node. @raghuvanshraj do you have the data around FDs around that time?

No I don't but I think this is easily reproducible, so we should be able to get that data.

**Comment by sachinpkale** [comment]
Fixed with https://github.com/opensearch-project/OpenSearch/pull/9471
