### ISSUE TITLE
[BUG] Deserialization of `SearchRequest` crashes

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/OpenSearch#7829]
SQL plugin team presents...

## Describe the bug
Deserialization of a serialized `SearchRequest` crashes.

## To Reproduce
Run a unit test from the attached diff: 
[SearchRequest-deserialization-test.patch](https://github.com/opensearch-project/OpenSearch/files/11604459/SearchRequest-deserialization-test.patch)
```java
    public void testRequestSerializationDeserializationRoundTrip() throws IOException {
        var request = new SearchRequest()
            .indices("account")
            .scroll(TimeValue.timeValueMinutes(1))
            .source(new SearchSourceBuilder()
                .from(0)
                .timeout(TimeValue.timeValueMinutes(1))
                .trackScores(false)
                .query(QueryBuilders.boolQuery()
                    .filter(QueryBuilders.matchQuery("address", "street"))
                    .filter(QueryBuilders.matchQuery("state", "OH")))
                .highlighter(new HighlightBuilder().field("*"))
                .fetchSource(new String[] { "firstmame", "lastname" }, new String[0])
                .size(2)
                .sort(DOC_FIELD_NAME, SortOrder.ASC));

        var outStream = new BytesStreamOutput();
        request.writeTo(outStream);
        outStream.flush();
        var deserialized = new SearchRequest(outStream.bytes().streamInput());
        // crashes here        ^^^^^^^^^^^^^
        assertEquals(request, deserialized);
    }
```
I added this test in `server/src/test/java/org/opensearch/action/search/SearchRequestTests.java`
Exception stack:
```
can't read named writeable from StreamInput
java.lang.UnsupportedOperationException: can't read named writeable from StreamInput
	at __randomizedtesting.SeedInfo.seed([C0164472CF724D04:AF8D8A47F3CD4769]:0)
	at org.opensearch.common.io.stream.StreamInput.readNamedWriteable(StreamInput.java:1111)
	at org.opensearch.common.io.stream.StreamInput.readOptionalNamedWriteable(StreamInput.java:1138)
	at org.opensearch.search.builder.SearchSourceBuilder.<init>(SearchSourceBuilder.java:239)
	at org.opensearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:963)
	at org.opensearch.action.search.SearchRequest.<init>(SearchRequest.java:227)
	at org.opensearch.action.search.SearchRequestTests.testRequestSerializationDeserializationRoundTrip(SearchRequestTests.java:243)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

## Expected behavior
Test should pass

## Plugins
N/A

## Screenshots
N/A

## Host/Environment
`main` @ a2014004636

## Additional context
Detected on `SearchRequest`, but scope could be much bigger.

**Comment by andrross** [comment]
Flagging #7780 as being potentially related to this.

**Comment by andrross** [comment]
@Yury-Fridlyand I think there is a problem with your test code. You should replace

```
var deserialized = new SearchRequest(outStream.bytes().streamInput());
```

with

```
var deserialized = new SearchRequest((new NamedWriteableAwareStreamInput(outStream.bytes().streamInput(), namedWriteableRegistry));
```

You must use a `NamedWriteableAwareStreamInput` with a `NamedWriteableRegistry` to be able to deserialize the named writables within a SearchRequest instance. (The base test class has a build-in method `copyWriteable()` that does this for you).

Does this answer solve your problem? If this doesn't help can you share more about the specific use case where you encountered this?

**Comment by Yury-Fridlyand** [comment]
Hi @andrross,
Thank you, that works.
Fortunately, I found a way how to avoid deserializing a `SearchRequest` in my code, so it is not needed now. But good to know!

**Comment by kdh6429** [comment]
Which repository has the `NamedWriteableAwareStreamInput` class? Neither `opensearch-core` nor `opensearch-common` has it.

**Comment by kdh6429** [comment]
I am using SearchRequest in org.opensearch.client.opensearch.core . There is no writeTo method here.

**Comment by andrross** [comment]
@kdh6429 You're using the class in [opensearch-java](https://github.com/opensearch-project/opensearch-java), which is the recommended Java client. The class in question here is from the rest client built into the OpenSearch distribution, and is no longer recommended in favor of opensearch-java.
