### ISSUE TITLE
[BUG] ./gradlew :plugins:repository-s3:s3ThirdPartyTest fails locally

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#7867]
**Describe the bug**

Running `./gradlew :plugins:repository-s3:s3ThirdPartyTest` doesn't work.

The plugin tests attempt to default to dummy  s3 service (using fixtures) which does not need environment variables. 

```
$ ./gradlew :plugins:repository-s3:s3ThirdPartyTest

2> RepositoryVerificationException[[test-repo] path [base_path_third_party_tests_D3F6CC897EF73528] is not accessible on cluster-manager node]; nested: IOException[Unable to upload object [base_path_third_party_tests_D3F6CC897EF73528/tests-6gn3JiNqQoauTkjN5QBJcA/master.dat] using a single upload]; nested: AmazonS3Exception[The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 176490011B630DA2; S3 Extended Request ID: ddfca6d0-b724-44e4-a502-bf7bf354205f; Proxy: null)];
        at app//org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1552)
        at app//org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324)
        at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
        at app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at java.base@19.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@19.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@19.0.2/java.lang.Thread.run(Thread.java:1589)

        Caused by:
        java.io.IOException: Unable to upload object [base_path_third_party_tests_D3F6CC897EF73528/tests-6gn3JiNqQoauTkjN5QBJcA/master.dat] using a single upload
            at org.opensearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:379)
            at org.opensearch.repositories.s3.S3BlobContainer.lambda$writeBlob$1(S3BlobContainer.java:144)
            at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
            at org.opensearch.repositories.s3.SocketAccess.doPrivilegedIOException(SocketAccess.java:61)
            at org.opensearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:142)
            at org.opensearch.repositories.s3.S3BlobContainer.writeBlobAtomic(S3BlobContainer.java:159)
            at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1545)
            ... 6 more

            Caused by:
            com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 176490011B630DA2; S3 Extended Request ID: ddfca6d0-b724-44e4-a502-bf7bf354205f; Proxy: null), S3 Extended Request ID: ddfca6d0-b724-44e4-a502-bf7bf354205f
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
                at app//com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
                at app//com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
                at app//com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
                at app//com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
                at app//com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
                at app//com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
                at app//com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6531)
                at app//com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
                at app//com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
                at app//org.opensearch.repositories.s3.S3BlobContainer.lambda$executeSingleUpload$18(S3BlobContainer.java:377)
                at app//org.opensearch.repositories.s3.SocketAccess.lambda$doPrivilegedVoid$0(SocketAccess.java:70)
                at java.base@19.0.2/java.security.AccessController.doPrivileged(AccessController.java:318)
                at app//org.opensearch.repositories.s3.SocketAccess.doPrivilegedVoid(SocketAccess.java:69)
                at app//org.opensearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:377)
                ... 12 more

    UncategorizedExecutionException[Failed execution]; nested: ExecutionException[java.io.IOException: Exception when deleting blob container [base_path_third_party_tests_D3F6CC897EF73528/]]; nested: IOException[Exception when deleting blob container [base_path_third_party_tests_D3F6CC897EF73528/]]; nested: AmazonS3Exception[The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 176490011BB5C035; S3 Extended Request ID: ddfca6d0-b724-44e4-a502-bf7bf354205f; Proxy: null)];
        at app//org.opensearch.common.util.concurrent.FutureUtils.rethrowExecutionException(FutureUtils.java:109)
        at app//org.opensearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:79)
        at app//org.opensearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:55)
        at app//org.opensearch.repositories.AbstractThirdPartyRepositoryTestCase.deleteAndAssertEmpty(AbstractThirdPartyRepositoryTestCase.java:96)
        at app//org.opensearch.repositories.AbstractThirdPartyRepositoryTestCase.tearDown(AbstractThirdPartyRepositoryTestCase.java:87)
        at java.base@19.0.2/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base@19.0.2/java.lang.reflect.Method.invoke(Method.java:578)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at app//org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at app//org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at app//org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at app//org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at app//org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base@19.0.2/java.lang.Thread.run(Thread.java:1589)

        Caused by:
        java.util.concurrent.ExecutionException: java.io.IOException: Exception when deleting blob container [base_path_third_party_tests_D3F6CC897EF73528/]
            at org.opensearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:286)
            at org.opensearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:273)
            at org.opensearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:104)
            at org.opensearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:74)
            ... 39 more

            Caused by:
            java.io.IOException: Exception when deleting blob container [base_path_third_party_tests_D3F6CC897EF73528/]
                at org.opensearch.repositories.s3.S3BlobContainer.delete(S3BlobContainer.java:197)
                at org.opensearch.repositories.AbstractThirdPartyRepositoryTestCase.lambda$deleteAndAssertEmpty$0(AbstractThirdPartyRepositoryTestCase.java:95)
                at org.opensearch.action.ActionRunnable$1.doRun(ActionRunnable.java:60)
                at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
                at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
                ... 1 more

                Caused by:
                com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 176490011BB5C035; S3 Extended Request ID: ddfca6d0-b724-44e4-a502-bf7bf354205f; Proxy: null), S3 Extended Request ID: ddfca6d0-b724-44e4-a502-bf7bf354205f
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
                    at app//com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
                    at app//com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
                    at app//com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
                    at app//com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
                    at app//com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
                    at app//com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5397)
                    at app//com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:928)
                    at app//org.opensearch.repositories.s3.S3BlobContainer.lambda$delete$3(S3BlobContainer.java:178)
                    at java.base@19.0.2/java.security.AccessController.doPrivileged(AccessController.java:318)
                    at app//org.opensearch.repositories.s3.SocketAccess.doPrivileged(SocketAccess.java:55)
                    at app//org.opensearch.repositories.s3.S3BlobContainer.delete(S3BlobContainer.java:178)
                    ... 7 more
```

**Expected behavior**

Tests to pass.

**Plugins**

repository-s3

**Host/Environment (please complete the following information):**
 - OS: 
 ```
$ uname -a
Darwin b0f1d8717713 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
```

main, 3.x

**Additional context**

Once fixed, update documentation added in https://github.com/opensearch-project/OpenSearch/pull/7868 to say that this is supposed to work without credentials.

Coming from https://github.com/opensearch-project/OpenSearch/issues/7866

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/runGradleCheck.groovy#L23-L24

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/7974#issuecomment-1583402773 explains why and how to run it in a way that passes, I'll update documentation and close this

**Comment by dreamer-89** [comment]
@dblock : I see https://github.com/opensearch-project/OpenSearch/pull/7868 is the document update PR. Do you mind linking this issue on PR so this issue auto closes on merge ?

**Comment by dblock** [comment]
This is still a problem. By default this test doesn't pass.

**Comment by raghuvanshraj** [comment]
> @raghuvanshraj any interest in fixing this as part of the s3 repository work? these tests should pass by default.

@dblock I'll try to pick it up this week, caught up with a few other items
