### ISSUE TITLE
[BUG] Fix org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and search_after} flaky test

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#7873]
**Describe the bug**
The org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and search_after} test case is flaky.

```
java.lang.AssertionError: Failure at [search/110_field_collapsing:254]: expected [4xx|5xx] status code but api [search] returned [200 OK] [{"took":3,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":1,"failed":1,"failures":[{"shard":0,"index":"test","node":"Y3WKi7AWToWkPSGJCPpURA","reason":{"type":"search_exception","reason":"cannot use `collapse` in conjunction with `search_after`"}}]},"hits":{"total":0,"max_score":0.0,"hits":[]}}]
	at __randomizedtesting.SeedInfo.seed([9A807F988B26D31A:12D4404225DABEE2]:0)
	at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:460)
	at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.test(OpenSearchClientYamlSuiteTestCase.java:433)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750
```
**To Reproduce**

```
./gradlew ':qa:mixed-cluster:v2.9.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and search_after}" -Dtests.seed=9A807F988B26D31A
```

**Expected behavior**
Test should always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/16677/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_110_field_collapsing_field_collapsing_and_search_after_/

**Comment by mingshl** [comment]
Reproduce in main branch, return test success

`./gradlew ':qa:mixed-cluster:v2.9.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and search_after}" -Dtests.seed=9A807F988B26D31A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-EC -Dtests.timezone=Asia/Dubai -Druntime.java=11
`


```
 [2.9.0] BUILD SUCCESSFUL in 3m 46s
 [2.9.0] 168 actionable tasks: 165 executed, 3 from cache

BUILD SUCCESSFUL in 4m 13s
186 actionable tasks: 22 executed, 164 up-to-date

```

**Comment by reta** [comment]
Interesting, I am able to consistently reproduce it:

```
./gradlew ':qa:mixed-cluster:v2.9.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and search_after}" -Dtests.seed=9A807F988B26D31A
                                                                                                                                                                                                                                                                                                                            
Tests with failures:                                                                                                                                                                                                                                                                                                                                  
 - org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and search_after}  
```

Will to look at the cause

**Comment by mingshl** [comment]
The only parameter that I change is the java version, which I changed from 19 to 11. Thinking that might relate to the failure.

**Comment by reta** [comment]
Oh yeah - local has no issues, but this is not what the test does - there is a mixed cluster , the `-Druntime.java=` also does not change the behaviour for  me - consistent test failure

**Comment by reta** [comment]
I was able to reproduce it, the server (2.9.0) indeed return `200 OK`:

```
{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 2,
        "successful": 1,
        "skipped": 1,
        "failed": 1,
        "failures": [
            {
                "shard": 0,
                "index": "test",
                "node": "XLL2vfQ_Q0Ocrc0-ii5oQg",
                "reason": {
                    "type": "search_exception",
                    "reason": "cannot use `collapse` in conjunction with `search_after`"
                }
            }
        ]
    },
    "hits": {
        "total": {
            "value": 0,
            "relation": "eq"
        },
        "max_score": 0.0,
        "hits": []
    }
}
```

**Comment by reta** [comment]
Here it the cause: flipping `allow_partial_search_results` default was causing the search request to **not report** an error but return just partial results instead.
