### ISSUE TITLE
[BUG] Unable to form multi-node cluster using opensearch-cluster-cdk for 3.0.0

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/OpenSearch#7959]
**Describe the bug**
I am unable to deploy a multi-node (3 manager and 3 data) cluster using [opensearch-cluster-cdk](https://github.com/opensearch-project/opensearch-cluster-cdk) while using the latest 3.0.0 bundle build https://build.ci.opensearch.org/job/distribution-build-opensearch/7945/. 
The OpenSearch process comes up on seed-node but on the other master node I am seeing below error:
```
java.lang.IllegalStateException: Received message from unsupported version: [2.8.0] minimal compatible version is: [2.9.0]
        at org.opensearch.transport.InboundDecoder.ensureVersionCompatibility(InboundDecoder.java:227) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundDecoder.readHeader(InboundDecoder.java:195) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundDecoder.internalDecode(InboundDecoder.java:95) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundDecoder.decode(InboundDecoder.java:73) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:134) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:94) ~[transport-netty4-client-3.0.0.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) [netty-handler-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.93.Final.jar:4.1.93.Final]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
[2023-06-07T20:48:24,432][WARN ][o.o.t.TcpTransport       ] [ip-10-0-5-26.ec2.internal] exception caught on transport layer [Netty4TcpChannel{localAddress=/10.0.5.26:9300, remoteAddress=/10.0.4.56:54770}], closing connection
java.lang.IllegalStateException: Received message from unsupported version: [2.8.0] minimal compatible version is: [2.9.0]
        at org.opensearch.transport.InboundDecoder.ensureVersionCompatibility(InboundDecoder.java:227) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundDecoder.readHeader(InboundDecoder.java:195) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundDecoder.internalDecode(InboundDecoder.java:95) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundDecoder.decode(InboundDecoder.java:73) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:134) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:94) ~[transport-netty4-client-3.0.0.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) [netty-handler-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.93.Final.jar:4.1.93.Final]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
```
As per the cdk deployment logs I can confirm that discovery-ec2 plugin for 3.0.0 is getting installed. 
```
+ sudo -u ec2-user bin/opensearch-plugin install https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/core-plugins/discovery-ec2-3.0.0.zip
-> Installing https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/core-plugins/discovery-ec2-3.0.0.zip
-> Downloading https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/core-plugins/discovery-ec2-3.0.0.zip
[==========>                                      ] 21%   
[=====================>                           ] 43%   
[===============================>                 ] 65%   
[==========================================>      ] 86%   
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission config#plus read
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission aws.accessKeyId read,write
* java.util.PropertyPermission aws.configFile read,write
* java.util.PropertyPermission aws.region read,write
* java.util.PropertyPermission aws.secretAccessKey read,write
* java.util.PropertyPermission aws.sharedCredentialsFile read,write
* java.util.PropertyPermission opensearch.path.conf read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

-> Installed discovery-ec2 with folder name discovery-ec2
```
Below are the `opensearch.yml` config for Seed node and master node:
Seed node:
```
cluster.name: opensearch-infra-stack-280-multinode-5923*******-us-east-1
cluster.initial_cluster_manager_nodes:
  - seed
discovery.seed_providers: ec2
discovery.ec2.tag.role: manager
network.host: 0.0.0.0

node.name: seed
node.roles:
  - cluster_manager

plugins.security.disabled: true
```

Manager Node:
```
cluster.name: opensearch-infra-stack-275-7945-x64-NEW-5923*******-us-east-1
cluster.initial_cluster_manager_nodes:
  - seed
discovery.seed_providers: ec2
discovery.ec2.tag.role: manager
network.host: 0.0.0.0

node.roles:
  - cluster_manager

plugins.security.disabled: true
```

**To Reproduce**
1. check out https://github.com/opensearch-project/opensearch-cluster-cdk and follow the steps for install node and cdk. 
2. run `bootstrap` command if you haven't already bootstrapped the region. 
3. Run `npm install && cdk deploy "*"  -c distributionUrl=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/7945/linux/x64/tar/dist/opensearch/opensearch-3.0.0-linux-x64.tar.gz -c region=us-east-1 -c suffix=275-7945-x64-NEW -c securityDisabled=true -c cpuArch=x64 -c singleNodeCluster=false -c distVersion=3.0.0 -c minDistribution=false -c serverAccessType=prefixList -c restrictServerAccessTo=pl-60b85b09 -c dataNodeCount=3 -c use50PercentHeap=true -c isInternal=false`
4. Log on to the ec2 instances using SSM and check logs at `/home/ec2-user/opensearch/logs`. 

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by rishabh6788** [comment]
The same deployment works as expected for 2.8.0 
`cdk deploy "*"  -c distributionUrl=https://artifacts.opensearch.org/releases/bundle/opensearch/2.8.0/opensearch-2.8.0-linux-x64.tar.gz -c region=us-east-1 -c suffix=280-multinode -c securityDisabled=true -c cpuArch=x64 -c singleNodeCluster=false -c distVersion=2.8.0 -c minDistribution=false -c serverAccessType=prefixList -c restrictServerAccessTo=pl-60b85b09 -c dataNodeCount=3 -c use50PercentHeap=true -c isInternal=false`

**Comment by dblock** [comment]
The error `Received message from unsupported version: [2.8.0] minimal compatible version is: [2.9.0]` is expected when a 3.0 node tries to connect to a 2.8 node. The latest 2.x is 2.9, and rolling upgrades are only supported from latest 2.x.

So why would a brand new 3.0 cluster try to connect to a 2.8 node?  I suspect that there's another cluster in the same account with nodes tagged "manager" from another run of the same CDK.

The discovery-ec2 plugin has no concept of cluster name AFAIK and queries nodes that have a "manager" tag to bootstrap because there's `discovery.ec2.tag.role: manager` in the configuration.

Let's confirm this theory?

1. Shutdown all other cluster nodes tagged "manager" in this account.
2. Deploy 3.0 using the CDK. 

It should work.

If it does, we should transfer this issue to https://github.com/opensearch-project/opensearch-cluster-cdk to create unique tags.

**Comment by rishabh6788** [comment]
Deleted all the other clusters and re-deployed 3.0.0 cluster and still facing the same issue except dicovery-ec2 version mismatch issue is gone but manager is still not found. 
Seed node comes up with below log:
```
[2023-06-08T00:12:57,655][WARN ][o.o.g.DanglingIndicesState] [seed] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
[2023-06-08T00:12:57,853][INFO ][o.o.n.Node               ] [seed] initialized
[2023-06-08T00:12:57,853][INFO ][o.o.n.Node               ] [seed] starting ...
[2023-06-08T00:12:57,955][INFO ][o.o.t.TransportService   ] [seed] publish_address {10.0.3.120:9300}, bound_addresses {[::]:9300}
[2023-06-08T00:12:58,103][INFO ][o.o.b.BootstrapChecks    ] [seed] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2023-06-08T00:12:58,119][INFO ][o.o.c.c.Coordinator      ] [seed] setting initial configuration to VotingConfiguration{Sipgqs9gTMuoNG7MBjcwzA}
[2023-06-08T00:12:58,168][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [seed] fetching nodes from IMDS (instance-states=[running, pending], availability-zones=[], tags={role=[manager]}) ...
[2023-06-08T00:12:58,171][INFO ][o.o.d.e.AwsEc2ServiceImpl] [seed] setting aws.sharedCredentialsFile=/home/ec2-user/opensearch/config
[2023-06-08T00:12:58,171][INFO ][o.o.d.e.AwsEc2ServiceImpl] [seed] setting aws.sharedCredentialsFile=/home/ec2-user/opensearch/config
[2023-06-08T00:12:58,271][INFO ][o.o.c.s.MasterService    ] [seed] elected-as-cluster-manager ([1] nodes joined)[{seed}{Sipgqs9gTMuoNG7MBjcwzA}{lu0r8jsgT0a1rmBpjP9Iog}{10.0.3.120}{10.0.3.120:9300}{m}{shard_indexing_pressure_enabled=true} elect leader, _BECOME_CLUSTER_MANAGER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: cluster-manager node changed {previous [], current [{seed}{Sipgqs9gTMuoNG7MBjcwzA}{lu0r8jsgT0a1rmBpjP9Iog}{10.0.3.120}{10.0.3.120:9300}{m}{shard_indexing_pressure_enabled=true}]}
[2023-06-08T00:12:58,312][INFO ][o.o.c.c.CoordinationState] [seed] cluster UUID set to [oizUdkLdTD-abUnNGXB3qg]
[2023-06-08T00:12:58,351][INFO ][o.o.c.s.ClusterApplierService] [seed] cluster-manager node changed {previous [], current [{seed}{Sipgqs9gTMuoNG7MBjcwzA}{lu0r8jsgT0a1rmBpjP9Iog}{10.0.3.120}{10.0.3.120:9300}{m}{shard_indexing_pressure_enabled=true}]}, term: 1, version: 1, reason: Publication{term=1, version=1}
[2023-06-08T00:12:58,364][INFO ][o.o.d.PeerFinder         ] [seed] setting findPeersInterval to [1s] as node commission status = [true] for local node [{seed}{Sipgqs9gTMuoNG7MBjcwzA}{lu0r8jsgT0a1rmBpjP9Iog}{10.0.3.120}{10.0.3.120:9300}{m}{shard_indexing_pressure_enabled=true}]
[2023-06-08T00:12:58,369][INFO ][o.o.h.AbstractHttpServerTransport] [seed] publish_address {10.0.3.120:9200}, bound_addresses {[::]:9200}
[2023-06-08T00:12:58,370][INFO ][o.o.n.Node               ] [seed] started
[2023-06-08T00:12:58,370][INFO ][o.o.s.OpenSearchSecurityPlugin] [seed] Node started
[2023-06-08T00:12:58,371][INFO ][o.o.s.OpenSearchSecurityPlugin] [seed] 0 OpenSearch Security modules loaded so far: []
[2023-06-08T00:12:58,375][INFO ][o.o.g.GatewayService     ] [seed] recovered [0] indices into cluster_state
[2023-06-08T00:12:59,830][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [seed] using dynamic transport addresses [10.0.5.66:9300, 10.0.5.152:9300, 10.0.5.155:9300, 10.0.3.103:9300, 10.0.4.59:9300, 10.0.4.83:9300, 10.0.4.238:9300, 10.0.5.92:9300, 10.0.5.10:9300]
```

Error log on one of the master eligible nodes:
```
[2023-06-08T00:13:11,091][INFO ][o.o.n.Node               ] [ip-10-0-5-246.ec2.internal] initialized
[2023-06-08T00:13:11,091][INFO ][o.o.n.Node               ] [ip-10-0-5-246.ec2.internal] starting ...
[2023-06-08T00:13:11,215][INFO ][o.o.t.TransportService   ] [ip-10-0-5-246.ec2.internal] publish_address {10.0.5.246:9300}, bound_addresses {[::]:9300}
[2023-06-08T00:13:11,383][INFO ][o.o.b.BootstrapChecks    ] [ip-10-0-5-246.ec2.internal] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2023-06-08T00:13:11,393][INFO ][o.o.c.c.ClusterBootstrapService] [ip-10-0-5-246.ec2.internal] skipping cluster bootstrapping as local node does not match bootstrap requirements: [seed]
[2023-06-08T00:13:11,397][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-246.ec2.internal] fetching nodes from IMDS (instance-states=[running, pending], availability-zones=[], tags={role=[manager]}) ...
[2023-06-08T00:13:11,399][INFO ][o.o.d.e.AwsEc2ServiceImpl] [ip-10-0-5-246.ec2.internal] setting aws.sharedCredentialsFile=/home/ec2-user/opensearch/config
[2023-06-08T00:13:11,400][INFO ][o.o.d.e.AwsEc2ServiceImpl] [ip-10-0-5-246.ec2.internal] setting aws.sharedCredentialsFile=/home/ec2-user/opensearch/config
[2023-06-08T00:13:12,907][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-246.ec2.internal] using dynamic transport addresses [10.0.5.66:9300, 10.0.5.152:9300, 10.0.5.155:9300, 10.0.3.103:9300, 10.0.4.59:9300, 10.0.4.83:9300, 10.0.4.238:9300, 10.0.5.92:9300, 10.0.5.10:9300]
[2023-06-08T00:13:21,398][WARN ][o.o.c.c.ClusterFormationFailureHelper] [ip-10-0-5-246.ec2.internal] cluster-manager not discovered yet, this node has not previously joined a bootstrapped cluster, and this node must discover cluster-manager-eligible nodes [seed] to bootstrap a cluster: have discovered [{ip-10-0-5-246.ec2.internal}{6eDVoTh6S227ivIkjDJrfw}{IeYq4EDUSqK57Ewghrgpdw}{10.0.5.246}{10.0.5.246:9300}{m}{shard_indexing_pressure_enabled=true}]; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, [::1]:9300, [::1]:9301, [::1]:9302, [::1]:9303, [::1]:9304, [::1]:9305, 10.0.5.66:9300, 10.0.5.152:9300, 10.0.5.155:9300, 10.0.3.103:9300, 10.0.4.59:9300, 10.0.4.83:9300, 10.0.4.238:9300, 10.0.5.92:9300, 10.0.5.10:9300] from hosts providers and [{ip-10-0-5-246.ec2.internal}{6eDVoTh6S227ivIkjDJrfw}{IeYq4EDUSqK57Ewghrgpdw}{10.0.5.246}{10.0.5.246:9300}{m}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2023-06-08T00:13:23,396][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-246.ec2.internal] fetching nodes from IMDS (instance-states=[running, pending], availability-zones=[], tags={role=[manager]}) ...
[2023-06-08T00:13:23,779][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-5-246.ec2.internal] using dynamic transport addresses [10.0.5.66:9300, 10.0.5.152:9300, 10.0.5.155:9300, 10.0.3.103:9300, 10.0.4.59:9300, 10.0.4.83:9300, 10.0.4.238:9300, 10.0.5.92:9300, 10.0.5.10:9300]
[2023-06-08T00:13:31,401][WARN ][o.o.c.c.ClusterFormationFailureHelper] [ip-10-0-5-246.ec2.internal] cluster-manager not discovered yet, this node has not previously joined a bootstrapped cluster, and this node must discover cluster-manager-eligible nodes [seed] to bootstrap a cluster: have discovered [{ip-10-0-5-246.ec2.internal}{6eDVoTh6S227ivIkjDJrfw}{IeYq4EDUSqK57Ewghrgpdw}{10.0.5.246}{10.0.5.246:9300}{m}{shard_indexing_pressure_enabled=true}]; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, [::1]:9300, [::1]:9301, [::1]:9302, [::1]:9303, [::1]:9304, [::1]:9305, 10.0.5.66:9300, 10.0.5.152:9300, 10.0.5.155:9300, 10.0.3.103:9300, 10.0.4.59:9300, 10.0.4.83:9300, 10.0.4.238:9300, 10.0.5.92:9300, 10.0.5.10:9300] from hosts providers and [{ip-10-0-5-246.ec2.internal}{6eDVoTh6S227ivIkjDJrfw}{IeYq4EDUSqK57Ewghrgpdw}{10.0.5.246}{10.0.5.246:9300}{m}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
```

**Comment by rishabh6788** [comment]
Reg `The discovery-ec2 plugin has no concept of cluster name AFAIK and queries nodes that have a "manager" tag to bootstrap because there's discovery.ec2.tag.role: manager in the configuration.`. 
I am able to deploy two multi-node clusters, one 2.7.0 and another 2.8.0 with different cluster names without any issue and both clusters not interfering with each other in the same region and same account. 
Response from 2.8.0 cluster:
Cluster name: `opensearch-infra-stack-280-multinode-5923*********-us-east-1`
```
sh-4.2$ curl http://localhost:9200/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles      cluster_manager name
10.0.5.113            1          61   1    0.07    0.21     0.10 di        data,ingest     -               ip-10-0-5-113.ec2.internal
10.0.5.35             4          98   1    0.04    0.15     0.08 m         cluster_manager -               ip-10-0-5-35.ec2.internal
10.0.3.245            1          61   1    0.07    0.22     0.11 di        data,ingest     -               ip-10-0-3-245.ec2.internal
10.0.4.33             1          61   1    0.08    0.24     0.12 di        data,ingest     -               ip-10-0-4-33.ec2.internal
10.0.4.54             7          98   1    0.05    0.20     0.10 m         cluster_manager *               seed
10.0.3.76             7          98   1    0.09    0.20     0.10 m         cluster_manager -               ip-10-0-3-76.ec2.internal
```

Response from 2.7.0 cluster in the same region and same aws account:
Cluster Name: `opensearch-infra-stack-270-multinode-5923********-us-east-1`
```
[root@ip-10-0-3-44 logs]# curl http://localhost:9200/_cat/nodes
10.0.5.86  1 61 4 0.66 0.39 0.16 di data,ingest     - ip-10-0-5-86.ec2.internal
10.0.3.44  1 61 4 0.49 0.33 0.13 di data,ingest     - ip-10-0-3-44.ec2.internal
10.0.3.136 7 98 3 0.73 0.44 0.18 m  cluster_manager - ip-10-0-3-136.ec2.internal
10.0.4.61  1 61 5 0.61 0.36 0.14 di data,ingest     - ip-10-0-4-61.ec2.internal
10.0.5.142 6 98 3 0.28 0.24 0.10 m  cluster_manager * seed
10.0.5.105 5 98 3 0.37 0.29 0.12 m  cluster_manager - ip-10-0-5-105.ec2.internal
```
This is not the case with 3.0.0 deployment. 
@dblock @saratvemulapalli

**Comment by rishabh6788** [comment]
Cluster Setup: 
Version: 3.0.0
Build: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/7945/linux/x64/tar/dist/opensearch/opensearch-3.0.0-linux-x64.tar.gz
Master: 3 (includes the seed node)
Data: 3

Logs containing `AwsEc2SeedHostsProvider` on seed node:
```
cat opensearch-infra-stack-300-multinode-592316141094-us-east-1.log |grep AwsEc2SeedHostsProvider
[2023-06-08T02:05:06,076][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [seed] fetching nodes from IMDS (instance-states=[running, pending], availability-zones=[], tags={role=[manager]}) ...
[2023-06-08T02:05:07,705][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [seed] using dynamic transport addresses [10.0.5.66:9300, 10.0.5.152:9300, 10.0.5.155:9300, 10.0.3.103:9300, 10.0.4.59:9300, 10.0.4.83:9300, 10.0.4.238:9300, 10.0.5.92:9300, 10.0.5.10:9300]
```

Logs containing `AwsEc2SeedHostsProvider` on Master node (i-0ff4568ccfe8df8bc) :
 ```
 [2023-06-08T02:05:15,122][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-65.ec2.internal] fetching nodes from IMDS (instance-states=[running, pending], availability-zones=[], tags={role=[manager]}) ...
[2023-06-08T02:05:16,623][INFO ][o.o.d.e.AwsEc2SeedHostsProvider] [ip-10-0-4-65.ec2.internal] using dynamic transport addresses [10.0.5.66:9300, 10.0.5.152:9300, 10.0.5.155:9300, 10.0.3.103:9300, 10.0.4.59:9300, 10.0.4.83:9300, 10.0.4.238:9300, 10.0.5.92:9300, 10.0.5.10:9300]
```
Same log on the other master node as well.
