### ISSUE TITLE
[BUG] org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#8030]
**Describe the bug**
The org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString is flaky:

```
ava.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([764966D9E696FCD0:23CE4B8EFD4B3BCC]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.opensearch.search.SearchWeightedRoutingIT.assertSearchInAZ(SearchWeightedRoutingIT.java:844)
	at org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString(SearchWeightedRoutingIT.java:1124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**To Reproduce**

```
 ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString" -Dtests.seed=764966D9E696FCD0 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-EC -Dtests.timezone=America/Indiana/Knox -Druntime.java=17
```

**Expected behavior**
The test should always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
https://build.ci.opensearch.org/job/gradle-check/17349/testReport/junit/org.opensearch.search/SearchWeightedRoutingIT/testStrictWeightedRoutingWithCustomString/

**Comment by ashking94** [comment]
https://github.com/opensearch-project/OpenSearch/issues/8423

**Comment by dblock** [comment]
This failed on 2.9 (RC), https://build.ci.opensearch.org/job/gradle-check/20433/consoleFull
