### ISSUE TITLE
snapshot - repository-s3 - sdk_client_exception: Unable to execute HTTP request

### ISSUE THREAD

**Issue by toby181** [opensearch-project/OpenSearch#8106]
**Describe the bug**
Creating a new snapshot repository leads to exception "sdk_client_exception: Failed to connect to service endpoint".

I could imagine that this is because we're not using the default https port but 9021 -> internals3.example.com:9021

Create snapshot repository via OpenSearch Dashboards Dev Tools
````
PUT /_snapshot/my-repo
{
  "type": "s3",
  "settings": {
    "bucket": "snapshots",
    "client": "backup1"
  }
}
````

Exception API:
````
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[my-repo] path  is not accessible on cluster-manager node"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[my-repo] path  is not accessible on cluster-manager node",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Unable to upload object [tests-eDxYp3qGTfWKIwZm8T2kOg/master.dat] using a single upload",
      "caused_by": {
        "type": "sdk_client_exception",
        "reason": "sdk_client_exception: Unable to execute HTTP request: snapshots.internals3.example.com",
        "caused_by": {
          "type": "i_o_exception",
          "reason": "snapshots.internals3.example.com"
        }
      }
    }
  },
  "status": 500
}
````

Exception data node:
`````
2023-06-16T14:08:16.359608931Z {"type": "console", "timestamp": "2023-06-16T14:08:16,356Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "opensearch-cluster-stage", "node.name": "opensearch-cluster-stage-data-2", "message": "path: /_snapshot/my-repo, params: {pretty=true, repository=my-repo}", "cluster.uuid": "Fm7YvaujTJysNe5YHD3z3w", "node.id": "-wVrVz_lSby85qrHCR_kiA" ,
2023-06-16T14:08:16.359653639Z "stacktrace": ["org.opensearch.transport.RemoteTransportException: [opensearch-cluster-stage-master-2][192.168.154.159:9300][cluster:admin/repository/put]",
2023-06-16T14:08:16.359658293Z "Caused by: org.opensearch.repositories.RepositoryVerificationException: [my-repo] path  is not accessible on cluster-manager node",
2023-06-16T14:08:16.359661447Z "at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1614) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359664827Z "at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359667626Z "at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359670627Z "at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359674511Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
2023-06-16T14:08:16.359677405Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
2023-06-16T14:08:16.359680659Z "at java.lang.Thread.run(Thread.java:833) [?:?]",
2023-06-16T14:08:16.359683792Z "Caused by: java.io.IOException: Unable to upload object [tests-lPhSi_Q1THK6BHd8exQPuA/master.dat] using a single upload",
2023-06-16T14:08:16.359687061Z "at org.opensearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:379) ~[?:?]",
2023-06-16T14:08:16.359690251Z "at org.opensearch.repositories.s3.S3BlobContainer.lambda$writeBlob$1(S3BlobContainer.java:144) ~[?:?]",
2023-06-16T14:08:16.359693391Z "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
2023-06-16T14:08:16.359697006Z "at org.opensearch.repositories.s3.SocketAccess.doPrivilegedIOException(SocketAccess.java:61) ~[?:?]",
2023-06-16T14:08:16.359700254Z "at org.opensearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:142) ~[?:?]",
2023-06-16T14:08:16.359703392Z "at org.opensearch.repositories.s3.S3BlobContainer.writeBlobAtomic(S3BlobContainer.java:159) ~[?:?]",
2023-06-16T14:08:16.359707059Z "at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1607) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359710508Z "at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359745254Z "at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359748834Z "at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359751868Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
2023-06-16T14:08:16.359754447Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
2023-06-16T14:08:16.359757016Z "at java.lang.Thread.run(Thread.java:833) ~[?:?]",
2023-06-16T14:08:16.359760020Z "Caused by: org.opensearch.common.io.stream.NotSerializableExceptionWrapper: sdk_client_exception: Unable to execute HTTP request: snapshots.internals3.example.com",
2023-06-16T14:08:16.359762676Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219) ~[?:?]",
2023-06-16T14:08:16.359765299Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165) ~[?:?]",
2023-06-16T14:08:16.359768143Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[?:?]",
2023-06-16T14:08:16.359771279Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[?:?]",
2023-06-16T14:08:16.359774025Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[?:?]",
2023-06-16T14:08:16.359776866Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[?:?]",
2023-06-16T14:08:16.359779529Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[?:?]",
2023-06-16T14:08:16.359782402Z "at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[?:?]",
2023-06-16T14:08:16.359785114Z "at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[?:?]",
2023-06-16T14:08:16.359799204Z "at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) ~[?:?]",
2023-06-16T14:08:16.359802107Z "at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) ~[?:?]",
2023-06-16T14:08:16.359804725Z "at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421) ~[?:?]",
2023-06-16T14:08:16.359807573Z "at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6531) ~[?:?]",
2023-06-16T14:08:16.359812007Z "at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861) ~[?:?]",
2023-06-16T14:08:16.359816118Z "at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821) ~[?:?]",
2023-06-16T14:08:16.359819812Z "at org.opensearch.repositories.s3.S3BlobContainer.lambda$executeSingleUpload$18(S3BlobContainer.java:377) ~[?:?]",
2023-06-16T14:08:16.359823359Z "at org.opensearch.repositories.s3.SocketAccess.lambda$doPrivilegedVoid$0(SocketAccess.java:70) ~[?:?]",
2023-06-16T14:08:16.359826989Z "at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]",
2023-06-16T14:08:16.359830803Z "at org.opensearch.repositories.s3.SocketAccess.doPrivilegedVoid(SocketAccess.java:69) ~[?:?]",
2023-06-16T14:08:16.359834470Z "at org.opensearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:377) ~[?:?]",
2023-06-16T14:08:16.359838520Z "at org.opensearch.repositories.s3.S3BlobContainer.lambda$writeBlob$1(S3BlobContainer.java:144) ~[?:?]",
2023-06-16T14:08:16.359842549Z "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
2023-06-16T14:08:16.359846122Z "at org.opensearch.repositories.s3.SocketAccess.doPrivilegedIOException(SocketAccess.java:61) ~[?:?]",
2023-06-16T14:08:16.359858536Z "at org.opensearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:142) ~[?:?]",
2023-06-16T14:08:16.359862552Z "at org.opensearch.repositories.s3.S3BlobContainer.writeBlobAtomic(S3BlobContainer.java:159) ~[?:?]",
2023-06-16T14:08:16.359866529Z "at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1607) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359870554Z "at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359874294Z "at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359878140Z "at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.359881670Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
2023-06-16T14:08:16.359884984Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
2023-06-16T14:08:16.359888758Z "at java.lang.Thread.run(Thread.java:833) ~[?:?]",
2023-06-16T14:08:16.359896967Z "Caused by: java.io.IOException: snapshots.internals3.example.com",
2023-06-16T14:08:16.359900993Z "at java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[?:?]",
2023-06-16T14:08:16.359904689Z "at java.net.InetAddress.getAllByName0(InetAddress.java:1524) ~[?:?]",
2023-06-16T14:08:16.359908309Z "at java.net.InetAddress.getAllByName(InetAddress.java:1381) ~[?:?]",
2023-06-16T14:08:16.359912107Z "at java.net.InetAddress.getAllByName(InetAddress.java:1305) ~[?:?]",
2023-06-16T14:08:16.359915951Z "at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[?:?]",
2023-06-16T14:08:16.359919762Z "at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[?:?]",
2023-06-16T14:08:16.359923439Z "at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[?:?]",
2023-06-16T14:08:16.359927358Z "at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[?:?]",
2023-06-16T14:08:16.359931034Z "at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[?:?]",
2023-06-16T14:08:16.359934861Z "at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]",
2023-06-16T14:08:16.359938988Z "at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]",
2023-06-16T14:08:16.359941808Z "at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[?:?]",
2023-06-16T14:08:16.359944547Z "at com.amazonaws.http.conn.$Proxy55.connect(Unknown Source) ~[?:?]",
2023-06-16T14:08:16.359947367Z "at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[?:?]",
2023-06-16T14:08:16.359951031Z "at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[?:?]",
2023-06-16T14:08:16.359953651Z "at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[?:?]",
2023-06-16T14:08:16.359956238Z "at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[?:?]",
2023-06-16T14:08:16.359958788Z "at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[?:?]",
2023-06-16T14:08:16.359972859Z "at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[?:?]",
2023-06-16T14:08:16.359977365Z "at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[?:?]",
2023-06-16T14:08:16.359983166Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346) ~[?:?]",
2023-06-16T14:08:16.359985727Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) ~[?:?]",
2023-06-16T14:08:16.359988413Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[?:?]",
2023-06-16T14:08:16.359990958Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[?:?]",
2023-06-16T14:08:16.359993547Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[?:?]",
2023-06-16T14:08:16.359996025Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[?:?]",
2023-06-16T14:08:16.359999454Z "at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[?:?]",
2023-06-16T14:08:16.360002013Z "at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[?:?]",
2023-06-16T14:08:16.360004566Z "at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[?:?]",
2023-06-16T14:08:16.360007220Z "at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) ~[?:?]",
2023-06-16T14:08:16.360009818Z "at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) ~[?:?]",
2023-06-16T14:08:16.360012360Z "at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421) ~[?:?]",
2023-06-16T14:08:16.360014906Z "at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6531) ~[?:?]",
2023-06-16T14:08:16.360017408Z "at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861) ~[?:?]",
2023-06-16T14:08:16.360019968Z "at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821) ~[?:?]",
2023-06-16T14:08:16.360022512Z "at org.opensearch.repositories.s3.S3BlobContainer.lambda$executeSingleUpload$18(S3BlobContainer.java:377) ~[?:?]",
2023-06-16T14:08:16.360025040Z "at org.opensearch.repositories.s3.SocketAccess.lambda$doPrivilegedVoid$0(SocketAccess.java:70) ~[?:?]",
2023-06-16T14:08:16.360027595Z "at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]",
2023-06-16T14:08:16.360030096Z "at org.opensearch.repositories.s3.SocketAccess.doPrivilegedVoid(SocketAccess.java:69) ~[?:?]",
2023-06-16T14:08:16.360032618Z "at org.opensearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:377) ~[?:?]",
2023-06-16T14:08:16.360035142Z "at org.opensearch.repositories.s3.S3BlobContainer.lambda$writeBlob$1(S3BlobContainer.java:144) ~[?:?]",
2023-06-16T14:08:16.360037595Z "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
2023-06-16T14:08:16.360040128Z "at org.opensearch.repositories.s3.SocketAccess.doPrivilegedIOException(SocketAccess.java:61) ~[?:?]",
2023-06-16T14:08:16.360042801Z "at org.opensearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:142) ~[?:?]",
2023-06-16T14:08:16.360045591Z "at org.opensearch.repositories.s3.S3BlobContainer.writeBlobAtomic(S3BlobContainer.java:159) ~[?:?]",
2023-06-16T14:08:16.360048270Z "at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1607) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.360050910Z "at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.360053539Z "at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.360056081Z "at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.7.0.jar:2.7.0]",
2023-06-16T14:08:16.360060905Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
2023-06-16T14:08:16.360063399Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
2023-06-16T14:08:16.360065936Z "at java.lang.Thread.run(Thread.java:833) ~[?:?]"] }
`````

Relevant configuration in HelmRelease:
````
  values:
...
    config:
      opensearch.yml: |
 ...
        #s3 configuration
        s3.client.backup1.endpoint: internals3.example.com:9021
        s3.client.backup1.protocol: https
````

I've verified the functionality of the s3 using the aws cli on my workstation. Just to demonstrate that it's a valid s3.
````
$ aws s3 ls s3://snapshots --endpoint-url https://internals3.example.com:9021
2023-06-16 17:11:56    5485325 repository-s3-2.7.0.zip

$ aws s3 cp test.txt s3://snapshots --endpoint-url https://internals3.example.com:9021                                                                                                                                                                        
upload: ./test.txt to s3://snapshots/test.txt

$ aws s3 ls s3://snapshots --endpoint-url https://internals3.example.com:9021
2023-06-16 17:11:56    5485325 repository-s3-2.7.0.zip
2023-06-16 17:14:02          0 test.txt
````

Within the OpenSearch data pod the s3 can be reached, tested with curl:
````
$ curl https://internals3.example.com:9021
<?xml version="1.0" encoding="utf-8"?>
<ListAllMyBucketsResult><Owner><ID>nobody</ID><DisplayName>nobody</DisplayName></Owner><Buckets/></ListAllMyBucketsResult>
````

**Plugins**
repository-s3 - version 2.7.0

**Additional context**
OpenSearch is running in version 2.7.0 on kubernetes. Installed via Helm.
No proxy configured within the OpenSearch setup.

**Comment by Bukhtawar** [comment]
```
2023-06-16T14:08:16.359658293Z "Caused by: org.opensearch.repositories.RepositoryVerificationException: [my-repo] path  is not accessible on cluster-manager node",
```
Can you try pinging the endpoint from the cluster manager node?

**Comment by toby181** [comment]
hey @Bukhtawar 
Here we go

````
[opensearch@opensearch-cluster-stage-master-1 ~]$ env | grep -i node.roles
node.roles=master,ingest,
[opensearch@opensearch-cluster-stage-master-1 ~]$ curl https://internals3.example.com:9021
<?xml version="1.0" encoding="utf-8"?>
<ListAllMyBucketsResult><Owner><ID>nobody</ID><DisplayName>nobody</DisplayName></Owner><Buckets/></ListAllMyBucketsResult>
````

Same result as for the data node.

I've also tried with a base_path but it's the same result.

**Comment by toby181** [comment]
Quick proof that there's no proxy set

````
[opensearch@opensearch-cluster-stage-master-1 ~]$ env | grep -i proxy
[opensearch@opensearch-cluster-stage-master-1 ~]$ aws
bash: aws: command not found
[opensearch@opensearch-cluster-stage-master-1 ~]$ env | grep -i java
OPENSEARCH_JAVA_OPTS=-Xms6g -Xmx6g
JAVA_HOME=/usr/share/opensearch/jdk
````

**Comment by toby181** [comment]
I've created an aws-cli pod (using bitnami/aws-cli image) in the same namespace and gave it a try, succeeds as well.

````
$ aws s3 ls s3://snapshots --endpoint-url https://internals3.example.com:9021
                           PRE dummy/
2023-06-16 15:11:56    5485325 repository-s3-2.7.0.zip
2023-06-16 16:01:22          0 test.txt
$ env | grep AWS
AWS_SECRET_ACCESS_KEY=****
AWS_ACCESS_KEY_ID=****
AWS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
I have no name!@tmp-awscli:/$
````

**Comment by dblock** [comment]
Would love to double check that things work in 2.9 (2.x branch) and main as we changed quite a few things, cc: @raghuvanshraj

**Comment by toby181** [comment]
@dblock 
Couldn't it be the port that we're using that leads to the connectivity issue?
I'm curious since there's no option to configure the s3 port and it's also missing in the exception... no hard evidence but might you can verify that?

**Comment by toby181** [comment]
@dblock @Bukhtawar 
This issue is resolved now.
We run a tcpdump and figured out that the plugin tries to resolve hostname snapshots. internals3.example.com.
After some further research we configured the setting below in the opensearch.yml
```
s3.client.default.path_style_access: true # whether to use the deprecated path-style bucket URLs.
```

The connection is working now but we get another exception.

**Comment by toby181** [comment]
see above

**Comment by dblock** [comment]
Thanks for digging this up @toby181. Anything we can do to fix/cleanup this mess? Documentation? Code? Maybe you can contribute?
