### ISSUE TITLE
[BUG] org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess is flaky

### ISSUE THREAD

**Issue by BhumikaSaini-Amazon** [opensearch-project/OpenSearch#8136]
**Describe the bug**
`org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess` is flaky

```java
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=309, name=opensearch[org.opensearch.indices.replication.SegmentReplicationTargetServiceTests][generic][T#1], state=RUNNABLE, group=TGRP-SegmentReplicationTargetServiceTests]
	at __randomizedtesting.SeedInfo.seed([834751BE1876BAD1:1CC3BBFBF9B6E49D]:0)
Caused by: org.apache.lucene.store.AlreadyClosedException: engine is closed
	at __randomizedtesting.SeedInfo.seed([834751BE1876BAD1]:0)
	at app//org.opensearch.index.shard.IndexShard.getEngine(IndexShard.java:3346)
	at app//org.opensearch.index.shard.IndexShard.lambda$getLatestSegmentInfosAndCheckpoint$7(IndexShard.java:1601)
	at java.base@20.0.1/java.util.Optional.map(Optional.java:260)
	at app//org.opensearch.index.shard.IndexShard.getLatestSegmentInfosAndCheckpoint(IndexShard.java:1587)
	at app//org.opensearch.index.shard.IndexShard.getLatestReplicationCheckpoint(IndexShard.java:1557)
	at app//org.opensearch.index.shard.IndexShard.shouldProcessCheckpoint(IndexShard.java:1660)
	at app//org.opensearch.indices.replication.SegmentReplicationTargetService.onNewCheckpoint(SegmentReplicationTargetService.java:243)
	at app//org.opensearch.indices.replication.SegmentReplicationTargetService.lambda$processLatestReceivedCheckpoint$7(SegmentReplicationTargetService.java:353)
	at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747)
	at java.base@20.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@20.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@20.0.1/java.lang.Thread.run(Thread.java:1623)
```

**To Reproduce**

```shell
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess" -Dtests.seed=834751BE1876BAD1 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=be-BY -Dtests.timezone=Europe/Guernsey -Druntime.java=20
```

**Additional context**
[Build link](https://build.ci.opensearch.org/job/gradle-check/17877/testReport/junit/org.opensearch.indices.replication/SegmentReplicationTargetServiceTests/testStartReplicationListenerSuccess/)

**Comment by mch2** [comment]
Looks related to engine closed error thrown when fetching checkpoint, should have been fixed with https://github.com/opensearch-project/OpenSearch/pull/8134 - please re-open if you still see this failing.

**Comment by gaobinlong** [comment]
This flaky test still exists, see: https://build.ci.opensearch.org/job/gradle-check/39944/testReport/junit/org.opensearch.indices.replication/SegmentReplicationTargetServiceTests/testStartReplicationListenerFailure/.
