### ISSUE TITLE
[BUG] null_pointer_exception in rollups aggregations

### ISSUE THREAD

**Issue by xavier-isecurity** [opensearch-project/OpenSearch#8153]
**Describe the bug**
I was trying to test new rollup features in version 2.5 an 2.7 of opensearch and got null_pointer_exception on search request.

**To Reproduce**
1. Deploy Opensearch 2.7v with docker container
2. Create an index
3. Insert some test data
4. Create a rollup job for some data
5. Try to search in **Dev Tools** or create a visualization

**Expected behavior**
When searching I was expecting the API response be 200, with json response of aggregated rollup data.

**Plugins**
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-geospatial
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-neural-search
opensearch-notifications
opensearch-notifications-core
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-security-analytics
opensearch-sql

**Screenshots**
Trying to search and receive null_pointer_exception:
![image](https://github.com/opensearch-project/OpenSearch/assets/66122973/ea903ab2-2f14-4b74-a9c7-bc9daed99554)

Description of rollup:
```{
    "_id": "rollup_agentname_neta_palo_alto",
    "_seqNo": 110,
    "_primaryTerm": 1,
    "rollup": {
        "rollup_id": "rollup_agentname_neta_palo_alto",
        "enabled": true,
        "schedule": {
            "interval": {
                "start_time": 1683838067918,
                "period": 8,
                "unit": "Hours",
                "schedule_delay": 0
            }
        },
        "last_updated_time": 1683838067919,
        "enabled_time": 1683838067918,
        "description": "",
        "schema_version": 17,
        "source_index": "neta_palo_alto*",
        "target_index": "rollup_agentname-000001",
        "metadata_id": "0UxJDogBFXQVsbqTW5lP",
        "page_size": 1000,
        "delay": 0,
        "continuous": true,
        "dimensions": [
            {
                "date_histogram": {
                    "fixed_interval": "1d",
                    "source_field": "event.ingested",
                    "target_field": "event.ingested",
                    "timezone": "Canada/Eastern"
                }
            },
            {
                "terms": {
                    "source_field": "log.sender.type",
                    "target_field": "log.sender.type"
                }
            },
            {
                "terms": {
                    "source_field": "log.sender.name",
                    "target_field": "log.sender.name"
                }
            },
            {
                "terms": {
                    "source_field": "agent.name",
                    "target_field": "agent.name"
                }
            }
        ],
        "metrics": []
    },
    "metadata": {
        "rollup_agentname_neta_palo_alto": {
            "metadata_id": "0UxJDogBFXQVsbqTW5lP",
            "rollup_metadata": {
                "rollup_id": "rollup_agentname_neta_palo_alto",
                "last_updated_time": 1687207668618,
                "continuous": {
                    "next_window_start_time": 1687147200000,
                    "next_window_end_time": 1687233600000
                },
                "status": "started",
                "failure_reason": null,
                "stats": {
                    "pages_processed": 40,
                    "documents_processed": 10000,
                    "rollups_indexed": 4,
                    "index_time_in_millis": 64,
                    "search_time_in_millis": 341
                }
            }
        }
    }
}
```

![image](https://github.com/opensearch-project/OpenSearch/assets/66122973/c59625af-a1ad-47c5-9f17-22d77d985cfa)

`null_pointer_exception
null
Error: Internal Server Error
    at Fetch._callee3$ (http://localhost:5601/6100/bundles/core/core.entry.js:15:585214)
    at tryCatch (http://localhost:5601/6100/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2179)
    at Generator._invoke (http://localhost:5601/6100/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:1802)
    at Generator.next (http://localhost:5601/6100/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2954)
    at fetch_asyncGeneratorStep (http://localhost:5601/6100/bundles/core/core.entry.js:15:578126)
    at _next (http://localhost:5601/6100/bundles/core/core.entry.js:15:578442)`

**Host/Environment (please complete the following information):**
Docker compose file:
```version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.7.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-node2:
    image: opensearchproject/opensearch:2.7.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node2 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data # Creates volume called opensearch-data2 and mounts it to the container
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.7.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - opensearch-net
  logstash-oss:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash-oss
    ports:
      - 10004:10004
    volumes:
      - /home/vxavier/logstash/pipeline:/usr/share/logstash/pipeline/
      - /home/vxavier/logstash/config:/usr/share/logstash/config/
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
```

**Additional context**
Cluster is green. No issues with shards. Discover working as usual.

Testing with some data in version 1.3 it works just fine. I can retrieve information with same rollup, data and search.

**Comment by xavier-isecurity** [comment]
This worked on 2.8
