### ISSUE TITLE
[BUG] opensearch-plugin doesn't work behind a proxy

### ISSUE THREAD

**Issue by rlueckl** [opensearch-project/OpenSearch#8215]
**Describe the bug**
The opensearch-plugin CLI doesn't work, when it's behind a HTTP proxy. This worked in Elasticsearch-OSS (6.7) and also works in Elasticsearch (8.x), so this is a bug in my opinion.

**To Reproduce**
1. Use a server which doesn't have a direct internet connection, and needs a HTTP proxy to reach the internet.
2. Try to install any plugin with `opensearch-plugin install`.
3. Wait for the installation to time out.
4. See exception.

**Expected behavior**
The plugin is downloaded immediately and installed.

**Host/Environment (please complete the following information):**
 - OS: Debian 11 Bullseye
 - Version 2.8.0

**Additional context**
```
# /usr/share/opensearch/bin/opensearch-plugin install repository-s3 -v
-> Installing repository-s3
Checking if url exists: https://artifacts.opensearch.org/releases/plugins/repository-s3/2.8.0/repository-s3-linux-x64-2.8.0.zip
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.net.ConnectException: Connection timed out
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at org.opensearch.plugins.InstallPluginCommand.urlExists(InstallPluginCommand.java:426)
	at org.opensearch.plugins.InstallPluginCommand.getOpenSearchUrl(InstallPluginCommand.java:393)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:310)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:273)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

I've tried setting a proxy with different methods, but none of these worked:
 * `CLI_JAVA_OPTS` environment variable as used in Elasticsearch 8.x -> https://www.elastic.co/guide/en/elasticsearch/plugins/current/_other_command_line_parameters.html#_proxy_settings
 * `ES_JAVA_OPTS` environment variable (same values as `CLI_JAVA_OPTS`), which I've been using with Elasticsearch-OSS 6.7 until now
 * `HTTP_PROXY`, `HTTPS_PROXY`, `http_proxy` and `https_proxy` environment variables.

**Comment by Xtansia** [comment]
Hi @rlueckl, the java opts environment variable used by OpenSearch is `OPENSEARCH_JAVA_OPTS`, could you please confirm whether using this environment variable to configure the proxy connection works for you?

**Comment by rlueckl** [comment]
Hi @Xtansia ,

yes, I can confirm, that it works with `OPENSEARCH_JAVA_OPTS`. Thank you!

**Comment by ashutoshkumaranshu** [comment]
Hi ,

@rlueckl  @Xtansia Could you please let me know how you did it ? Have you passed anything inside helm chart values ?
 I have opensearch which is behind proxy and its not allowing to install Prometheus exporter using GitHub url.
error 👎 
opensearch-plugin install https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.9.0.0/prometheus-exporter-2.9.0.0.zip
-> Installing https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.9.0.0/prometheus-exporter-2.9.0.0.zip
-> Downloading https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.9.0.0/prometheus-exporter-2.9.0.0.zip
-> Failed installing https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.9.0.0/prometheus-exporter-2.9.0.0.zip
-> Rolling back https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.9.0.0/prometheus-exporter-2.9.0.0.zip
-> Rolled back https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.9.0.0/prometheus-exporter-2.9.0.0.zip
Exception in thread "main" java.net.UnknownHostException: github.com

**Comment by rlueckl** [comment]
Hi @ashutoshkumaranshu ,

I've used the `OPENSEARCH_JAVA_OPTS` as suggested by @Xtansia.

For example: 
```
sudo OPENSEARCH_JAVA_OPTS="-Dhttp.proxyHost=host_name -Dhttp.proxyPort=port_number -Dhttps.proxyHost=host_name -Dhttps.proxyPort=https_port_number" bin/opensearch-plugin install prometheus-exporter
```

You can use the Elasticsearch documentation for reference, just make sure to replace `CLI_JAVA_OPTS` with `OPENSEARCH_JAVA_OPTS`:
https://www.elastic.co/guide/en/elasticsearch/plugins/current/_other_command_line_parameters.html#_proxy_settings

**Comment by ashutoshkumaranshu** [comment]
Hi @rlueckl ,

This is the manual process right ?
Is there any way to do it using helm chart ? As we have deployed using helm on k8's.

Thanks in advance !
