### ISSUE TITLE
Raise an exception that includes the name of the plugin class being loaded 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#824]
**Is your feature request related to a problem? Please describe.**

Plugins are loaded via https://github.com/opensearch-project/OpenSearch/blob/0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0/server/src/main/java/org/opensearch/plugins/PluginsService.java#L665. When loading fails, the exception does not state which plugin is being loaded.

```
[2021-06-06T23:34:56,147][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [5212f8feb61b8ad0390770292d8e654b] fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: com/amazon/opendistroforelasticsearch/jobscheduler/spi/JobSchedulerExtension
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.opensearch.plugins.PluginsService.loadPluginClass(PluginsService.java:697)
        at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:665)
        at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492)
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181)
        at org.opensearch.node.Node.<init>(Node.java:363)
        at org.opensearch.node.Node.<init>(Node.java:302)
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240)
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:185)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:176)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
        at org.opensearch.cli.Command.main(Command.java:103)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:142)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:108)
Caused by: java.lang.ClassNotFoundException: com.amazon.opendistroforelasticsearch.jobscheduler.spi.JobSchedulerExtension
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 29 more
```

This makes it very difficult to debug problems like these.

**Describe the solution you'd like**

Catch and raise an exception that includes at least the name of the plugin being loaded.

**Comment by jayeshathila** [comment]
Will be looking into this.

**Comment by CEHENKLE** [comment]
Coolio.  I'll assign it to you, Jayesh, but if you don't have time, I have someone who could pick it up.  Just LMK.  

Thanks,
/C

**Comment by jayeshathila** [comment]
I was planning on picking this actively over weekend. Let me know if we this before that.

**Comment by CEHENKLE** [comment]
Definitely not! Just assigning it to you so no one else picked it up.  :) 

/C

**Comment by jayeshathila** [comment]
@dblock We can close this issue.
