### ISSUE TITLE
[BUG] [Segment Replication] replica fails after write some data

### ISSUE THREAD

**Issue by xiaoyuan0821** [opensearch-project/OpenSearch#8286]
**Describe the bug**
Replica shard fails with segment replication enabled.
I have a cluster with 2 nodes, OpenSearch 2.8.0

**To Reproduce**
1. create index
```
PUT my-index1
{
  "settings": {
    "number_of_shards": 3, 
    "index": {
      "replication.type": "SEGMENT"
    }
  }
}
```
2. enable balanced primary  allocation and backpressure
```
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.balance.prefer_primary": true,
    "segrep.pressure.enabled": true
  }
}
```
4. use `_bulk` API send data to `my-index1`
5. replica fails, see error attached
[stack.txt](https://github.com/opensearch-project/OpenSearch/files/11881526/stack.txt)

6. cluster allocation explain
```
shard has exceeded the maximum number of retries [5] on failed allocation attempts - manually call [/_cluster/reroute?retry_failed=true] to retry, [unassigned_info[[reason=ALLOCATION_FAILED], at[2023-06-27T09:36:09.126Z], failed_attempts[5], failed_nodes[[WMstn7uvRqKhylJPSxyTAg]], delayed=false, details[failed shard on node [WMstn7uvRqKhylJPSxyTAg]: failed to create shard, failure IOException[failed to obtain in-memory shard lock]; nested: ShardLockObtainFailedException[[my-index1][1]: obtaining shard lock for [starting shard] timed out after [5000ms], lock already held for [closing shard] with age [41447ms]]; ], allocation_status[no_attempt]]]
```

**Expected behavior**
replica shard should not fail.

**Plugins**
all default plugins

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch/assets/4684163/9483005f-a3e6-4a26-b66a-19ba0861fcfa)

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version 2.8.0

**Additional context**

**Comment by xiaoyuan0821** [comment]
After some debug, i find that before the shard fail,  the replica is lagging a lot:
```
shardId        target_node            target_host   checkpoints_behind bytes_behind current_lag last_completed_lag rejected_requests
[my-index1][0] opensearch-node-1 172.16.103.58 0                  0b           0s          464ms              0
[my-index1][1] opensearch-node-2 172.16.88.179 256                676.8mb      8.8m        1.6s               6967
[my-index1][2] opensearch-node-1 172.16.103.58 0                  0b           0s          219ms              0

```

**Comment by Rishikesh1159** [comment]
@xiaoyuan0821 Thanks for trying out segment replication. Looks like the bug you are facing is not actually a bug but an expected behaviour when you enable segment replication backpressure. With segment replication back pressure enabled `("segrep.pressure.enabled": true)` when replica shards fall behind primary for certain time we fail the replica shard and a new replica shard will replace it eventually. More information about segment replication back pressure can be found [here](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/segment-replication/backpressure/).

If you don't want this behaviour of replica shards failing when they fall behind primary for too long then you can just disable backpressure setting. `("segrep.pressure.enabled": false)`

**Comment by xiaoyuan0821** [comment]
@Rishikesh1159 I tried to disabled back pressure and replica still fail.
```
GET _cluster/settings
{
  "persistent": {
    "cluster": {
      "routing": {
        "allocation": {
          "balance": {
            "prefer_primary": "true"
          }
        }
      }
    },
    "segrep": {
      "pressure": {
        "enabled": "false"
      }
    },
    "plugins": {
      "index_state_management": {
        "template_migration": {
          "control": "-1"
        }
      }
    }
  },
  "transient": {}
}
```

shards allocation:
```
my-index1 1 p STARTED    42286114 80.3gb 172.16.103.58 opensearch-node-1
my-index1 1 r UNASSIGNED                               
my-index1 2 p STARTED    42278032 69.1gb 172.16.88.179 opensearch-node-2
my-index1 2 r STARTED    14629609   18gb 172.16.103.58 opensearch-node-1
my-index1 0 p STARTED    42288192 71.6gb 172.16.88.179 opensearch-node-2
my-index1 0 r UNASSIGNED                               
```

only shard 2 replica is still allocated to node1, and it's lagging a lot:
```
GET _cat/segment_replication?v
shardId        target_node            target_host   checkpoints_behind bytes_behind current_lag last_completed_lag rejected_requests
[my-index1][2]opensearch-node-1 172.16.103.58 13063              32.4gb       8.4h        1.7s               0

```

**Comment by dreamer-89** [comment]
Thank you @xiaoyuan0821 for sharing this issue. This is interesting! 
I followed the repro steps mentioned in the issue description but did not hit the unassigned replics shard issue. From experiment I ran, the lagging replica shards were marked failed but they recovered automatically without any intervention.

From replica shard logs attached in issue description, it seems segment replication event failed due to index corruption exception because of missing segment file (possibly deleted by different process?). This is not expected and need more deep dive.
```
Caused by: org.apache.lucene.index.CorruptIndexException: Problem reading index. (resource=/opt/elastic/data/nodes/0/indices/NXaGk6pxTHankHCQzTP2hg/1/index/_39w.cfe)
...
Caused by: java.nio.file.NoSuchFileException: /opt/elastic/data/nodes/0/indices/NXaGk6pxTHankHCQzTP2hg/1/index/_39w.cfe
```

In my setup, I used 2 c5.large data node and continuously ingest `so` benchmark [dataset](https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/so). In order to mimic your setup more closely, do you mind sharing below information. 
1. Data node type
2. Type of data indexed
3. Ingestion mechanism
4. Was there any other action performed on index during this experimentation ?

**Comment by dreamer-89** [comment]
> @dreamer-89 I don't think we can close this just yet, your PR fixes the corruption case on engine close, but why did the replicas fail to re-recover? They should have recovered after either the corruption and failure from backpressure getting applied.

@mch2 : Thanks for the comment. Yes, why replica remain unassigned (fail to recover) is not yet identified. I followed the repro steps as mentioned in issue description but without success.

**Comment by damslo** [comment]
Hello, we are facing the same issue, let me know if you need any details that could help.

**Comment by xiao-6666** [comment]
Our cluster has the same problem, the primary shard and replica shard sizes are not consistent, almost all indexes can be affected by this problem.
In the Opensearch cluster, a large number of index primary shards and duplicate shards have different sizes, resulting in different query data.
![index02 (1)](https://github.com/user-attachments/assets/0b383cbc-6537-403e-94dd-384ee38c0482)


“version” : {  “version”：{
“distribution” : “opensearch”,
“distribution”：“opensearch”，
“number” : “2.13.0”,  “number”：“2.13.0”，
“build_snapshot” : false,
“build_snapshot”：false，
“lucene_version” : “9.10.0”,
“lucene_version”：“9.10.0”，
“minimum_wire_compatibility_version” : “7.10.0”,
“minimum_wire_compatibility_version”：“7.10.0”，
“minimum_index_compatibility_version” : “7.0.0”
“minimum_index_compatibility_version”：“7.0.0”

error log:
![image](https://github.com/user-attachments/assets/8d02ce57-eda4-495e-b9da-0b2e5f8de7e3)

2025-01-06T11:24:43,236][ERROR][o.o.i.r.SegmentReplicationTargetService] [[vm-gs-ols-hot-prod-039.prd.ols.gs.internal.vgcserv.com.cn](http://vm-gs-ols-hot-prod-039.prd.ols.gs.internal.vgcserv.com.cn/)] [shardId [prd-aks-corebe-webapp-logs-2025.01.03.02][5]] [replication id 54873] Replication failed, timing data: {INIT=0, GET_CHECKPOINT_INFO=1, FILE_DIFF=1356, REPLICATING=0, GET_FILES=1}
Jan 6, 2025 @ 11:25:12.783 org.opensearch.indices.replication.common.ReplicationFailedException: Segment Replication failed at org.opensearch.indices.replication.SegmentReplicationTargetService$3.onFailure(SegmentReplicationTargetService.java:590) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:84) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:126) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112) [opensearch-2.13.0.jar:2.13.0] at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) [?:?] at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:160) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:141) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.action.StepListener.innerOnResponse(StepListener.java:79) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.core.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:58) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$4.onResponse(ActionListener.java:182) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$6.onResponse(ActionListener.java:301) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:183) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:70) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleResponse(SecurityInterceptor.java:398) [opensearch-security-2.13.0.0.jar:2.13.0.0] at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1505) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:420) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.transport.InboundHandler.lambda$handleResponse$3(InboundHandler.java:414) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854) [opensearch-2.13.0.jar:2.13.0] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: org.opensearch.indices.replication.common.ReplicationFailedException: java.nio.file.NoSuchFileException: /opt/ols/data/nodes/0/indices/pnQzYkN3QDi43-fgKOOLjQ/5/index/_138.si at org.opensearch.indices.replication.SegmentReplicationTarget.finalizeReplication(SegmentReplicationTarget.java:316) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$startReplication$3(SegmentReplicationTarget.java:184) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) ~[opensearch-core-2.13.0.jar:2.13.0] … 23 more Caused by: java.nio.file.NoSuchFileException: /opt/ols/data/nodes/0/indices/pnQzYkN3QDi43-fgKOOLjQ/5/index/_138.si at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?] at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?] at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?] at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224) ~[?:?] at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309) ~[?:?] at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369) ~[?:?] at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.opensearch.index.store.FsDirectoryFactory$HybridDirectory.openInput(FsDirectoryFactory.java:183) ~[opensearch-2.13.0.jar:2.13.0] at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:156) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.codecs.lucene99.Lucene99SegmentInfoFormat.read(Lucene99SegmentInfoFormat.java:94) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:411) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:368) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:315) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.opensearch.index.store.Store.buildSegmentInfos(Store.java:820) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.indices.replication.SegmentReplicationTarget.finalizeReplication(SegmentReplicationTarget.java:285) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$startReplication$3(SegmentReplicationTarget.java:184) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) ~[opensearch-core-2.13.0.jar:2.13.0] … 23 more Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (3b2a4f7d). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(Snapshot of SegmentInfos)) at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:375) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:315) ~[lucene-core-9.10.0.jar:9.10.0 695c0ac84508438302cd346a812cfa2fdc5a10df - 2024-02-14 16:48:06] at org.opensearch.index.store.Store.buildSegmentInfos(Store.java:820) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.indices.replication.SegmentReplicationTarget.finalizeReplication(SegmentReplicationTarget.java:285) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$startReplication$3(SegmentReplicationTarget.java:184) ~[opensearch-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:126) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112) [opensearch-2.13.0.jar:2.13.0] at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) [?:?] at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:160) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:141) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.action.StepListener.innerOnResponse(StepListener.java:79) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.core.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:58) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$4.onResponse(ActionListener.java:182) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.core.action.ActionListener$6.onResponse(ActionListener.java:301) [opensearch-core-2.13.0.jar:2.13.0] at org.opensearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:183) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:70) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleResponse(SecurityInterceptor.java:398) [opensearch-security-2.13.0.0.jar:2.13.0.0] at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1505) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:420) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.transport.InboundHandler.lambda$handleResponse$3(InboundHandler.java:414) [opensearch-2.13.0.jar:2.13.0] at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854) [opensearch-2.13.0.jar:2.13.0] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by dreamer-89** [comment]
Thank you, @xiao-6666, for reporting this issue. Since it still persists, I will reopen it. The exception seems to stem when replica builds the `SegmentInfos` object required to perform commit but the file does not exist on local store. 
```
 Caused by: org.opensearch.indices.replication.common.ReplicationFailedException: java.nio.file.NoSuchFileException: /opt/ols/data/nodes/0/indices/pnQzYkN3QDi43-fgKOOLjQ/5/index/_138.si at org.opensearch.indices.replication.SegmentReplicationTarget.finalizeReplication(SegmentReplicationTarget.java:316)
```

Could you please provide the steps to reproduce the issue? This would significantly expedite the resolution, as I was unable to replicate it in my last attempt.

@mch2, do you have any insights on the possible causes or reproduction steps? I’d be happy to take on the fix.
