### ISSUE TITLE
[BUG] org.opensearch.plugin.correlation.core.index.codec.correlation950.CorrelationCodecTests.testCorrelationVectorIndex is flaky

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/OpenSearch#8329]
See: https://build.ci.opensearch.org/job/gradle-check/18621/

```
REPRODUCE WITH: ./gradlew ':plugins:events-correlation-engine:test' --tests "org.opensearch.plugin.correlation.core.index.codec.correlation950.CorrelationCodecTests.testCorrelationVectorIndex" -Dtests.seed=5E5BD7BB82E4598E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=hu-HU -Dtests.timezone=Asia/Katmandu -Druntime.java=20
```

Error:
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
perFieldCorrelationVectorsFormat.getKnnVectorsFormatForField(
    "test_vector_one"
);
Wanted 1 time:
-> at org.opensearch.plugin.correlation.core.index.codec.correlation950.CorrelationCodecTests.testCorrelationVectorIndex(CorrelationCodecTests.java:108)
But was 2 times:
-> at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter.getInstance(PerFieldKnnVectorsFormat.java:133)
-> at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter.getInstance(PerFieldKnnVectorsFormat.java:133)


	at __randomizedtesting.SeedInfo.seed([5E5BD7BB82E4598E:151651F24B527EA2]:0)
	at app//org.opensearch.plugin.correlation.core.index.codec.correlation950.CorrelationCodecTests.testCorrelationVectorIndex(CorrelationCodecTests.java:108)
	at app//org.opensearch.plugin.correlation.core.index.codec.correlation950.CorrelationCodecTests.testCorrelationVectorIndex(CorrelationCodecTests.java:61)
	at java.base@20.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base@20.0.1/java.lang.reflect.Method.invoke(Method.java:578)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at app//org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at app//org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at app//org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at app//org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at app//org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at app//org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at app//org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at app//org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at app//org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base@20.0.1/java.lang.Thread.run(Thread.java:1623)
```

**Comment by andrross** [comment]
@sbcd90 FYI

**Comment by sbcd90** [comment]
thanks @andrross . will look into it.

**Comment by sbcd90** [comment]
hi @andrross ,
the flaky test happens when there is a `random force merge`.
![Screenshot 2023-06-29 at 3 40 30 PM](https://github.com/opensearch-project/OpenSearch/assets/617607/c72c3d4c-dada-4b61-b859-d6a6a6fd63b2)
there are 2 calls made when there is a `random force merge`.

will change 
```
verify(perFieldCorrelationVectorsFormatSpy).getKnnVectorsFormatForField(eq(FIELD_NAME_ONE));
```
to
```
verify(perFieldCorrelationVectorsFormatSpy, atleastOnce()).getKnnVectorsFormatForField(eq(FIELD_NAME_ONE));
```
for fixing it.

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch/pull/8986#issuecomment-1673710815

**Comment by dblock** [comment]
@sbcd90 are you fixing this?

**Comment by sbcd90** [comment]
hi @dblock , its fixed in pr #7771 https://github.com/opensearch-project/OpenSearch/pull/7771/files#diff-9c1447da4ddbca541d65c094dddf65706b6424f83968cae002354df780e05e8cR109

**Comment by dblock** [comment]
Consider extracting if that PR takes a while.
