### ISSUE TITLE
[BUG] 1.0.0-rc1: unable to disable the security plugin

### ISSUE THREAD

**Issue by tgurr** [opensearch-project/OpenSearch#835]
**Describe the bug**
I was able to successfully setup the security plugin via `/usr/share/opensearch/plugins/opensearch-security/tools/install_demo_configuration.sh` however when trying to run opensearch with the security plugin disabled via `plugins.security.disabled: true` added to `opensearch.yml` as described on https://docs-beta.opensearch.org/docs/security/configuration/disable/ opensearch fails to start.

**To Reproduce**
1. Add `plugins.security.disabled: true` to `opensearch.yml`
2. systemctl start opensearch.service
3. See error `java.lang.IllegalArgumentException: unknown setting [plugins.security.disabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`

**Expected behavior**
Start without error.

**Plugins**
Default minus `opensearch-security`

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version: 1.0.0-rc1

**Additional context**
```
[2021-06-10T13:47:29,310][INFO ][o.o.n.Node               ] [localhost] version[1.0.0-rc1], pid[21721], build[tar/26d579287f50bb33e17c8fe1f05ea208d5c64d1f/2021-05-28T18:18:49.848386Z], OS[Linux/5.11.1/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]
[2021-06-10T13:47:29,313][INFO ][o.o.n.Node               ] [localhost] JVM home [/usr/share/opensearch/jdk], using bundled JDK [true]
[2021-06-10T13:47:29,313][INFO ][o.o.n.Node               ] [localhost] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-2781166334739805016, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/opensearch, -XX:ErrorFile=/var/log/opensearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/opensearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/usr/share/opensearch, -Dopensearch.path.conf=/etc/opensearch, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2021-06-10T13:47:29,314][WARN ][o.o.n.Node               ] [localhost] version [1.0.0-rc1] is a pre-release version of OpenSearch and is not suitable for production
[2021-06-10T13:47:30,096][INFO ][o.o.p.c.PluginSettings   ] [localhost] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true, batch-metrics-retention-period-minutes: 7, rpc-port: 9650, webservice-port 9600
[2021-06-10T13:47:30,207][INFO ][o.o.p.PerformanceAnalyzerPlugin] [localhost] Shard IndexingPressure not present in this OpenSearch version. Skipping ShardIndexingPressureMetricsCollector
[2021-06-10T13:47:30,484][INFO ][o.o.i.r.ReindexPlugin    ] [localhost] ReindexPlugin reloadSPI called
[2021-06-10T13:47:30,485][INFO ][o.o.i.r.ReindexPlugin    ] [localhost] Unable to find any implementation for RemoteReindexExtension
[2021-06-10T13:47:30,495][INFO ][o.o.j.JobSchedulerPlugin ] [localhost] Loaded scheduler extension: opendistro-index-management, index: .opendistro-ism-config
[2021-06-10T13:47:30,499][INFO ][o.o.j.JobSchedulerPlugin ] [localhost] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
[2021-06-10T13:47:30,520][INFO ][o.o.j.JobSchedulerPlugin ] [localhost] Loaded scheduler extension: reports-scheduler, index: .opendistro-reports-definitions
[2021-06-10T13:47:30,522][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [aggs-matrix-stats]
[2021-06-10T13:47:30,522][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [analysis-common]
[2021-06-10T13:47:30,522][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [geo]
[2021-06-10T13:47:30,522][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [ingest-common]
[2021-06-10T13:47:30,522][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [ingest-geoip]
[2021-06-10T13:47:30,522][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [ingest-user-agent]
[2021-06-10T13:47:30,523][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [lang-expression]
[2021-06-10T13:47:30,523][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [lang-mustache]
[2021-06-10T13:47:30,523][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [lang-painless]
[2021-06-10T13:47:30,523][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [mapper-extras]
[2021-06-10T13:47:30,523][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [opensearch-dashboards]
[2021-06-10T13:47:30,523][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [parent-join]
[2021-06-10T13:47:30,523][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [percolator]
[2021-06-10T13:47:30,524][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [rank-eval]
[2021-06-10T13:47:30,524][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [reindex]
[2021-06-10T13:47:30,524][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [repository-url]
[2021-06-10T13:47:30,524][INFO ][o.o.p.PluginsService     ] [localhost] loaded module [transport-netty4]
[2021-06-10T13:47:30,525][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-alerting]
[2021-06-10T13:47:30,525][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-anomaly-detection]
[2021-06-10T13:47:30,525][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-asynchronous-search]
[2021-06-10T13:47:30,525][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-index-management]
[2021-06-10T13:47:30,525][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-job-scheduler]
[2021-06-10T13:47:30,525][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-knn]
[2021-06-10T13:47:30,525][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-notebooks]
[2021-06-10T13:47:30,526][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-performance-analyzer]
[2021-06-10T13:47:30,526][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-reports-scheduler]
[2021-06-10T13:47:30,526][INFO ][o.o.p.PluginsService     ] [localhost] loaded plugin [opensearch-sql]
[2021-06-10T13:47:30,549][INFO ][o.o.e.NodeEnvironment    ] [localhost] using [1] data paths, mounts [[/ (/dev/root)]], net usable_space [143.4gb], net total_space [232.5gb], types [ext4]
[2021-06-10T13:47:30,550][INFO ][o.o.e.NodeEnvironment    ] [localhost] heap size [1gb], compressed ordinary object pointers [true]
[2021-06-10T13:47:30,580][INFO ][o.o.n.Node               ] [localhost] node name [localhost], node ID [tQjsF0lUQ1yLVhay5_BBQQ], cluster name [opensearch], roles [master, remote_cluster_client, data, ingest]
[2021-06-10T13:47:32,302][ERROR][o.o.b.Bootstrap          ] [localhost] Exception
java.lang.IllegalArgumentException: unknown setting [plugins.security.disabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:557) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:502) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:473) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:444) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:162) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:417) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) [opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) [opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) [opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) [opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) [opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.main(Command.java:103) [opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) [opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) [opensearch-1.0.0-rc1.jar:1.0.0-rc1]
[2021-06-10T13:47:32,305][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [localhost] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [plugins.security.disabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.main(Command.java:103) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
Caused by: java.lang.IllegalArgumentException: unknown setting [plugins.security.disabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:557) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:502) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:473) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:444) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:162) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:417) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	... 6 more
```

**Comment by tgurr** [comment]
Disregard, it's an either or, either set the `plugins.security.disabled: true` in `opensearch.yml` or remove `plugins/opensearch-security` which is stated in the documentation.

**Comment by dblock** [comment]
cc: @aetter

@tgurr care to check whether the docs in https://github.com/opensearch-project/documentation-website/ are accurate with reality or raise an issue?

**Comment by tgurr** [comment]
@dblock It's basically fine, I just got confused by first adding `plugins.security.disabled: true` and then additionally removing the plugin, but when removing the plugin the configuration option must not exist anymore which is already mentioned clearly in the docs in a following sentence, I just overread it.

For opensearch-dashboards the information could maybe improved to also add the information to remove the `opensearch_security.` configuration entries from `opensearch_dashboards.yml` when having removed the OpenSearch dashboards security plugin(?).

I'm a real beginner when it comes not only to OpenSearch but also Elasticsearch so please double check my statements. Reason is I'm packaging OpenSearch on a distribution and at least have to give it a plain test run. It's not that I'm not also really interested to dig further into OpenSearch and all the possible use-cases but as always in life time is an issue.

**Comment by aetter** [comment]
> For opensearch-dashboards the information could maybe improved to also add the information to remove the `opensearch_security.` configuration entries from `opensearch_dashboards.yml` when having removed the OpenSearch dashboards security plugin(?).

Thanks a bunch @tgurr, thanks a great point. Added a sentence here: https://docs-beta.opensearch.org/dashboards/install/plugins#remove-plugins
