### ISSUE TITLE
[BUG] Flaky Test org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testNodeDropWithOngoingReplication

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#8439]
**Describe the bug**
Test `org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testNodeDropWithOngoingReplication` is flaky.
https://build.ci.opensearch.org/job/gradle-check/19091/

```
org.junit.ComparisonFailure: expected:<[U2pjDUQBSTGCCg5HgIy6P]Q> but was:<[2z3KRqgjRm2_YTrHqhobE]Q>
	at __randomizedtesting.SeedInfo.seed([E3E4A8C827F2BF8:6EE1AACB8B1101EE]:0)
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.indices.replication.SegmentReplicationIT.testNodeDropWithOngoingReplication(SegmentReplicationIT.java:450)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
```

**To Reproduce**
`./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testNodeDropWithOngoingReplication" -Dtests.seed=E3E4A8C827F2BF8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=tr -Dtests.timezone=CST -Druntime.java=20`

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by ltaragi** [comment]
Failed again [here](https://build.ci.opensearch.org/job/gradle-check/36199/testReport/junit/org.opensearch.remotestore/SegmentReplicationUsingRemoteStoreIT/testNodeDropWithOngoingReplication/)

**Comment by reta** [comment]
Closing in favour https://github.com/opensearch-project/OpenSearch/issues/14329
