### ISSUE TITLE
[BUG] AccessDeniedException[/usr/share/opensearch/data/nodes

### ISSUE THREAD

**Issue by drBenway** [opensearch-project/OpenSearch#845]
**Describe the bug**
I get AccessDeniedExecption when I update my ansible script from ELK 7.10.2 to opensearch

**To Reproduce**
use the [gist ](https://gist.github.com/drBenway/9b47db3e043530ac1b388df80befe34d)

[The ELK gist I used ](https://gist.github.com/drBenway/af1e606720228485870f1f1bddb165fc)

**Expected behavior**
I get "OpenSearch Dashboards server is not ready yet" and the error below in the docker logs for the node.

I got the same error when I tried to create a K8s setup based on the docker compose file for RC1

**Host/Environment (please complete the following information):**
 - OS: Linux mint 21

```
[2021-06-14T15:28:26,113][INFO ][o.o.p.PluginsService     ] [logging-qa] loaded plugin [opensearch-sql]
[2021-06-14T15:28:26,122][INFO ][o.o.s.OpenSearchSecurityPlugin] [logging-qa] Disabled https compression by default to mitigate BREACH attacks. You can enable it by setting 'http.compression: true' in opensearch.yml
[2021-06-14T15:28:26,128][DEPRECATION][o.o.d.c.s.Settings       ] [logging-qa] [node.max_local_storage_nodes] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
[2021-06-14T15:28:26,160][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [logging-qa] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: OpenSearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/opensearch/data/nodes];
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.main(Command.java:103) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
uncaught exception in thread [main]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
Caused by: org.opensearch.OpenSearchException: failed to bind service
	at org.opensearch.node.Node.<init>(Node.java:740) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/opensearch/data/nodes
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:388) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:694) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:801) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:787) ~[?:?]
	at org.opensearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:288) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:225) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:285) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:373) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	... 6 more
OpenSearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/opensearch/data/nodes];
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/opensearch/data/nodes
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:388)
	at java.base/java.nio.file.Files.createDirectory(Files.java:694)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:801)
	at java.base/java.nio.file.Files.createDirectories(Files.java:787)
	at org.opensearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:288)
	at org.opensearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:225)
	at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:285)
	at org.opensearch.node.Node.<init>(Node.java:373)
	at org.opensearch.node.Node.<init>(Node.java:301)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105)
For complete error details, refer to the log at /usr/share/opensearch/logs/logging-qa.log
```

**Comment by dblock** [comment]
@drBenway Did you figure this one out by any chance? Did this work out of the box with Elasticsearch 7.10.2?

**Comment by meghasaik** [comment]
Getting a "Bind for 0.0.0.0:9200 failed: port is already allocated" when trying to reproduce this bug. These are the steps I did:
- Ran the user’s ELK ansible script through the steps mentioned by him in the elasticsearch-7.10.2 folder. Except for the jvm.options file, all the other .yml files were not provided. Hence,  provided these files: logstash.yml-7.10.2, heartbeat.yml-7.10.2 and a kibana.yml-7.10.2. The files not provided are: cron_delete_after_20_days.sh, logstash.conf and test.json. 
- This script ran without any error.
-  After that, I ran the user's OpenSearch sensible script in the opensearch-1.0.0-rc1 folder.
- Except for the jvm.options file, all the other .yml files were not provided. Hence,  provided these files: opensarch.yml and opensearch-dashboard.yml for 1.0.0-rc1 version. The files not provided are: logstash.yml, logstash.conf and heartbeat.yml". 
-  This step led to the following error mentioned above Port already allocated error for 9200. The ports 9200 and 5601 are used in the elk as well as the OpenSearch ansible scripts.
<img width="1391" alt="Screen Shot 2021-10-01 at 1 04 06 PM" src="https://user-images.githubusercontent.com/44311835/135679945-b4ae7245-acff-4a8f-912e-1f5d31347140.png">

@drBenway Is this the correct way to proceed for reproducing the bug or am I missing any step. As the .yml files were not provided, Could you please provide more information or context on these files?

**Comment by dblock** [comment]
- Is this the container's port 9200? What is port 9200 used for?
- Or does the host need to have that port open as well (are you running an instance of OpenSearch already on it?)?

**Comment by meghasaik** [comment]
Yes, this is the container's port. In the Elk ansible script, the port :9200 is for ElasticSearch container for pulling its image. The user also needs it, as the port 9200 is also being used for OpenSearch installation in the OpenSearch ansible script.

**Comment by meghasaik** [comment]
After running the ansible-playbook playbook.yml cmd at the root of the opensearch-1.0.0-rc1 folder which downloads the opensearch and the opensearch-dashboard docker-images. For running the OpenSearch, the cmd: `docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:1.0.0-rc1` is run where the OpensearchDistro starts rather than starting OpenSearch. Also the node name with which it is started is different, as the node name that is given in the `tasks/main.yml which is logging.qa` is not used. An error is also generated: 

`[2021-10-04T22:50:32,620][ERROR][o.o.i.i.ManagedIndexCoordinator] [8710ec6b5172] Failed to clear ManagedIndexMetadata for index uuid: [OnFSdsEUQZS_ti17nKtQCA#metadata], failureMessage: [.opendistro-ism-config] IndexNotFoundException[no such index [.opendistro-ism-config]]  `

<img width="1488" alt="Screen Shot 2021-10-04 at 4 21 08 PM" src="https://user-images.githubusercontent.com/44311835/135937582-51076d8f-5166-4b40-a087-e9fcd59503c7.png">

**Comment by meghasaik** [comment]
Running the OpenSearch with a custom opensearch.yml through the command:  `docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -v /home/ubuntu/sample_data/custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml opensearchproject/opensearch:1.0.0-rc1` gives a Startup Exception error: failed to load plugin class      
 ```
[2021-10-05T16:08:01,925][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [single-node] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
```
<img width="1405" alt="Screen Shot 2021-10-05 at 10 55 53 AM" src="https://user-images.githubusercontent.com/44311835/136077023-80b6fa35-eae1-4da8-9a8a-1d30e1231ead.png">

**Comment by meghasaik** [comment]
Running the Opensearch ansible script installs the docker images and runs the Opensearch-1.0.0-rc1 version. This is verified through the `curl -XGET https://localhost:9200 -u 'admin:admin' --insecure` cmd.  By checking the logs through docker ID, the error specified in the above comment shows up: `[2021-10-04T22:50:32,620][ERROR][o.o.i.i.ManagedIndexCoordinator] [8710ec6b5172] Failed to clear ManagedIndexMetadata for index uuid: [OnFSdsEUQZS_ti17nKtQCA#metadata], failureMessage: [.opendistro-ism-config] IndexNotFoundException[no such index [.opendistro-ism-config]]`.  Even though this error is generated, the OpenSearch Dashboards error is not generated and the OpenSearch-Dashboards page can be viewed through:  `http://localhost:5601` in the browser.  The log:
<img width="1353" alt="Screen Shot 2021-10-05 at 3 52 34 PM" src="https://user-images.githubusercontent.com/44311835/136123833-5af5881f-9cdd-41f4-a6d3-7b59ec8f9bee.png">
