### ISSUE TITLE
[BUG][repository-gcs] proxy - Error getting access token for service account: Connect timed out

### ISSUE THREAD

**Issue by toby181** [opensearch-project/OpenSearch#8493]
**Describe the bug**
We're using the repository-gcs plugin in version 2.8.0 to store snapshots in a GCP bucket (google cloud storage). To connect to it it's necessary to configure a proxy, like we do for many other internal applications too. The in OpenSearch configured proxy has no effect, the connection to the bucket times out.

My configuration and tests:

**Test 1**
opensearch.yml
-> no proxy in opensearch.yml

API command for "custom1" (OpenSearch Dashboard Dev Tools):
```
PUT /_snapshot/opensearch-config-snapshot-custom1
{
  "type": "gcs",
  "settings": {
    "bucket": "opensearch-bucket1",
    "base_path": "snapshots",
    "client": "custom1",
    "connect_timeout": "5s",
    "endpoint": "https://storage.googleapis.com",
    "proxy.type": "http",
    "proxy.host": "proxy.example.com",
    "proxy.port": "3128"
  }
}
```
Test was executed without "endpoint" as well. Same result.
"connect_timeout" has NO effect. It times out after 20s.

Exception in Dev Tools:
```
{
  "error": {
    "root_cause": [
      {
        "type": "storage_exception",
        "reason": "storage_exception: Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[opensearch-config-snapshot-default] path [snapshots] is not accessible on cluster-manager node",
    "caused_by": {
      "type": "storage_exception",
      "reason": "storage_exception: Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com",
      "caused_by": {
        "type": "i_o_exception",
        "reason": "Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com",
        "caused_by": {
          "type": "i_o_exception",
          "reason": "Connect timed out"
        }
      }
    }
  },
  "status": 500
}
```

opensearch data node log below:
There's no log from the master node of this API command.
```
2023-07-06T15:14:47.884316888Z "Caused by: org.opensearch.common.io.stream.NotSerializableExceptionWrapper: storage_exception: Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com",
2023-07-06T15:14:47.884351516Z "at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:231) ~[?:?]",
2023-07-06T15:14:47.884354504Z "at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:312) ~[?:?]",
2023-07-06T15:14:47.884357637Z "at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:221) ~[?:?]",
2023-07-06T15:14:47.884361424Z "at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:218) ~[?:?]",
2023-07-06T15:14:47.884363931Z "at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[?:?]",
2023-07-06T15:14:47.884365978Z "at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[?:?]",
2023-07-06T15:14:47.884368375Z "at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[?:?]",
2023-07-06T15:14:47.884370486Z "at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:217) ~[?:?]",
2023-07-06T15:14:47.884372570Z "at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:171) ~[?:?]",
2023-07-06T15:14:47.884374699Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.lambda$writeBlobMultipart$7(GoogleCloudStorageBlobStore.java:361) ~[?:?]",
2023-07-06T15:14:47.884376768Z "at org.opensearch.repositories.gcs.SocketAccess.lambda$doPrivilegedVoidIOException$0(SocketAccess.java:67) ~[?:?]",
2023-07-06T15:14:47.884378828Z "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
2023-07-06T15:14:47.884380832Z "at org.opensearch.repositories.gcs.SocketAccess.doPrivilegedVoidIOException(SocketAccess.java:66) ~[?:?]",
2023-07-06T15:14:47.884382880Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobMultipart(GoogleCloudStorageBlobStore.java:361) ~[?:?]",
2023-07-06T15:14:47.884384945Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:263) ~[?:?]",
2023-07-06T15:14:47.884387105Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:95) ~[?:?]",
2023-07-06T15:14:47.884389193Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlobAtomic(GoogleCloudStorageBlobContainer.java:100) ~[?:?]",
2023-07-06T15:14:47.884391225Z "at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1608) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884393237Z "at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884395354Z "at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884397405Z "at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884408890Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
2023-07-06T15:14:47.884411281Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
2023-07-06T15:14:47.884413374Z "at java.lang.Thread.run(Thread.java:833) ~[?:?]",
2023-07-06T15:14:47.884427474Z "Caused by: java.io.IOException: Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com",
2023-07-06T15:14:47.884429513Z "at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:569) ~[?:?]",
2023-07-06T15:14:47.884434813Z "at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:257) ~[?:?]",
2023-07-06T15:14:47.884437056Z "at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:254) ~[?:?]",
2023-07-06T15:14:47.884439225Z "at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]",
2023-07-06T15:14:47.884441898Z "at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[?:?]",
2023-07-06T15:14:47.884443965Z "at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:580) ~[?:?]",
2023-07-06T15:14:47.884446332Z "at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:220) ~[?:?]",
2023-07-06T15:14:47.884448367Z "at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:170) ~[?:?]",
2023-07-06T15:14:47.884450500Z "at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:967) ~[?:?]",
2023-07-06T15:14:47.884452609Z "at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[?:?]",
2023-07-06T15:14:47.884454716Z "at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[?:?]",
2023-07-06T15:14:47.884456748Z "at org.opensearch.repositories.gcs.GoogleCloudStorageService$1.lambda$getHttpRequestInitializer$0(GoogleCloudStorageService.java:164) ~[?:?]",
2023-07-06T15:14:47.884458855Z "at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109) ~[?:?]",
2023-07-06T15:14:47.884460916Z "at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88) ~[?:?]",
2023-07-06T15:14:47.884462971Z "at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:521) ~[?:?]",
2023-07-06T15:14:47.884465032Z "at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455) ~[?:?]",
2023-07-06T15:14:47.884467056Z "at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565) ~[?:?]",
2023-07-06T15:14:47.884471550Z "at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:309) ~[?:?]",
2023-07-06T15:14:47.884473654Z "at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:221) ~[?:?]",
2023-07-06T15:14:47.884475718Z "at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:218) ~[?:?]",
2023-07-06T15:14:47.884477758Z "at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[?:?]",
2023-07-06T15:14:47.884479848Z "at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[?:?]",
2023-07-06T15:14:47.884481933Z "at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[?:?]",
2023-07-06T15:14:47.884484018Z "at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:217) ~[?:?]",
2023-07-06T15:14:47.884486060Z "at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:171) ~[?:?]",
2023-07-06T15:14:47.884488112Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.lambda$writeBlobMultipart$7(GoogleCloudStorageBlobStore.java:361) ~[?:?]",
2023-07-06T15:14:47.884490197Z "at org.opensearch.repositories.gcs.SocketAccess.lambda$doPrivilegedVoidIOException$0(SocketAccess.java:67) ~[?:?]",
2023-07-06T15:14:47.884492224Z "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
2023-07-06T15:14:47.884494229Z "at org.opensearch.repositories.gcs.SocketAccess.doPrivilegedVoidIOException(SocketAccess.java:66) ~[?:?]",
2023-07-06T15:14:47.884500163Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobMultipart(GoogleCloudStorageBlobStore.java:361) ~[?:?]",
2023-07-06T15:14:47.884505846Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:263) ~[?:?]",
2023-07-06T15:14:47.884507928Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:95) ~[?:?]",
2023-07-06T15:14:47.884509951Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlobAtomic(GoogleCloudStorageBlobContainer.java:100) ~[?:?]",
2023-07-06T15:14:47.884512005Z "at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1608) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884542348Z "at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884575406Z "at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884579575Z "at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884582408Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
2023-07-06T15:14:47.884584945Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
2023-07-06T15:14:47.884587351Z "at java.lang.Thread.run(Thread.java:833) ~[?:?]",
2023-07-06T15:14:47.884589492Z "Caused by: java.io.IOException: Connect timed out",
2023-07-06T15:14:47.884592180Z "at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]",
2023-07-06T15:14:47.884594416Z "at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]",
2023-07-06T15:14:47.884596499Z "at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]",
2023-07-06T15:14:47.884598618Z "at java.net.Socket.connect(Socket.java:633) ~[?:?]",
2023-07-06T15:14:47.884600814Z "at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]",
2023-07-06T15:14:47.884603025Z "at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]",
2023-07-06T15:14:47.884605133Z "at sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]",
2023-07-06T15:14:47.884607164Z "at sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]",
2023-07-06T15:14:47.884609213Z "at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]",
2023-07-06T15:14:47.884611190Z "at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]",
2023-07-06T15:14:47.884613607Z "at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]",
2023-07-06T15:14:47.884616130Z "at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]",
2023-07-06T15:14:47.884618318Z "at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]",
2023-07-06T15:14:47.884620385Z "at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]",
2023-07-06T15:14:47.884622597Z "at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430) ~[?:?]",
2023-07-06T15:14:47.884624682Z "at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401) ~[?:?]",
2023-07-06T15:14:47.884626731Z "at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[?:?]",
2023-07-06T15:14:47.884628799Z "at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113) ~[?:?]",
2023-07-06T15:14:47.884630921Z "at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[?:?]",
2023-07-06T15:14:47.884643139Z "at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[?:?]",
2023-07-06T15:14:47.884645354Z "at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:564) ~[?:?]",
2023-07-06T15:14:47.884647431Z "at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:257) ~[?:?]",
2023-07-06T15:14:47.884649483Z "at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:254) ~[?:?]",
2023-07-06T15:14:47.884651459Z "at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]",
2023-07-06T15:14:47.884653501Z "at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[?:?]",
2023-07-06T15:14:47.884655647Z "at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:580) ~[?:?]",
2023-07-06T15:14:47.884657792Z "at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:220) ~[?:?]",
2023-07-06T15:14:47.884659934Z "at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:170) ~[?:?]",
2023-07-06T15:14:47.884662014Z "at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:967) ~[?:?]",
2023-07-06T15:14:47.884664032Z "at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[?:?]",
2023-07-06T15:14:47.884666097Z "at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[?:?]",
2023-07-06T15:14:47.884668210Z "at org.opensearch.repositories.gcs.GoogleCloudStorageService$1.lambda$getHttpRequestInitializer$0(GoogleCloudStorageService.java:164) ~[?:?]",
2023-07-06T15:14:47.884670298Z "at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109) ~[?:?]",
2023-07-06T15:14:47.884672302Z "at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88) ~[?:?]",
2023-07-06T15:14:47.884674382Z "at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:521) ~[?:?]",
2023-07-06T15:14:47.884676515Z "at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455) ~[?:?]",
2023-07-06T15:14:47.884689666Z "at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565) ~[?:?]",
2023-07-06T15:14:47.884691997Z "at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:309) ~[?:?]",
2023-07-06T15:14:47.884694169Z "at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:221) ~[?:?]",
2023-07-06T15:14:47.884696193Z "at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:218) ~[?:?]",
2023-07-06T15:14:47.884698238Z "at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[?:?]",
2023-07-06T15:14:47.884700274Z "at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[?:?]",
2023-07-06T15:14:47.884702501Z "at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[?:?]",
2023-07-06T15:14:47.884704581Z "at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:217) ~[?:?]",
2023-07-06T15:14:47.884706587Z "at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:171) ~[?:?]",
2023-07-06T15:14:47.884708707Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.lambda$writeBlobMultipart$7(GoogleCloudStorageBlobStore.java:361) ~[?:?]",
2023-07-06T15:14:47.884713513Z "at org.opensearch.repositories.gcs.SocketAccess.lambda$doPrivilegedVoidIOException$0(SocketAccess.java:67) ~[?:?]",
2023-07-06T15:14:47.884715618Z "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
2023-07-06T15:14:47.884720119Z "at org.opensearch.repositories.gcs.SocketAccess.doPrivilegedVoidIOException(SocketAccess.java:66) ~[?:?]",
2023-07-06T15:14:47.884722267Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobMultipart(GoogleCloudStorageBlobStore.java:361) ~[?:?]",
2023-07-06T15:14:47.884724394Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:263) ~[?:?]",
2023-07-06T15:14:47.884726428Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:95) ~[?:?]",
2023-07-06T15:14:47.884728474Z "at org.opensearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlobAtomic(GoogleCloudStorageBlobContainer.java:100) ~[?:?]",
2023-07-06T15:14:47.884730556Z "at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1608) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884732656Z "at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:324) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884734713Z "at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884736697Z "at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.8.0.jar:2.8.0]",
2023-07-06T15:14:47.884738731Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
2023-07-06T15:14:47.884740848Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
2023-07-06T15:14:47.884742924Z "at java.lang.Thread.run(Thread.java:833) ~[?:?]"] }
```

**Test 2**
opensearch.yml
```
        #gcs configuration
        gcs.client.default.proxy.type: http
        gcs.client.default.proxy.host: proxy.example.com # the hostname for your proxy server
        gcs.client.default.proxy.port: 3128 # port for your proxy server
```

API command for "default" (OpenSearch Dashboard Dev Tools):
```
PUT /_snapshot/opensearch-config-snapshot-default
{
  "type": "gcs",
  "settings": {
    "bucket": "opensearch-bucket1",
    "base_path": "snapshots",
    "client": "default"
  }
}
```
Exception in Dev Tools for "custom1"

######

**Test 3**

proxy set via environment variable:
```
values:
...
    extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
    - name: HTTP_PROXY
      value: http://proxy.example.com:3128
    - name: HTTPS_PROXY
      value: http://proxy.example.com:3128
    - name: NO_PROXY
      value: ".example.com"
    - name: http_proxy
      value: http://proxy.example.com:3128
    - name: https_proxy
      value: http://proxy.example.com:3128
    - name: no_proxy
      value: ".proxy.example"
```
API command for "custom1" (OpenSearch Dashboard Dev Tools):
```
PUT /_snapshot/opensearch-config-snapshot-custom1
{
  "type": "gcs",
  "settings": {
    "bucket": "opensearch-bucket1",
    "base_path": "snapshots",
    "client": "custom1"
  }
}
```

Exception in Dev Tools
```
{
  "error": {
    "root_cause": [
      {
        "type": "storage_exception",
        "reason": "storage_exception: Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[opensearch-config-snapshot-default] path [snapshots] is not accessible on cluster-manager node",
    "caused_by": {
      "type": "storage_exception",
      "reason": "storage_exception: Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com",
      "caused_by": {
        "type": "i_o_exception",
        "reason": "Error getting access token for service account: Connect timed out, iss: opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com",
        "caused_by": {
          "type": "i_o_exception",
          "reason": "Connect timed out"
        }
      }
    }
  },
  "status": 500
}
```

**Test 4**
proxy set via environment variable:
```
values:
...
    extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
    - name: HTTP_PROXY
      value: http://proxy.example.com:3128
    - name: HTTPS_PROXY
      value: http://proxy.example.com:3128
    - name: NO_PROXY
      value: ".example.com"
    - name: http_proxy
      value: http://proxy.example.com:3128
    - name: https_proxy
      value: http://proxy.example.com:3128
    - name: no_proxy
      value: ".proxy.example"
```

Running curl within the pod opensearch-cluster-stage-master-1  to prove a successful usage of proxy:
```
[opensearch@opensearch-cluster-stage-master-1 ~]$ env | grep -i proxy
NO_PROXY=.example.com
http_proxy=http://proxy.example.com:3128
HTTPS_PROXY=http://proxy.example.com:3128
https_proxy=http://proxy.example.com:3128
no_proxy=.example.com
HTTP_PROXY=http://proxy.example.com:3128
[opensearch@opensearch-cluster-stage-master-1 ~]$ curl https://storage.googleapis.com
<?xml version='1.0' encoding='UTF-8'?><Error><Code>MissingSecurityHeader</Code><Message>Your request was missing a required header.</Message><Details>Authorization</Details></Error>
```

**Expected behavior**
OpenSearch either takes the proxy in opensearch.yml or in the API (Dev Tools) command into account.

**Plugins**
repository-gcs - 2.8.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - Kubernetes 1.24
 - OpenSearch 2.8.0

**Additional context**

**Comment by dblock** [comment]
This needs some debugging to see where the proxy settings are being loaded and used, to begin with.

**Comment by toby181** [comment]
I did a test outside of OpenSearch to verify the functionality of the bucket and the proxy, which I did already before but did not document it here.
The used docker image is google/cloud-sdk:alpine. Running in the same namespace as OpenSearch.

proxy set
```
temp-gcloud:/# gcloud config list
[component_manager]
disable_update_check = true
[core]
account = opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com
disable_usage_reporting = true
[metrics]
environment = github_docker_image
[proxy]
address = proxy.example.com
port = 3128
type = http

temp-gcloud:/# gsutil ls gs://opensearch-bucket1
gs://opensearch-bucket1/angry-bird.jpeg
```

proxy unset
```
temp-gcloud:/# gcloud config unset proxy/address
Unset property [proxy/address].
temp-gcloud:/# gcloud config unset proxy/port
Unset property [proxy/port].
temp-gcloud:/# gcloud config unset proxy/type
Unset property [proxy/type].

temp-gcloud:/# gcloud config list
[component_manager]
disable_update_check = true
[core]
account = opensearch-bucket1@gcp-project-name.iam.gserviceaccount.com
disable_usage_reporting = true
[metrics]
environment = github_docker_image

Your active configuration is: [default]

temp-gcloud:/# gsutil ls gs://opensearch-bucket1
INFO 0707 07:19:46.689703 retry_util.py] Retrying request, attempt #1...
INFO 0707 07:20:49.158464 retry_util.py] Retrying request, attempt #2...
INFO 0707 07:21:53.489726 retry_util.py] Retrying request, attempt #3...
^CCaught CTRL-C (signal 2) - exiting
```

**Comment by dblock** [comment]
Thanks @toby181. Are you trying to debug it?

**Comment by toby181** [comment]
Thought you're doing that @dblock 😆
How can I debug that?

**Comment by dblock** [comment]
> Thought you're doing that @dblock 😆 How can I debug that?

Sorry, haven't worked with repository-gcs at all.

**Comment by minalsha** [comment]
Havent worked on this repo. QQ: @toby181  with the inputs provided by @dblock  above, are you able to debug?
