### ISSUE TITLE
[BUG] Flaky test RemoteStoreIT.testStaleCommitDeletionWithInvokeFlush

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#8504]
**Describe the bug**
org.opensearch.remotestore.RemoteStoreIT.testStaleCommitDeletionWithInvokeFlush is flaky.

```
	Suppressed: java.lang.AssertionError: expected:<5> but was:<6>
		at org.junit.Assert.fail(Assert.java:89)
		at org.junit.Assert.failNotEquals(Assert.java:835)
		at org.junit.Assert.assertEquals(Assert.java:647)
		at org.junit.Assert.assertEquals(Assert.java:633)
		at org.opensearch.remotestore.RemoteStoreIT.lambda$testStaleCommitDeletionWithInvokeFlush$4(RemoteStoreIT.java:303)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1072)
		... 39 more
```
**To Reproduce**
CI build - https://build.ci.opensearch.org/job/gradle-check/19303/

**Expected behavior**
Test should pass.

**Plugins**
Standard

**Screenshots**
NA

**Host/Environment (please complete the following information):**

**Additional context**
NA

**Comment by sachinpkale** [comment]
Muting these tests as part of https://github.com/opensearch-project/OpenSearch/pull/8516. I will work on fixing the flakiness.
