### ISSUE TITLE
[Concurrent Segment Search] Fix SignificantTerms related ITs

### ISSUE THREAD

**Issue by jed326** [opensearch-project/OpenSearch#8509]
Subtask for #7357 to focus on the test failures related to SigTerms:

```
org.opensearch.search.aggregations.bucket.TermsShardMinDocCountIT.testShardMinDocCountSignificantTermsTest

REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.TermsShardMinDocCountIT.testShardMinDocCountSignificantTermsTest" -Dtests.seed=5A2A89155E5AADBB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb -Dtests.timezone=Africa/Addis_Ababa -Druntime.java=17

java.lang.AssertionError: 
Expected: <0>
     but: was <2>
Expected :<0>
Actual   :<2>
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([5A2A89155E5AADBB:2F32E39B05FAA329]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.aggregations.bucket.TermsShardMinDocCountIT.testShardMinDocCountSignificantTermsTest(TermsShardMinDocCountIT.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

```
org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testBackgroundVsSeparateSet
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testBackgroundVsSeparateSet" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testBackgroundVsSeparateSet" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17

java.lang.NullPointerException: Cannot invoke "org.opensearch.search.aggregations.bucket.terms.SignificantTerms$Bucket.getSignificanceScore()" because the return value of "org.opensearch.search.aggregations.bucket.terms.SignificantTerms.getBucketByKey(String)" is null

	at org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testBackgroundVsSeparateSet(SignificantTermsSignificanceScoreIT.java:358)
	at org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testBackgroundVsSeparateSet(SignificantTermsSignificanceScoreIT.java:261)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
```
org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testScoresEqualForPositiveAndNegative
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testScoresEqualForPositiveAndNegative" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testScoresEqualForPositiveAndNegative" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17

Failed to execute phase [query], all shards failed
; shardFailures {[ssHwNGysTLmOcFBG_NA27w][test][0]: RemoteTransportException[[node_s0][127.0.0.1:51969][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NotSerializableExceptionWrapper[runtime_exception: java.util.concurrent.ExecutionException: java.lang.AssertionError: StoredFieldsReader are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[opensearch[node_s0][index_searcher][T#3],5,TGRP-SignificantTermsSignificanceScoreIT] and consumed in Thread[opensearch[node_s0][index_searcher][T#2],5,TGRP-SignificantTermsSignificanceScoreIT].]; nested: NotSerializableExceptionWrapper[execution_exception: java.lang.AssertionError: StoredFieldsReader are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[opensearch[node_s0][index_searcher][T#3],5,TGRP-SignificantTermsSignificanceScoreIT] and consumed in Thread[opensearch[node_s0][index_searcher][T#2],5,TGRP-SignificantTermsSignificanceScoreIT].]; nested: NotSerializableExceptionWrapper[assertion_error: StoredFieldsReader are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[opensearch[node_s0][index_searcher][T#3],5,TGRP-SignificantTermsSignificanceScoreIT] and consumed in Thread[opensearch[node_s0][index_searcher][T#2],5,TGRP-SignificantTermsSignificanceScoreIT].]; }
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:665)

```
```
org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testXContentResponse

REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testXContentResponse" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17

java.lang.AssertionError: 
Expected: "{\"class\":{\"doc_count_error_upper_bound\":0,\"sum_other_doc_count\":0,\"buckets\":[{\"key\":\"0\",\"doc_count\":4,\"sig_terms\":{\"doc_count\":4,\"bg_count\":7,\"buckets\":[{\"key\":0,\"doc_count\":4,\"score\":0.39999999999999997,\"bg_count\":5}]}},{\"key\":\"1\",\"doc_count\":3,\"sig_terms\":{\"doc_count\":3,\"bg_count\":7,\"buckets\":[{\"key\":1,\"doc_count\":3,\"score\":0.75,\"bg_count\":4}]}}]}}"
     but: was "{\"class\":{\"doc_count_error_upper_bound\":0,\"sum_other_doc_count\":0,\"buckets\":[{\"key\":\"0\",\"doc_count\":4,\"sig_terms\":{\"doc_count\":4,\"bg_count\":14,\"buckets\":[{\"key\":0,\"doc_count\":4,\"score\":0.39999999999999997,\"bg_count\":10}]}},{\"key\":\"1\",\"doc_count\":3,\"sig_terms\":{\"doc_count\":3,\"bg_count\":14,\"buckets\":[{\"key\":1,\"doc_count\":3,\"score\":0.75,\"bg_count\":8}]}}]}}"
Expected :{\"class\":{\"doc_count_error_upper_bound\":0,\"sum_other_doc_count\":0,\"buckets\":[{\"key\":\"0\",\"doc_count\":4,\"sig_terms\":{\"doc_count\":4,\"bg_count\":7,\"buckets\":[{\"key\":0,\"doc_count\":4,\"score\":0.39999999999999997,\"bg_count\":5}]}} ...

Actual   :{\"class\":{\"doc_count_error_upper_bound\":0,\"sum_other_doc_count\":0,\"buckets\":[{\"key\":\"0\",\"doc_count\":4,\"sig_terms\":{\"doc_count\":4,\"bg_count\":14,\"buckets\":[{\"key\":0,\"doc_count\":4,\"score\":0.39999999999999997,\"bg_count\":10}] ...

```
```
org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testReduceFromSeveralShards
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testReduceFromSeveralShards" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17

java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <240L>
Expected :<0L>
Actual   :<240L>
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([6D7B107FC7821E62:13A8213967CADF8]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.opensearch.test.InternalTestCluster.lambda$ensureEstimatedStats$41(InternalTestCluster.java:2659)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1084)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1057)

```
```
org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testPopularTermManyDeletedDocs
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testPopularTermManyDeletedDocs" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17

java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <240L>
Expected :<0L>
Actual   :<240L>
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([6D7B107FC7821E62:C84246803B2AAFB0]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.opensearch.test.InternalTestCluster.lambda$ensureEstimatedStats$41(InternalTestCluster.java:2659)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1084)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1057)
	at org.opensearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2657)
	at org.opensearch.test.TestCluster.assertAfterTest(TestCluster.java:104)
```

**Comment by jed326** [comment]
Breaking down the different failures here:

| Test | Failure Reason |
| --- | --- |
| `SignificantTermsSignificanceScoreIT.testBackgroundVsSeparateSet` | The test is not finding the correct buckets in the aggs response |
| `SignificantTermsSignificanceScoreIT.testScoresEqualForPositiveAndNegative` | Shard queries are failing. Seems to be the same issue as #8095, should be resolved after #8303 |
| `SignificantTermsSignificanceScoreIT.testXContentResponse` | Aggs response output is not as expected |
| `SignificantTermsSignificanceScoreIT.testReduceFromSeveralShards` | After test execution failures, likely due to other tests failing. Does not fail when run on its own. |
| `SignificantTermsSignificanceScoreIT.testPopularTermManyDeletedDocs` | After test execution failures, likely due to other tests failing. Does not fail when run on its own. |
| `TermsShardMinDocCountIT.testShardMinDocCountSignificantTermsTest` | tbd |

**Comment by jed326** [comment]
Took a deeper look at this and there are 3 main issues here, which I'm going to further break into other tasks to have a clear conversation thread.
1. `bg_count` in SignificantTerms performs a shard level query, so when we reduce the slice level aggs these counts get incorrectly summed together.
2. `significantText` queries are encountering assert codec failures even after #8303 is merged
3. `SignificantTermsSignificanceScoreIT.testBackgroundVsSeparateSet` is not finding the expected number of buckets. Currently I suspect this is due to the `bg_count` issue messing with scoring so planning on revisiting this later.

**Comment by jed326** [comment]
I ran some more tests and confirmed that https://github.com/opensearch-project/OpenSearch/issues/8790 should resolve the rest of the test failures under `SignificantTermsSignificanceScoreIT`. 
I am still seeing test failures for `TermsShardMinDocCountIT.testShardMinDocCountSignificantTermsTest`, however these seem related to concurrent aggs in general rather than specifically significant terms aggs, so I will track that in a different issue.
