### ISSUE TITLE
[Concurrent Segment Search] Fix Sort related ITs

### ISSUE THREAD

**Issue by jed326** [opensearch-project/OpenSearch#8510]
Subtask for #7357 to focus on Sort related failures

```
org.opensearch.search.sort.FieldSortIT.testScriptFieldSort
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.sort.FieldSortIT.testScriptFieldSort" -Dtests.seed=F657C804A435520E -Dtests.locale=cs -Dtests.timezone=Pacific/Auckland -Druntime.java=17

java.lang.AssertionError: 
Expected: <0.0>
     but: was <2.0>
Expected :<0.0>
Actual   :<2.0>
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([F657C804A435520E:DB88407EB070FA46]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.sort.FieldSortIT.testScriptFieldSort(FieldSortIT.java:1993)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

```
org.opensearch.search.sort.SimpleSortIT.testSimpleSorts
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.sort.SimpleSortIT.testSimpleSorts" -Dtests.seed=DC7EE9541460FD12 -Dtests.locale=es-NI -Dtests.timezone=America/Campo_Grande -Druntime.java=17

java.lang.AssertionError: 
Expected: "1"
     but: was "2"
Expected :1
Actual   :2
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([DC7EE9541460FD12:9E050C9C2006810C]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.sort.SimpleSortIT.testSimpleSorts(SimpleSortIT.java:216)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by jed326** [comment]
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.sort.SimpleSortIT.testSimpleSorts" -Dtests.seed=5B6F53240BBECC6D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-HN -Dtests.timezone=Australia/Hobart -Druntime.java=20
  2> Failed to execute phase [query], all shards failed; shardFailures {[KnelMzCcR4iT9A4nGZDbQA][test][0]: RemoteTransportException[[node_s5][127.0.0.1:34989][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute concurrent segment search thread]]; nested: NotSerializableExceptionWrapper[assertion_error: Numeric doc values are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[#3196,opensearch[node_s5][index_searcher][T#1],5,TGRP-SimpleSortIT] and consumed in Thread[#3198,opensearch[node_s5][index_searcher][T#3],5,TGRP-SimpleSortIT].]; }
        at __randomizedtesting.SeedInfo.seed([5B6F53240BBECC6D:1914B6EC3FD8B073]:0)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:677)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:373)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:716)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:485)
        at app//org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:295)
        at app//org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
        at app//org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74)
        at app//org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:749)
        at app//org.opensearch.transport.TransportService$6.handleException(TransportService.java:875)
        at app//org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1483)
        at app//org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:421)
        at app//org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
        at app//org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:419)
        at app//org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:411)
        at app//org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:159)
        at app//org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:115)
        at app//org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:767)
        at app//org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
        at app//org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
        at app//org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
        at app//org.opensearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:341)
        at app//org.opensearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:246)
        at app//org.opensearch.nio.BytesChannelContext.read(BytesChannelContext.java:59)
        at app//org.opensearch.nio.EventHandler.handleRead(EventHandler.java:152)
        at app//org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167)
        at app//org.opensearch.nio.NioSelector.handleRead(NioSelector.java:438)
        at app//org.opensearch.nio.NioSelector.processKey(NioSelector.java:264)
        at app//org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:191)
        at app//org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148)
        at java.base@20.0.2/java.lang.Thread.run(Thread.java:1623)

        Caused by:
        NotSerializableExceptionWrapper[assertion_error: Numeric doc values are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[#3196,opensearch[node_s5][index_searcher][T#1],5,TGRP-SimpleSortIT] and consumed in Thread[#3198,opensearch[node_s5][index_searcher][T#3],5,TGRP-SimpleSortIT].]
            at org.apache.lucene.tests.index.AssertingLeafReader.assertThread(AssertingLeafReader.java:67)
            at org.apache.lucene.tests.index.AssertingLeafReader$AssertingSortedDocValues.advanceExact(AssertingLeafReader.java:879)
            at org.apache.lucene.index.SingletonSortedSetDocValues.advanceExact(SingletonSortedSetDocValues.java:85)
            at org.opensearch.index.fielddata.FieldData$12.advanceExact(FieldData.java:429)
            at org.opensearch.index.fielddata.ScriptDocValues$BinaryScriptDocValues.setNextDocId(ScriptDocValues.java:506)
            at org.opensearch.index.fielddata.ScriptDocValues$Strings.setNextDocId(ScriptDocValues.java:545)
            at org.opensearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:100)
            at org.opensearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:55)
            at org.opensearch.search.sort.SimpleSortIT$CustomScriptPlugin.lambda$pluginScripts$0(SimpleSortIT.java:90)
            at org.opensearch.script.MockDeterministicScript$1.apply(MockDeterministicScript.java:55)
            at org.opensearch.script.MockScriptEngine$MockStringSortScriptFactory$1.execute(MockScriptEngine.java:770)
            at org.opensearch.search.sort.ScriptSortBuilder$1$1.binaryValue(ScriptSortBuilder.java:374)
            at org.apache.lucene.search.FieldComparator$TermValComparator.getValueForDoc(FieldComparator.java:239)
            at org.apache.lucene.search.FieldComparator$TermValComparator.copy(FieldComparator.java:260)
            at org.apache.lucene.search.TopFieldCollector$TopFieldLeafCollector.collectAnyHit(TopFieldCollector.java:125)
            at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.collect(TopFieldCollector.java:209)
            at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:274)
            at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:254)
            at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71)
            at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
            at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:317)
            at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:276)
            at org.apache.lucene.search.IndexSearcher.lambda$search$1(IndexSearcher.java:723)
            at java.util.concurrent.FutureTask.run(FutureTask.java:317)
            at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
            at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
            at java.lang.Thread.run(Thread.java:1623)

```

**Comment by neetikasinghal** [comment]
i am working on this

**Comment by neetikasinghal** [comment]
Both the tests are failing due to a common issue. There is common instance of NumberSortScript in the initialization of DoubleValuesComparatorSource that is being shared by all the leaves, ref: [link](https://github.com/opensearch-project/OpenSearch/blob/8255050540249696f1de672db693f0e2c9e14390/server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java#L406-L420). The problem happens during the search phase(ref: [link](https://github.com/opensearch-project/OpenSearch/blob/8255050540249696f1de672db693f0e2c9e14390/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L321)) when the doubleValue is being accessed through the leafScript that is updated by some other thread (ref: [link](https://github.com/opensearch-project/OpenSearch/blob/8255050540249696f1de672db693f0e2c9e14390/server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java#L420))

A similar problem exists for the String use-case as well, refer: [link](https://github.com/opensearch-project/OpenSearch/blob/8255050540249696f1de672db693f0e2c9e14390/server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java#L358-L375)

The initialization of the above ComparatorSource happens when the sort is being built with the help of ScriptSortBuilder.java (ref: [link](https://github.com/opensearch-project/OpenSearch/blob/8255050540249696f1de672db693f0e2c9e14390/server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java#L323)) during the executeQueryPhase.

https://github.com/opensearch-project/OpenSearch/compare/main...neetikasinghal:OpenSearch:sort-tests fixes the tests, seems to be one of the possible ways of dealing with this issue.

**Comment by neetikasinghal** [comment]
@sohami @reta @andrross I would love to hear your thoughts on this.

**Comment by reta** [comment]
> @sohami @reta @andrross I would love to hear your thoughts on this.

Thanks @neetikasinghal , I think the solution you've implemented is basically thread local `XxxSortScript`, we could switch to `ThreadLocal` instead of map but that won't make the flow better. 

> The initialization of the above ComparatorSource happens when the sort is being built with the help of ScriptSortBuilder.java during the executeQueryPhase.

It looks (at first) that the issue is that sort is set globally, per `SearchContext` which make sense in general but does not play well in case of concurrent search flow. What if we do instead pass the new sort instance to each TopDocsCollectorContext (TopDocsCollectorContext::createTopDocsCollectorContext) in this case?

**Comment by neetikasinghal** [comment]
>It looks (at first) that the issue is that sort is set globally, per SearchContext which make sense in general but does not play well in case of concurrent search flow. What if we do instead pass the new sort instance to each TopDocsCollectorContext (TopDocsCollectorContext::createTopDocsCollectorContext) in this case?

@reta what do u mean by "pass the new sort instance to each TopDocsCollectorContext"?
TopDocsCollectorContext::createTopDocsCollectorContext is called only once in case of the concurrent search flow as well, its during search phase(ref: [link](https://github.com/opensearch-project/OpenSearch/blob/8255050540249696f1de672db693f0e2c9e14390/server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java#L82)) when the sort script is being shared across the leaves.

**Comment by reta** [comment]
@neetikasinghal may be I am mistaken but it looks that all the issues come from sharing the `sort`, so if you look into `TopDocsCollectorContext`, there are two classes there, `SimpleTopDocsCollectorContext` and `CollapsingTopDocsCollectorContext`. 

In `SimpleTopDocsCollectorContext` we create the shared collector manager instance, using the shared `sort`, like here for example: 

```
return TopFieldCollector.createSharedManager(sortAndFormats.sort, numHits, (FieldDoc) searchAfter, hitCountThreshold);
```

Later on, this `sort` internally is passed to each collector instance created by the collector manager. So I was thinking to modify this part and always provide the copy of `sort` to each collector.

**Comment by neetikasinghal** [comment]
@reta got it, yes I thought about it as well, but currently here is the flow

```
search -> searchLeaf -> bulkScorer.score (ContextIndexSearcher.java) ->  collector.collect(Weight.java - lucene) -> TopFieldLeafCollector:: collect
```

the collect function in `TopFieldLeafCollector` of lucene doesnt have any dependency on the sort, it uses comparators to count hits, creates a slot and copies the value(getting this value is done by the script for this teat) to the slot.
sort is only used in the `canEarlyTerminate::TopFieldLeafCollector` of lucene, so even if we have a new instance of sort created, I don't think, it will solve this use-case.

**Comment by reta** [comment]
> the collect function in TopFieldLeafCollector of lucene doesnt have any dependency on the sort, it uses comparators to count hits, 

Ah didn't see that, thanks @neetikasinghal

**Comment by sohami** [comment]
> I think the solution you've implemented is basically thread local XxxSortScript, we could switch to ThreadLocal instead of map but that won't make the flow better.

>> Thanks for the suggestion, yes using ThreadLocal would improve the code readability, we could switch to that, in case we choose to go with this solution.

@reta If my understanding is correct with `ThreadLocal` it will still keep the variable around until the thread is terminated. So if same thread serves different types of request it will hold on to this `LeafScript` (which may not be needed and can cause weird behavior if stale value is consumed in some path). I think with the local map that problem will not be there also it is along the lines of the `DoubleValueComparatorSource` implementation using the `IndexFieldData` to keep track of each leaf context. Here it is cache of leafScripts vs fieldData. However, with threadLocal the contention across slices will not be there. I am still leaning to keep using map here as same holds for fieldData cache. thoughts ?

**Comment by reta** [comment]
> I am still leaning to keep using map here as same holds for fieldData cache. thoughts ?
Correct, the thread local needs cleanup, so map alternative is not as bad, worth trying out. I will try to spend some time figuring out if there is any other option out there.

**Comment by neetikasinghal** [comment]
thanks @sohami and @reta, I have raised a PR for this.
