### ISSUE TITLE
[BUG] Flaky org.opensearch.index.codec.CodecTests.testCodecServiceWithNullMapperService tests

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#8593]
**Describe the bug**
The org.opensearch.index.codec.CodecTests.testCodecServiceWithNullMapperService test is flaky

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([3B9EE058DD15AB90:12A18189C846CB09]:0)
	at org.opensearch.index.codec.CodecService.<init>(CodecService.java:74)
	at org.opensearch.index.codec.CodecTests.testCodecServiceWithNullMapperService(CodecTests.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl
```

CC @sarthakaggarwal97 

**To Reproduce**
```
./gradlew ':server:test' --tests "org.opensearch.index.codec.CodecTests.testCodecServiceWithNullMapperService" -Dtests.seed=3B9EE058DD15AB90 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-EC -Dtests.timezone=America/Matamoros -Druntime.java=17
```

**Expected behavior**
Test must always pass

**Plugins**
Standard

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
https://build.ci.opensearch.org/job/gradle-check/19677/testReport/junit/org.opensearch.index.codec/CodecTests/testCodecServiceWithNullMapperService/

**Comment by sarthakaggarwal97** [comment]
@reta I think we can close this?
