### ISSUE TITLE
[BUG] org.opensearch.indices.replication.RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty is failing

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#8699]
**Describe the bug**

The org.opensearch.indices.replication.RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty is failing on `main`, apparently after https://github.com/opensearch-project/OpenSearch/pull/8433

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=100, name=opensearch[org.opensearch.indices.replication.RemoteStoreReplicationSourceTests][remote_refresh][T#1], state=RUNNABLE, group=TGRP-RemoteStoreReplicationSourceTests]
Caused by: java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([92C4ACD8A776127B]:0)
	at org.opensearch.index.seqno.ReplicationTracker.setLatestReplicationCheckpoint(ReplicationTracker.java:1216)
	at org.opensearch.index.shard.IndexShard.onCheckpointPublished(IndexShard.java:1857)
	at org.opensearch.index.shard.RemoteStoreRefreshListener.syncSegments(RemoteStoreRefreshListener.java:195)
	at org.opensearch.index.shard.RemoteStoreRefreshListener.lambda$afterRefresh$0(RemoteStoreRefreshListener.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**To Reproduce**
```
./gradlew ':server:test' --tests "org.opensearch.indices.replication.RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty" -Dtests.seed=92C4ACD8A776127B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sk-SK -Dtests.timezone=Canada/Yukon -Druntime.java=20
```

**Expected behavior**
The test should always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI
 - 
**Additional context**
https://build.ci.opensearch.org/job/gradle-check/20172/
https://build.ci.opensearch.org/job/gradle-check/20196/

**Comment by reta** [comment]
@ankitkala it seems like it is caused by https://github.com/opensearch-project/OpenSearch/pull/8433, cloud you please take a look?
