### ISSUE TITLE
[BUG] S3 repository is not getting registered with Credentials error

### ISSUE THREAD

**Issue by swapnilsvaidya** [opensearch-project/OpenSearch#8741]
**Describe the bug**
I am getting authentication error while using AssumeRole functionality while registering S3 repository
I have followed the steps to configure S3 repository with OpenSearch as mentioned in https://opensearch.org/docs/2.7/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#amazon-s3
**To Reproduce**
1) Installed S3 plugin
2) Added S3 settings in opensearch.yml
3) Created keystore.
4) Added role arn and role session name in keystore using following commands.
sudo ./bin/opensearch-keystore add s3.client.default.role_arn
sudo ./bin/opensearch-keystore add s3.client.default.role_session_name
5) Started OpenSearch.

After completion of above steps when I am trying to register S3 repo using following API:
PUT http://<IP address>:9200/_snapshot/my-s3-repository
{
  "type": "s3",
  "settings": {
    "bucket": "<bucket name>"
  }
}

I am getting following error:
Caused by: java.io.IOException: Unable to upload object [tests-cYs_EAlrSHudGi6LLl1LZA/master.dat] using a single upload
	at org.opensearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:379) ~[?:?]
	at org.opensearch.repositories.s3.S3BlobContainer.lambda$writeBlob$1(S3BlobContainer.java:144) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at org.opensearch.repositories.s3.SocketAccess.doPrivilegedIOException(SocketAccess.java:61) ~[?:?]
	at org.opensearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:142) ~[?:?]
	at org.opensearch.repositories.s3.S3BlobContainer.writeBlobAtomic(S3BlobContainer.java:159) ~[?:?]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1607) ~[opensearch-2.7.0.jar:2.7.0]
	... 6 more
Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@11fa7f99: access denied ("java.io.FilePermission" "/home/opensearch/.aws/credentials" "read"), com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@2dd39cd2: Failed to connect to service endpoint: ]

**Expected behavior**
S3 repository should get registered with OpenSearch

**Plugins**
repository-s3

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: ubuntu
 - Version 2.7.0

**Additional context**

**Comment by Bukhtawar** [comment]
```
Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@11fa7f99: access denied ("java.io.FilePermission" "/home/opensearch/.aws/credentials" "read"), com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@2dd39cd2: Failed to connect to service endpoint: ]


```

Looks like more of credential setup issue rather than a code bug. Looks like the permission on this file is insufficient
```
/home/opensearch/.aws/credentials
```
