### ISSUE TITLE
[Flaky Test] SnapshotResiliencyTests.testConcurrentSnapshotDeleteAndDeleteIndex if flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#8771]
https://build.ci.opensearch.org/job/gradle-check/20332/

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotDeleteAndDeleteIndex" -Dtests.seed=B7F15DFF786CE73D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-NI -Dtests.timezone=Asia/Oral -Druntime.java=17
NOTE: leaving temporary files on disk at: /var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.snapshots.SnapshotResiliencyTests_B7F15DFF786CE73D-001
NOTE: test params are: codec=Asserting(Lucene95): {}, docValues:{}, maxPointsInLeafNode=330, maxMBSortInHeap=6.1702426242178525, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=es-NI, timezone=Asia/Oral
NOTE: Linux 5.15.0-1036-aws amd64/Eclipse Adoptium 17.0.7 (64-bit)/cpus=96,threads=1,free=189188400,total=536870912
```

**Comment by dblock** [comment]
https://build.ci.opensearch.org/job/gradle-check/26641/

https://github.com/opensearch-project/OpenSearch/issues/10318#event-10531174487

**Comment by andrross** [comment]
https://github.com/opensearch-project/OpenSearch/pull/12335#issuecomment-1946461615:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotDeleteAndDeleteIndex" -Dtests.seed=E816C7242330BF50 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms-MY -Dtests.timezone=Europe/Athens -Druntime.java=21

org.opensearch.snapshots.SnapshotResiliencyTests > testConcurrentSnapshotDeleteAndDeleteIndex FAILED
    java.lang.AssertionError: java.lang.StringIndexOutOfBoundsException: Range [13, 2) out of bounds for length 6
        at __randomizedtesting.SeedInfo.seed([E816C7242330BF50:BD5D3283E0ED3D1D]:0)
        at org.opensearch.repositories.blobstore.BlobStoreRepository.lambda$executeOneStaleIndexDelete$40(BlobStoreRepository.java:1709)
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74)
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at org.opensearch.cluster.coordination.AbstractCoordinatorTestCase$1.run(AbstractCoordinatorTestCase.java:1498)
        at org.opensearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:147)
        at org.opensearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:141)
        at org.opensearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:91)
        at org.opensearch.snapshots.SnapshotResiliencyTests.runUntil(SnapshotResiliencyTests.java:1613)
        at org.opensearch.snapshots.SnapshotResiliencyTests.verifyReposThenStopServices(SnapshotResiliencyTests.java:335)

        Caused by:
        java.lang.StringIndexOutOfBoundsException: Range [13, 2) out of bounds for length 6
            at java.****/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
            at java.****/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
            at java.****/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
            at java.****/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
            at java.****/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
            at java.****/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
            at java.****/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
            at java.****/java.lang.String.checkBoundsBeginEnd(String.java:4865)
            at java.****/java.lang.String.substring(String.java:2834)
            at org.opensearch.repositories.blobstore.BlobStoreRepository.lambda$executeOneStaleIndexDelete$40(BlobStoreRepository.java:1658)
            ... 9 more
```
