### ISSUE TITLE
[BUG] Cluster setting 'cluster.remote_store.repository' renamed in 2.x branch without backwards compatibility

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#8902]
**Describe the bug**

The cluster setting `cluster.remote_store.repository` is renamed to `cluster.remote_store.segment.repository` in the commit
https://github.com/opensearch-project/OpenSearch/commit/91398c3830850ec9d48bd5dffef8d13c7b75e753#diff-a93623446c8ee94dffd709a37ec974ee8c27f0f9f31335f35e753ed802a8dc7b. The setting is needed to use remote store feature.

In released version 2.9.0:
https://github.com/opensearch-project/OpenSearch/blob/1164221ee2b8ba3560f0ff492309867beea28433/server/src/main/java/org/opensearch/indices/IndicesService.java#L262
(https://github.com/opensearch-project/OpenSearch/blob/2.9.0/server/src/main/java/org/opensearch/indices/IndicesService.java#L262)

In current 2.x branch, which is version 2.10.0:
https://github.com/opensearch-project/OpenSearch/blob/1eea7fd6a04b0bf80d2425d59ebeadf86e650bac/server/src/main/java/org/opensearch/indices/IndicesService.java#L262

It will cause error when using the old setting name to start version 2.10 cluster:
```
[2023-07-26T23:34:42,867][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [127.0.0.1] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [cluster.remote_store.repository] did you mean any of [cluster.remote_store.segment.repository, cluster.remote_store.translog.repository, cluster.remote_store.enabled]?
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.10.0.jar:2.10.0]
...
```

**To Reproduce**
Assign the old setting `cluster.remote_store.repository: xxx` into config/opensearch.yml, and start OpenSearch node version 2.10.0 that built from current 2.x branch.

**Expected behavior**

**Plugins**
n/a

**Screenshots**
n/a

**Host/Environment (please complete the following information):**

**Additional context**
I found this problem when using [opensearch cluster cdk](https://github.com/opensearch-project/opensearch-cluster-cdk) to deploy a cluster with "remote store" feature enabled. The script assigns the mentioned setting into nodes in this [line](https://github.com/opensearch-project/opensearch-cluster-cdk/commit/d1adf6d8bf09f7f1afb60c81cdcc08f3ab58de28#diff-d7c4924379311512de5d5b043d465129d2b5fb1254d7a08737f2e3f9b1c13f64R488).

Although using remote store feature with segment replication is an experimental feature, it causes confusion to both user and developers who use this feature in both version 2.9.0 and 2.10.0 .

**Comment by tlfeng** [comment]
Close the issue, because it's fair to having breaking change when the a feature is gated by feature flag.
