### ISSUE TITLE
[BUG] org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating is flaky

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/OpenSearch#8928]
**Describe the bug**
- org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating is flaky
- Sample run: https://build.ci.opensearch.org/job/gradle-check/21062/testReport/org.opensearch.indices.replication/SegmentReplicationTargetServiceTests/testShardAlreadyReplicating/
- Failed twice on #8506 

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating" -Dtests.seed=D8312943A799670E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-AE -Dtests.timezone=America/Manaus -Druntime.java=20
```

**Expected behavior**
- Test to pass

**Comment by dreamer-89** [comment]
Tried with given seed, but test passes locally. Running test in repeat mode until failure.

**Comment by dreamer-89** [comment]
No failure observed in 10k runs with given seed. 

<img width="745" alt="Screenshot 2023-07-27 at 10 26 27 AM" src="https://github.com/opensearch-project/OpenSearch/assets/79435743/53c4b797-6608-47c7-9436-e4ff4733a46d">

Next steps: Running test class on repeat

**Comment by dreamer-89** [comment]
Not much success with running tests at class level.
<img width="751" alt="Screenshot 2023-07-27 at 11 59 09 AM" src="https://github.com/opensearch-project/OpenSearch/assets/79435743/bde7d097-9291-4073-a8f4-aaa5400c8178">

**Comment by dreamer-89** [comment]
On doing a closer look on the test, it assumes the first round of segment replication is active for the test to pass. This assumption may not hold everytime and it is possible that first round of segment replication completes before control goes to start another round 

```
    public void testShardAlreadyReplicating() {
   1 -->     sut.startReplication(replicaShard, mock(SegmentReplicationTargetService.SegmentReplicationListener.class));
   2 -->    sut.startReplication(replicaShard, new SegmentReplicationTargetService.SegmentReplicationListener() {
            @Override
            public void onReplicationDone(SegmentReplicationState state) {
                Assert.fail("Should not succeed");
            }

            @Override
            public void onReplicationFailure(SegmentReplicationState state, ReplicationFailedException e, boolean sendShardFailure) {
                assertEquals("Shard " + replicaShard.shardId() + " is already replicating", e.getMessage());
                assertFalse(sendShardFailure);
            }
        });
    }
```

**Comment by dreamer-89** [comment]
This test is still failing, reopening

**Comment by dreamer-89** [comment]
This test fails while expecting call to [processLatestReceivedCheckpoint](https://github.com/opensearch-project/OpenSearch/blob/60d272bc2fe875d7edd1e65ac87ac31999505ee1/server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java#L297). 

From https://build.ci.opensearch.org/job/gradle-check/22784
```
Wanted but not invoked:
segmentReplicationTargetService.processLatestReceivedCheckpoint(
    org.opensearch.index.shard.IndexShard@35f0ec9a,
    <any>
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating(SegmentReplicationTargetServiceTests.java:295)

However, there were exactly 5 interactions with this mock:
segmentReplicationTargetService.startReplication(
    org.opensearch.indices.replication.SegmentReplicationTarget$MockitoMock$CY6zJxTo@54ccd0b4
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating(SegmentReplicationTargetServiceTests.java:291)

segmentReplicationTargetService.onNewCheckpoint(
    ReplicationCheckpoint{shardId=[index][0], primaryTerm=88, segmentsGen=3, version=8, size=0, codec=Lucene95},
    org.opensearch.index.shard.IndexShard@35f0ec9a
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating(SegmentReplicationTargetServiceTests.java:294)

segmentReplicationTargetService.updateLatestReceivedCheckpoint(
    ReplicationCheckpoint{shardId=[index][0], primaryTerm=88, segmentsGen=3, version=8, size=0, codec=Lucene95},
    org.opensearch.index.shard.IndexShard@35f0ec9a
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetService.onNewCheckpoint(SegmentReplicationTargetService.java:216)

segmentReplicationTargetService.startReplication(
    org.opensearch.index.shard.IndexShard@35f0ec9a,
    ReplicationCheckpoint{shardId=[index][0], primaryTerm=88, segmentsGen=3, version=8, size=0, codec=Lucene95},
    org.opensearch.indices.replication.SegmentReplicationTargetService$1@4c9dfcab
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetService.onNewCheckpoint(SegmentReplicationTargetService.java:245)

segmentReplicationTargetService.startReplication(
    org.opensearch.indices.replication.SegmentReplicationTarget@10dfa5d1
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetService.startReplication(SegmentReplicationTargetService.java:419)
```

**Comment by Rishikesh1159** [comment]
Not able to reproduce the test failure. Tried running entire test suite class but still not able to reproduce. This flaky test might be fixed from some changes happened in last 2 months. I will unmute the test for now with PR #10660 (as we are not able to repro) and I am adding trace logging with test, so next time if we see this test failing we can get more info from logs.

**Comment by reta** [comment]
```
Wanted but not invoked:
segmentReplicationTargetService.processLatestReceivedCheckpoint(
    org.opensearch.index.shard.IndexShard@4876cf44,
    <any>
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating(SegmentReplicationTargetServiceTests.java:316)

However, there were exactly 5 interactions with this mock:
segmentReplicationTargetService.startReplication(
    org.opensearch.indices.replication.SegmentReplicationTarget$MockitoMock$8gnjoQCG@b2e2a95
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating(SegmentReplicationTargetServiceTests.java:312)

segmentReplicationTargetService.onNewCheckpoint(
    ReplicationCheckpoint{shardId=[index][0], primaryTerm=95, segmentsGen=3, version=8, size=0, codec=Lucene99},
    org.opensearch.index.shard.IndexShard@4876cf44
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating(SegmentReplicationTargetServiceTests.java:315)

segmentReplicationTargetService.updateLatestReceivedCheckpoint(
    ReplicationCheckpoint{shardId=[index][0], primaryTerm=95, segmentsGen=3, version=8, size=0, codec=Lucene99},
    org.opensearch.index.shard.IndexShard@4876cf44
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetService.onNewCheckpoint(SegmentReplicationTargetService.java:273)

segmentReplicationTargetService.startReplication(
    org.opensearch.index.shard.IndexShard@4876cf44,
    ReplicationCheckpoint{shardId=[index][0], primaryTerm=95, segmentsGen=3, version=8, size=0, codec=Lucene99},
    org.opensearch.indices.replication.SegmentReplicationTargetService$1@aa0c9f5
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetService.onNewCheckpoint(SegmentReplicationTargetService.java:302)

segmentReplicationTargetService.startReplication(
    org.opensearch.indices.replication.SegmentReplicationTarget@3fec1515
);
-> at org.opensearch.indices.replication.SegmentReplicationTargetService.startReplication(SegmentReplicationTargetService.java:498)
```

**Comment by getsaurabh02** [comment]
@dreamer-89 Are we still actively looking into this one?
