### ISSUE TITLE
[BUG] org.opensearch.index.engine.InternalEngineTests.testLastRefreshCheckpoint is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#9029]
**Describe the bug**

The org.opensearch.index.engine.InternalEngineTests.testLastRefreshCheckpoint is flaky:

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=649, name=Thread-197, state=RUNNABLE, group=TGRP-InternalEngineTests]
	at __randomizedtesting.SeedInfo.seed([B448FCE4648CA4EB:7A3CB282E14976E1]:0)
Caused by: java.lang.AssertionError: 
Expected: a value equal to or greater than <0L>
     but: <-1L> was less than <0L>
	at __randomizedtesting.SeedInfo.seed([B448FCE4648CA4EB]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.index.engine.InternalEngineTests.lambda$testLastRefreshCheckpoint$84(InternalEngineTests.java:6643)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

See please: https://build.ci.opensearch.org/job/gradle-check/21580/testReport/junit/org.opensearch.index.engine/InternalEngineTests/testLastRefreshCheckpoint/

**To Reproduce**
```
./gradlew ':server:test' --tests "org.opensearch.index.engine.InternalEngineTests.testLastRefreshCheckpoint" -Dtests.seed=B448FCE4648CA4EB
```

**Expected behavior**
Test must always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
The flaky assertion was introduced in https://github.com/opensearch-project/OpenSearch/pull/7653

CC @ankitkala

**Comment by ankitkala** [comment]
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=649, name=Thread-197, state=RUNNABLE, group=TGRP-InternalEngineTests]
	at __randomizedtesting.SeedInfo.seed([B448FCE4648CA4EB:7A3CB282E14976E1]:0)
Caused by: java.lang.AssertionError: 
Expected: a value equal to or greater than <0L>
     but: <-1L> was less than <0L>
	at __randomizedtesting.SeedInfo.seed([B448FCE4648CA4EB]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.index.engine.InternalEngineTests.lambda$testLastRefreshCheckpoint$84(InternalEngineTests.java:6643)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by ankitkala** [comment]
The initialising value for `lastRefreshedCheckpoint` might be `-1` in some cases.  I'm trying to repro this locally but haven't got any failure even after 8K test iterations. 

`lastRefreshedCheckpoint`/`LastRefreshedCheckpointListener.refreshedCheckpoint` gets initialised from `localCheckpointTracker.getProcessedCheckpoint`  which should never be null ideally ([code link](https://github.com/opensearch-project/OpenSearch/blob/164fbb168316622831f71d82174790d2d10ec0cd/server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java#L92)). 

Any update to `LastRefreshedCheckpointListener.refreshedCheckpoint` will also be monotonically increasing ([code link](https://github.com/opensearch-project/OpenSearch/blob/639d28ad46927f8fbb6c940bc7efd4e935528526/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L2811))

**Comment by ankitkala** [comment]
I was not able to reproduce this even after 50K tests iterations.

`pendingCheckpoint` and `refreshedCheckpoint` are initialized with same value. `pendingCheckpoint` keeps track of the the processedCheckpoint for the ongoing refresh and updates the `refreshedCheckpoint` with the value after refresh. Only reason this error above (`pendingCheckpoint=-1 && refreshedCheckpoint=0`) can happen is if the `pendingCheckpoint` was set to `-1` during refresh whereas `refreshedCheckpoint` was initialized with `0`
