### ISSUE TITLE
[BUG] 2.x cluster crash in `IOUtils`

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/OpenSearch#9056]
**Describe the bug**
Cluster crashes on random place during SQL plugin IT on 2.x branch.
https://github.com/opensearch-project/OpenSearch/blob/e660d568de20aa54ef39f0431b496e9368835498/libs/common/src/main/java/org/opensearch/common/util/io/IOUtils.java#L239-L240
Nice place to crash isn't it?

<details>
<summary>Exception stack</summary>

```
[ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [integTest-0] fatal error in thread [opensearch[integTest-0][clusterApplierService#updateTask][T#1]], exiting
java.lang.AssertionError: null
	at org.opensearch.common.util.io.IOUtils$1.postVisitDirectory(IOUtils.java:240) ~[opensearch-common-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.common.util.io.IOUtils$1.postVisitDirectory(IOUtils.java:232) ~[opensearch-common-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at java.nio.file.Files.walkFileTree(Files.java:2743) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2797) ~[?:?]
	at org.opensearch.common.util.io.IOUtils.rm(IOUtils.java:232) ~[opensearch-common-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.common.util.io.IOUtils.rm(IOUtils.java:216) ~[opensearch-common-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.env.NodeEnvironment.deleteShardDirectoryUnderLock(NodeEnvironment.java:580) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.indices.IndicesService.deleteShardStore(IndicesService.java:1147) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.IndexService.onShardClose(IndexService.java:659) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.IndexService$StoreCloseListener.accept(IndexService.java:782) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.IndexService$StoreCloseListener.accept(IndexService.java:769) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.store.Store.closeInternal(Store.java:556) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.store.Store$1.closeInternal(Store.java:194) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:78) ~[opensearch-common-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.store.Store.decRef(Store.java:529) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.store.Store.close(Store.java:536) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.IndexService.closeShard(IndexService.java:635) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.IndexService.removeShard(IndexService.java:599) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.index.IndexService.close(IndexService.java:374) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.indices.IndicesService.removeIndex(IndicesService.java:983) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:355) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:285) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:606) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:593) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:561) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:484) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:186) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245) ~[opensearch-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
</details>

**To Reproduce**
1. Check out [`dbg-cluster-crash`](https://github.com/Bit-Quill/opensearch-project-sql/tree/dbg-cluster-crash)
2. Run IT: `./gradlew :integ-test:integTest`
3. ...
4. PROFIT

**Expected behavior**
IT complete and probably pass.

**Plugins**
SQL

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
`2.x`
OpenSearch distro based on 6e470954

**Additional context**
Full log : [here](https://github.com/opensearch-project/OpenSearch/files/12235109/cluster_crash_pewpew.txt)

**Comment by nknize** [comment]
This looks like a red herring as the crash doesn't have anything to do with commit 6e47095. That commit just removes the deprecated leniency for fractional BytesSizeValue. 


This looks like something triggered an index deletion and during cleanup the Shard files on disk don't exist.

What's odd to me are all of the other errors in this log, there's a real suspicious one a ways before the IT cluster implosion where memory cannot be allocated to write files. 

```
java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /mnt/c/GitHub/opensearch-project-sql-dbg/integ-test/build/testclusters/integTest-0/data/nodes/0/indices/gvpq7N5TTrq5UIsPkQ0umQ/_state: Cannot allocate memory
	at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:169) ~[?:?]
	at 
```

Perhaps direct memory was exhausted and file cache couldn't be allocated?


There are many other client side errors before even getting to that error like:

```
Client side error during query execution
org.opensearch.sql.exception.SemanticCheckException: can't resolve Symbol(namespace=FIELD_NAME, name=invalid) in type env
```

Even several odd aggregation errors like:

```
Error happened in pretty formatter
org.opensearch.sql.legacy.exception.SqlFeatureNotImplementedException: Aggregation type nested is not yet implemented
```

Is that common in the SQL plugin logs?

I haven't tried to repro yet. I'll do that tomorrow and see what I find. Having never looked at the SQL plugin it would be helpful to have some context as to what errors are normal that can be "ignored".

cc: @mch2 have y'all seen errors like this in segrep IT testing where shard removal are trying to delete files that don't exist?

**Comment by reta** [comment]
Very strange, it seems like we have a failure coming from the  native call. The bootstrap check complains about low vm space, but not sure this is an issue either.

```
[2023-08-01T18:05:57,305][WARN ][o.o.b.BootstrapChecks    ] [integTest-0] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

> Also cc: @reta in case you get around to this earlier. I noticed some netty failures which makes me think this could be direct memory related. Or maybe that's a red herring too?

I saw some failures in processing pipeline (netty transport) but those are non issue I think, or you have seen some netty allocation issues?

**Comment by Yury-Fridlyand** [comment]
> Is that common in the SQL plugin logs?

Yes, these error are benign, they are part of the tests.

I can't reproduce either today - all snapshots were updated and IT uses another versions.
