### ISSUE TITLE
[BUG] Test failure in "SimpleNetty4TransportTests.testHandshakeUpdatesVersion"

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#912]
**Describe the bug**
Comes from https://github.com/opensearch-project/OpenSearch/pull/902

The test passes at most time, but fails with the specific seed. Failure is only reproducible  in the current `main` branch, and not in `1.x` or `1.0` branch.
```
  2> REPRODUCE WITH: ./gradlew ':modules:transport-netty4:test' --tests "org.opensearch.transport.netty4.SimpleNetty4TransportTests.testHandshakeUpdatesVersion" -Dtests.seed=59DADD0DFC828D39 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=en-AU -Dtests.timezone=Etc/GMT-14 -Druntime.java=15
  2> java.lang.AssertionError: expected:<7.10.2> but was:<1.1.0>
        at __randomizedtesting.SeedInfo.seed([59DADD0DFC828D39:E8996B23DD77BEC4]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.opensearch.transport.AbstractSimpleTransportTestCase.testHandshakeUpdatesVersion(AbstractSimpleTransportTestCase.java:2016)
...
```
```
Tests with failures:
 - org.opensearch.transport.netty4.SimpleNetty4TransportTests.testHandshakeUpdatesVersion
```

Another assertion error with a different seed (appeared in PR https://github.com/opensearch-project/OpenSearch/pull/913):
```
> Task :modules:transport-netty4:test

REPRODUCE WITH: ./gradlew ':modules:transport-netty4:test' --tests "org.opensearch.transport.netty4.SimpleNetty4TransportTests.testHandshakeUpdatesVersion" -Dtests.seed=425B0821A98A1BA3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=es-VE -Dtests.timezone=Asia/Yangon -Druntime.java=15

org.opensearch.transport.netty4.SimpleNetty4TransportTests > testHandshakeUpdatesVersion FAILED
    java.lang.AssertionError: expected:<7.10.2> but was:<1.0.0>
        at __randomizedtesting.SeedInfo.seed([425B0821A98A1BA3:F318BE0F887F285E]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.opensearch.transport.AbstractSimpleTransportTestCase.testHandshakeUpdatesVersion(AbstractSimpleTransportTestCase.java:2016)
...
```

**To Reproduce**
1. Clone OpenSearch repository, and checkout `main` branch.
2. Run the command in the root directory:
```
./gradlew ':modules:transport-netty4:test' --tests "org.opensearch.transport.netty4.SimpleNetty4TransportTests.testHandshakeUpdatesVersion" -Dtests.seed=59DADD0DFC828D39
```
or
```
./gradlew ':modules:transport-netty4:test' --tests "org.opensearch.transport.netty4.SimpleNetty4TransportTests.testHandshakeUpdatesVersion" -Dtests.seed=425B0821A98A1BA3
```
3. See the error.

**Expected behavior**
Test passes.

**Plugins**
No plugins installed.

**Screenshots**
(none)

**Host/Environment (please complete the following information):**
 - OS: macOS and Ubuntu

**Additional context**
(none)

**Comment by mch2** [comment]
Getting the same error here with a different seed - -Dtests.seed=5A0D96AFB55B443E

**Comment by nknize** [comment]
Fixed by: https://github.com/opensearch-project/OpenSearch/pull/928
