### ISSUE TITLE
[BUG] 2.9.0 snapshot remote_storage fails from functioning S3 repository with exception

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/OpenSearch#9125]
**Describe the bug**
I'm trying to use the searchable snapshots feature, but restoring the snapshot fails. Picture > 1000 words, so I made a video:

https://download.ict-one.nl/searchable_snapshots.mp4

Exception:

`opensearch-search-nodes [2023-08-04T20:05:32,890][WARN ][o.o.i.c.IndicesClusterStateService] [opensearch-search-nodes-0] [alert-suricata-alert-2023.03.27][0] marking and sending shard failed due to [failed recovery]                      ││ opensearch-search-nodes org.opensearch.indices.recovery.RecoveryFailedException: [alert-suricata-alert-2023.03.27][0]: Recovery failed on {opensearch-search-nodes-0}{O_PqK9fAS1W5_u1y6C3mdw}{H41SDUAxRVG1b5ydGM-jHA}{10.244.20.218}{10.244. ││ opensearch-search-nodes     at org.opensearch.index.shard.IndexShard.lambda$executeRecovery$30(IndexShard.java:3554) [opensearch-2.9.0.jar:2.9.0]                                                                                            ││ opensearch-search-nodes     at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88) [opensearch-2.9.0.jar:2.9.0]                                                                                                         ││ opensearch-search-nodes     at org.opensearch.index.shard.StoreRecovery.lambda$recoveryListener$8(StoreRecovery.java:510) [opensearch-2.9.0.jar:2.9.0]                                                                                       ││ opensearch-search-nodes     at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88) [opensearch-2.9.0.jar:2.9.0]                                                                                                         ││ opensearch-search-nodes     at org.opensearch.action.ActionListener.completeWith(ActionListener.java:345) [opensearch-2.9.0.jar:2.9.0]                                                                                                       ││ opensearch-search-nodes     at org.opensearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:113) [opensearch-2.9.0.jar:2.9.0]                                                                                                ││ opensearch-search-nodes     at org.opensearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2620) [opensearch-2.9.0.jar:2.9.0]                                                                                                     ││ opensearch-search-nodes     at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) [opensearch-2.9.0.jar:2.9.0]                                                                                                             ││ opensearch-search-nodes     at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.9.0.jar:2.9.0]                                                              ││ opensearch-search-nodes     at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.9.0.jar:2.9.0]                                                                                             ││ opensearch-search-nodes     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]                                                                                                                         ││ opensearch-search-nodes     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]                                                                                                                         ││ opensearch-search-nodes     at java.lang.Thread.run(Thread.java:833) [?:?]                                                                                                                                                                   ││ opensearch-search-nodes Caused by: org.opensearch.index.shard.IndexShardRecoveryException: failed recovery                                                                                                                                   ││ opensearch-search-nodes     ... 11 more                                                                                                                                                                                                      ││ opensearch-search-nodes Caused by: java.lang.ArithmeticException: long overflow                                                                                                                                                              ││ opensearch-search-nodes     at java.lang.Math.addExact(Math.java:903) ~[?:?]                                                                                                                                                                 ││ opensearch-search-nodes     at org.opensearch.repositories.s3.S3RetryingInputStream.openStream(S3RetryingInputStream.java:121) ~[?:?]                                                                                                        ││ opensearch-search-nodes     at org.opensearch.repositories.s3.S3RetryingInputStream.<init>(S3RetryingInputStream.java:100) ~[?:?]                                                                                                            ││ opensearch-search-nodes     at org.opensearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:143) ~[?:?]                                                                                                                      ││ opensearch-search-nodes     at org.opensearch.index.store.remote.utils.TransferManager.lambda$createIndexInput$1(TransferManager.java:87) ~[opensearch-2.9.0.jar:2.9.0]                                                                      ││ opensearch-search-nodes     at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]                                                                                                                                 ││ opensearch-search-nodes     at org.opensearch.index.store.remote.utils.TransferManager.createIndexInput(TransferManager.java:83) ~[opensearch-2.9.0.jar:2.9.0]                                                                               ││ opensearch-search-nodes     at org.opensearch.index.store.remote.utils.TransferManager$DelayedCreationCachedIndexInput.getIndexInput(TransferManager.java:135) ~[opensearch-2.9.0.jar:2.9.0]                                                 ││ opensearch-search-nodes     at org.opensearch.index.store.remote.utils.TransferManager.fetchBlob(TransferManager.java:72) ~[opensearch-2.9.0.jar:2.9.0]                                                                                      ││ opensearch-search-nodes     at org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.fetchBlock(OnDemandBlockSnapshotIndexInput.java:147) ~[opensearch-2.9.0.jar:2.9.0]                                                     ││ opensearch-search-nodes     at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.demandBlock(OnDemandBlockIndexInput.java:340) ~[opensearch-2.9.0.jar:2.9.0]                                                                    ││ opensearch-search-nodes     at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.seekInternal(OnDemandBlockIndexInput.java:311) ~[opensearch-2.9.0.jar:2.9.0]                                                                   ││ opensearch-search-nodes     at org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.seek(OnDemandBlockIndexInput.java:209) ~[opensearch-2.9.0.jar:2.9.0]                                                                           ││ opensearch-search-nodes     at org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.seek(OnDemandBlockSnapshotIndexInput.java:28) ~[opensearch-2.9.0.jar:2.9.0]                                                            ││ opensearch-search-nodes     at org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:533) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                                         ││ opensearch-search-nodes     at org.apache.lucene.codecs.lucene90.Lucene90CompoundReader.<init>(Lucene90CompoundReader.java:87) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                 ││ opensearch-search-nodes     at org.apache.lucene.codecs.lucene90.Lucene90CompoundFormat.getCompoundReader(Lucene90CompoundFormat.java:86) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]      ││ opensearch-search-nodes     at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:103) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                                  ││ opensearch-search-nodes     at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:92) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                                             ││ opensearch-search-nodes     at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:94) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                       ││ opensearch-search-nodes     at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:77) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                       ││ opensearch-search-nodes     at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:774) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                                ││ opensearch-search-nodes     at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:109) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                          ││ opensearch-search-nodes     at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:146) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]                                          ││ opensearch-search-nodes     at org.opensearch.index.engine.ReadOnlyEngine.open(ReadOnlyEngine.java:235) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                        ││ opensearch-search-nodes     at org.opensearch.index.engine.ReadOnlyEngine.<init>(ReadOnlyEngine.java:147) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                      ││ opensearch-search-nodes     at org.opensearch.indices.IndicesService.lambda$getEngineFactory$10(IndicesService.java:854) ~[opensearch-2.9.0.jar:2.9.0]                                                                                       ││ opensearch-search-nodes     at org.opensearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2340) ~[opensearch-2.9.0.jar:2.9.0]                                                                                          ││ opensearch-search-nodes     at org.opensearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2302) ~[opensearch-2.9.0.jar:2.9.0]                                                                                          ││ opensearch-search-nodes     at org.opensearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2272) ~[opensearch-2.9.0.jar:2.9.0]                                                                                    ││ opensearch-search-nodes     at org.opensearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:630) ~[opensearch-2.9.0.jar:2.9.0]                                                                                       ││ opensearch-search-nodes     at org.opensearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:115) ~[opensearch-2.9.0.jar:2.9.0]                                                                                      ││ opensearch-search-nodes     at org.opensearch.action.ActionListener.completeWith(ActionListener.java:342) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                      ││ opensearch-search-nodes     ... 8 more`

**To Reproduce**
See vid

**Expected behavior**
Snapshot restored and available for searching

**Plugins**
s3 repository plugin

**Screenshots**

**Host/Environment (please complete the following information):**
Default Opensearch 2.9.0 docker image with S3 plugin enabled.
S3 storage is a Scality appliance, but since the normal restore works I don't suspect that's the issue?

**Additional context**

**Comment by andrross** [comment]
Hi @ict-one-nl, I'm blocked from downloading that video with this error:

> Why have I been blocked?
> 
> This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

Taking a wild guess since I can't see the error, but the [parameter value you need to pass to the restore API](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/) is `remote_snapshot` not `remote_storage`.

**Comment by ict-one-nl** [comment]
Hi, I'm using cloudflare, blocking traffic from outside the EU; but that's not viable, so I removed the WAF-rule. Your comment is valid, but I made a typo in the report (but not in the API-calls) :)

**Comment by ict-one-nl** [comment]
Side-effect: index was marked as red, which triggered cluster state as red, which stopped data-ingest entirely. Removed the searchable snapshot just now: cluster green and everything is okay again.

**Comment by ict-one-nl** [comment]
Okay, got one step further, at node boot:
```
2023-08-07T14:29:35,537][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch-search-nodes-1] uncaught exception in thread [main]                                                                                │
│ opensearch-search-nodes org.opensearch.bootstrap.StartupException: SettingsException[Unable to initialize the search-data node: Missing value for configuration node.search.cache.size]                                                           │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                        │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                     │
│ opensearch-search-nodes     at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                 │
│ opensearch-search-nodes     at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.9.0.jar:2.9.0]                                                                                                            │
│ opensearch-search-nodes     at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.9.0.jar:2.9.0]                                                                                                                                │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                        │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                        │
│ opensearch-search-nodes Caused by: org.opensearch.common.settings.SettingsException: Unable to initialize the search-data node: Missing value for configuration node.search.cache.size                                                            │
│ opensearch-search-nodes     at org.opensearch.node.Node.initializeFileCache(Node.java:1745) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                         │
│ opensearch-search-nodes     at org.opensearch.node.Node.<init>(Node.java:632) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                                       │
│ opensearch-search-nodes     at org.opensearch.node.Node.<init>(Node.java:389) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                                       │
│ opensearch-search-nodes     at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                      │
│ opensearch-search-nodes     at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                         │
│ opensearch-search-nodes     at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                          │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.9.0.jar:2.9.0]                                                                                                                        │
│ opensearch-search-nodes     ... 6 more                                                                                                                                                                                                            │
│ opensearch-search-nodes SettingsException[Unable to initialize the search-data node: Missing value for configuration node.search.cache.size]                                                                                                      │
│ opensearch-search-nodes     at org.opensearch.node.Node.initializeFileCache(Node.java:1745)                                                                                                                                                       │
│ opensearch-search-nodes     at org.opensearch.node.Node.<init>(Node.java:632)                                                                                                                                                                     │
│ opensearch-search-nodes     at org.opensearch.node.Node.<init>(Node.java:389)                                                                                                                                                                     │
│ opensearch-search-nodes     at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)                                                                                                                                                    │
│ opensearch-search-nodes     at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)                                                                                                                                                       │
│ opensearch-search-nodes     at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)                                                                                                                                                        │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)                                                                                                                                                      │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)                                                                                                                                                   │
│ Stream closed EOF for mdtitss-siem/opensearch-search-nodes-1 (create-volume-keystore)                                                                                                                                                             │
│ opensearch-search-nodes     at org.opensearch.cli.Command.main(Command.java:101)                                                                                                                                                                  │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)                                                                                                                                                      │
│ opensearch-search-nodes     at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)                                                                                                                                                      │
│ opensearch-search-nodes For complete error details, refer to the log at /usr/share/opensearch/logs/siem.log
```

I find this a bit cumbersome:

1. This setting is not mentioned in the docs. Unclear to me if we're talking memory or storage and what the units should be.
2. The call to restore is ack'ed, but fails immediately. Feedback would be welcome in some form
4. The exception that follows in the logs the restore is very vague (not being able to parse a long)
5. Maybe a sensible default value should be set and docs provided to guide the user when to deviate
6. The restore that fails throws the cluster to red state which stops all functionality. This seems a bit harsh.

Yet, still:

![image](https://github.com/opensearch-project/OpenSearch/assets/2643715/388d445a-afc4-49bc-81f2-f7ba885d4a41)

**Comment by andrross** [comment]
@ict-one-nl Thank you. Definitely a bug here. The long overflow is coming from [this line](https://github.com/opensearch-project/OpenSearch/blob/2.9/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java#L121). Given that file sizes approaching `Long.MAX_VALUE` are implausibly large, I suspect we're encountering an exception and hitting [this fallback path](https://github.com/opensearch-project/OpenSearch/blob/2.9/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java#L156). It is unfortunate there is no debug logging there. Any chance you can enable assertions in your JVM (by passing `-ea` as a command line parameter when launching the Java process) on the off chance it will hit one of those assert statements and we can get some more info here?

Alternatively or in addition to, is there any chance you could test this with OpenSearch 2.8? There were some changes in this code related to the upgrade to AWS SDK v2 that _could_ be related, but those were just done in version 2.9.

**Comment by ict-one-nl** [comment]
Thanks, sure I'll try to provide some more details. Give me a day or so.

What do you think about the cache size setting? Should that be a separate issue?

**Comment by ict-one-nl** [comment]
Behavior on 2.8.0 is definitely different from 2.9.0. I'm able to restore the snapshot:

![image](https://github.com/opensearch-project/OpenSearch/assets/2643715/69b10829-dd0f-4ff2-a1f8-fa87a130f0c7)

<img width="1332" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/2643715/c5ce4de4-4df5-4f59-a3be-00ea130d2dd2">

And it searches:

![image](https://github.com/opensearch-project/OpenSearch/assets/2643715/8e7a1bc4-e758-4ace-981f-cf1ecb619a1b)

But index state is yellow and thus the cluster state is yellow as well.

**Comment by ict-one-nl** [comment]
okay, I do have a debug trace of trying to restore a remote snapshot on 2.9.0. Strangely it did seem to work once on the cluster I upgraded from 2.8.0 to 2.9.0 restoring a remote snapshot from 2.8.0 in a 2.9.0 cluster. Have to look if I can reproduce it, but the amount of logging and the performance impact makes that difficult.

Unfortunately the logs are quite big, we're talking several hundred megabytes in a matter of minutes when I put the whole node logging to debug.  It also makes the cluster almost unresponsive.

```
status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n

rootLogger.level = error
rootLogger.appenderRef.console.ref = console
```

I'm hesitant to share the logs publicly, don't want to expose infrastructure details on a public forum. I would be open to share it privately with the dev team. Or I might be able to share more openly if it's not this much and I'm able to shrink the logs down.

**Comment by andrross** [comment]
@ict-one-nl Thanks for working through this! Are you still able to reproduce the error? If so, I'd like to see the results of enabling assertions. My suspicion is that it is reaching [this line](https://github.com/opensearch-project/OpenSearch/blob/b15ffc9caaec0303b91ecaff1ab39bb9e860ba48/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java#L154) and there actually isn't any debug logging statements there. However, if you enable assertions, then the JVM will crash when that assertion is hit and should print the details to the stdout or stderr.

Regarding the cache size and replica behavior, you are absolutely right that we need better documentation. To quickly answer your questions:
- The "cache" in question here is the portion of the disk reserved for data retrieved from remote storage in order to serve search requests. Searches that access the same data will not need to fetch remote data again if it is already local in the cache. The cache is a fixed size and will evict least recently used data once it becomes full. If you have a node dedicated to the `search` role, then a default cache size will be chosen. Otherwise, you need to define a portion of the disk to use for this cache that will be unavailable for use by normal "local" indexes.
- Searchable snapshots can have replica shards like normal indexes and you must have enough `search` nodes to allocate them as you have discovered. However, for many cases a replica may not be necessary and this setting can be changed at restore time.

**Comment by ict-one-nl** [comment]
I'm consistently getting the error when using 2.9.0 for snapshot + restore. It's working consistently on 2.8.0. Strange enough a snapshot on 2.8.0 restored correctly as remote_snapshot on 2.9.0. While typing this comment and trying to enable assertions we are suffering a production problem on our kubernetes cluster, I'll come back to that later.

I'm hoping that we can solve this before the 2.10 release, otherwise I'll be stuck with this error for at least two more months :) The explanation you've given in this comment would be very useful in the docs, even if it's just a copy/paste from this ticket :) This info is missing from the docs at this time.

**Comment by ict-one-nl** [comment]
Okay another round of testing, another result...

Situation:

1. Snapshot repo that was initiatalised before, but without snapshots in it
2. Dropped all storage from cluster
3. Spun up a fresh cluster
4. Pushed security settings with admintool
5. Connected snapshot repo
6. Created a testindex with one record
7. Created one snapshot of the testindex
8. Dropped testindex

```
POST _snapshot/s3-archive/testindex/_restore
{
  "indices": "testindex",
  "storage_type" : "remote_snapshot"
}
```

Cluster state yellow, index state yellow (different from before, then it was red).

```
GET _cluster/allocation/explain?pretty
{
}
```

```
{
  "index": "testindex",
  "shard": 0,
  "primary": false,
  "current_state": "unassigned",
  "unassigned_info": {
    "reason": "NEW_INDEX_RESTORED",
    "at": "2023-08-09T17:47:23.947Z",
    "details": "restore_source[s3-archive/testindex]",
    "last_allocation_status": "no_attempt"
  },
  "can_allocate": "no",
  "allocate_explanation": "cannot allocate because allocation is not permitted to any of the nodes",
  "node_allocation_decisions": [
    {
      "node_id": "16KaBF9FSx6CV9YqqcqRew",
      "node_name": "opensearch-search-nodes-1",
      "transport_address": "10.244.20.234:9300",
      "node_attributes": {
        "shard_indexing_pressure_enabled": "true"
      },
      "node_decision": "no",
      "deciders": [
        {
          "decider": "replica_after_primary_active",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "same_shard",
          "decision": "NO",
          "explanation": "a copy of this shard is already allocated to this node [[testindex][0], node[16KaBF9FSx6CV9YqqcqRew], [P], recovery_source[snapshot recovery [PGVR1bqrTOe683wkzxCPjQ] from s3-archive:testindex/JJq6xAsKQvGTm_q8u3H9Rg], s[INITIALIZING], a[id=DEE-ADOzTpahNJuqqP-Gug], unassigned_info[[reason=NEW_INDEX_RESTORED], at[2023-08-09T17:47:23.947Z], delayed=false, details[restore_source[s3-archive/testindex]], allocation_status[fetching_shard_data]]]"
        },
        {
          "decider": "throttling",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        }
      ]
    },
    {
      "node_id": "1bTLmPKITraN6XfFZNznPA",
      "node_name": "opensearch-search-nodes-0",
      "transport_address": "10.244.39.13:9300",
      "node_attributes": {
        "shard_indexing_pressure_enabled": "true"
      },
      "node_decision": "no",
      "deciders": [
        {
          "decider": "replica_after_primary_active",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "throttling",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        }
      ]
    },
    {
      "node_id": "FggOXN-BRuKZatmU4kI-sw",
      "node_name": "opensearch-data-nodes-hot-1",
      "transport_address": "10.244.17.100:9300",
      "node_attributes": {
        "temp": "hot",
        "shard_indexing_pressure_enabled": "true"
      },
      "node_decision": "no",
      "deciders": [
        {
          "decider": "replica_after_primary_active",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "throttling",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "target_pool",
          "decision": "NO",
          "explanation": "Routing pools are incompatible. Shard pool: [REMOTE_CAPABLE], Node Pool: [LOCAL_ONLY]"
        }
      ]
    },
    {
      "node_id": "e7pkrWmwRdCs21GnDupJxA",
      "node_name": "opensearch-data-nodes-hot-2",
      "transport_address": "10.244.45.149:9300",
      "node_attributes": {
        "temp": "hot",
        "shard_indexing_pressure_enabled": "true"
      },
      "node_decision": "no",
      "deciders": [
        {
          "decider": "replica_after_primary_active",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "throttling",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "target_pool",
          "decision": "NO",
          "explanation": "Routing pools are incompatible. Shard pool: [REMOTE_CAPABLE], Node Pool: [LOCAL_ONLY]"
        }
      ]
    },
    {
      "node_id": "hgEZ0haURGiRajhrWawHFw",
      "node_name": "opensearch-data-nodes-hot-0",
      "transport_address": "10.244.46.163:9300",
      "node_attributes": {
        "temp": "hot",
        "shard_indexing_pressure_enabled": "true"
      },
      "node_decision": "no",
      "deciders": [
        {
          "decider": "replica_after_primary_active",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "throttling",
          "decision": "NO",
          "explanation": "primary shard for this replica is not yet active"
        },
        {
          "decider": "target_pool",
          "decision": "NO",
          "explanation": "Routing pools are incompatible. Shard pool: [REMOTE_CAPABLE], Node Pool: [LOCAL_ONLY]"
        }
      ]
    }
  ]
}
```

Will ask the storage guys to drop everything from the S3 container tomorrow to get a total fresh environment to test further.

**Comment by ict-one-nl** [comment]
Okay, I need further time to get consistent scenario's. I do know 2.8.0 works like a charm, but I can't pinpoint the problem. At this time we're not sure if it's:

1. The Scality appliance (professional grade stuff and I can't find problem reports about SDK V2 vs Scality, but still)
2. The Amazon S3 V2 SDK
3. The Opensearch implementation

Unless I'm mistaken there is no functional/technical need to implement the new SDK, it's more a matter of technical debt. Would it be an idea to:

1. Revert the change for 2.10.0 and rely on the old code a bit longer
2. Shelve the changes or merge it into the 3.0 branch

This would buy us some time and prevents a potentially confusing point release for users (Do I need to upgrade, why is there a point release, is there a security issue?). If there is a interoperability problem between the Scality and the new SDK, it's likely more people will report it to the SDK devs so fixes can be made.

In the meantime I'm more than willing to test further and help debugging. I could look into exposing our Scality to the Opensearch devs (but I need to talk to our storage team for that, security policies and such). That would make debugging the issue much easier I suppose.

**Comment by dblock** [comment]
The SDK was upgraded as a prerequisite for performance improvements in repository-s3, using features only available in the newer version. Reverting the change will be a lot of work, so let's only do it if we're 100% confident we can't fix a problem while moving forward? I suggest we debug the problem first. Btw, there's another bug report that's potentially a side effect of the upgrade, https://github.com/opensearch-project/OpenSearch/issues/9265. 

@raghuvanshraj any ideas?

**Comment by ict-one-nl** [comment]
Ah didn't know that, thank you. What can I do to help? Are there new requirements for the S3 endpoint? Can I do some low level testing with a command line client based on the new SDK to rule out opensearch itself and pinpoint the problem?

**Comment by dblock** [comment]
I think @andrross correctly called out where we have a problem (https://github.com/opensearch-project/OpenSearch/issues/9125#issuecomment-1668829058), but the only helpful thing to do would be to continue to narrow this down to the smallest repro possible. 

Otherwise since you can reproduce fairly consistently, are you able to build the source? I would check-out the 2.9 branch and add more debug logging around that error to find out what caused it.

**Comment by andrross** [comment]
@ict-one-nl @dblock The primary suspect is [this code that parses an HTTP header](https://github.com/opensearch-project/OpenSearch/blob/2.9/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/utils/HttpRangeUtils.java#L21). Is it possible that the Scality appliance intercepts and changes headers returned from S3? If you're able to reproduce the error with assertions enabled, then we should be able to confirm this theory as [this assertion](https://github.com/opensearch-project/OpenSearch/blob/2.9/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java#L155) should trip and print the exception to stderr.

**Comment by ict-one-nl** [comment]
Will try, I tried running the docker image with the -ea option in the jvm.options but I didn't hit it. But I'm not sure the -ea flag has been picked up properly. Running opensearch on my mac is somewhat troublesome, so I need to revive my Windows laptop. WIll try to look into it asap.

**Comment by ict-one-nl** [comment]
With the help of Andrew talking me through it, giving me some pointers and the help of our storage team I think I finally nailed down the problem... Hard one to diagnose as the exceptions opensearch threw didn't set me on the right path.

The culprit seems to be this setting on the endpoint:
--object-lock-enabled-for-bucket | --no-object-lock-enabled-for-bucket (boolean)

We had an inconsistancy between different buckets, this was the one difference we found. Enabled it and now it's working on the cluster that was consistently malfunctioning. Many thanks to our storage team and Andrew for both their patience ghehe.

I suppose the docs could be improved that this is required for the snapshots to function. Exception handling could be improved so it doesn't throw these odd exceptions. What do you think?

**Comment by Bukhtawar** [comment]
@andrross, @bbarani  do we know the blockers or overhead in doing patch release.

**Comment by ict-one-nl** [comment]
Good news is I've been able to confirm the fix :)
