### ISSUE TITLE
[BUG][Remote Store] Tests on IndicesRequestIT are failing with Remote Store Enabled

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#9158]
**Describe the bug**
Tests on IndicesRequestIT are failing with `timed out waiting for green state` when remote store is enabled.

```
java.lang.AssertionError: timed out waiting for green state
	at __randomizedtesting.SeedInfo.seed([20D6EC8B922F952F:26302B03469C0F11]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1030)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:961)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:950)
	at org.opensearch.action.IndicesRequestIT.setup(IndicesRequestIT.java:189)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
`REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.action.IndicesRequestIT.testGetFieldMappings" -Dtests.seed=20D6EC8B922F952F -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=Pacific/Kosrae -Druntime.java=20`

**Expected behavior**
All tests should pass with remote store enabled.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by sachinpkale** [comment]
Taking a look

**Comment by sachinpkale** [comment]
Created PR: https://github.com/opensearch-project/OpenSearch/pull/9529

**Comment by sachinpkale** [comment]
Fix is provided in the branch: https://github.com/sachinpkale/OpenSearch/tree/mocknrt-remote-store-repo-reg
