### ISSUE TITLE
[BUG] Tasks are not completed or canceled 

### ISSUE THREAD

**Issue by mousemaxx** [opensearch-project/OpenSearch#9183]
Sometimes after a network problem on a part of the cluster, many tasks remain in the “_cat/tasks”.
Tasks remain hanging until nodes are reloaded.
New data is written to the indexes, no index lock occurs, the cluster state is green

I can’t specifically reproduce the problem, but now I have a live example on a running cluster.

`GET _cat/tasks?v&h=action,type,running_time,node,task_id,parent_task_id&s=running_time:desc`
![89aa888a67b8ef27789b86724a3b23fa67576942](https://github.com/opensearch-project/OpenSearch/assets/81787548/dd70b1e4-4558-435f-b438-b8a687384336)

```
GET /_tasks/G9gVoTdtT8Ons3Fxpisnog:98174152

{
  "completed": false,
  "task": {
    "node": "G9gVoTdtT8Ons3Fxpisnog",
    "id": 98174152,
    "type": "transport",
    "action": "indices:data/write/bulk[s]",
    "status": {
      "phase": "waiting_on_primary"
    },
    "description": "requests[1], index[security-auditlog-2023.07.23][0], refresh[IMMEDIATE]",
    "start_time_in_millis": 1690111112962,
    "running_time_in_nanos": 1344489031813227,
    "cancellable": false,
    "cancelled": false,
    "parent_task_id": "u9p6P23kTLqIaLls5j5GJQ:1554631381",
    "headers": {},
    "resource_stats": {
      "total": {
        "cpu_time_in_nanos": 0,
        "memory_in_bytes": 0
      }
    }
  }
}
```

```
GET /_tasks/u9p6P23kTLqIaLls5j5GJQ:1554631381

{
  "error": {
    "root_cause": [
      {
        "type": "resource_not_found_exception",
        "reason": "task [u9p6P23kTLqIaLls5j5GJQ:1554631381] isn't running and hasn't stored its results"
      }
    ],
    "type": "resource_not_found_exception",
    "reason": "task [u9p6P23kTLqIaLls5j5GJQ:1554631381] isn't running and hasn't stored its results"
  },
  "status": 404
}
```

I guess the problem is the missing parent task

**Expected behavior**
It was expected that child tasks would be executed or automatically canceled due to the missing of the parent task.
Well, or that in the absence of a parent task, it was possible to cancel tasks manually. This is currently not possible ("cancellable": false)

OpenSearch version - 2.7.0
OS - CentOS Stream release 8 [4.18.0-383.el8.x86_64]

**Additional context**
[forum discussion](https://forum.opensearch.org/t/tasks-are-not-completed-or-canceled/12265)

**Comment by dblock** [comment]
A task running for 15 days (?) is definitely a bug.

**Comment by mousemaxx** [comment]
@dblock, If I understand correctly, then the task is waiting for a primary ("status":{ "phase": "waiting_on_primary"}), which does not exist.
The task will be running until I restart the service on the node
Нeap dump has a size of 3 GB, I do not have enough knowledge to understand what to look for in it :(

**Comment by mousemaxx** [comment]
Although, not always parental tasks are missing.
For example, this chain:
![image](https://github.com/opensearch-project/OpenSearch/assets/81787548/09ebeb2d-8c3e-42be-9baf-fc00c4ade399)

```
GET /_tasks/G9gVoTdtT8Ons3Fxpisnog:98174510

{
  "completed": false,
  "task": {
    "node": "G9gVoTdtT8Ons3Fxpisnog",
    "id": 98174510,
    "type": "transport",
    "action": "indices:data/write/index",
    "status": {
      "phase": "starting"
    },
    "description": """index {[security-auditlog-2023.07.23][null], source[{"audit_trace_task_parent_id":"EWrZAyRuTnOktuuDhDtyOw:572254432","audit_cluster_name":"***","audit_transport_headers":{"_opendistro_security_initial_action_class_header":"Request","_opendistro_security_origin_header":"LOCAL","_opendistro_security_remotecn":"***"},"audit_node_name":"***-mst01","audit_trace_task_id":"G9gVoTdtT8Ons3Fxpisnog:98174487","audit_transport_request_type":"ConcreteReplicaRequest","audit_category":"MISSING_PRIVILEGES","audit_request_origin":"LOCAL","audit_node_id":"G9gVoTdtT8Ons3Fxpisnog","audit_request_layer":"TRANSPORT","@timestamp":"2023-07-23T11:19:14.644+00:00","audit_format_version":4,"audit_request_privilege":"indices:admin/seq_no/retention_lease_background_sync[r]","audit_node_host_address":"***","audit_node_host_name":"***"}]}""",
    "start_time_in_millis": 1690111154693,
    "running_time_in_nanos": 1603651937540595,
    "cancellable": false,
    "cancelled": false,
    "headers": {},
    "resource_stats": {
      "total": {
        "cpu_time_in_nanos": 0,
        "memory_in_bytes": 0
      }
    }
  }
}
```

```
GET /_tasks/G9gVoTdtT8Ons3Fxpisnog:98174511

{
  "completed": false,
  "task": {
    "node": "G9gVoTdtT8Ons3Fxpisnog",
    "id": 98174511,
    "type": "transport",
    "action": "indices:data/write/bulk[s]",
    "status": {
      "phase": "waiting_on_primary"
    },
    "description": "requests[1], index[security-auditlog-2023.07.23][0], refresh[IMMEDIATE]",
    "start_time_in_millis": 1690111154693,
    "running_time_in_nanos": 1603881475288518,
    "cancellable": false,
    "cancelled": false,
    "parent_task_id": "G9gVoTdtT8Ons3Fxpisnog:98174510",
    "headers": {},
    "resource_stats": {
      "total": {
        "cpu_time_in_nanos": 0,
        "memory_in_bytes": 0
      }
    }
  }
}
```

```
GET /_tasks/G9gVoTdtT8Ons3Fxpisnog:98174512

{
  "completed": false,
  "task": {
    "node": "G9gVoTdtT8Ons3Fxpisnog",
    "id": 98174512,
    "type": "direct",
    "action": "indices:data/write/bulk[s][p]",
    "status": {
      "phase": "primary"
    },
    "description": "requests[1], index[security-auditlog-2023.07.23][0], refresh[IMMEDIATE]",
    "start_time_in_millis": 1690111154693,
    "running_time_in_nanos": 1603914725567003,
    "cancellable": false,
    "cancelled": false,
    "parent_task_id": "G9gVoTdtT8Ons3Fxpisnog:98174511",
    "headers": {},
    "resource_stats": {
      "total": {
        "cpu_time_in_nanos": 0,
        "memory_in_bytes": 0
      }
    }
  }
}
```

Index security-auditlog-2023.07.23 has 2 shards (primary + replica) on nodes G9gVoTdtT8Ons3Fxpisnog and EWrZAyRuTnOktuuDhDtyOw
At the time when there was supposedly a problem on EWrZAyRuTnOktuuDhDtyOw in the log, I see:


```
[INFO ][o.o.c.c.FollowersChecker ] [***-mst02] FollowerChecker{discoveryNode={***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{****:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}, failureCountSinceLastSuccess=1, [cluster.fault_detection.follower_check.retry_count]=3} failed, retrying
org.opensearch.transport.ReceiveTimeoutTransportException: [***-mst01][***:9300][internal:coordination/fault_detection/follower_check] request_id [538453465] timed out after [10006ms]
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1308) [opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.7.0.jar:2.7.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

[WARN ][o.o.t.TransportService   ] [***-mst02] Received response for a request that has timed out, sent [19811ms] ago, timed out [9805ms] ago, action [internal:coordination/fault_detection/follower_check], node [{***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}], id [538453465]

[INFO ][o.o.c.c.FollowersChecker ] [***-mst02] FollowerChecker{discoveryNode={***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}, failureCountSinceLastSuccess=2, [cluster.fault_detection.follower_check.retry_count]=3} failed, retrying
org.opensearch.transport.ReceiveTimeoutTransportException: [***-mst01][***:9300][internal:coordination/fault_detection/follower_check] request_id [538454273] timed out after [10005ms]
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1308) [opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.7.0.jar:2.7.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

[INFO ][o.o.c.c.FollowersChecker ] [***-mst02] FollowerChecker{discoveryNode={***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}, failureCountSinceLastSuccess=3, [cluster.fault_detection.follower_check.retry_count]=3} failed too many times
org.opensearch.transport.ReceiveTimeoutTransportException: [***-mst01][***:9300][internal:coordination/fault_detection/follower_check] request_id [538455143] timed out after [10005ms]
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1308) [opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.7.0.jar:2.7.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

[INFO ][o.o.c.c.FollowersChecker ] [***-mst02] FollowerChecker{discoveryNode={***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}, failureCountSinceLastSuccess=3, [cluster.fault_detection.follower_check.retry_count]=3} marking node as faulty

[INFO ][o.o.c.s.MasterService    ] [***-mst02] node-left[{***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true} reason: followers check retry count exceeded], term: 118, version: 56949166, delta: removed {{***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}}

[INFO ][o.o.c.s.ClusterApplierService] [***-mst02] removed {{***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}}, term: 118, version: 56949166, reason: Publication{term=118, version=56949166}
[INFO ][o.o.a.c.ADClusterEventListener] [***-mst02] Cluster node changed, node removed: true, node added: false
[INFO ][o.o.a.c.HashRing         ] [***-mst02] Node removed: [G9gVoTdtT8Ons3Fxpisnog]
[INFO ][o.o.a.c.HashRing         ] [***-mst02] Remove data node from AD version hash ring: G9gVoTdtT8Ons3Fxpisnog
```
After 13 seconds, the node G9gVoTdtT8Ons3Fxpisnog returned to the cluster.

The document that tried to write in the G9gVoTdtT8Ons3Fxpisnog:98174510 task is not currently in the index.

**Comment by mousemaxx** [comment]
on G9gVoTdtT8Ons3Fxpisnog in log:

```
[INFO ][o.o.c.c.Coordinator      ] [***-mst01] cluster-manager node [{***-mst02}{EWrZAyRuTnOktuuDhDtyOw}{4M5V6J7lSjyurzHlLlxp-w}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}] failed, restarting discovery
org.opensearch.OpenSearchException: node [{***-mst02}{EWrZAyRuTnOktuuDhDtyOw}{4M5V6J7lSjyurzHlLlxp-w}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}] failed [3] consecutive checks
        at org.opensearch.cluster.coordination.LeaderChecker$CheckScheduler$1.handleException(LeaderChecker.java:320) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleException(SecurityInterceptor.java:312) ~[?:?]
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1414) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1305) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.7.0.jar:2.7.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.opensearch.transport.ReceiveTimeoutTransportException: [***-mst02][***:9300][internal:coordination/fault_detection/leader_check] request_id [82540943] timed out after [10005ms]

[INFO ][o.o.c.s.ClusterApplierService] [***-mst01] cluster-manager node changed {previous [{***-mst02}{EWrZAyRuTnOktuuDhDtyOw}{4M5V6J7lSjyurzHlLlxp-w}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}], current []}, term: 118, version: 56949165, reason: becoming candidate: onLeaderFailure

[WARN ][o.o.a.b.TransportShardBulkAction] [***-mst01] [[security-auditlog-2023.07.23][0]] failed to perform indices:data/write/bulk[s] on replica [security-auditlog-2023.07.23][0], node[EWrZAyRuTnOktuuDhDtyOw], [R], s[STARTED], a[id=2Mqj78tvQBGwZeWuiGQy-Q]
org.opensearch.transport.RemoteTransportException: [***-mst02][***:9300][indices:data/write/bulk[s][r]]
Caused by: java.lang.IllegalStateException: [security-auditlog-2023.07.23][0] operation primary term [1] is too old (current [2])
        at org.opensearch.index.shard.IndexShard.lambda$innerAcquireReplicaOperationPermit$42(IndexShard.java:3866) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:58) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.index.shard.IndexShardOperationPermits$2.doRun(IndexShardOperationPermits.java:285) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.index.shard.IndexShardOperationPermits.lambda$acquire$2(IndexShardOperationPermits.java:277) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130) ~[opensearch-2.7.0.jar:2.7.0]

[WARN ][o.o.c.a.s.ShardStateAction] [***-mst01] no cluster-manager known for action [internal:cluster/shard/failure] for shard entry [shard id [[security-auditlog-2023.07.23][0]], allocation id [2Mqj78tvQBGwZeWuiGQy-Q], primary term [1], message [failed to perform indices:data/write/bulk[s] on replica [security-auditlog-2023.07.23][0], node[EWrZAyRuTnOktuuDhDtyOw], [R], s[STARTED], a[id=2Mqj78tvQBGwZeWuiGQy-Q]], failure [RemoteTransportException[[***-mst02][***:9300][indices:data/write/bulk[s][r]]]; nested: IllegalStateException[[security-auditlog-2023.07.23][0] operation primary term [1] is too old (current [2])]; ], markAsStale [true]]

[WARN ][o.o.c.c.ClusterFormationFailureHelper] [***-mst01] cluster-manager not discovered or elected yet, an election requires at least 2 nodes with ids from [G9gVoTdtT8Ons3Fxpisnog, Cdr_6h2MTeGaPNy3zBolSg, EWrZAyRuTnOktuuDhDtyOw], have discovered [{***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{zone=***, shard_indexing_pressure_enabled=true, type=service}, {***-mst03}{Cdr_6h2MTeGaPNy3zBolSg}{mZHKmOPOQHKggJmiRcFgvQ}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}] which is a quorum; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, ***:9300, ***:9300] from hosts providers and [{***-mst02}{EWrZAyRuTnOktuuDhDtyOw}{4M5V6J7lSjyurzHlLlxp-w}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}, {***-mst03}{Cdr_6h2MTeGaPNy3zBolSg}{mZHKmOPOQHKggJmiRcFgvQ}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}, {***-mst01}{G9gVoTdtT8Ons3Fxpisnog}{VPG3x0ovSYyxZQ9JKYIv2A}{***}{***:9300}{dm}{zone=***, shard_indexing_pressure_enabled=true, type=service}] from last-known cluster state; node term 118, last-accepted version 56949165 in term 118

[WARN ][o.o.a.b.TransportShardBulkAction] [***-mst01] [[security-auditlog-2023.07.23][0]] failed to perform indices:data/write/bulk[s] on replica [security-auditlog-2023.07.23][0], node[EWrZAyRuTnOktuuDhDtyOw], [R], s[STARTED], a[id=2Mqj78tvQBGwZeWuiGQy-Q]
org.opensearch.transport.RemoteTransportException: [***-mst02][***:9300][indices:data/write/bulk[s][r]]
Caused by: java.lang.IllegalStateException: [security-auditlog-2023.07.23][0] operation primary term [1] is too old (current [2])
        at org.opensearch.index.shard.IndexShard.lambda$innerAcquireReplicaOperationPermit$42(IndexShard.java:3866) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:309) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:254) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.index.shard.IndexShard.lambda$acquireReplicaOperationPermit$40(IndexShard.java:3805) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.index.shard.IndexShard.innerAcquireReplicaOperationPermit(IndexShard.java:3925) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.index.shard.IndexShard.acquireReplicaOperationPermit(IndexShard.java:3799) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.action.support.replication.TransportReplicationAction.acquireReplicaOperationPermit(TransportReplicationAction.java:1204) ~[opensearch-2.7.0.jar:2.7.0]


[INFO ][o.o.c.s.ClusterApplierService] [***-mst01] cluster-manager node changed {previous [], current [{***-mst02}{EWrZAyRuTnOktuuDhDtyOw}{4M5V6J7lSjyurzHlLlxp-w}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}]}, removed {{***-ing02}{u9p6P23kTLqIaLls5j5GJQ}{T3n0iE1ASRipACeBAZKiAg}{***}{***:9300}{zone=***, shard_indexing_pressure_enabled=true},{***-ing01}{uUQV-5KZQSaiPrZJInSfnw}{0KTrT3tuRbWV-N5un0xLjQ}{***}{***:9300}{zone=***, shard_indexing_pressure_enabled=true}}, term: 118, version: 56949169, reason: ApplyCommitRequest{term=118, version=56949169, sourceNode={***-mst02}{EWrZAyRuTnOktuuDhDtyOw}{4M5V6J7lSjyurzHlLlxp-w}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}}


[WARN ][o.o.c.a.s.ShardStateAction] [***-mst01] unexpected failure while sending request [internal:cluster/shard/failure] to [{***-mst02}{EWrZAyRuTnOktuuDhDtyOw}{4M5V6J7lSjyurzHlLlxp-w}{***}{***:9300}{dm}{type=service, zone=***, shard_indexing_pressure_enabled=true}] for shard entry [shard id [[security-auditlog-2023.07.23][0]], allocation id [2Mqj78tvQBGwZeWuiGQy-Q], primary term [1], message [failed to perform indices:data/write/bulk[s] on replica [security-auditlog-2023.07.23][0], node[EWrZAyRuTnOktuuDhDtyOw], [R], s[STARTED], a[id=2Mqj78tvQBGwZeWuiGQy-Q]], failure [RemoteTransportException[[***-mst02][***:9300][indices:data/write/bulk[s][r]]]; nested: IllegalStateException[[security-auditlog-2023.07.23][0] operation primary term [1] is too old (current [2])]; ], markAsStale [true]]
org.opensearch.transport.RemoteTransportException: [***-mst02][***:9300][internal:cluster/shard/failure]
Caused by: org.opensearch.cluster.action.shard.ShardStateAction$NoLongerPrimaryShardException: primary term [1] did not match current primary term [2]
        at org.opensearch.cluster.action.shard.ShardStateAction$ShardFailedClusterStateTaskExecutor.execute(ShardStateAction.java:485) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:874) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:424) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:295) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:206) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:179) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:217) ~[opensearch-2.7.0.jar:2.7.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) ~[opensearch-2.7.0.jar:2.7.0]
```

It looks like the following happened:

0. node **G9gVoTdtT8Ons3Fxpisnog** had a primary shard with index security-auditlog-2023.07.23. Node **EWrZAyRuTnOktuuDhDtyOw** had replica
1. there was a task to add an entry to the index, the task began to be executed on the **G9gVoTdtT8Ons3Fxpisnog** node, it wrote the data and primed the shard and started trying to write a replica
2. at this moment the node **G9gVoTdtT8Ons3Fxpisnog** has lost connection with the cluster
3. node **EWrZAyRuTnOktuuDhDtyOw** saw that it had a replica of the security-auditlog-2023.07.23 index shard and the primary became unavailable. therefore, the replica became primary and recording began in it
4. when the **G9gVoTdtT8Ons3Fxpisnog** node returned to the cluster, it tried to continue the task, but could not complete it. And it doesn't cancel.

**Comment by dblock** [comment]
this is above my understanding, maybe @andrross can help?

**Comment by andrross** [comment]
@shwetathareja are you aware of any known bugs here? It looks like tasks can get orphaned on a node that has a network interruption but rejoins the cluster and the only way to remove the tasks is to restart the process on that node.
