### ISSUE TITLE
[Flaky Test]SnapshotResiliencyTests.testTransportGetSnapshotsAction

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#9186]
**Describe the bug**
https://build.ci.opensearch.org/job/gradle-check/22110/
Tests with failures:
 - org.opensearch.snapshots.SnapshotResiliencyTests.testTransportGetSnapshotsAction

```

java.lang.AssertionError: Blobstore is closed already
	at __randomizedtesting.SeedInfo.seed([A26299704FDB6338:1BB7497D88CBC8D2]:0)
	at org.opensearch.snapshots.mockstore.MockEventuallyConsistentRepository$MockBlobStore.ensureNotClosed(MockEventuallyConsistentRepository.java:193)
	at org.opensearch.snapshots.mockstore.MockEventuallyConsistentRepository$MockBlobStore$MockBlobContainer.delete(MockEventuallyConsistentRepository.java:274)
	at org.opensearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:1839)
	at org.opensearch.repositories.RepositoriesService$3.lambda$doRun$1(RepositoriesService.java:375)
	at org.opensearch.cluster.coordination.AbstractCoordinatorTestCase$1.run(AbstractCoordinatorTestCase.java:1468)
	at org.opensearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:146)
	at org.opensearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:140)
	at org.opensearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:90)
	at org.opensearch.snapshots.SnapshotResiliencyTests.testTransportGetSnapshotsAction(SnapshotResiliencyTests.java:822)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.snapshots.SnapshotResiliencyTests.testTransportGetSnapshotsAction" -Dtests.seed=A26299704FDB6338 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-MT -Dtests.timezone=Pacific/Pago_Pago -Druntime.java=20
```

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by Bukhtawar** [comment]
Looks related to https://github.com/opensearch-project/OpenSearch/pull/8377/
