### ISSUE TITLE
[BUG] repository-multi-version bwc test is failing for elasticsearch version V7.10.2

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#919]
**Describe the bug**

The backwards compatibility tests for Elasticsearch version v7.10.2 are failing for the `repository-multi-version`. These tests verify if a snapshot repository is not getting corrupted during the cluster upgrade.

Failing Tests:

`testCreateAndRestoreSnapshot`
`testReadOnlyRepo`

**To Reproduce**
`./gradlew :qa:repository-multi-version:v7.10.2#Step3OldClusterTest`

**Expected behavior**
The tests should pass

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux 2
 - Version 2

**Additional context**

**Comment by saratvemulapalli** [comment]
I tried to take a pass at this.
Seems like the test setup is failing rather than test case itself.
The new OpenSearch cluster when it comes up, master is not discovered.

Here is the stack trace:
Platform: Ubuntu x64
```
REPRODUCE WITH: ./gradlew ':qa:repository-multi-version:v7.10.2#Step3OldClusterTest' --tests "org.opensearch.upgrades.MultiVersionRepositoryAccessIT.testCreateAndRestoreSnapshot" -Dtests.seed=7196B28679317809 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=sl -Dtests.timezone=Africa/Bissau -Druntime.java=15

org.opensearch.upgrades.MultiVersionRepositoryAccessIT > testCreateAndRestoreSnapshot FAILED
    org.opensearch.client.ResponseException: method [DELETE], host [http://[::1]:35483], URI [_snapshot/testCreateAndRestoreSnapshot], status line [HTTP/1.1 503 Service Unavailable]
    {"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
        at org.opensearch.client.RestClient.convertResponse(RestClient.java:345)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:315)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:305)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:305)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:321)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:289)
        at org.opensearch.test.rest.OpenSearchRestTestCase.deleteRepository(OpenSearchRestTestCase.java:637)
        at org.opensearch.upgrades.MultiVersionRepositoryAccessIT.testCreateAndRestoreSnapshot(MultiVersionRepositoryAccessIT.java:166)

    java.net.SocketTimeoutException: 60.000 milliseconds timeout on connection http-outgoing-4 [ACTIVE]
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:890)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:302)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:289)
        at org.opensearch.test.rest.OpenSearchRestTestCase.ensureNoInitializingShards(OpenSearchRestTestCase.java:906)
        at org.opensearch.test.rest.OpenSearchRestTestCase.cleanUpCluster(OpenSearchRestTestCase.java:327)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:832)

        Caused by:
        java.net.SocketTimeoutException: 60.000 milliseconds timeout on connection http-outgoing-4 [ACTIVE]
            at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
            at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
            at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
            at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
            at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
            at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
            at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
            at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
            ... 1 more

REPRODUCE WITH: ./gradlew ':qa:repository-multi-version:v7.10.2#Step3OldClusterTest' --tests "org.opensearch.upgrades.MultiVersionRepositoryAccessIT.testReadOnlyRepo" -Dtests.seed=7196B28679317809 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=sl -Dtests.timezone=Africa/Bissau -Druntime.java=15

org.opensearch.upgrades.MultiVersionRepositoryAccessIT > testReadOnlyRepo FAILED
    OpenSearchStatusException[OpenSearch exception [type=master_not_discovered_exception, reason=null]]
        at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:200)
        at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1673)
        at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1650)
        at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1407)
        at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1364)
        at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1334)
        at org.opensearch.client.SnapshotClient.createRepository(SnapshotClient.java:113)
        at org.opensearch.upgrades.MultiVersionRepositoryAccessIT.createRepository(MultiVersionRepositoryAccessIT.java:300)
        at org.opensearch.upgrades.MultiVersionRepositoryAccessIT.testReadOnlyRepo(MultiVersionRepositoryAccessIT.java:175)

    java.net.ConnectException: Connection refused
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:905)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:302)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:305)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:305)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:289)
        at org.opensearch.test.rest.OpenSearchRestTestCase.ensureNoInitializingShards(OpenSearchRestTestCase.java:906)
        at org.opensearch.test.rest.OpenSearchRestTestCase.cleanUpCluster(OpenSearchRestTestCase.java:327)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:832)

        Caused by:
        java.net.ConnectException: Connection refused
            at java.base/sun.nio.ch.Net.pollConnect(Native Method)
            at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
            at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
            at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
            at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
            at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
            at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
            at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
```

**Comment by VachaShah** [comment]
Debugging details:

When the downgrade happens from the new cluster to the old cluster in step3, the master dies abruptly with the following error and the other node is not able to find it:

```
[2021-10-20T18:28:42,191][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.10.2-old-0] fatal error in thread [elasticsearch[v7.10.2-old-0][snapshot][T#5]], exiting
java.lang.AssertionError: Index meta generations should have been empty but was [IndexMetaDataGenerations{lookup:{snapshot-step1/9AP-cr3sSr2ofoTwPxkoZQ={[test-index/QG1E38c1ToO69nqfpCYLlA]=F5ZuvDXHQp6tRe8OkrTIDw-_na_-1-1-1}, snapshot-step2/xsVQY29xRvCdmFQQtsb7Gg={[test-index/QG1E38c1ToO69nqfpCYLlA]=0jPix1rNQN-cgFwAEpe63g-_na_-1-1-1}}}{identifier:{0jPix1rNQN-cgFwAEpe63g-_na_-1-1-1=Crf2nnwBEBlHYuDOY2JI, F5ZuvDXHQp6tRe8OkrTIDw-_na_-1-1-1=IJP2nnwBUvrhpEpvOKjy}}]
        at org.elasticsearch.repositories.RepositoryData.addSnapshot(RepositoryData.java:293) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$finalizeSnapshot$38(BlobStoreRepository.java:1110) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:66) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:46) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:743) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.10.2.jar:7.10.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

This happens while [creating a snapshot](https://github.com/opensearch-project/OpenSearch/blob/main/qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java#L131) for step3. This failure happens in the old cluster at [RepositoryData](https://github.com/elastic/elasticsearch/blob/7.10/server/src/main/java/org/elasticsearch/repositories/RepositoryData.java#L293).

The index metas are empty for this step even after the index is created successfully for the step3 which reaches [this condition](https://github.com/elastic/elasticsearch/blob/7.10/server/src/main/java/org/elasticsearch/repositories/RepositoryData.java#L291).

I was able to print the details for step 2 since that is in the current version of OpenSearch (step 3 is in the old cluster so I was not able to get the details for it). For step 2, the index metas are not empty:

```
index: {test-index=[test-index/QG1E38c1ToO69nqfpCYLlA]}
Indices GET
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test-index 0jPix1rNQN-cgFwAEpe63g   3   0          0            0       416b           416b
indexmetablobs: {[test-index/QG1E38c1ToO69nqfpCYLlA]=0jPix1rNQN-cgFwAEpe63g-_na_-1-1-1}
```
