### ISSUE TITLE
[BUG] org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing flaky failure

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#9191]
**Describe the bug**

4 failures in org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing (21818,21853,22063,22065)

Meta issue - https://github.com/opensearch-project/OpenSearch/issues/8279

**Comment by reta** [comment]
Sadly the  issue is not fixed:

```
java.lang.AssertionError: timed out waiting for relocation iteration [1] 
	at org.opensearch.indices.recovery.IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing(IndexPrimaryRelocationIT.java:128)
	at org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing(RemoteIndexPrimaryRelocationIT.java:54)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

https://build.ci.opensearch.org/job/gradle-check/30517/testReport/junit/org.opensearch.remotestore/RemoteIndexPrimaryRelocationIT/testPrimaryRelocationWhileIndexing/

**Comment by peternied** [comment]
- Impacted PR #11193, failure [logs](https://build.ci.opensearch.org/job/gradle-check/30535/)

**Comment by dreamer-89** [comment]
@sachinpkale : Can you please look into this flaky test ? This is the topmost flaky test.

```
➜  workspace ruby ~/Desktop/Older\ Desktop/flaky-finder.rb --s 29000 --e 31322                                
Will crawl builds from 29000 to 31322
------------------
124 org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing (30490,30501,30501,30518,30520,30523,30535,30536,30536,30567,30568,30573,30581,30583,30585,30593,30599,30607,30607,30617,30625,30630,30630,30630,30631,30640,30641,30650,30655,30661,30674,30682,30682,30684,30691,30693,30697,30714,30735,30740,30741,30743,30758,30761,30786,30796,30813,30814,30823,30837,30839,30881,30890,30896,30896,30897,30898,30921,30922,30922,30931,30932,30938,30939,30942,30945,30945,30949,30951,30959,30963,30964,30968,30976,30981,30981,31005,31006,31008,31010,31025,31047,31058,31068,31077,31084,31089,31092,31105,31109,31116,31119,31121,31128,31130,31134,31153,31165,31168,31168,31168,31189,31190,31192,31215,31215,31217,31220,31229,31231,31232,31235,31235,31252,31263,31280,31280,31284,31295,31304,31305,31306,31320,31322)
77 org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=pit/10_basic/Delete all} (29035,29108,29112,29250,29251,29266,29266,29336,29408,29554,29857,29876,29893,29900,29942,29997,29997,30019,30026,30040,30047,30060,30070,30112,30185,30188,30200,30243,30245,30331,30347,30348,30444,30469,30502,30502,30507,30507,30508,30599,30601,30638,30639,30660,30693,30720,30747,30758,30766,30770,30881,30936,30939,31008,31032,31032,31053,31082,31088,31089,31089,31102,31107,31107,31107,31114,31117,31217,31229,31229,31242,31252,31255,31277,31289,31312,31315)
...
```

**Comment by peternied** [comment]
- Impacting PR https://github.com/opensearch-project/OpenSearch/pull/12260 logs https://build.ci.opensearch.org/job/gradle-check/33572/testReport/org.opensearch.remotestore/RemoteIndexPrimaryRelocationIT/testPrimaryRelocationWhileIndexing/

**Comment by sohami** [comment]
CI with failure: https://build.ci.opensearch.org/job/gradle-check/33937/testReport/junit/org.opensearch.remotestore/RemoteIndexPrimaryRelocationIT/testPrimaryRelocationWhileIndexing/

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing" -Dtests.seed=39EA872CCCBDE24A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-US -Dtests.timezone=America/Goose_Bay -Druntime.java=21

feb 19, 2024 8:47:37 P.M. com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
ADVERTENCIA: Uncaught exception in thread: Thread[#2029,opensearch[node_t1][generic][T#2],5,TGRP-RemoteIndexPrimaryRelocationIT]
java.lang.AssertionError: local checkpoint [9] does not match checkpoint from primary context [PrimaryContext{clusterStateVersion=15, checkpoints={MYNdvCfISO-NnoEkwL95lw=LocalCheckpointState{localCheckpoint=9, globalCheckpoint=8, inSync=true, tracked=true, replicated=true}, i5IiBar_QwK4i2YqQkpIjg=LocalCheckpointState{localCheckpoint=8, globalCheckpoint=8, inSync=true, tracked=true, replicated=true}}, routingTable=IndexShardRoutingTable([test][0]){[test][0], node[3pqwwzGRS7qWaTAVaIrnqw], relocating [I_Z9NuQWSSyxkaQmz-M3eQ], [P], s[RELOCATING], a[id=MYNdvCfISO-NnoEkwL95lw, rId=i5IiBar_QwK4i2YqQkpIjg]}}]
	at __randomizedtesting.SeedInfo.seed([39EA872CCCBDE24A]:0)
	at org.opensearch.index.shard.IndexShard.activateWithPrimaryContext(IndexShard.java:3451)
	at org.opensearch.indices.recovery.RecoveryTarget.handoffPrimaryContext(RecoveryTarget.java:258)
	at org.opensearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:430)
	at org.opensearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:424)
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106)
	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:480)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by peternied** [comment]
New failure: https://build.ci.opensearch.org/job/gradle-check/33963/testReport/

`java.lang.AssertionError: Count is 2 hits but 1 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:`

**Comment by peternied** [comment]
@sachinpkale This test seems to be heavily influencing flaky run failures - how we help get this issue resolved?

**Comment by sachinpkale** [comment]
> @sachinpkale This test seems to be heavily influencing flaky run failures - how we help get this issue resolved?

I will try to prioritize the fix.

**Comment by peternied** [comment]
@sachinpkale @rramachand21 In the past 30 days, this flaky test has impacted pull requests including [#12394, #12383, #12382 (repeated), #12376, #12375 (repeated), #12374 (repeated), #12372, #12368 (repeated), #12367, #12343, #12337 (repeated), #12326 (repeated), #12320 (repeated), #12316, #12301 (repeated), #12293 (repeated), #12290 (repeated), #12278, #12273 (repeated), #12260, #12196, #12193, #12183, #12180, #12168 (repeated), #12154, #12148 (repeated), #12136, #12133 (repeated), #12121, #12111 (repeated)].

Please prioritize fixing this test or disabling the test case until it can be fixed.

**Comment by sachinpkale** [comment]
The test is fixed as part of https://github.com/opensearch-project/OpenSearch/pull/12494
