### ISSUE TITLE
[Concurrent Segment Search] parent-join test failures

### ISSUE THREAD

**Issue by jed326** [opensearch-project/OpenSearch#9316]
Subtask for #7357 to focus on parent-join aggregation failure

```
REPRODUCE WITH: ./gradlew ':modules:parent-join:internalClusterTest' --tests "org.opensearch.join.aggregations.ParentIT.testSimpleParentAgg" -Dtests.seed=1D45D9B19138B210 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=da -Dtests.timezone=Etc/GMT-13 -Druntime.java=20
```

```
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.join.aggregations.ParentIT.testSimpleParentAgg" -Dtests.seed=1D45D9B19138B210 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=da -Dtests.timezone=Etc/GMT-13 -Druntime.java=11

java.lang.AssertionError: Request: {"size":10000,"query":{"match":{"randomized":{"query":true,"operator":"OR","prefix_length":0,"max_expansions":50,"fuzzy_transpositions":true,"lenient":false,"zero_terms_query":"NONE","auto_generate_synonyms_phrase_query":true,"boost":1.0}}},"aggregations":{"to_article":{"parent":{"type":"comment"},"aggregations":{"category":{"terms":{"field":"category","size":10000,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]}}}}}}
Response: {"took":92462,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":6,"relation":"eq"},"max_score":0.5260931,"hits":[{"_index":"test","_id":"article-1","_score":0.5260931,"_source":{"id":"article-1","category":["1"],"randomized":true,"join_field":{"name":"article"}}},{"_index":"test","_id":"comment-2","_score":0.5260931,"_routing":"article-1","_source":{"id":"comment-2","randomized":true,"join_field":{"parent":"article-1","name":"comment"},"commenter":"2"}},{"_index":"test","_id":"article-0","_score":0.5260931,"_source":{"id":"article-0","category":["0"],"randomized":true,"join_field":{"name":"article"}}},{"_index":"test","_id":"comment-3","_score":0.5260931,"_routing":"article-1","_source":{"id":"comment-3","randomized":true,"join_field":{"parent":"article-1","name":"comment"},"commenter":"3"}},{"_index":"test","_id":"comment-1","_score":0.5260931,"_routing":"article-0","_source":{"id":"comment-1","randomized":true,"join_field":{"parent":"article-0","name":"comment"},"commenter":"1"}},{"_index":"test","_id":"comment-0","_score":0.5260931,"_routing":"article-0","_source":{"id":"comment-0","randomized":true,"join_field":{"parent":"article-0","name":"comment"},"commenter":"0"}}]},"aggregations":{"to_article":{"doc_count":3,"category":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"1","doc_count":2},{"key":"0","doc_count":1}]}}}}

Expected: <2L>
     but: was <3L>
Expected :<2L>
Actual   :<3L>
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([1D45D9B19138B210:C90EB7EA85D96A22]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.opensearch.join.aggregations.ParentIT.testSimpleParentAgg(ParentIT.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

The `doc_count` result in the aggregation is incorrect, even before it reaches the reduce phase.

**Comment by jed326** [comment]
This issue was originally created as a subtask for #7357 to focus on parent-join aggregation failure. Keep the original test failures below since the scope of the issue has expanded:

```
REPRODUCE WITH: ./gradlew ':modules:parent-join:internalClusterTest' --tests "org.opensearch.join.aggregations.ParentIT.testSimpleParentAgg" -Dtests.seed=1D45D9B19138B210 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=da -Dtests.timezone=Etc/GMT-13 -Druntime.java=20
```

```
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.join.aggregations.ParentIT.testSimpleParentAgg" -Dtests.seed=1D45D9B19138B210 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=da -Dtests.timezone=Etc/GMT-13 -Druntime.java=11

java.lang.AssertionError: Request: {"size":10000,"query":{"match":{"randomized":{"query":true,"operator":"OR","prefix_length":0,"max_expansions":50,"fuzzy_transpositions":true,"lenient":false,"zero_terms_query":"NONE","auto_generate_synonyms_phrase_query":true,"boost":1.0}}},"aggregations":{"to_article":{"parent":{"type":"comment"},"aggregations":{"category":{"terms":{"field":"category","size":10000,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]}}}}}}
Response: {"took":92462,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":6,"relation":"eq"},"max_score":0.5260931,"hits":[{"_index":"test","_id":"article-1","_score":0.5260931,"_source":{"id":"article-1","category":["1"],"randomized":true,"join_field":{"name":"article"}}},{"_index":"test","_id":"comment-2","_score":0.5260931,"_routing":"article-1","_source":{"id":"comment-2","randomized":true,"join_field":{"parent":"article-1","name":"comment"},"commenter":"2"}},{"_index":"test","_id":"article-0","_score":0.5260931,"_source":{"id":"article-0","category":["0"],"randomized":true,"join_field":{"name":"article"}}},{"_index":"test","_id":"comment-3","_score":0.5260931,"_routing":"article-1","_source":{"id":"comment-3","randomized":true,"join_field":{"parent":"article-1","name":"comment"},"commenter":"3"}},{"_index":"test","_id":"comment-1","_score":0.5260931,"_routing":"article-0","_source":{"id":"comment-1","randomized":true,"join_field":{"parent":"article-0","name":"comment"},"commenter":"1"}},{"_index":"test","_id":"comment-0","_score":0.5260931,"_routing":"article-0","_source":{"id":"comment-0","randomized":true,"join_field":{"parent":"article-0","name":"comment"},"commenter":"0"}}]},"aggregations":{"to_article":{"doc_count":3,"category":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"1","doc_count":2},{"key":"0","doc_count":1}]}}}}

Expected: <2L>
     but: was <3L>
Expected :<2L>
Actual   :<3L>
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([1D45D9B19138B210:C90EB7EA85D96A22]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.opensearch.join.aggregations.ParentIT.testSimpleParentAgg(ParentIT.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

The `doc_count` result in the aggregation is incorrect, even before it reaches the reduce phase.

**Comment by jed326** [comment]
I repurposed this issue as a backlog item to support parent-join aggregations in concurrent segment search and added all of my findings at the top level. I'll create another issue to track creating a dynamic cluster setting for disabling concurrent segment search for specific aggregators.

In the meantime @reta @sohami would like to get your thoughts on the changes I suggested in the top level issue above (including if you agree with the new dynamic cluster setting).

**Comment by sohami** [comment]
@jed326 Thanks for capturing the details here around parent-join aggregation. Would be great to verify and add a similar test case for child aggregation which fails with concurrent segment search.

> I'll create another issue to track creating a dynamic cluster setting for disabling concurrent segment search for specific aggregators.

+1. As you called out, setting based mechanism will be useful to disable for specific aggregations dynamically for subset of requests having such operations. Whereas other requests can still benefit from using concurrent search.

**Comment by jed326** [comment]
> Would be great to verify and add a similar test case for child aggregation which fails with concurrent segment search.

Added test cases as a part of #9446. A few things to note though:
- Children aggregation type doesn't see the same issue with over-counting because it is a many-to-one mapping instead of a one-to-many mapping like parent aggregation. 
- Because we iterate over all of the segments for the index in each Aggregator instance, this will actually cover up the issues with shard routing considerations at the slice level (problem 1). This means that today if we enable concurrent segment search and have 1 child and 1 parent document on different segment slices, then we would still see the relationship between the documents due to each aggregator iterating over all segments.
