### ISSUE TITLE
[BUG] AccessDenied while trying to install analysis-icu-2.9.0 for x86_64

### ISSUE THREAD

**Issue by bastbnl** [opensearch-project/OpenSearch#9402]
**Describe the bug**
I installed `opensearch-2.9.0` using from an apt repository using the instructions found here: 
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/#install-opensearch-from-an-apt-repository and I'm trying to install `analysis-icu`. This fails on a Debian 12 x86_64 machine.

This machine may try to connect to artifacts.opensearch.org using ipv6. Internet connectivity is not an issue: I was able to run `apt-get update` without any errors 

**To Reproduce**
1. Login to the machine
2. Run `sudo -- /usr/share/opensearch/bin/opensearch-plugin install analysis-icu -v`

```
-> Installing analysis-icu
Checking if url exists: https://artifacts.opensearch.org/releases/plugins/analysis-icu/2.9.0/analysis-icu-linux-x64-2.9.0.zip
-> Failed installing analysis-icu
-> Rolling back analysis-icu
-> Rolled back analysis-icu
Exception in thread "main" java.net.SocketException: Network is unreachable
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
        at org.opensearch.plugins.InstallPluginCommand.urlExists(InstallPluginCommand.java:426)
        at org.opensearch.plugins.InstallPluginCommand.getOpenSearchUrl(InstallPluginCommand.java:393)
        at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:310)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:273)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

Opening https://artifacts.opensearch.org/releases/plugins/analysis-icu/2.9.0/analysis-icu-linux-x64-2.9.0.zip using Firefox on my machine returns an xml page containing an error:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>SDS2R14GM0M5X6HH</RequestId>
<HostId>
bv4bf6JaBCItyDFl8r1UOayCSR/hPlBEB+XK3XQ0KePFDhlZIZq6U/Oa8tQIcSHvv074OJbTRZS4jeSyyxBDbEVDsrCWTuQt3ws82q+EAZI=
</HostId>
</Error>
```

Trying to open the parent directory or any parent directory fails with a similar message.

**Expected behavior**
I expect the program to install `analysis-icu`

**Plugins**
[opensearch-security, opensearch-neural-search, opensearch-knn, opensearch-cross-cluster-replication, opensearch-anomaly-detection, opensearch-reports-scheduler, opensearch-job-scheduler, opensearch-alerting, opensearch-index-management, opensearch-ml, opensearch-performance-analyzer, opensearch-geospatial, opensearch-notifications-core, opensearch-security-analytics, opensearch-asynchronous-search, opensearch-observability, opensearch-notifications, opensearch-sql]

**Host/Environment (please complete the following information):**
- OS: Debian 
 - Version 12.1
 - uname: `Linux opensearch-01 6.1.0-11-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`

**Additional context**

**Comment by bastbnl** [comment]
Looks like it has something to do with the filename being requested, since I was able to work around the issue.

Here's what I did:
- Download the plugin to a local directory via `curl  https://artifacts.opensearch.org/releases/plugins/analysis-icu/2.9.0/analysis-icu-2.9.0.zip --output /tmp/analysis-icu-2.9.0.zip`
- Install from that local copy using `sudo -- /usr/share/opensearch/bin/opensearch-plugin install file:///tmp/analysis-icu-2.9.0.zip`

Inspired by the issue documented here: https://forum.opensearch.org/t/analysis-icu-plugin-vs-analysis-icu-client-plugin/10490

**Comment by peternied** [comment]
This is expected behavior the first URL used to install the plugin was missing a part the platform and architecture: `https://artifacts.opensearch.org/releases/plugins/analysis-icu/2.9.0/analysis-icu-`**linux-x64-**`2.9.0.zip`

If there is a specific place that provided a bad url or how to lookup a url could you create an issue to address that?  Thanks
