### ISSUE TITLE
[BUG] org.opensearch.backwards.IndexingIT is flaky

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#9407]
```
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "shardStats" is null
	at __randomizedtesting.SeedInfo.seed([50FFF0AEEC143354:AA02D9ADCA8C830]:0)
	at org.opensearch.backwards.IndexingIT.buildShards(IndexingIT.java:511)
	at org.opensearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$11(IndexingIT.java:484)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1072)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1057)
	at org.opensearch.backwards.IndexingIT.assertSeqNoOnShards(IndexingIT.java:482)
	at org.opensearch.backwards.IndexingIT.testIndexingWithReplicaOnBwcNodes(IndexingIT.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

- org.opensearch.backwards.IndexingIT.testIndexingWithReplicaOnBwcNodes
- org.opensearch.backwards.IndexingIT.testIndexVersionPropagation
- org.opensearch.backwards.IndexingIT.testIndexingWithPrimaryOnBwcNodes
- org.opensearch.backwards.IndexingIT.testSeqNoCheckpoints

https://build.ci.opensearch.org/job/gradle-check/22903/

**Comment by ashking94** [comment]
This test has not been reported since last 2-3 months. I am running this on loop to see if there are failures.

**Comment by ashking94** [comment]
This had ran for 7K iterations without any failure.
