### ISSUE TITLE
[BUG] org.opensearch.index.translog.RemoteFSTranslogTests.testConcurrentWriteViewsAndSnapshot is flaky

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#9455]
Reference: https://build.ci.opensearch.org/job/gradle-check/22090/testReport/junit/org.opensearch.index.translog/RemoteFSTranslogTests/testConcurrentWriteViewsAndSnapshot/

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=342, name=writer_2, state=RUNNABLE, group=TGRP-RemoteFSTranslogTests]
	at __randomizedtesting.SeedInfo.seed([5975FDF9236312D9:7DAC04D4F8F4E15A]:0)
Caused by: java.lang.AssertionError: [index][1] Expected non-empty readers
	at __randomizedtesting.SeedInfo.seed([5975FDF9236312D9]:0)
	at org.opensearch.index.translog.RemoteFsTranslog.deleteStaleRemotePrimaryTerms(RemoteFsTranslog.java:430)
	at org.opensearch.index.translog.RemoteFsTranslog.trimUnreferencedReaders(RemoteFsTranslog.java:400)
	at org.opensearch.index.translog.RemoteFSTranslogTests$2.doRun(RemoteFSTranslogTests.java:822)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

**Comment by sachinpkale** [comment]
Fixing it as part of: https://github.com/opensearch-project/OpenSearch/pull/8951
