### ISSUE TITLE
[BUG][Segment Replication] Test QuorumGatewayIT.testQuorumRecovery fails with Segment Replication

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#9484]
**Describe the bug**
Test QuorumGatewayIT.testQuorumRecovery fails with Segment Replication enabled.

```
java.lang.AssertionError: Count is 2 hits but 3 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:

	at __randomizedtesting.SeedInfo.seed([D1A9FCD4E6943947:3496C00747E9EE5C]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHitCount(OpenSearchAssertions.java:303)
	at org.opensearch.gateway.QuorumGatewayIT.lambda$testQuorumRecovery$0(QuorumGatewayIT.java:118)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1085)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1058)
	at org.opensearch.gateway.QuorumGatewayIT.testQuorumRecovery(QuorumGatewayIT.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

This bug is tracked as part of meta issue #8927 

**To Reproduce**
-> Enable segment replication and run the test.

`REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.gateway.QuorumGatewayIT.testQuorumRecovery" -Dtests.seed=D1A9FCD4E6943947 -Dtests.locale=is-IS -Dtests.timezone=Indian/Comoro -Druntime.java=14`

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dreamer-89** [comment]
Tried this test locally and it passes 100 times without failure when waiting for replication to complete by adding assertBusy before search requests.
