### ISSUE TITLE
can't install repository-s3 plugin

### ISSUE THREAD

**Issue by anthony1910** [opensearch-project/OpenSearch#951]
i am having the issue to install repository-s3 plugin in OpenSearch Node with the following error:

[opensearch@77afa25bb073 bin]$ sh opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0-rc1.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.opensearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:438)
        at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:515)
        at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:306)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
        at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
        at org.opensearch.cli.Command.main(Command.java:103)
        at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

Anyone has any idea what can i do?

**Comment by jkowall** [comment]
It seems like only a subset of plugins are included in the rc1 release, and the other plugins are likely not available to download yet. I assume this will be fixed in 1.0 which is actually due out this week. I do not have access to the artifacts.opensearch.org server so I am not able to debug anymore than this. You'll have to wait for an AWS employee to provide more feedback on this. Should be today I would assume.

**Comment by bbarani** [comment]
@anthony1910 Our current plan is to include all pre-compiled plugins on artifacts.opensearch.org post GA launch (fast follow GA launch). I have opened an issue in build repo to track the progress as well https://github.com/opensearch-project/opensearch-build/issues/86

**Comment by abbashus** [comment]
@anthony1910 as a workaround you can build plugin artifact locally and install it like this

```
cd <OpenSearch repo folder>
./gradlew :plugins:repository-s3:assemble
```
The artifacts are generated here
` <OpenSearch repo folder>/plugins/repository-s3/build/distributions/repository-s3-1.1.0-SNAPSHOT.zip`

Then install it like this
```
bin/opensearch-plugin install file:///<OpenSearch repo folder>/plugins/repository-s3/build/distributions/repository-s3-1.1.0-SNAPSHOT.zip
```

**Comment by anthony1910** [comment]
@abbashus : i can build succesfully but still failed in installing the package:

![image](https://user-images.githubusercontent.com/87245399/125493206-93c9950d-f114-45e9-81f3-0bc65ae1c3f8.png)

the plugin is for OpenSearch version 1.1.0, but the current one that i am running is only version 1.0.0
![image](https://user-images.githubusercontent.com/87245399/125493687-4b373d48-7c54-44f3-8da7-4bd27a4d7ec6.png)

**Comment by saratvemulapalli** [comment]
> @abbashus : i can build succesfully but still failed in installing the package:
> 
> ![image](https://user-images.githubusercontent.com/87245399/125493206-93c9950d-f114-45e9-81f3-0bc65ae1c3f8.png)
> 
> the plugin is for OpenSearch version 1.1.0, but the current one that i am running is only version 1.0.0
> ![image](https://user-images.githubusercontent.com/87245399/125493687-4b373d48-7c54-44f3-8da7-4bd27a4d7ec6.png)

Try building the plugin from OpenSearch/1.0 tree instead of OpenSearch/main. 
It will now build 1.0.0 version of the plugin. This should be able to install the plugin with 1.0.0. 

```
cd <OpenSearch repo folder>
git checkout 1.0
./gradlew :plugins:repository-s3:assemble -Dbuild.snapshot=false
```

**Comment by anthony1910** [comment]
Thank you so much!
I installed it successfully
![image](https://user-images.githubusercontent.com/87245399/125496774-d310dd42-3d1d-425f-bcbb-d3c0500ac57c.png)

**Comment by bbarani** [comment]
@anthony1910 I am closing this issue as core issue will be addressed as part of opensearch-project/opensearch-build#86
