### ISSUE TITLE
[BUG][Segment Replication] DiskThresholdDeciderIT fails with Segment Replication enabled

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/OpenSearch#9643]
**Describe the bug**
DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark fails with segment replication enabled.

```
java.lang.AssertionError: Mismatching shard routings: []
Expected: a collection with size <1>
     but: collection size was <0>
	at __randomizedtesting.SeedInfo.seed([7D3377EC33CD3D81:6F8BD18D58742239]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.lambda$assertBusyWithDiskUsageRefresh$25(DiskThresholdDeciderIT.java:598)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1085)
	at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.assertBusyWithDiskUsageRefresh(DiskThresholdDeciderIT.java:591)
	at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark(DiskThresholdDeciderIT.java:433)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
-> enabled segment replication.
-> run DiskThresholdDeciderIT.java

`REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark" -Dtests.seed=7D3377EC33CD3D81 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=lt-LT -Dtests.timezone=Etc/Greenwich -Druntime.java=20`

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by tlfeng** [comment]
It's reproducible with the test seed.

**Comment by Rishikesh1159** [comment]
The test fails with segment replication because of node having not enough space for allocation of shard.

The node doesn't have enough space to allocate shard because of increase in size of segments_n file after restore from snapshot.

The size of segments_n is increased because of additional flush operation performed [here](https://github.com/opensearch-project/OpenSearch/blob/b7dbf46e9ec1d5c8cea4a95266f325a5a7520249/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L605) in segment replication when a new shard is started.

This additional flush operation is not performed in case of document replication, so the increase in segments_n file doesn't happen and the node will have enough space to allocate shard. So the test doesn't fail in docrep case.

This additional flush operation is used in segrep case because replicas need to get all changes from new primary rather than waiting for more docs to get indexed.

So test `DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark` is not compatible with segrep, we either need to exclude this from segrep testing or we have to update the test to make it compatible with segrep.

Closing this issue for now as there is no actual bug here with segment replication.
