### ISSUE TITLE
[BUG] Deserialization error when handling 'node stats' response - java.io.IOException: Invalid vInt ((ffffffa4 & 0x7f) << 28) | xxxxxxx 

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#9674]
**Describe the bug**
Found during running benchmark test using `opensearch-benchmark` against OpenSearch built from code in `2.x` branch. May related to the code change in commit https://github.com/opensearch-project/OpenSearch/commit/a1dc776fbbb30c8e6471ee30a0d5e42cfd1ce3cf.
The error only occurs in 2 clusters out of 6 running the test, and shown up right after the node joined the cluster.
I will double check If this only affects `opensearch-benchmark` tool.

logs in data nodes:
```
2023-08-30T01:34:13.537-07:00
[2023-08-30T08:34:13,415][WARN ][o.o.t.InboundHandler     ] [ip-10-0-5-164.ec2.internal] Failed to deserialize response from [10.0.3.81/10.0.3.81:9300]

2023-08-30T01:34:13.537-07:00
org.opensearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.opensearch.transport.TransportService$ContextRestoreResponseHandler/org.opensearch.transport.TransportService$6/[cluster:monitor/nodes/stats[n]]:org.opensearch.action.support.nodes.TransportNodesAction$AsyncAction$1@b75b409]
	at org.opensearch.transport.InboundHandler.handleResponse(InboundHandler.java:376) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:161) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:115) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:767) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:95) [transport-netty4-client-2.10.0.jar:2.10.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) [netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]

2023-08-30T01:34:13.538-07:00
Caused by: java.io.IOException: Invalid vInt ((ffffffa4 & 0x7f) << 28) | 5942cf3
	at org.opensearch.core.common.io.stream.StreamInput.readVInt(StreamInput.java:235) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.index.translog.TranslogStats.<init>(TranslogStats.java:61) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.core.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:970) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:262) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.indices.NodeIndicesStats.<init>(NodeIndicesStats.java:79) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.action.admin.cluster.node.stats.NodeStats.<init>(NodeStats.java:150) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.action.admin.cluster.node.stats.TransportNodesStatsAction.newNodeResponse(TransportNodesStatsAction.java:98) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.action.admin.cluster.node.stats.TransportNodesStatsAction.newNodeResponse(TransportNodesStatsAction.java:56) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.action.support.nodes.TransportNodesAction$AsyncAction$1.read(TransportNodesAction.java:272) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.action.support.nodes.TransportNodesAction$AsyncAction$1.read(TransportNodesAction.java:269) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService$6.read(TransportService.java:896) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService$6.read(TransportService.java:876) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1487) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1474) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundHandler.handleResponse(InboundHandler.java:372) ~[opensearch-2.10.0.jar:2.10.0]
	... 26 more
```

**To Reproduce**
unclear

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
OpenSearch version:
```
number | "2.10.0"
build_hash | "f81e990de7edd2e81a8bbc0e71c382f647917c1d"
build_date | "2023-08-30T01:35:08.947940696Z"
```

**Additional context**

**Comment by dblock** [comment]
@kotwanikunal @tlfeng this got closed? what was the issue?

**Comment by kotwanikunal** [comment]
> @kotwanikunal @tlfeng this got closed? what was the issue?

@dblock Tianli was trying to run rolling upgrades with the `2.x` branch while features were being merged. We missed adding the details here - but it was operator error.
