### ISSUE TITLE
[BUG] org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testMultipleShards

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#9712]
**Describe the bug**
New flaky test: org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testMultipleShards

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testMultipleShards" -Dtests.seed=FDC711BB3E51455 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=et-EE -Dtests.timezone=America/Porto_Velho -Druntime.java=20


java.lang.AssertionError: Expected search hits on node: node_t2 to be at least 29 but was: 14
	at __randomizedtesting.SeedInfo.seed([FDC711BB3E51455:F49B0CEF7DFB0A79]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.lambda$waitForSearchableDocs$0(SegmentReplicationBaseIT.java:125)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1085)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:120)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:115)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:132)
	at org.opensearch.indices.replication.SegmentReplicationIT.testMultipleShards(SegmentReplicationIT.java:377)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testMultipleShards" -Dtests.seed=FDC711BB3E51455 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=et-EE -Dtests.timezone=America/Porto_Velho -Druntime.java=20
```

**Expected behavior**
On CI, the test is flaky, see please 
https://build.ci.opensearch.org/job/gradle-check/24205/
[https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6061.log for example.,](https://build.ci.opensearch.org/job/gradle-check/24205/testReport/junit/org.opensearch.remotestore/SegmentReplicationUsingRemoteStoreIT/testMultipleShards/)

**Plugins**
Standard.

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
CI

**Additional context**
N/A

**Comment by dreamer-89** [comment]
Recent gradle check failures due to this test.
5 org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testMultipleShards (24057,24205,24358,25310,25397)
