### ISSUE TITLE
[BUG] org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#9780]
**Describe the bug**
The org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans is flaky

```
org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans

java.lang.AssertionError: expected:&lt;org.opensearch.test.telemetry.tracing.MockSpan@19146f98&gt; but was:&lt;null&gt;
	at __randomizedtesting.SeedInfo.seed([D9BCB54305D17127:BF4A5911DBDD9525]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans(DefaultTracerTests.java:385)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)</pre>org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans
```

**To Reproduce**
```
 ./gradlew ':libs:opensearch-telemetry:test' --tests "org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans" -Dtests.seed=D9BCB54305D17127 
```

**Expected behavior**
Test must always pass

**Plugins**
Standard

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - CI
 - 
**Additional context**
https://build.ci.opensearch.org/job/gradle-check/24505/testReport/junit/org.opensearch.telemetry.tracing/DefaultTracerTests/testSpanAcrossThreadsMultipleSpans/

**Comment by reta** [comment]
@Gaganjuneja could you please take a look? thank you

**Comment by Gaganjuneja** [comment]
Sure.
