### ISSUE TITLE
[BUG] Node failed to join cluster - java.lang.IllegalStateException: unexpected byte [0x0f]

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#9801]
**Describe the bug**
Found the error during running performance test.
OpenSearch is built by code in 2.x branch on `2023-09-06T05:35:01.514600169Z` (Sept.5 11pm PDT)

The cluster is having `cluster_manager_not_discovered_exception` when calling cluster health or other REST APIs.
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "cluster_manager_not_discovered_exception",
        "reason" : null
      }
    ],
    "type" : "cluster_manager_not_discovered_exception",
    "reason" : null
  },
  "status" : 503
}
```

In opensearch.log in each node, the below error kept showing.
```
[2023-09-06T07:46:25,554][INFO ][o.o.c.c.JoinHelper       ] [ip-10-0-5-236.ec2.internal] failed to join {seed}{J0dCW626RyGudMRyxiZGoA}{BvXvhMJeQ7ukWtBZb4M6mw}{10.0.3.112}{10.0.3.112:9300}{m}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={ip-10-0-5-236.ec2.internal}{RqqyRLvFTGG2MATpNnknWw}{ve5aTLELRMSD80MWiMKQAQ}{10.0.5.236}{10.0.5.236:9300}{di}{shard_indexing_pressure_enabled=true}, minimumTerm=1, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={ip-10-0-5-236.ec2.internal}{RqqyRLvFTGG2MATpNnknWw}{ve5aTLELRMSD80MWiMKQAQ}{10.0.5.236}{10.0.5.236:9300}{di}{shard_indexing_pressure_enabled=true}, targetNode={seed}{J0dCW626RyGudMRyxiZGoA}{BvXvhMJeQ7ukWtBZb4M6mw}{10.0.3.112}{10.0.3.112:9300}{m}{shard_indexing_pressure_enabled=true}}]}
```
```
org.opensearch.transport.RemoteTransportException: [seed][10.0.3.112:9300][internal:cluster/coordination/join]
```
```
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.opensearch.cluster.coordination.Coordinator$2.onFailure(Coordinator.java:636) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1506) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:421) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) ~[opensearch-2.10.0.jar:2.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
```
Caused by: org.opensearch.transport.RemoteTransportException: [ip-10-0-5-236.ec2.internal][10.0.5.236:9300][internal:cluster/coordination/join/validate_compressed]
```
```
Caused by: java.lang.IllegalStateException: unexpected byte [0x0f]
	at org.opensearch.core.common.io.stream.StreamInput.readBoolean(StreamInput.java:592) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.core.common.io.stream.StreamInput.readBoolean(StreamInput.java:582) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.core.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:971) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.metadata.RepositoryMetadata.<init>(RepositoryMetadata.java:185) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.core.common.io.stream.StreamInput.readCollection(StreamInput.java:1209) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.core.common.io.stream.StreamInput.readList(StreamInput.java:1160) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.metadata.RepositoriesMetadata.<init>(RepositoriesMetadata.java:183) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.core.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:63) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.core.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:54) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.metadata.Metadata.readFrom(Metadata.java:1099) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.ClusterState.readFrom(ClusterState.java:760) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.JoinHelper.handleCompressedValidateJoinRequest(JoinHelper.java:264) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.JoinHelper.lambda$new$4(JoinHelper.java:231) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:454) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.10.0.jar:2.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
OpenSearch version:
```
    "number" : "2.10.0",
    "build_type" : "tar",
    "build_hash" : "affbd76963ed61d7178df704b935529c9b6b66b0",
    "build_date" : "2023-09-06T05:35:01.514600169Z",
```

**Additional context**
May relate to https://github.com/opensearch-project/OpenSearch/commit/24862c190f4a9d3ed16908d9b6a2ebf7067193f1

**Comment by tlfeng** [comment]
backwards compatibility or rolling upgrade is not supported in unreleased version, so this is not a bug.

**Comment by aaronmcohen** [comment]
@tlfeng We are still seeing this issue post 2.10.0 release.
