### ISSUE TITLE
[BUG] Flaky test InternalEngineTests.testUnreferencedFileCleanUpFailsOnSegmentMergeFailureWhenDirectoryClosed

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#9891]
**Describe the bug**
Flaky test failure : `org.opensearch.index.engine.InternalEngineTests.testUnreferencedFileCleanUpFailsOnSegmentMergeFailureWhenDirectoryClosed`

```
junit.framework.AssertionFailedError: Expected any of the following exception types: [IOException, IllegalStateException] but no exception was thrown.
	at __randomizedtesting.SeedInfo.seed([F1629301ED2AA739:CA39F823A7D722DF]:0)
	at org.apache.lucene.tests.util.LuceneTestCase.expectThrowsAnyOf(LuceneTestCase.java:2905)
	at org.opensearch.index.engine.InternalEngineTests.testUnreferencedFileCleanUpFailsOnSegmentMergeFailureWhenDirectoryClosed(InternalEngineTests.java:3546)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```
**To Reproduce**
https://build.ci.opensearch.org/job/gradle-check/24908/

**Expected behavior**
Test should pass

**Comment by RS146BIJAY** [comment]
Closing https://github.com/opensearch-project/OpenSearch/issues/9891 as completed via [#10801](https://github.com/opensearch-project/OpenSearch/pull/10801).

**Comment by ashking94** [comment]
@RS146BIJAY seeing flaky behaviour - https://build.ci.opensearch.org/job/gradle-check/30685/.
