### ISSUE TITLE
[BUG] Flaky test S3BlobContainerRetriesTests

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#9905]
**Describe the bug**

com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.opensearch.repositories.s3.S3BlobContainerRetriesTests: 
   1) Thread[id=52, name=sdk-ScheduledExecutor-4-0, state=TIMED_WAITING, group=TGRP-S3BlobContainerRetriesTests]
        at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
        at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
        at java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
        at java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)

**To Reproduce**
https://build.ci.opensearch.org/job/gradle-check/24970/

**Expected behavior**
Test should pass

**Comment by gbbafna** [comment]
@shourya035 can you please take a look at this ?

**Comment by BhumikaSaini-Amazon** [comment]
```shell

...

Removing network cecfaffbad8f91d35778c3983160aef9_minio-fixture__│
default                                                          │
                                                                 │
BUILD SUCCESSFUL in 1m 11s                                       │
67 actionable tasks: 11 executed, 56 up-to-date                  │
=================================================================│
==                                                               │
4917                                                             │
=================================================================│
==                                                               │
=======================================                          │
OpenSearch Build Hamster says Hello!                             │
  Gradle Version        : 8.7                                    │
  OS Info               : <redacted>                             │
  JDK Version           : 11 (Amazon Corretto JDK)               │
  JAVA_HOME             : /usr/lib/jvm/java-11-amazon-corretto   │
  Random Testing Seed   : 8802C3ED079BC1EE                       │
  In FIPS 140 mode      : false                                  │
=======================================                          │
                                                                 │
> Task :test:fixtures:s3-fixture:composeBuild                    │
Building s3-fixture                                              │
Building s3-fixture-other                                        │
Building s3-fixture-repositories-metering                        │
Building s3-fixture-with-session-token                           │
Building s3-fixture-with-ec2                                     │

...

```

No repro yet in 4k+ suite runs with unique master seeds. Will repro for longer and check.

**Comment by BhumikaSaini-Amazon** [comment]
```shell
Removing cecfaffbad8f91d35778c3983160aef9_minio-fixture__minio-fi│
xture_1                   ... done                               │
Removing network cecfaffbad8f91d35778c3983160aef9_minio-fixture__│
default                                                          │
                                                                 │
BUILD SUCCESSFUL in 1m 10s                                       │
67 actionable tasks: 11 executed, 56 up-to-date                  │
=================================================================│
==                                                               │
9565                                                             │
=================================================================│
==                                                               │
=======================================                          │
OpenSearch Build Hamster says Hello!                             │
  Gradle Version        : 8.7                                    │
  OS Info               : <redacted>
```

No repro
